Repository sonic-net/sonic-mgmt, pull requests merged in 2018-11, with the labels that each got.

#727 update ecn testcase to use sudo privilege for ecnconfig command
  ansible/roles/test/tasks/ecn_wred.yml
  ansible/roles/test/tasks/ecn_wred_worker.yml
Labels: enhancement

#732 [linkstate]: Fix copy of fanout_listener in up.yml
  ansible/linkstate/up.yml
Labels: bug

#734 [snmp] enhance/fix lldp mib subtest
  ansible/roles/test/tasks/snmp/lldp.yml
Labels: bug, enhancement

#736 [fib_warm_restart.yml]: add new test case to restart docker/system in parallel to fib test.
  ansible/roles/test/tasks/shared-fib.yml
  ansible/roles/test/tasks/simple-fib.yml
  ansible/roles/test/tasks/warm-reboot-fib.yml
  ansible/roles/test/vars/testcases.yml
Labels: enhancement
