Repository sonic-net/sonic-mgmt, pull requests merged in 2018-12, with the labels that each got.

#743 [test]: Fix typo
  ansible/roles/test/tasks/test_sonic_by_testname.yml
Labels: enhancement

#668 Add new platform configure for Seastone DX010 32x100G mode
  ansible/group_vars/sonic/vars
  ansible/library/minigraph_facts.py
Labels: enhancement

#751 [acl]: Fix print out wrong information
  ansible/roles/test/files/acstests/acltb_test.py
Labels: enhancement

#750 [acl]: Enable ACL test on t1-64-lag topology
  ansible/roles/test/files/acstests/acltb_test.py
  ansible/roles/test/templates/acltb.j2
Labels: enhancement

#752 Wait until VLAN and CPU port up
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: enhancement

#757 [minigraph] always generate neighbor device information
  ansible/config_sonic_basedon_testbed.yml
Labels: bug

#742 [config_test]: Add config test to validate IP/LAG commands
  ansible/roles/test/tasks/config.yml
  ansible/roles/test/vars/testcases.yml
Labels: enhancement

#753 [acl]: Revisit ACL test
  ansible/roles/test/files/acstests/acltb_test.py
  ansible/roles/test/tasks/acl/acltb_test_rules.json
  ansible/roles/test/tasks/acl/acltb_test_rules_part_1.json
  ansible/roles/test/tasks/acl/acltb_test_rules_part_2.json
Labels: enhancement

#701 Vxlan decap test implementation
  ansible/library/minigraph_facts.py
  ansible/roles/test/files/ptftests/vxlan-decap.py
  ansible/roles/test/tasks/ptf_runner.yml
  ansible/roles/test/tasks/vxlan-decap.yml
  ansible/roles/test/templates/vxlan_db.json.j2
  ansible/roles/test/templates/vxlan_decap.json.j2
  ansible/roles/test/vars/testcases.yml
Labels: bug, enhancement, new

#762 [start vm] provide a method to respin some vms
  ansible/roles/vm_set/tasks/start_vm.yml
Labels: enhancement

#748 [port-toggle.yml] Correct the commmand for shutdown/startup interface
  ansible/roles/test/tasks/port_toggle.yml
Labels: enhancement
