Repository sonic-net/sonic-mgmt, pull requests merged in 2018-02, with the labels that each got.

#470 [pfcwd]: add docker exec to avoid tty error
  ansible/roles/test/tasks/pfc_wd/functional_test/functional_test.yml
Labels: bug

#471 [Fast-reboot]: Add extract_logs action to concatenate logs after log rotate
  ansible/library/extract_log.py
  ansible/roles/test/tasks/fast-reboot.yml
Labels: enhancement

#472 [Fast-reboot]: Ignore ansible output in extract_log
  ansible/library/extract_log.py
Labels: bug

#474 Add support for additional timestamp format
  ansible/library/extract_log.py
Labels: bug

#480 [test infrastructure] allow overriding recover system actioin
  ansible/roles/test/tasks/base_sanity.yml
  ansible/roles/test/tasks/interface.yml
  ansible/roles/test/tasks/test_sonic_by_testname.yml
Labels: enhancement

#484 Add test case port toggle
  ansible/roles/test/tasks/base_sanity.yml
  ansible/roles/test/tasks/interface.yml
  ansible/roles/test/tasks/port_toggle.yml
  ansible/roles/test/vars/testcases.yml
Labels: bug, enhancement

#483 [test case] Add test: restart swss service
  ansible/roles/test/tasks/restart_swss.yml
  ansible/roles/test/vars/testcases.yml
Labels: enhancement
