Repository sonic-net/sonic-mgmt, pull requests merged in 2019-11, with the labels that each got.

#1192 Fix wrong GRE type constant in ferret.py
  ansible/roles/test/files/helpers/ferret.py
Labels: Bug, Request for 201811 branch :shipit:

#1195 [201811][mlnx][fanout] simplify mlnx pfc storm on fanout functionality
  ansible/plugins/connection/switch.py
  ansible/roles/fanout/tasks/mlnx/check_pfcwd_fanout.yml
  ansible/roles/fanout/tasks/mlnx/deploy_pfcwd_fanout.yml
  ansible/roles/fanout/templates/mlnx_deploy_pfcwd_fanout.j2
  ansible/roles/test/files/mlnx/docker-tests-pfcgen/start.sh
  ansible/roles/test/files/mlnx/docker-tests-saveargs/Dockerfile
  ansible/roles/test/files/mlnx/docker-tests-saveargs/Makefile
  ansible/roles/test/files/mlnx/docker-tests-saveargs/save_args.sh
  ansible/roles/test/templates/pfc_storm_mlnx.j2
  ansible/roles/test/templates/pfc_storm_stop_mlnx.j2
Labels: Included in 201811 branch

#1193 [sensors] use platform string to index sensor test data
  ansible/group_vars/sonic/sku-sensors-data.yml
  ansible/roles/sonic-common/tasks/sensors_check.yml
Labels: Enhancement, Request for 201811 branch :shipit:

#1198 [sensors] add back definition for x86_64-mlnx_msn3700c-r0
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Bug

#1187 [test] Add lacp fallback test cases
  ansible/library/minigraph_facts.py
  ansible/minigraph/switch-t0.xml
  ansible/roles/sonicv2/templates/teamd.j2
  ansible/roles/test/tasks/lag_2.yml
  ansible/roles/test/tasks/lag_fallback.yml
Labels: New

#1172 [tests] add sym link to ansible.cfg for pytest-tests
  tests/ansible.cfg
Labels: Request for 201811 branch :shipit:

#1199 Add port map for Q64 hwsku
  ansible/roles/test/files/brcm/66_interface_to_front_map.ini
Labels: Request for 201811 branch :shipit:

#1204 Fix bgp_speaker testcase after change sonic-buildimage master
  ansible/roles/test/tasks/bgp_speaker.yml
Labels: Bug

#1217 [devices.py] Refactor method of determining whether a service is fully started
  tests/common/devices.py
Labels: Enhancement

#1206 [plugin/connect/switch] Fix the stuck issue of connecting fanout
  ansible/plugins/connection/switch.py
Labels: Request for 201811 branch :shipit:

#1241 [test behavior] disable allow_recover by default
  ansible/roles/test/tasks/test_sonic_by_testname.yml
Labels: Enhancement, Request for 201811 branch :shipit:
