Repository sonic-net/sonic-mgmt, pull requests merged in 2019-02, with the labels that each got.

#799 [ansible] increase ansible cache timeout to 20 minutes
  ansible/ansible.cfg
Labels: Request_for_201811_branch :shipit:, enhancement

#801 [vxlan_decap]: Fix import issue for the scapy module
  ansible/roles/test/files/ptftests/vxlan-decap.py
Labels: bug

#805 [warm/fast reboot] fail fast/warm reboot test if BGP GR timeout is detected
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: Request_for_201811_branch :shipit:, enhancement

#809 [config test] enable config test case for T0-116 topology
  ansible/roles/test/tasks/config.yml
  ansible/roles/test/vars/testcases.yml
Labels: Request_for_201811_branch :shipit:, enhancement

#798 [snmp] Improve the error handling of snmp pfc_counters check
  ansible/roles/test/tasks/snmp/pfc_counters.yml
Labels: Request_for_201811_branch :shipit:

#796 [acl] Add ACL rules to allow BGP traffic
  ansible/roles/test/tasks/acl/acltb_test_rules.json
  ansible/roles/test/tasks/acl/acltb_test_rules_part_2.json
Labels: Request_for_201811_branch :shipit:
