Repository sonic-net/sonic-mgmt, pull requests merged in 2019-09, with the labels that each got.

#1105 Adding Celestica E1031 SKU and related changes to testcases (Phase 1)
  ansible/group_vars/sonic/vars
  ansible/library/minigraph_facts.py
  ansible/roles/eos/templates/t0-52-leaf.j2
  ansible/roles/test/files/ptftests/IP_decap_test.py
  ansible/roles/test/files/ptftests/fib_test.py
  ansible/roles/test/tasks/crm.yml
  ansible/roles/test/tasks/decap.yml
  ansible/roles/test/tasks/fdb.yml
  ansible/roles/test/tasks/shared-fib.yml
  ansible/roles/test/templates/fib.j2
  ansible/roles/test/vars/testcases.yml
Labels: Request for 201811 branch :shipit:

#1095 [warm-reboot] Fix trying to access match group when regex match failed
  ansible/roles/test/files/ptftests/sad_path.py
Labels: Bug, Request for 201811 branch :shipit:

#1096 [warm-reboot] Preboot sad path automation for n vlan ports
  ansible/roles/test/files/ptftests/advanced-reboot.py
  ansible/roles/test/files/ptftests/sad_path.py
  ansible/roles/test/tasks/advanced-reboot.yml
  ansible/roles/test/tasks/advanced_reboot/validate_preboot_list.yml
  ansible/roles/test/tasks/ptf_runner_reboot.yml
  ansible/roles/test/tasks/warm-reboot-multi-sad.yml
  ansible/roles/test/tasks/warm-reboot-sad.yml
Labels: Enhancement, Request for 201811 branch :shipit:

#1098 [everflow_policer] stabilize policer test case
  ansible/roles/test/files/acstests/everflow_policer_test.py
Labels: Bug

#1093 enhance the interface status and sfp modules checking in platform test
  tests/platform/check_all_interface_info.py
  tests/platform/check_interface_status.py
  tests/platform/test_reboot.py
  tests/platform/test_reload_config.py
  tests/platform/test_sequential_restart.py
Labels: Enhancement

#1107 Fix the exit code return issue in shell scripts
  ansible/roles/test/files/helpers/change_mac.sh
  ansible/roles/test/files/helpers/remove_ip.sh
  tests/scripts/change_mac.sh
  tests/scripts/remove_ip.sh
Labels: Request for 201811 branch :shipit:

#1113 [fib]: Fixed FIB V4/V6: aligned facts generator
  ansible/roles/test/templates/fib.j2
Labels: Bug

#1116 [fast/warm-reboot] Avoid the FDB clear
  ansible/roles/test/tasks/ptf_runner_reboot.yml
Labels: Bug, Request for 201811 branch :shipit:

#1102 [everflow]: Add pause to stablize the test
  ansible/roles/test/tasks/everflow_testbed/testcase_8.yml
Labels: Enhancement

#1092 [platform test]Platform test enhancement
  tests/common/devices.py
  tests/common/mellanox_data.py
  tests/platform/check_daemon_status.py
  tests/platform/check_interface_status.py
  tests/platform/mellanox/check_sysfs.py
  tests/platform/mellanox/test_check_sfp_presence.py
  tests/platform/test_reboot.py
Labels: Enhancement

#1118 update sku-sensors-data.yml
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Request for 201811 branch :shipit:

#1062 Make link flap timeout configurable for link_flap test case
  ansible/roles/test/tasks/link_flap/link_flap_helper.yml
Labels: Request for 201811 branch :shipit:

#1079 [tests/platform/test_reboot.py] add testcases for reboot cause
  tests/platform/test_reboot.py
Labels: Enhancement

#1083 [hash]: Add hash test to validate the hash fields
  ansible/roles/test/files/ptftests/hash_test.py
  ansible/roles/test/tasks/hash.yml
  ansible/roles/test/tasks/test_sonic_by_tag.yml
  ansible/roles/test/vars/testcases.yml
Labels: Enhancement

#1082 [tests/platform/mellanox] check PSU state against sysfs on Mellanox devices
  tests/platform/mellanox/check_sysfs.py
  tests/platform/test_platform_info.py
Labels: Enhancement

#1132 Add SKU sensors data for Arista-7050-QX-32S
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Request for 201811 branch :shipit:
