Repository sonic-net/sonic-mgmt, pull requests merged in 2019-08, with the labels that each got.

#1038 [pytest] improvements for pytest infrastructure
  .gitignore
  ansible/roles/test/tasks/lldp.yml
  ansible/roles/test/tasks/lldp_neighbor.yml
  ansible/roles/test/tasks/pytest_runner.yml
  tests/ansible_fixtures.py
  tests/ansible_host.py
  tests/conftest.py
  tests/eos
  tests/fdb/change_mac.sh
  tests/fdb/conftest.py
  tests/fdb/fdb.j2
  tests/fdb/test_fdb.py
  tests/platform/check_critical_services.py
  tests/platform/check_interface_status.py
  tests/platform/check_transceiver_status.py
  tests/platform/test_platform_info.py
  tests/platform/test_reboot.py
  tests/platform/test_reload_config.py
  tests/platform/test_sequential_restart.py
  tests/platform/test_sfp.py
  tests/platform/test_xcvr_info_in_db.py
  tests/ptf_fixtures.py
  tests/ptf_runner.py
  tests/ptfadapter/README.md
  tests/ptfadapter/__init__.py
  tests/ptfadapter/ptfadapter.py
  tests/ptfadapter/templates/ptf_nn_agent.conf.ptf.j2
  tests/scripts/change_mac.sh
  tests/scripts/remove_ip.sh
  tests/test_bgp_fact.py
  tests/test_bgp_speaker.py
  tests/test_fdb.py
  tests/test_lldp.py
Labels: Enhancement

#1049 [vxlan-decap]: Add extended statistics output for vxlan-decap test
  ansible/roles/test/files/ptftests/vxlan-decap.py
Labels: Enhancement

#1053 [CRM] Wait more time for CRM stats to update - 201811 branch
  ansible/roles/test/tasks/crm.yml
  ansible/roles/test/tasks/crm/crm_test_acl_counter.yml
  ansible/roles/test/tasks/crm/crm_test_acl_entry.yml
  ansible/roles/test/tasks/crm/crm_test_fdb_entry.yml
  ansible/roles/test/tasks/crm/crm_test_ipv4_neighbor.yml
  ansible/roles/test/tasks/crm/crm_test_ipv4_nexthop.yml
  ansible/roles/test/tasks/crm/crm_test_ipv4_route.yml
  ansible/roles/test/tasks/crm/crm_test_ipv6_neighbor.yml
  ansible/roles/test/tasks/crm/crm_test_ipv6_nexthop.yml
  ansible/roles/test/tasks/crm/crm_test_ipv6_route.yml
  ansible/roles/test/tasks/crm/crm_test_nexthop_group.yml
  ansible/roles/test/tasks/crm/crm_test_nexthop_group_member.yml
Labels: Included in 201811 branch

#1060 [everflow/policer] remove route after session is removed
  ansible/roles/test/tasks/everflow_testbed/testcase_8.yml
Labels: Enhancement

#1057 [vxlan decap]: Use one tunnel with N tunnel maps.
  ansible/roles/test/files/ptftests/vxlan-decap.py
  ansible/roles/test/tasks/vxlan-decap.yml
  ansible/roles/test/templates/vxlan_db.json.j2
  ansible/roles/test/templates/vxlan_db.maps.json.j2
  ansible/roles/test/templates/vxlan_db.tunnel.json.j2
Labels: Enhancement

#1056 [vlan_trunk] stabilize vlan trunk test
  ansible/roles/test/tasks/vlan_cleanup.yml
  ansible/roles/test/tasks/vlan_configure.yml
  ansible/roles/test/tasks/vlan_test.yml
  ansible/roles/test/templates/vlan_configuration.j2
Labels: Bug

#1071 Some improvements for vxlan decap test
  ansible/roles/test/tasks/common_tasks/reboot_sonic.yml
  ansible/roles/test/tasks/vxlan-decap.yml
Labels: Enhancement, Request for 201811 branch :shipit:

#1066 [warm-reboot] Add lag flap check after warm boot
  ansible/roles/test/files/ptftests/advanced-reboot.py
  ansible/roles/test/files/ptftests/arista.py
Labels: Enhancement, Request for 201811 branch :shipit:

#1074 Add sensor data for Arista-7260CX3-Q64
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Enhancement, Request for 201811 branch :shipit:

#1075 [vxlan-decap]: Improvements of the test
  ansible/roles/test/files/ptftests/vxlan-decap.py
  ansible/roles/test/tasks/vxlan-decap.yml
Labels: Enhancement, Request for 201811 branch :shipit:

#1078 [vxlan-decap]: Generate mapping between vlan member ports and vlan ip address robustly
  ansible/ansible.cfg
  ansible/roles/test/files/ptftests/vxlan-decap.py
  ansible/roles/test/tasks/vxlan-decap.yml
Labels: Bug, Enhancement, Request for 201811 branch :shipit:

#1076 [vm-set]: Add setting of RCVBUF default parameter
  ansible/roles/vm_set/tasks/main.yml
Labels: Enhancement, Request for 201811 branch :shipit:

#1077 [everflow]: Add Mellanox support due to specific GRE packet format
  ansible/roles/test/files/acstests/everflow_policer_test.py
Labels: Enhancement, Request for 201811 branch :shipit:

#1036 [warm-reboot] Preboot sad path automation for n lag members
  ansible/roles/test/files/ptftests/advanced-reboot.py
  ansible/roles/test/files/ptftests/arista.py
  ansible/roles/test/files/ptftests/sad_path.py
  ansible/roles/test/tasks/advanced_reboot/validate_preboot_list.yml
  ansible/roles/test/tasks/warm-reboot-multi-sad.yml
Labels: Enhancement, Request for 201811 branch :shipit:
