Repository sonic-net/sonic-mgmt, pull requests merged in 2019-01, with the labels that each got.

#769 [warm/fast reboot] refactoring advanced-reboot script
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: bug, enhancement

#773 [dhcp_relay] skip teamd restart test in dhcp_relay test
  ansible/roles/test/tasks/dhcp_relay.yml
Labels: bug

#761 [decap] Extend the existing decap test to cover TTL testing
  ansible/roles/test/files/ptftests/IP_decap_test.py
  ansible/roles/test/tasks/decap.yml
  ansible/roles/test/templates/decap_conf.j2
  ansible/roles/test/templates/fib.j2
Labels: enhancement

#777 [dhcp relay] remove the teamd service restart test
  ansible/roles/test/tasks/dhcp_relay.yml
Labels: bug

#784 set default testbed file for test
  ansible/roles/test/tasks/sonic.yml
Labels: Request_for_201811_branch :shipit:

#607 [copp]: Add UDLD test in COPP test suite
  ansible/roles/test/files/ptftests/copp_tests.py
  ansible/roles/test/tasks/copp.yml
Labels: enhancement

#786 [testbed] define default testbed file name
  ansible/config_sonic_basedon_testbed.yml
Labels: Request_for_201811_branch :shipit:, bug

#765 Replace shutdown with reboot
  ansible/upgrade_sonic.yml
Labels: bug

#779 [reboot_sonic] Fix reboot task
  ansible/roles/test/tasks/common_tasks/reboot_sonic.yml
Labels: Request_for_201811_branch :shipit:, bug

#790 [warm/fast reboot] fix warm reboot test issue and update bgp graceful restart timeout
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: Request_for_201811_branch :shipit:, bug, enhancement
