Repository sonic-net/sonic-mgmt, pull requests merged in 2019-07, with the labels that each got.

#985 Disabled IPv6 DAD: aligned with SONiC
  ansible/roles/eos/files/rc.eos
  ansible/roles/eos/tasks/main.yml
Labels: Enhancement

#988 [everflow]: Fix the tearing down procedure order
  ansible/roles/test/tasks/everflow_testbed/testcase_8.yml
Labels: Bug

#994 [loganalyzer] Fix the IOError of opening match file
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_analyze.yml
Labels: Bug

#998 [dhcp_relay] Correct to use port alias instead of port name
  ansible/roles/test/tasks/dhcp_relay.yml
Labels: Bug

#997 [loganalyzer] Generate dump of log within 1 hour by default if test failed
  ansible/roles/test/files/tools/loganalyzer/loganalyzer.py
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_end.yml
Labels: Request for 201811 branch :shipit:

#1000 [fast-reboot] Upgrade FW for mellanox before fast-reboot
  ansible/roles/test/files/mlnx/upgrade_mlnx_fw.sh
  ansible/roles/test/tasks/advanced-reboot.yml
  ansible/roles/test/tasks/advanced_reboot/upgrade_mlnx_fw.yml
Labels: Enhancement, Request for 201811 branch :shipit:

#1003 [warm reboot] save config after upgrading into new image
  ansible/roles/test/tasks/advanced-reboot.yml
Labels: Request for 201811 branch :shipit:

#1010 Merge EVERFLOW test updates
  ansible/roles/test/files/acstests/everflow_policer_test.py
  ansible/roles/test/files/helpers/mirror_session.py
  ansible/roles/test/tasks/everflow_testbed/apply_config.yml
  ansible/roles/test/tasks/everflow_testbed/del_config.yml
  ansible/roles/test/tasks/everflow_testbed/get_port_info.yml
  ansible/roles/test/tasks/everflow_testbed/get_session_info.yml
  ansible/roles/test/tasks/everflow_testbed/run_test.yml
  ansible/roles/test/tasks/everflow_testbed/testcase_1.yml
  ansible/roles/test/tasks/everflow_testbed/testcase_2.yml
  ansible/roles/test/tasks/everflow_testbed/testcase_3.yml
  ansible/roles/test/tasks/everflow_testbed/testcase_4.yml
  ansible/roles/test/tasks/everflow_testbed/testcase_5.yml
  ansible/roles/test/tasks/everflow_testbed/testcase_6.yml
  ansible/roles/test/tasks/everflow_testbed/testcase_7.yml
  ansible/roles/test/tasks/everflow_testbed/testcase_8.yml
Labels: Enhancement

#1011 [warm-reboot] Add test parameter for increasing sniff time
  ansible/roles/test/files/ptftests/advanced-reboot.py
  ansible/roles/test/tasks/advanced-reboot.yml
  ansible/roles/test/tasks/ptf_runner_reboot.yml
Labels: Enhancement, Request for 201811 branch :shipit:

#1013 [warm reboot] always save the configuration
  ansible/roles/test/tasks/advanced-reboot.yml
Labels: Request for 201811 branch :shipit:

#747 Modified the ecn profiles in script to LOSSLESS as all platforms doesnt have LOSSY profile
  ansible/roles/test/tasks/ecn_wred.yml
  ansible/roles/test/tasks/ecn_wred_worker.yml
Labels: Enhancement, Request for 201811 branch :shipit:

#953 add t0-64-32 topology to shared-fib test
  ansible/roles/test/tasks/shared-fib.yml
Labels: Bug

#1005 [ansible-plugin] back port stdout callback plugin 'yaml' from ansible2.5
  ansible/ansible.cfg
  ansible/plugins/callback/yaml.py
Labels: Request for 201811 branch :shipit:

#1018 [fast/warm reboot] check the existence of correct file as stated
  ansible/roles/test/tasks/advanced-reboot.yml
Labels: Bug, Request for 201811 branch :shipit:

#1020 [sonic_upgrade] remove non-current and non-next images
  ansible/library/reduce_and_add_sonic_images.py
Labels: Enhancement, Request for 201811 branch :shipit:

#1019 [minigraph] allow generating minigraph without data plane acl defined
  ansible/templates/minigraph_dpg.j2
  ansible/testbed-cli.sh
Labels: Enhancement, Request for 201811 branch :shipit:

#996 [bgp-gr-helper] Add script for testing the BGP graceful restart helper function
  ansible/group_vars/eos/eos.yml
  ansible/roles/eos/templates/t1-64-lag-tor.j2
  ansible/roles/eos/templates/t1-lag-tor.j2
  ansible/roles/eos/templates/t1-tor.j2
  ansible/roles/test/tasks/bgp_gr_helper.yml
  ansible/roles/test/tasks/bgp_gr_helper/get_vm_info.yml
  ansible/roles/test/tasks/bgp_gr_helper/routes_update_expect.txt
  ansible/roles/test/tasks/bgp_gr_helper/routes_update_match.txt
  ansible/roles/test/vars/testcases.yml
Labels: New

#993 Add 't0-64-32' testbed_type for FibTest.
  ansible/roles/test/templates/fib.j2
Labels: Enhancement

#1014 [warm-reboot] Add time diff check between BGP v4 and v6 peers
  ansible/roles/test/files/ptftests/arista.py
Labels: Enhancement, Request for 201811 branch :shipit:

#1004 [warm-reboot] Add Preboot n BGP member down and n Lag down tests
  ansible/roles/test/files/ptftests/advanced-reboot.py
  ansible/roles/test/files/ptftests/sad_path.py
  ansible/roles/test/tasks/advanced-reboot.yml
  ansible/roles/test/tasks/advanced_reboot/validate_preboot_list.yml
  ansible/roles/test/tasks/warm-reboot-multi-sad.yml
  ansible/roles/test/vars/testcases.yml
Labels: Enhancement, Request for 201811 branch :shipit:

#1035 [advanced-reboot] help switch to populate fdb table before test
  ansible/roles/test/files/ptftests/advanced-reboot.py
  ansible/roles/test/tasks/ptf_runner_reboot.yml
Labels: Request for 201811 branch :shipit:

#1041 [mlnx][fanout] disable mac learning on fanout
  ansible/roles/fanout/templates/mlnx_fanout.j2
Labels: Request for 201811 branch :shipit:

#1039 Fix error in testcase doc
  ansible/README.test.md
Labels: Enhancement
