Repository sonic-net/sonic-mgmt, pull requests merged in 2019-03, with the labels that each got.

#816 Add 'ERR ntpd' to loganalyzer ignore files
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
  ansible/roles/test/tasks/acl/acltb_ignore_messages.txt
  ansible/roles/test/tasks/fib/fib_ignore_messages.txt
  ansible/roles/test/tasks/lag/lag_ignore_messages.txt
  ansible/roles/test/tasks/pfc_wd/config_test/config_test_ignore_messages
  ansible/roles/test/tasks/pfc_wd/functional_test/ignore_pfc_wd_messages
Labels: Request_for_201811_branch :shipit:, bug

#822 [logAnalyzer] Avoid logAnalyzer logs being overwritten
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_init.yml
  ansible/roles/test/tasks/acltb_ranges_test.yml
  ansible/roles/test/tasks/decap.yml
  ansible/roles/test/tasks/lag.yml
  ansible/vars/run_config_test_vars.yml
  ansible/vars/run_loganalyzer_vars.yml
  ansible/vars/run_ping_test_vars.yml
  ansible/vars/run_ptf_test_vars.yml
Labels: Request_for_201811_branch :shipit:

#826 [t0-64 template] avoid deploying conflict routing entries on leaf switch
  ansible/roles/eos/templates/t0-64-leaf.j2
Labels: Request_for_201811_branch :shipit:, bug

#824 [arp ping] add VLAN arp ping to warm/fast reboot test
  ansible/roles/test/files/helpers/arp_responder.py
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: Request_for_201811_branch :shipit:, enhancement

#833 [warm/fast reboot] refactor test code to reduce duplicate logic
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: Request_for_201811_branch :shipit:, enhancement

#831 [logAnalyzer] Fix the issue of unmatched start and end mark
  ansible/roles/test/tasks/acl/acl_traffic_test/run_ping_test.yml
  ansible/roles/test/tasks/acl/acl_traffic_test/run_ptf_test.yml
  ansible/roles/test/tasks/run_command_with_log_analyzer.yml
  ansible/roles/test/tasks/run_loganalyzer.yml
  ansible/vars/run_config_test_vars.yml
  ansible/vars/run_loganalyzer_vars.yml
  ansible/vars/run_ping_test_vars.yml
  ansible/vars/run_ptf_test_vars.yml
Labels: Request_for_201811_branch :shipit:

#716 Add tests for interface naming mode
  ansible/library/show_interface.py
  ansible/roles/test/tasks/iface_naming_mode.yml
  ansible/roles/test/tasks/iface_naming_mode/add_user.yml
  ansible/roles/test/tasks/iface_naming_mode/check_userifmode.yml
  ansible/roles/test/tasks/iface_naming_mode/iface_naming_mode_tests.yml
  ansible/roles/test/tasks/iface_naming_mode/interface_config.yml
  ansible/roles/test/tasks/iface_naming_mode/show_acl.yml
  ansible/roles/test/tasks/iface_naming_mode/show_arp.yml
  ansible/roles/test/tasks/iface_naming_mode/show_interface.yml
  ansible/roles/test/tasks/iface_naming_mode/show_ip_route.yml
  ansible/roles/test/tasks/iface_naming_mode/show_pfc_counters.yml
  ansible/roles/test/tasks/iface_naming_mode/show_portchannel.yml
  ansible/roles/test/tasks/iface_naming_mode/show_queue_counters.yml
  ansible/roles/test/tasks/iface_naming_mode/vars/iface_naming_vars.yml
  ansible/roles/test/vars/testcases.yml
Labels: enhancement

#839 [lag_rate] Restore lag setting on VMs in case of failure in test
  ansible/roles/test/tasks/single_lag_lacp_rate_test.yml
Labels: Request_for_201811_branch :shipit:

#842 [acltb] Apply BGP ACL forward rules in acltb_test_rules_part_1.json
  ansible/roles/test/tasks/acl/acltb_test_rules_part_1.json
Labels: Request_for_201811_branch :shipit:
