Repository sonic-net/sonic-mgmt, pull requests merged in 2020-08, with the labels that each got.

#2014 [Platform API][Chassis] Ignore case when comparing base MAC address
  tests/platform_tests/api/test_chassis.py
Labels: Enhancement, Platform, Pytest :snake:

#2011 [fib, t0-116] hard code announced route for t0-116
  ansible/vars/topo_t0-116.yml
  tests/common/plugins/fib.py
Labels: Bug :bug:, Enhancement, Pytest :snake:

#2006 [lag update] add log analysis exception
  tests/pc/test_po_update.py
Labels: Bug :bug:, Pytest :snake:

#2013 [run_test.sh] add maxfail option and improve help information
  tests/run_tests.sh
Labels: Enhancement

#1989 [Mellanox] Add retry to check fan speed sysfs
  tests/platform_tests/mellanox/check_sysfs.py
Labels: Enhancement, Platform

#2007 [everflow] Improve Everflow v6 tests
  tests/everflow/templates/acl_rule_v6.json.j2
  tests/everflow/test_everflow_ipv6.py
Labels: Bug :bug:, Cleanup :droplet:, Pytest :snake:

#1993 [pytest] Fix unicode error in pfcwd
  ansible/roles/test/files/ptftests/pfc_wd.py
Labels: Bug :bug:

#2002 Fix get_ip_route_info()
  tests/bgp/test_bgp_gr_helper.py
  tests/common/devices.py
  tests/route/test_default_route.py
Labels: Bug :bug:, Pytest :snake:, Request for 201811 branch :shipit:

#1997 Remove the route add/del in pfcwd
  tests/pfcwd/conftest.py
Labels: Pytest :snake:

#2016 Fix call check_vendor_specific_psustatus error
  tests/platform_tests/cli/test_show_platform.py
  tests/platform_tests/test_platform_info.py
Labels: Bug :bug:, Platform, Pytest :snake:

#1996 [pytest] Add fixture "conn_graph_facts_multi_duts"
  tests/common/fixtures/conn_graph_facts.py
  tests/conftest.py
Labels: Pytest :snake:

#2019 [Platform API][pytest]Api tests for thermal class
  tests/common/helpers/platform_api/thermal.py
  tests/platform_tests/api/test_fan.py
  tests/platform_tests/api/test_thermal.py
Labels: Enhancement, Platform, Pytest :snake:

#2009 [Platform API][Module] Inherit from PlatformApiTestBase class
  tests/platform_tests/api/test_module.py
Labels: Enhancement, Platform, Pytest :snake:

#2024 [show interface] make show interface compatible w or w/o fec information
  ansible/library/show_interface.py
Labels: Bug :bug:, Enhancement, Pytest :snake:, Request for 201811 branch :shipit:

#2029 [Arista] Fix 7050QX-32 sku sensors data
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Bug :bug:, Platform

#2033 [device] simplify AnsibleHostBase constructor parameter handling
  tests/common/devices.py
Labels: Cleanup :droplet:, Enhancement, Pytest :snake:

#2031 [acl] Flush dataplane before running ACL tests
  tests/acl/test_acl.py
Labels: Bug :bug:, Pytest :snake:

#2027 [syslog] Add wait_until to syslog test to stabilize kvm runners
  tests/syslog/__init__.py
  tests/syslog/test_syslog.py
Labels: KVM Testing :test_tube:, Pytest :snake:

#2030 [copp] Fix recent COPP test failures
  tests/common/system_utils/docker.py
  tests/copp/test_copp.py
Labels: Bug :bug:, Pytest :snake:

#2020 [docker]: Automate sonic-mgmt container creation
  README.md
  ansible/doc/README.testbed.VsSetup.md
  setup-container.sh
Labels: Enhancement

#2023 Fix cleanup when running ansible version for pfc_all_port_storm
  ansible/roles/test/tasks/pfc_wd/functional_test/storm_all_action.yml
Labels: Bug :bug:, Request for 201811 branch :shipit:

#2040 [ser] address broadcom SER test issues
  tests/conftest.py
  tests/platform_tests/broadcom/test_ser.py
Labels: Bug :bug:, Pytest :snake:

#2035 [Spytest] Adapt to 'show interfaces status' change
  spytest/templates/show_interfaces_status_qa.tmpl
Labels: Bug :bug:, Spytest

#2049 Fix spelling mistake in verify_show_platform_temperature_output
  tests/platform_tests/cli/test_show_platform.py
Labels: Cleanup :droplet:, Platform

#2043 [LGTM] address a few LGTM warnings
  tests/conftest.py
  tests/platform_tests/broadcom/test_ser.py
Labels: Cleanup :droplet:, Pytest :snake:

#2054 [get_ip_route_info]: Return empty rtinfo when there is no route_entry
  tests/bgp/test_bgp_gr_helper.py
  tests/common/devices.py
Labels: Bug :bug:, Pytest :snake:

#2042 [minigraph]: Copy prefix_v6 into templates
  ansible/library/vlan_config.py
Labels: Bug :bug:

#2057 [SER injection] change Broadcom SER test stragety
  tests/platform_tests/broadcom/files/ser_injector.py
Labels: Bug :bug:, Enhancement, Pytest :snake:

#2060 [Telemetry-Pytest] fix docker image present check
  tests/telemetry/test_telemetry.py
Labels: Bug :bug:, Pytest :snake:, Telemetry

#2067 Bug fix in advanced-reboot check-sonic-version
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: Bug :bug:, Pytest :snake:

#2036 [platform] Import sonic-py-common in lieu of sonic-daemon-base
  tests/platform_tests/files/getportmap.py
Labels: Cleanup :droplet:, Platform

#2061 [test_dhcp_relay] Ignore snmp error in LogAnalyzer
  tests/dhcp_relay/test_dhcp_relay.py
Labels: Bug :bug:, Pytest :snake:

#2073 [Platform API][pytest]Fan_drawer class basic platform api tests
  tests/common/helpers/platform_api/fan_drawer.py
  tests/platform_tests/api/test_fan_drawer.py
Labels: Enhancement, Platform, Pytest :snake:

#2071 [docker] Fix docker credential management
  tests/common/system_utils/docker.py
  tests/conftest.py
  tests/copp/test_copp.py
  tests/qos/qos_sai_base.py
Labels: Bug :bug:, Cleanup :droplet:, Pytest :snake:

#2015 [pytest] Add test_gen_spytestbed.py to generate Spytest testbed file
  ansible/library/conn_graph_facts.py
  tests/templates/spytest_testbed.yaml.j2
  tests/testbed_setup/test_gen_spy_testbed.py
Labels: Pytest :snake:, Spytest, Testbed

#1944 Add a test to check ipv6 routes over ipv4 bgp session
  ansible/library/exabgp.py
  ansible/roles/test/files/ptftests/fib.py
  ansible/roles/test/files/ptftests/fib_test.py
  ansible/roles/test/files/ptftests/lpm.py
  tests/bgp/test_bgp_speaker.py
Labels: Enhancement, New, Pytest :snake:

#2076 [ptf_runner] Add timeout option for ptf test run
  tests/ptf_runner.py
Labels: Enhancement, Pytest :snake:

#2077 [qos] Add timeout for qos sai ptf run
  tests/qos/qos_sai_base.py
Labels: Enhancement, Pytest :snake:

#2005 [Pytest] Convert CRM test to pytest
  ansible/roles/test/tasks/crm.yml
  ansible/roles/test/tasks/crm/crm_test_acl_counter.yml
  ansible/roles/test/tasks/crm/crm_test_acl_entry.yml
  ansible/roles/test/tasks/crm/crm_test_fdb_entry.yml
  ansible/roles/test/tasks/crm/crm_test_ipv4_neighbor.yml
  ansible/roles/test/tasks/crm/crm_test_ipv4_nexthop.yml
  ansible/roles/test/tasks/crm/crm_test_ipv4_route.yml
  ansible/roles/test/tasks/crm/crm_test_ipv6_neighbor.yml
  ansible/roles/test/tasks/crm/crm_test_ipv6_nexthop.yml
  ansible/roles/test/tasks/crm/crm_test_ipv6_route.yml
  ansible/roles/test/tasks/crm/crm_test_nexthop_group.yml
  ansible/roles/test/tasks/crm/crm_test_nexthop_group_member.yml
  ansible/roles/test/tasks/crm/crm_test_threshold.yml
  ansible/roles/test/tasks/crm/crm_test_vnet_bitmap.yml
  ansible/roles/test/tasks/crm/expect_crm_th_clear
  ansible/roles/test/tasks/crm/expect_crm_th_exceeded
  ansible/roles/test/tasks/crm/fdb.json
  tests/crm/conftest.py
  tests/crm/templates/acl.json
  tests/crm/test_crm.py
Labels: Enhancement, Pytest :snake:

#2079 [drop counters] Skip test cases requiring explicit fanout support
  tests/drop_packets/__init__.py
  tests/drop_packets/combined_drop_counters.yml
  tests/drop_packets/drop_packets.py
  tests/drop_packets/test_drop_counters.py
Labels: Cleanup :droplet:, Pytest :snake:

#2086 [testbed_setup] address populate fdb test issue
  ansible/roles/test/files/ptftests/populate_fdb.py
  tests/testbed_setup/test_populate_fdb.py
Labels: Bug :bug:, Pytest :snake:

#2087 [reboot] Fail the test when SSH timeout failure is encountered
  tests/common/reboot.py
Labels: Bug :bug:, Pytest :snake:

#2085 [syslog] address syslog test issues
  tests/syslog/test_syslog.py
  tests/test_cleanup_testbed.py
Labels: Bug :bug:, Cleanup :droplet:, Pytest :snake:

#2089 [kvm] Add missing veos_vtb reference
  tests/veos_vtb
Labels: Bug :bug:, KVM Testing :test_tube:

#2091 Fix the issue of parsing yaml inventory file in the testbed_vm_info module
  ansible/library/testbed_vm_info.py
Labels: Enhancement, Testbed

#2093 [drop counters] Re-add missing json import
  tests/drop_packets/test_drop_counters.py
Labels: Bug :bug:

#2072 Convert inventory files to YAML
  ansible/doc/README.testbed.VsSetup.md
  ansible/example_ixia
  ansible/inventory
  ansible/lab
  ansible/ocp
  ansible/veos
  ansible/veos.vtb
  ansible/veos_vtb
  tests/veos_vtb
Labels: Enhancement

#2039 [Platform API] Add basic tests for Component class
  tests/common/helpers/platform_api/component.py
  tests/platform_tests/api/test_component.py
Labels: Enhancement, Platform, Pytest :snake:

#2028 [everflow] Migrate Everflow v4 tests to use ptfadapter
  tests/everflow/everflow_test_utilities.py
  tests/everflow/test_everflow_ipv6.py
  tests/everflow/test_everflow_testbed.py
Labels: Cleanup :droplet:, Pytest :snake:

#2098 Add "router_mac" to SonicHost.facts
  tests/common/devices.py
Labels: Enhancement, Pytest :snake:

#2100 Ignore snmp subagent errors in loganalyzer
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Enhancement, Pytest :snake:

#2094 [pfcwd] Add option to fake PFC storm and adapt tests
  tests/pfcwd/conftest.py
  tests/pfcwd/test_pfcwd_function.py
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: Enhancement, Pytest :snake:

#2105 Replace all references to 'py.test' with 'pytest'
  ansible/roles/test/tasks/pytest_runner.yml
  tests/docs/pytest.org.md
  tests/run_tests.sh
  tests/show_techsupport/README.md
Labels: Enhancement, Pytest :snake:

#2110 [acl] Reinit ptfadapter before running ACL tests
  tests/acl/test_acl.py
Labels: Bug :bug:, Pytest :snake:

#2104 [test reporting] Add parser to convert JUnit XML to JSON
  test_reporting/README.md
  test_reporting/__init__.py
  test_reporting/junit_xml_parser.py
  test_reporting/requirements.txt
  test_reporting/tests/__init__.py
  test_reporting/tests/files/sample_tr.xml
  test_reporting/tests/test_junit_xml_parser.py
Labels: Pytest :snake:, Testbed

#2097 Add 'mgmt_ip' property to non-localhost ansible hosts
  tests/common/devices.py
Labels: Enhancement, Pytest :snake:

#2117 [pfcwd] Include regexp to ignore invalid OIDs error during loganalysis
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: Enhancement, Pytest :snake:

#2115 [Ansible] Support multiple passwords for SSH connection
  ansible/plugins/connection/multi_passwd_ssh.py
Labels: Enhancement, Testbed

#2125 [dir_bcast] Skip the prefix if not an IPv4 prefix
  ansible/roles/test/files/ptftests/dir_bcast_test.py
Labels: Bug :bug:

#2126 Continuous warm reboot test improvements
  ansible/roles/test/files/ptftests/advanced-reboot.py
  tests/common/fixtures/advanced_reboot.py
  tests/platform_tests/args/cont_warm_reboot_args.py
  tests/platform_tests/test_cont_warm_reboot.py
  tests/ptf_runner.py
Labels: Enhancement, Pytest :snake:

#2141 Added missing import of advanced reboot fixture
  tests/platform_tests/conftest.py
Labels: Bug :bug:, Pytest :snake:

#2142 [pytest]: Make DUT name optional for `run_tests.sh`
  tests/run_tests.sh
Labels: Enhancement

#2135 [docker] Shutdown BGP before swap_syncd to force mgmt route
  tests/common/system_utils/docker.py
Labels: Bug :bug:, Pytest :snake:

#2113 Vnet vxlan pytest conversion
  tests/conftest.py
  tests/vxlan/__init__.py
  tests/vxlan/templates/vnet_config.j2
  tests/vxlan/templates/vnet_interface.j2
  tests/vxlan/templates/vnet_nbr.j2
  tests/vxlan/templates/vnet_routes.j2
  tests/vxlan/templates/vnet_vxlan.j2
  tests/vxlan/test_vnet_vxlan.py
  tests/vxlan/vnet_constants.py
  tests/vxlan/vnet_utils.py
Labels: Pytest :snake:
