Repository sonic-net/sonic-mgmt, pull requests merged in 2020-10, with the labels that each got.

#2229 [Platform API][Thermal] Compare applicable data against values from platform.json
  tests/platform_tests/api/test_thermal.py
Labels: Enhancement, Platform, Pytest :snake:

#2302 [everflow] Make monitor port parsing more robust
  tests/everflow/everflow_test_utilities.py
Labels: Bug :bug:, Master Branch Quality

#2274 [Platform API][Fan][Fan Drawer] add fan tests for fan drawers and compare applicable values against platform.json
  tests/common/helpers/platform_api/fan_drawer_fan.py
  tests/platform_tests/api/test_fan_drawer_fans.py
Labels: Enhancement, Platform, Pytest :snake:

#2305 [Platform API][Fan][PSU] add fan tests for PSU's and compare applicable values against platform.json
  tests/common/helpers/platform_api/psu_fan.py
  tests/platform_tests/api/test_psu_fans.py
Labels: Enhancement, Platform, Pytest :snake:

#2303 [drop counters] Shut link from fanout side for test_egress_drop_on_down_link
  tests/drop_packets/drop_packets.py
Labels: Bug :bug:, Pytest :snake:

#2315 [Platform API][Fans][Pytest] Align file and class naming
  tests/platform_tests/api/test_chassis_fans.py
  tests/platform_tests/api/test_fan_drawer_fans.py
  tests/platform_tests/api/test_psu_fans.py
Labels: Cleanup :droplet:, Platform, Pytest :snake:

#2325 [Platform API][Fan][PSU][FanDrawer] Fix typos in Fan_Drawer_fans test and PSU_fans test
  tests/platform_tests/api/test_fan_drawer_fans.py
  tests/platform_tests/api/test_psu_fans.py
Labels: Bug :bug:, Platform, Pytest :snake:

#2326 [Platform API][pytest] Remove 'self' parameters from method calls
  tests/platform_tests/api/test_chassis_fans.py
  tests/platform_tests/api/test_component.py
  tests/platform_tests/api/test_fan_drawer_fans.py
  tests/platform_tests/api/test_psu.py
  tests/platform_tests/api/test_psu_fans.py
  tests/platform_tests/api/test_sfp.py
  tests/platform_tests/api/test_thermal.py
Labels: Bug :bug:, Platform, Pytest :snake:

#2308 [pytest] Skip testing the auto-restart feature of radv container on T1 devices
  tests/autorestart/test_container_autorestart.py
Labels: Bug :bug:, Pytest :snake:

#2332 [reporting] Add summary message for failures/errors/skipped tests
  test_reporting/junit_xml_parser.py
  test_reporting/tests/test_junit_xml_parser.py
Labels: Enhancement, Pytest :snake:

#2343 [Platform API][Chassis][Module] Remove tests for deprecated, redundant get_serial_number() methods
  tests/common/helpers/platform_api/chassis.py
  tests/common/helpers/platform_api/module.py
  tests/platform_tests/api/test_chassis.py
  tests/platform_tests/api/test_module.py
Labels: Cleanup :droplet:, Platform, Pytest :snake:

#2353 disable loganalyzer for test_watchdog
  tests/platform_tests/api/test_watchdog.py
Labels: Enhancement, Platform, Pytest :snake:

#2368 [broadcom ser] add more misaligned memory entries
  tests/platform_tests/broadcom/files/ser_injector.py
Labels: Bug :bug:, Enhancement, Pytest :snake:

#2337 [pfcwd] Fix pfcwd async fake storm
  tests/common/reboot.py
  tests/common/utilities.py
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: Bug :bug:, Pytest :snake:

#2355 [pfcwd] Filter rx ports out of test ports
  tests/pfcwd/files/pfcwd_helper.py
Labels: Bug :bug:, Pytest :snake:

#2367 [Mellanox] Align sensors labels for human readable output for MSN3420
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Enhancement, Platform

#2366 [Mellanox] Align sensors labels for human readable output for MSN2740
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Enhancement, Platform

#2365 [Mellanox] Align sensors labels for human readable output for MSN2700
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Enhancement, Platform

#2364 [Mellanox] Align sensors labels for human readable output for MSN2410
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Enhancement, Platform

#2363 [Mellanox] Align sensors labels for human readable output for MSN2100
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Enhancement, Platform

#2362 [Mellanox] Align sensors labels for human readable output for MSN2010
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Enhancement, Platform

#2370 [Platform API] Add test cases for new API methods
  tests/common/helpers/platform_api/chassis.py
  tests/common/helpers/platform_api/fan.py
  tests/common/helpers/platform_api/fan_drawer.py
  tests/common/helpers/platform_api/psu.py
  tests/common/helpers/platform_api/sfp.py
  tests/common/helpers/platform_api/thermal.py
  tests/platform_tests/api/test_chassis.py
  tests/platform_tests/api/test_chassis_fans.py
  tests/platform_tests/api/test_fan_drawer.py
  tests/platform_tests/api/test_psu.py
  tests/platform_tests/api/test_sfp.py
  tests/platform_tests/api/test_thermal.py
Labels: Enhancement, Platform, Pytest :snake:

#2388 [Ansible] Add check for duts_name
  ansible/roles/vm_set/tasks/main.yml
Labels: Bug :bug:

#2394 Add 'model' field to DuT in ansible/lab file
  ansible/lab
Labels: Enhancement

#2396 [Platform API][Fan Drawer] Align code with other similar tests
  tests/platform_tests/api/test_fan_drawer.py
Labels: Cleanup :droplet:, Platform, Pytest :snake:

#2395 [Platform API][SFP] Remove 'skip_sanity=True' pytest marker
  tests/platform_tests/api/test_sfp.py
Labels: Cleanup :droplet:

#2245 [Multi asic]:parameterize asic_index and dut_index
  ansible/library/config_facts.py
  tests/bgp/test_bgp_fact.py
  tests/common/devices.py
  tests/common/helpers/constants.py
  tests/conftest.py
Labels: Enhancement

#2403 [platform_tests] Add test to check memory and cpu usage
  ansible/library/monit_process.py
  tests/platform_tests/test_cpu_memory_usage.py
Labels: Pytest :snake:

#2411 [parametize by ports] add infrastructure to allow test parametized by ports
  tests/common/helpers/dut_ports.py
  tests/conftest.py
  tests/metadata/sample-testbed.json
  tests/platform_tests/test_link_flap.py
  tests/test_pretest.py
Labels: Enhancement, Pytest :snake:

#2429 [sensors]: Improve test verbosity/readability
  tests/platform_tests/test_sensors.py
Labels: Enhancement

#2427 [multi-dut] refactoring fanouthosts and conn_graph_facts to be multi-dut ready
  ansible/library/conn_graph_facts.py
  ansible/roles/fanout/templates/arista_7060_deploy.j2
  ansible/roles/fanout/templates/arista_7260cx3_deploy.j2
  ansible/roles/fanout/templates/force10_s6100_deploy.j2
  ansible/roles/fanout/templates/sonic_deploy.j2
  ansible/roles/test/tasks/check_fanout_interfaces.yml
  ansible/roles/test/tasks/continuous_link_flap.yml
  ansible/roles/test/tasks/ecmp.yml
  ansible/roles/test/tasks/interface.yml
  ansible/roles/test/tasks/link_flap.yml
  ansible/roles/test/tasks/pfc_wd.yml
  tests/common/devices.py
  tests/common/fixtures/conn_graph_facts.py
  tests/common/fixtures/pfc_asym.py
  tests/common/ixia/ixia_helpers.py
  tests/common/platform/device_utils.py
  tests/common/plugins/sanity_check/recover.py
  tests/conftest.py
  tests/drop_packets/drop_packets.py
  tests/drop_packets/fanout/mellanox/mellanox_fanout.py
  tests/drop_packets/test_configurable_drop_counters.py
  tests/pc/test_lag_2.py
  tests/pfc/test_pfc_pause_lossless.py
  tests/pfcwd/conftest.py
  tests/platform_tests/mellanox/test_check_sfp_presence.py
  tests/platform_tests/mellanox/test_check_sfp_using_ethtool.py
  tests/platform_tests/test_cont_warm_reboot.py
  tests/platform_tests/test_link_flap.py
  tests/platform_tests/test_reboot.py
  tests/platform_tests/test_reload_config.py
  tests/platform_tests/test_sequential_restart.py
  tests/platform_tests/test_sfp.py
  tests/platform_tests/test_xcvr_info_in_db.py
  tests/qos/qos_fixtures.py
  tests/qos/test_pfc_counters.py
  tests/qos/test_pfc_pause.py
  tests/testbed_setup/test_gen_spy_testbed.py
Labels: Enhancement, Pytest :snake:

#2438 [dual-tor] augment dualtor testbed topology type to t0
  tests/conftest.py
Labels: Enhancement, Pytest :snake:

#2439 [lag 2] parameterize testcase test_lag_2
  tests/pc/test_lag_2.py
Labels: Enhancement, Pytest :snake:
