Repository sonic-net/sonic-mgmt, pull requests merged in 2020-02, with the labels that each got.

#1366 [dhcp-relay] Make mac addresses of ptf interfaces unique
  tests/test_dhcp_relay.py
Labels: Enhancement

#1337 Add 'ptf' to testbed config
  ansible/testbed-cli.sh
  ansible/testbed.csv
  ansible/vtestbed.csv
Labels: Enhancement

#1371 [deploy server] changes to make server deployment smoother
  ansible/roles/vm_set/tasks/docker.yml
  ansible/roles/vm_set/tasks/external_port.yml
  ansible/roles/vm_set/tasks/main.yml
Labels: Request for 201811 branch :shipit:

#1333 Thermal control test
  tests/common/mellanox_data.py
  tests/platform/files/invalid_format_policy.json
  tests/platform/files/invalid_value_policy.json
  tests/platform/files/valid_policy.json
  tests/platform/mellanox/mellanox_thermal_control_test_helper.py
  tests/platform/test_platform_info.py
  tests/platform/thermal_control_test_helper.py
Labels: Enhancement

#1400 [exabgp] Fix start/restart verification condition
  ansible/library/exabgp.py
Labels: Bug

#1402 [bgp] Fix exabgp port used in bgp speaker test
  tests/test_bgp_speaker.py
Labels: Bug

#1409 [link] fix the sonic management docker download link
  ansible/doc/README.testbed.Setup.md
Labels: Enhancement
