Repository sonic-net/sonic-mgmt, pull requests merged in 2020-01, with the labels that each got.

#1310 Reload config from config_db in cleanup section
  ansible/roles/test/tasks/neighbour-mac-noptf.yml
Labels: Bug

#1309 [everflow]: Add test for mirroring ARP/ND packets
  ansible/roles/test/files/acstests/everflow_neighbor_test.py
  ansible/roles/test/tasks/everflow_testbed/run_test.yml
  ansible/roles/test/tasks/everflow_testbed/testcase_6.yml
Labels: Enhancement

#1308 [advanced-reboot] assert on total_disrupt_time
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: Bug, Request for 201811 branch :shipit:

#1346 Revert "[advanced-reboot] assert on total_disrupt_time"
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: Bug, Request for 201811 branch :shipit:

#1356 Added required files as symbolic link
  ansible/roles/eos/templates/t1-64-lag-clet-spine.j2
  ansible/roles/eos/templates/t1-64-lag-clet-tor.j2
Labels: Request for 201811 branch :shipit:

#1357 Fix Ansible compatibility issues in warm-reboot sad scripts
  ansible/roles/test/tasks/warm-reboot-sad-bgp.yml
  ansible/roles/test/tasks/warm-reboot-sad-lag-member.yml
  ansible/roles/test/tasks/warm-reboot-sad-lag.yml
  ansible/roles/test/tasks/warm-reboot-sad-vlan-port.yml
Labels: Bug
