Repository sonic-net/sonic-mgmt, pull requests merged in 2020-07, with the labels that each got.

#1828 Filter out unnecessary PTF logs when calling the ptfadapter plugin
  tests/conftest.py
Labels: Enhancement, Pytest :snake:

#1823 [pytest] Loganalyzer enhancements
  tests/common/plugins/loganalyzer/loganalyzer.py
Labels: Enhancement, Pytest :snake:

#1824 [pytest] Pfcwd warm reboot test
  tests/common/helpers/pfc_storm.py
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: Enhancement, Pytest :snake:

#1825 correct telemetry certs creation to include subject name
  ansible/config_sonic_basedon_testbed.yml
Labels: Bug :bug:, Jenkins-Pilot

#1829 [PDU] Read SNMP community string from pdu.yml
  ansible/group_vars/pdu/pdu.yml
  tests/common/plugins/psu_controller/__init__.py
  tests/common/plugins/psu_controller/snmp_psu_controllers.py
  tests/conftest.py
Labels: Enhancement

#1834 Update README.testbed.VsSetup.md
  ansible/doc/README.testbed.VsSetup.md
Labels: Documentation

#1836 Move pytest doc files to tests/docs
  tests/docs/pytest.logging.md
  tests/pytest.org.md
Labels: Documentation

#1835 [Platform API][pytest] Test inherited methods in Chassis class
  tests/common/helpers/platform_api/chassis.py
  tests/platform_tests/api/conftest.py
  tests/platform_tests/api/test_chassis.py
Labels: Enhancement, Pytest :snake:

#1840 [Platform API][pytest] Minor case adjustments
  tests/platform_tests/api/test_chassis.py
  tests/platform_tests/api/test_watchdog.py
Labels: Cleanup :droplet:

#1842 [Platform API][pytest] Add basic tests for Module class
  tests/common/helpers/platform_api/module.py
  tests/platform_tests/api/test_module.py
Labels: Enhancement, Pytest :snake:

#1844 [sflow] skip sflow test when feature is not enabled
  tests/common/devices.py
  tests/sflow/test_sflow.py
  tests/test_features.py
Labels: Enhancement, Pytest :snake:

#1841 New Pytest testcase - continuous-warm-reboot
  tests/platform_tests/args/cont_warm_reboot_args.py
  tests/platform_tests/conftest.py
  tests/platform_tests/test_cont_warm_reboot.py
Labels: Enhancement, Pytest :snake:

#1854 Pfcwd: copy ptftests dir to ptf
  tests/pfcwd/conftest.py
Labels: Bug :bug:, Pytest :snake:

#1817 [Platform API][pytest] Add basic tests for PSU class
  tests/common/helpers/platform_api/psu.py
  tests/platform_tests/api/test_psu.py
Labels: Enhancement, Pytest :snake:

#1858 Revert "[snmp_interfaces] add snmp interface counters check"
  tests/snmp/test_snmp_interfaces.py
Labels: KVM Testing :test_tube:

#1859 Warm-reboot test fix - remove unicode characters from docstrings
  tests/platform_tests/test_cont_warm_reboot.py
Labels: Bug :bug:, Pytest :snake:

#1860 [kvm] Add VS marker for current set of KVM-compatible test cases
  tests/bgp/test_bgp_fact.py
  tests/bgp/test_bgp_gr_helper.py
  tests/bgp/test_bgp_speaker.py
  tests/cacl/test_control_plane_acl.py
  tests/dhcp_relay/test_dhcp_relay.py
  tests/lldp/test_lldp.py
  tests/ntp/test_ntp.py
  tests/pc/test_po_update.py
  tests/route/test_default_route.py
  tests/snmp/test_snmp_cpu.py
  tests/snmp/test_snmp_interfaces.py
  tests/snmp/test_snmp_lldp.py
  tests/snmp/test_snmp_pfc_counters.py
  tests/snmp/test_snmp_queue.py
  tests/tacacs/test_ro_user.py
  tests/tacacs/test_rw_user.py
  tests/test_interfaces.py
Labels: Enhancement, KVM Testing :test_tube:

#1171 Wrong DIP on packet
  ansible/roles/test/files/ptftests/copp_tests.py
  ansible/roles/test/tasks/copp.yml
Labels: Request for 201811 branch :shipit:

#1861 [test runner] add a script to run pytests
  tests/run_tests.sh
Labels: Enhancement, Pytest :snake:

#1857 Fixing COPP test cases that do not involve policer
  ansible/swap_syncd.yml
  tests/common/system_utils/docker.py
  tests/templates/ptf_nn_agent.conf.dut.j2
Labels: Request for 201811 branch :shipit:

#1867 [Platform API][pytest] Fix Module class tests
  tests/platform_tests/api/test_module.py
Labels: Bug :bug:, Pytest :snake:

#1868 [run_test.sh] fix junit log path for in individual test function
  tests/run_tests.sh
Labels: Bug :bug:, Pytest :snake:

#1865 [mgmt vrf] Fix LGTM and PEP8 errors in mgmt vrf tests
  tests/test_mgmtvrf.py
Labels: Cleanup :droplet:, Pytest :snake:

#1853 [everflow] Add IPv6 Match Tests to Everflow testbed
  tests/everflow/__init__.py
  tests/everflow/everflow_test_utilities.py
  tests/everflow/templates/acl_rule_v6.json.j2
  tests/everflow/test_everflow_ipv6.py
  tests/everflow/test_everflow_testbed.py
Labels: Pytest :snake:

#1877 Add support for starting stopping VMs of specified test setup
  ansible/group_vars/sonic/variables
  ansible/roles/vm_set/tasks/main.yml
  ansible/roles/vm_set/tasks/start.yml
  ansible/roles/vm_set/tasks/stop.yml
  ansible/testbed-cli.sh
Labels: Enhancement

#1878 Add support for starting stopping VMs of specified test setup - 201811
  ansible/group_vars/sonic/variables
  ansible/roles/vm_set/tasks/main.yml
  ansible/roles/vm_set/tasks/start.yml
  ansible/roles/vm_set/tasks/stop.yml
  ansible/testbed-cli.sh
Labels: Enhancement, Included in 201811 branch

#1847 [Mellanox] Change drop_counters infrastructure
  ansible/library/feature_facts.py
  tests/drop_counters/test_drop_counters.py
  tests/drop_packets/acl_templates/acl_rule_del.json
  tests/drop_packets/acl_templates/acltb_test_rule.json
  tests/drop_packets/combined_drop_counters.yml
  tests/drop_packets/configurable_drop_counters.py
  tests/drop_packets/drop_packets.py
  tests/drop_packets/fanout/__init__.py
  tests/drop_packets/fanout/fanout_base.py
  tests/drop_packets/fanout/mellanox/__init__.py
  tests/drop_packets/fanout/mellanox/exec_template.yml
  tests/drop_packets/fanout/mellanox/mellanox_fanout.py
  tests/drop_packets/fanout/mellanox/mlnx_del_of_rule.j2
  tests/drop_packets/fanout/mellanox/mlnx_update_mac.j2
  tests/drop_packets/test_configurable_drop_counters.py
  tests/drop_packets/test_drop_counters.py
Labels: Enhancement

#1893 Copp fix for Non-policier test case
  ansible/roles/test/templates/ptf_nn_agent.conf.dut.j2
  ansible/swap_syncd.yml
Labels: Bug :bug:, Included in 201811 branch

#1891 [tests] add some instructions regarding how to run py tests
  tests/README.md
Labels: Documentation, Pytest :snake:

#1892 [everflow] Fix policer test case failures
  tests/everflow/everflow_test_utilities.py
  tests/everflow/test_everflow_testbed.py
Labels: Bug :bug:, Cleanup :droplet:, Pytest :snake:

#1890 [link flap] disable log analysis for link flap test
  tests/platform_tests/test_link_flap.py
Labels: Bug :bug:, Pytest :snake:

#1903 [util tests] add markers to help reduce util group execution logs
  tests/pytest.ini
  tests/run_tests.sh
  tests/test_announce_routes.py
  tests/test_nbr_health.py
Labels: Enhancement, Pytest :snake:

#1900 Add "-x" bash option to run_tests.sh
  tests/run_tests.sh
Labels: Enhancement, Pytest :snake:

#1908 [201811][bgp_speaker] Terminate all processes with 'exabgp' in the command line
  ansible/roles/test/tasks/bgp_speaker.yml
Labels: Bug :bug:, Included in 201811 branch

#1898 [Ansible] Start ptf_tgen in ptf container
  ansible/roles/vm_set/tasks/add_topo.yml
  ansible/roles/vm_set/tasks/start_ptf_tgen.yml
Labels: Spytest, Testbed

#1848 [Spytest] Add multi-DUT testbed deployment support
  ansible/library/conn_graph_facts.py
  ansible/roles/fanout/tasks/rootfanout_connect.yml
  ansible/roles/vm_set/library/vlan_port.py
  ansible/roles/vm_set/library/vm_topology.py
  ansible/roles/vm_set/tasks/add_topo.yml
  ansible/roles/vm_set/tasks/main.yml
  ansible/roles/vm_set/tasks/remove_topo.yml
  ansible/roles/vm_set/tasks/set_dut_port.yml
  ansible/testbed_add_vm_topology.yml
  ansible/testbed_remove_vm_topology.yml
  ansible/vars/topo_fullmesh.yml
Labels: Enhancement, Spytest, Testbed

#1904 [copp] Fix COPP test failures and make clean-up more robust
  tests/common/system_utils/docker.py
  tests/copp/conftest.py
  tests/copp/copp_utils.py
  tests/copp/test_copp.py
Labels: Bug :bug:, Pytest :snake:

#1915 [201811][bgp_speaker] Ignore errors upon terminating exabgp processes
  ansible/roles/test/tasks/bgp_speaker.yml
Labels: Bug :bug:, Included in 201811 branch

#1917 [ansible] Add revert_syncd task to automate cleaning up after swap_syncd
  ansible/revert_syncd.yml
Labels: Request for 201811 branch :shipit:, Testbed

#1919 [platform] Update SFP keys to reflect new naming convention
  tests/common/platform/transceiver_utils.py
  tests/platform_tests/check_transceiver_status.py
Labels: Enhancement, Platform, Pytest :snake:

#1918 Fix accessing instance attribute in AdvancedReboot
  tests/common/fixtures/advanced_reboot.py
Labels: Bug :bug:

#1880 Integrating IO with continuous warm reboot test
  ansible/roles/test/files/ptftests/advanced-reboot.py
  tests/common/fixtures/advanced_reboot.py
  tests/platform_tests/args/cont_warm_reboot_args.py
  tests/platform_tests/conftest.py
  tests/platform_tests/test_cont_warm_reboot.py
Labels: Enhancement, Pytest :snake:

#1881 [Platform API][watchdog] Inherit from PlatformApiTestBase
  tests/platform_tests/api/test_watchdog.py
Labels: Enhancement, Platform, Pytest :snake:

#1925 [cacl] Update DHCP rules per change in caclmgrd
  tests/cacl/test_cacl_application.py
Labels: Control Plane ACL, Enhancement, Pytest :snake:

#1934 Fix test_watchdog.py import issues
  tests/platform_tests/api/test_watchdog.py
Labels: Bug :bug:, Pytest :snake:

#1932 [test_ntp] Increase NTP sync wait time
  tests/ntp/test_ntp.py
Labels: Bug :bug:, Pytest :snake:

#1913 [fast-reboot]: Increase packet timeout to handle ARP flooding
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: Bug :bug:

#1926 [docs] Add style/documentation guidelines for pytest
  tests/styleguide.md
Labels: Documentation

#1936 [run_test] fix run_test.sh option list issue
  tests/run_tests.sh
Labels: Bug :bug:, Critical, Pytest :snake:

#1938 [pre-test] prepare DUT to run tests when option --deep_clean is provided
  tests/conftest.py
  tests/test_cleanup_dut.py
Labels: Enhancement, Pytest :snake:

#1946 [Platform API] Add status LED tests to Chassis class tests
  tests/common/helpers/platform_api/chassis.py
  tests/platform_tests/api/test_chassis.py
Labels: Enhancement, Platform, Pytest :snake:

#1950 [run_tests.sh] user can specify either topology or test case list
  tests/README.md
  tests/run_tests.sh
Labels: Enhancement, Pytest :snake:

#1951 [IPv6][TACACS]: Run IPv6 TACACS only when ptf docker is configured with IPv6 address
  tests/common/plugins/tacacs.py
Labels: Bug :bug:, Pytest :snake:

#1954 [copp] Remove extra parameter in copp test
  tests/copp/test_copp.py
Labels: Bug :bug:, Pytest :snake:

#1958 Revert "Add AnsibleHost.mgmt_ip and SonicHost.facts['router_mac']"
  tests/common/devices.py
Labels: Bug :bug:, Critical, Pytest :snake:

#1959 [copp] ignore snmp error messages during COPP tests
  tests/copp/test_copp.py
Labels: Bug :bug:, Pytest :snake:

#1952 [kvm/setup] Add script to setup VS management network
  ansible/doc/README.testbed.VsSetup.md
  ansible/setup-management-network.sh
Labels: Enhancement, KVM Testing :test_tube:, Testbed

#1957 Fix pfcwd test errors on T1
  tests/pfcwd/conftest.py
Labels: Bug :bug:, Pytest :snake:

#1960 [po_update] ignore a couple syncd complaints
  tests/pc/test_po_update.py
Labels: Bug :bug:, Pytest :snake:

#1967 [cacl] More robust ACL parsing; No longer expect default drop rules on FORWARD chain
  tests/cacl/test_cacl_application.py
Labels: Control Plane ACL, Enhancement, Pytest :snake:

#1968 [Ixia/Keysight] changing the import statements from common.xxx to tests.common.xxx
  tests/common/ixia/ixia_helpers.py
  tests/ixia/test_ixia_traffic.py
Labels: Bug :bug:, Pytest :snake:

#1963 [sanity check] add BGP to the sanity check list
  ansible/library/bgp_facts.py
  tests/common/devices.py
  tests/common/plugins/sanity_check/README.md
  tests/common/plugins/sanity_check/__init__.py
  tests/common/plugins/sanity_check/checks.py
  tests/common/plugins/sanity_check/constants.py
  tests/common/plugins/sanity_check/recover.py
  tests/conftest.py
Labels: Bug :bug:, Enhancement, Pytest :snake:

#1965 Fix pfcwd error setting poll interval
  tests/pfcwd/conftest.py
Labels: Bug :bug:, Pytest :snake:

#1927 Test completeness feature for Pytests
  tests/common/plugins/custom_markers/__init__.py
  tests/common/plugins/test_completeness/README.md
  tests/common/plugins/test_completeness/__init__.py
  tests/conftest.py
  tests/platform_tests/test_link_flap.py
  tests/pytest.ini
Labels: Enhancement, Pytest :snake:

#1970 [pytest] Allow 'fullmesh' in testbed type check
  tests/conftest.py
Labels: Spytest, Testbed

#1982 Add ipv6 prefixes to vlans
  ansible/templates/minigraph_dpg.j2
  ansible/vars/topo_t0-116.yml
  ansible/vars/topo_t0-16.yml
  ansible/vars/topo_t0-52.yml
  ansible/vars/topo_t0-56.yml
  ansible/vars/topo_t0-64-32.yml
  ansible/vars/topo_t0-64.yml
  ansible/vars/topo_t0.yml
Labels: Enhancement, Request for 201811 branch :shipit:, Testbed

#1990 [run_tests] improve run_tests.sh's usability
  tests/run_tests.sh
Labels: Enhancement, Pytest :snake:

#1977 Image installation during continuous warm reboot test
  tests/common/fixtures/advanced_reboot.py
  tests/platform_tests/args/cont_warm_reboot_args.py
  tests/platform_tests/test_cont_warm_reboot.py
Labels: Enhancement, Pytest :snake:

#1991 [sequential restart] making swss restart test failing as it should be
  tests/common/platform/processes_utils.py
  tests/platform_tests/check_critical_services.py
  tests/platform_tests/test_sequential_restart.py
Labels: Bug :bug:, Pytest :snake:

#1964 [platform][pytest] Create 'cli' subdirectory to house platform-related CLI tests
  tests/platform_tests/cli/__init__.py
  tests/platform_tests/cli/test_show_platform.py
  tests/platform_tests/cli/util.py
  tests/platform_tests/test_platform_info.py
  tests/platform_tests/test_syseeprom.py
Labels: Cleanup :droplet:, Enhancement, Platform, Pytest :snake:

#1986 [pytest]: Fail WR ARP test earlier with empty DIP
  tests/arp/test_wr_arp.py
Labels: Bug :bug:, Pytest :snake:

#1992 [sequential restart] restore DUT health before ending test
  tests/common/platform/processes_utils.py
  tests/platform_tests/test_sequential_restart.py
Labels: Bug :bug:, Pytest :snake:

#1939 Add upgrade_path pytest case
  ansible/library/reduce_and_add_sonic_images.py
  ansible/roles/test/files/ptftests/advanced-reboot.py
  tests/upgrade_path/conftest.py
  tests/upgrade_path/test_upgrade_path.py
Labels: Pytest :snake:

#1987 [Platform API][pytest] basic tests for FAN class
  tests/common/helpers/platform_api/fan.py
  tests/platform_tests/api/test_fan.py
Labels: Enhancement, Platform, Pytest :snake:

#1999 [test-telemetry] add check for docker image
  tests/telemetry/test_telemetry.py
Labels: Enhancement, Pytest :snake:

#2001 [pytest]: add remove_ip.sh and arp_responder.py to ptfhost_utils
  tests/arp/test_wr_arp.py
  tests/bgp/test_bgp_speaker.py
  tests/common/fixtures/ptfhost_utils.py
  tests/decap/test_decap.py
  tests/drop_packets/test_configurable_drop_counters.py
  tests/fdb/test_fdb.py
  tests/ipfwd/test_dip_sip.py
  tests/sflow/test_sflow.py
  tests/vlan/test_vlan.py
  tests/vxlan/test_vxlan_decap.py
Labels: Enhancement, Pytest :snake:
