Repository sonic-net/sonic-mgmt, pull requests merged in 2020-11, with the labels that each got.

#2424 Upgrade path fixes and improvements
  ansible/library/reduce_and_add_sonic_images.py
  ansible/roles/test/files/ptftests/advanced-reboot.py
  tests/common/fixtures/advanced_reboot.py
  tests/upgrade_path/test_upgrade_path.py
Labels: Enhancement, Pytest :snake:

#2442 [Platform API] Add missing tests for new API methods in DeviceBase class
  tests/common/helpers/platform_api/component.py
  tests/common/helpers/platform_api/fan_drawer_fan.py
  tests/common/helpers/platform_api/module.py
  tests/common/helpers/platform_api/psu_fan.py
  tests/platform_tests/api/test_component.py
  tests/platform_tests/api/test_fan_drawer_fans.py
  tests/platform_tests/api/test_module.py
  tests/platform_tests/api/test_psu_fans.py
Labels: Enhancement, Platform, Pytest :snake:

#2401 [acl] Refactor test_acl.py and add t0 support
  tests/acl/templates/acltb_test_rules.j2
  tests/acl/templates/acltb_test_rules_part_2.j2
  tests/acl/test_acl.py
Labels: Enhancement, Pytest :snake:

#2455 [test_reporting] Add default values when combining test results
  test_reporting/junit_xml_parser.py
Labels: Bug :bug:, Pytest :snake:

#2408 [kvm] Re-enable test_po_update for KVM test
  tests/kvmtest.sh
Labels: KVM Testing :test_tube:, Pytest :snake:

#2461 Check CRM limit for route performance test
  tests/route/test_route_perf.py
Labels: Bug :bug:, Pytest :snake:

#2460 [multi-dut] add infrastructure to update dut port to ptf port index map
  tests/common/devices.py
  tests/conftest.py
  tests/pc/test_lag_2.py
Labels: Enhancement, Pytest :snake:

#2456 Fix issue: psu_fan.get_status_led argument error
  tests/common/helpers/platform_api/psu_fan.py
  tests/platform_tests/api/test_fan_drawer.py
  tests/platform_tests/api/test_sfp.py
Labels: Bug :bug:, Platform

#2384 [Mellanox] Adjust test case due to support of PSU max fan speed
  tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
  tests/platform_tests/mellanox/test_thermal_control.py
Labels: Enhancement

#2389 Converted port_toggle test and continuous_link_flap test to pytest
  tests/common/port_toggle.py
  tests/platform_tests/conftest.py
  tests/platform_tests/link_flap/__init__.py
  tests/platform_tests/link_flap/conftest.py
  tests/platform_tests/link_flap/link_flap_utils.py
  tests/platform_tests/link_flap/test_cont_link_flap.py
  tests/platform_tests/link_flap/test_link_flap.py
  tests/platform_tests/test_link_flap.py
  tests/platform_tests/test_port_toggle.py
Labels: Pytest :snake:

#2469 [multi DUT] making test_nbr_health multi-DUT ready
  tests/test_nbr_health.py
Labels: Enhancement, Pytest :snake:

#2470 [multi-dut] making test_show_features multi-dut ready
  tests/test_features.py
Labels: Enhancement, Pytest :snake:

#2404 [platform api] Fix argument mismatch in platform API test
  tests/common/helpers/platform_api/fan_drawer_fan.py
  tests/common/helpers/platform_api/psu_fan.py
  tests/platform_tests/api/test_fan_drawer_fans.py
  tests/platform_tests/api/test_module.py
  tests/platform_tests/api/test_psu_fans.py
Labels: Enhancement, Pytest :snake:

#2471 [multi-DUT] making test_interfaces multi-DUT ready
  tests/test_interfaces.py
Labels: Enhancement, Pytest :snake:

#2473 [copp] Clean-up apt lists before updating and installing NN packages
  tests/copp/copp_utils.py
Labels: Bug :bug:, Pytest :snake:

#2475 [multi-dut] Make test_posttest and test_pretest multi-dut ready
  tests/test_posttest.py
  tests/test_pretest.py
Labels: Enhancement, Pytest :snake:

#2474 [SonicHost] Ignore non-zero return code from 'supervisorctl status' in critical_process_status()
  tests/common/devices.py
Labels: Bug :bug:

#2481 [cont_link_flap] address issue in fixture bring_up_fanout_interfaces
  tests/platform_tests/link_flap/conftest.py
  tests/platform_tests/link_flap/link_flap_utils.py
  tests/platform_tests/link_flap/test_cont_link_flap.py
Labels: Bug :bug:, Pytest :snake:

#2483 [ptf map] address ptf map indexing issue
  tests/common/devices.py
Labels: Bug :bug:, Pytest :snake:

#2494 [enumerators] unify naming convention of the parameter enumerators
  tests/bgp/test_bgp_fact.py
  tests/conftest.py
  tests/pc/test_lag_2.py
  tests/platform_tests/link_flap/test_link_flap.py
  tests/test_features.py
  tests/test_interfaces.py
  tests/test_nbr_health.py
  tests/test_posttest.py
  tests/test_pretest.py
Labels: Cleanup :droplet:, Enhancement, Pytest :snake:

#2484 [link flap] replace bring_up_fanout_interfaces with in place restoration
  tests/platform_tests/link_flap/conftest.py
  tests/platform_tests/link_flap/link_flap_utils.py
  tests/platform_tests/link_flap/test_cont_link_flap.py
  tests/platform_tests/link_flap/test_link_flap.py
Labels: Enhancement, Pytest :snake:

#2487 [Mellanox] Align sensors labels for human readable output for MSN4700
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Enhancement

#2503 Fix issue: the 10G ports are lost from ptf port map
  tests/common/fixtures/ptfhost_utils.py
Labels: Bug :bug:

#2528 [testbed] don't silently prefer testbed.yaml over testbed.csv
  tests/common/testbed.py
Labels: Pytest :snake:

#2530 [pytest] Skip ‘dsserve’ process in syncd when testing autorestart
  tests/autorestart/test_container_autorestart.py
Labels: Bug :bug:

#2531 Fix COPP regression error
  tests/copp/test_copp.py
Labels: Bug :bug:, Pytest :snake:

#2536 [test_nbr_health] ignore SmartCable and/or peer neighbor
  tests/test_nbr_health.py
Labels: Enhancement, Pytest :snake:

#2535 [arp cleaner] add a fixture to cleanup accumulated arp entries
  tests/conftest.py
Labels: Enhancement, Pytest :snake:

#2534 [acl] update acl test to make it almost dualtor ready
  tests/acl/test_acl.py
  tests/common/devices.py
  tests/pc/test_lag_2.py
Labels: Enhancement, Pytest :snake:

#2533 [autorestart] parametize autorestart test
  tests/autorestart/test_container_autorestart.py
  tests/common/devices.py
  tests/conftest.py
  tests/test_pretest.py
Labels: Enhancement, Pytest :snake:

#2544 [SonicHost] Also ignore non-zero return code from 'supervisorctl status' when checking PMon container
  tests/common/devices.py
Labels: Bug :bug:

#2522 [upgrade_sonic] Support upgrading all DUTs in testbed
  ansible/upgrade_sonic.yml
Labels: Enhancement

#2546 Fix the next hop ips for T0-56 topo
  ansible/vars/topo_t0-56.yml
Labels: Bug :bug:, Testbed

#2551 [Platform API][Module] Use proper variable to index lists
  tests/platform_tests/api/test_module.py
Labels: Bug :bug:, Platform

#2545 Modify reboot test to check for activating state of warmboot_finalizer
  tests/common/reboot.py
Labels: Bug :bug:, Pytest :snake:

#2560 Skip traffic generator tests in nightly
  tests/ixia/test_ixia_traffic.py
  tests/ixia/test_tgen.py
Labels: Bug :bug:, Pytest :snake:

#2561 [reporting] Add option to skip over malformed tr.xml files
  test_reporting/junit_xml_parser.py
Labels: Bug :bug:, Pytest :snake:

#2566 test_pfc_pause - fix file path issue and use PTF fixtures
  tests/qos/qos_helpers.py
  tests/qos/test_pfc_pause.py
Labels: Bug :bug:, Enhancement

#2567 [lldpctl patch] patch lldpctl script to work around ansible bug
  tests/conftest.py
  tests/ipfwd/test_dip_sip.py
  tests/lldp/test_lldp.py
  tests/snmp/test_snmp_lldp.py
Labels: Bug :bug:, Pytest :snake:

#2550 [Platform_api test] Add a "--skip-absent-sfp" option to rule out absent Transceivers from SFP Platform API tests
  tests/platform_tests/api/test_sfp.py
  tests/platform_tests/args/api_sfp_args.py
  tests/platform_tests/conftest.py
Labels: Enhancement, Platform

#2542 [minigraph facts] get minigraph facts through get_extended_minigraph_facts() method
  tests/acl/test_acl.py
  tests/arp/test_arpall.py
  tests/arp/test_wr_arp.py
  tests/bgp/test_bgp_multipath_relax.py
  tests/bgp/test_bgp_speaker.py
  tests/common/fixtures/advanced_reboot.py
  tests/common/fixtures/pfc_asym.py
  tests/common/fixtures/populate_fdb.py
  tests/common/port_toggle.py
  tests/copp/test_copp.py
  tests/crm/conftest.py
  tests/dhcp_relay/test_dhcp_pkt_fwd.py
  tests/dhcp_relay/test_dhcp_relay.py
  tests/drop_packets/drop_packets.py
  tests/drop_packets/test_configurable_drop_counters.py
  tests/ecmp/test_fgnhg.py
  tests/everflow/everflow_test_utilities.py
  tests/everflow/test_everflow_testbed.py
  tests/fdb/test_fdb_mac_expire.py
  tests/fib/test_fib.py
  tests/iface_namingmode/test_iface_namingmode.py
  tests/ipfwd/test_dip_sip.py
  tests/ipfwd/test_dir_bcast.py
  tests/lldp/test_lldp.py
  tests/pc/test_po_cleanup.py
  tests/pc/test_po_update.py
  tests/pfcwd/conftest.py
  tests/platform_tests/conftest.py
  tests/platform_tests/link_flap/test_cont_link_flap.py
  tests/platform_tests/mellanox/test_check_sfp_using_ethtool.py
  tests/platform_tests/test_cont_warm_reboot.py
  tests/platform_tests/test_port_toggle.py
  tests/platform_tests/test_sfp.py
  tests/qos/qos_sai_base.py
  tests/sflow/test_sflow.py
  tests/show_techsupport/test_techsupport.py
  tests/snmp/test_snmp_lldp.py
  tests/test_interfaces.py
  tests/upgrade_path/test_upgrade_path.py
  tests/vxlan/__init__.py
  tests/vxlan/test_vxlan_decap.py
Labels: Enhancement, Pytest :snake:
