Repository sonic-net/sonic-mgmt, pull requests merged in 2020-06, with the labels that each got.

#1718 [pytest ini] remove norecursedirs option
  tests/pytest.ini
Labels: Bug :bug:, Pytest :snake:

#1722 [sonic image installer] remove config_db.json before booting into new image
  ansible/library/reduce_and_add_sonic_images.py
Labels: Bug :bug:, Request for 201811 branch :shipit:

#1719 [pytest/sanity_check]: use show ip[v6] bgp summary
  tests/common/plugins/sanity_check/constants.py
Labels: Bug :bug:

#1723 [advanced-reboot] Fix use of inventory file
  tests/common/fixtures/advanced_reboot.py
Labels: Bug :bug:

#1725 [wr_arp] Fix use of inventory file
  tests/arp/test_wr_arp.py
Labels: Bug :bug:

#1729 Check if /etc/sonic/core_analyzer.rc.json exists before update
  ansible/config_sonic_basedon_testbed.yml
Labels: Request for 201811 branch :shipit:

#1710 Improve the pytest logging
  ansible/ansible.cfg
  tests/common/devices.py
  tests/conftest.py
  tests/pytest.ini
  tests/pytest.logging.md
Labels: Enhancement, Pytest :snake:

#1736 [testbed] Fix YAML spacing issue in config_sonic_based_on_testbed
  ansible/config_sonic_basedon_testbed.yml
Labels: Bug :bug:, Testbed

#1726 [201811] Qos SAI test restructure
  ansible/group_vars/sonic/vars
  ansible/roles/test/tasks/qos_get_ports.yml
  ansible/roles/test/tasks/qos_sai.yml
  ansible/vars/qos.yml
Labels: Enhancement, Included in 201811 branch

#1730 [conn_graph_facts] Get graph facts for all fanouts connected to the DUT
  tests/common/fixtures/conn_graph_facts.py
Labels: Bug :bug:, Pytest :snake:

#1734 [pytest] Adds test metadata to pytest xml report
  tests/conftest.py
Labels: Jenkins-Pilot

#1715 [ixia] enable stand alone system centered by an Ixia tester
  ansible/example_ixia
  ansible/files/creategraph.py
  ansible/files/example_ixia_connection_graph.xml
  ansible/files/sonic_example_ixia_devices.csv
  ansible/files/sonic_example_ixia_link.csv
  ansible/group_vars/all/inv_mapping.yml
  ansible/group_vars/example-ixia/example-ixia.yml
  ansible/group_vars/example-ixia/secrets.yml
  ansible/library/conn_graph_facts.py
  ansible/testbed.csv
  tests/common/devices.py
Labels: Enhancement, Pytest :snake:

#1743 [platform] Move system EEPROM tests to separate file
  tests/platform_tests/test_platform_info.py
  tests/platform_tests/test_syseeprom.py
Labels: Jenkins-Pilot, Pytest :snake:

#1534 [pytest/pfc_asym] Convert PFC asymmetric to pytest
  ansible/roles/test/tasks/pfc_asym.yml
  ansible/roles/test/templates/pfc_storm_stop_mlnx.j2
  tests/common/devices.py
  tests/common/fixtures/pfc_asym.py
  tests/common/helpers/generators.py
  tests/conftest.py
  tests/pfc_asym/conftest.py
  tests/pfc_asym/test_pfc_asym.py
  tests/saitests/pfc_asym.py
  tests/scripts/arp_responder.py
  tests/scripts/exec_template.yml
Labels: Jenkins-Pilot

#1746 [spytest]: Add execute permissions
  spytest/bin/python
  spytest/bin/spytest
  spytest/bin/upgrade_requirements.sh
Labels: Bug :bug:, Spytest

#1757 [devices] Refactor critical services to be a DUT property
  tests/common/devices.py
  tests/conftest.py
  tests/platform_tests/check_critical_services.py
  tests/test_vrf.py
Labels: Cleanup :droplet:, Jenkins-Pilot, Pytest :snake:

#1754 [loganalyzer] Address whitespace issue and write marker to syslog after update
  tests/common/plugins/loganalyzer/README.md
  tests/common/plugins/loganalyzer/loganalyzer.py
Labels: Bug :bug:, Jenkins-Pilot, Pytest :snake:

#1741 [pytest] Convert FDB MAC Expire Test
  ansible/roles/test/templates/fdb.j2
  tests/fdb/__init__.py
  tests/fdb/args/__init__.py
  tests/fdb/args/fdb_args.py
  tests/fdb/conftest.py
  tests/fdb/files/fdb.j2
  tests/fdb/test_fdb_mac_expire.py
Labels: Jenkins-Pilot

#1770 [kvm] Allow user to specify location for KVM image files
  ansible/roles/vm_set/tasks/start_sonic_vm.yml
Labels: Jenkins-Pilot, KVM Testing :test_tube:, Testbed

#1745 [advanced-reboot] Change Dest IP of VM/Server Originated Packets
  tests/common/fixtures/advanced_reboot.py
Labels: Bug :bug:

#1776 [pytest]: parsing multiple whitespaces correct for ip route info
  tests/common/devices.py
Labels: Bug :bug:

#1764 [pfc_wd] Detach pfc_gen.py from terminal when run in background on Me…
  ansible/roles/test/templates/pfc_storm_mlnx.j2
Labels: Request for 201811 branch :shipit:

#1783 [doc]: change lab server to 18.04
  ansible/doc/README.testbed.Setup.md
Labels: Cleanup :droplet:

#1748 [pytest] Make Copy [ptf,sai,acs]tests Fixture Session Scope
  tests/arp/test_wr_arp.py
  tests/bgp/test_bgp_speaker.py
  tests/common/fixtures/advanced_reboot.py
  tests/common/fixtures/pfc_asym.py
  tests/common/fixtures/populate_fdb.py
  tests/common/fixtures/ptfhost_utils.py
  tests/common/plugins/ansible_fixtures.py
  tests/conftest.py
  tests/copp/copp_utils.py
  tests/decap/test_decap.py
  tests/dhcp_relay/test_dhcp_relay.py
  tests/everflow/test_everflow_testbed.py
  tests/fdb/test_fdb.py
  tests/fdb/test_fdb_mac_expire.py
  tests/fib/test_fib.py
  tests/ipfwd/test_dip_sip.py
  tests/ipfwd/test_dir_bcast.py
  tests/ipfwd/test_mtu.py
  tests/pc/test_lag_2.py
  tests/pfc_asym/conftest.py
  tests/pfcwd/conftest.py
  tests/qos/qos_sai_base.py
  tests/sflow/test_sflow.py
  tests/test_vrf.py
  tests/vxlan/test_vxlan_decap.py
Labels: Jenkins-Pilot

#1759 [Platform API][pytest] Add basic tests for Chassis class
  tests/common/helpers/platform_api/chassis.py
  tests/platform_tests/api/test_chassis.py
Labels: Enhancement, Pytest :snake:

#1751 Convert portstat test to pytest
  ansible/roles/test/tasks/portstat.yml
  ansible/roles/test/tasks/portstat/portstat_all_fields.yml
  ansible/roles/test/tasks/portstat/portstat_clear.yml
  ansible/roles/test/tasks/portstat/portstat_delete_all_no_saved_stats.yml
  ansible/roles/test/tasks/portstat/portstat_delete_all_stats.yml
  ansible/roles/test/tasks/portstat/portstat_delete_tag.yml
  ansible/roles/test/tasks/portstat/portstat_period.yml
  tests/portstat/test_portstat.py
Labels: Pytest :snake:

#1742 Add support of running general Ansible modules on EosHost
  ansible/group_vars/all/creds.yml
  tests/common/devices.py
  tests/conftest.py
Labels: Jenkins-Pilot

#1765 [pytest] PFCwd functional test
  ansible/roles/test/files/helpers/pfc_gen.py
  ansible/roles/test/tasks/pfc_wd/functional_test/ignore_pfc_wd_messages
  ansible/roles/test/templates/pfc_storm_arista.j2
  ansible/roles/test/templates/pfc_storm_icos.j2
  ansible/roles/test/templates/pfc_storm_mlnx.j2
  ansible/roles/test/templates/pfc_storm_stop_arista.j2
  ansible/roles/test/templates/pfc_storm_stop_icos.j2
  ansible/roles/test/templates/pfc_storm_stop_mlnx.j2
  tests/common/errors.py
  tests/common/helpers/pfc_gen.py
  tests/common/helpers/pfc_storm.py
  tests/common/templates/pfc_storm_arista.j2
  tests/common/templates/pfc_storm_icos.j2
  tests/common/templates/pfc_storm_mlnx.j2
  tests/common/templates/pfc_storm_stop_arista.j2
  tests/common/templates/pfc_storm_stop_icos.j2
  tests/common/templates/pfc_storm_stop_mlnx.j2
  tests/pfcwd/__init__.py
  tests/pfcwd/conftest.py
  tests/pfcwd/files/pfcwd_helper.py
  tests/pfcwd/templates/ignore_pfc_wd_messages
  tests/pfcwd/test_pfcwd_function.py
Labels: Enhancement, Jenkins-Pilot, Pytest :snake:

#1766 [pytest] PFCwd all port storm and restore test
  tests/pfcwd/test_pfcwd_all_port_storm.py
Labels: Enhancement, Jenkins-Pilot, Pytest :snake:

#1756 [Platform API] HTTP server provides default JSON serialization for unserializable objects
  tests/common/helpers/platform_api/scripts/platform_api_server.py
Labels: Enhancement

#1739 Fix the issue of unprintable RunAnsibleModuleFail object
  tests/common/errors.py
Labels: Bug :bug:, Critical, Pytest :snake:

#1696 [drop counters] Adds initial support for testing configurable drop counters
  tests/common/devices.py
  tests/drop_counters/configurable_drop_counters.py
  tests/drop_counters/test_configurable_drop_counters.py
  tests/drop_counters/test_drop_counters.py
Labels: Jenkins-Pilot, New, Pytest :snake:

#1787 [pytest] Fixed PFC asymmetric test case
  tests/common/devices.py
  tests/scripts/exec_template.yml
Labels: Bug :bug:, Pytest :snake:

#1803 Fix PFC ansible testcase config error of poll time greater than detection/restoration time.
  ansible/roles/test/tasks/pfc_wd.yml
Labels: Request for 201811 branch :shipit:

#1789 [pytest] Pfcwd timer test
  tests/pfcwd/conftest.py
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: Enhancement, Pytest :snake:

#1806 [spytest] Support junit-xml
  spytest/spytest/framework.py
Labels: Bug :bug:, Spytest

#1809 [ntp] Improve NTP test stability and reduce chatty output
  tests/ntp/test_ntp.py
Labels: Bug :bug:, Enhancement, Jenkins-Pilot, Pytest :snake:

#1774 Increase installation required space
  ansible/library/reduce_and_add_sonic_images.py
Labels: Bug :bug:

#1804 [pytest][platform] Check serial, base MAC and EEPROM data against expected values
  ansible/lab
  tests/platform_tests/api/test_chassis.py
Labels: Enhancement, Pytest :snake:

#1811 [device] get attributes from super class when unavailabe
  tests/common/devices.py
Labels: Bug :bug:, Pytest :snake:

#1815 [reboot] ignore module failure when checking SSH port status
  tests/common/reboot.py
Labels: Bug :bug:, Pytest :snake:

#1820 [service_acl] Wait until SSH is in 'stopped' state rather than waiting for 'started' state to timeout
  ansible/roles/test/tasks/service_acl.yml
Labels: Enhancement, Request for 201811 branch :shipit:

#1786 Workaround for no Exception issue for some failed ansible modules
  tests/common/devices.py
Labels: Pytest :snake:

#1749 [Platform API] Make HTTP server deployment more robust
  tests/platform_tests/api/conftest.py
Labels: Enhancement, Pytest :snake:

#1822 [Platform API] HTTP server handles NotImplementedError
  tests/common/helpers/platform_api/scripts/platform_api_server.py
Labels: Enhancement

#1830 [Platform API][pytest] Add basic tests for SFP class
  tests/common/helpers/platform_api/sfp.py
  tests/platform_tests/api/platform_api_test_base.py
  tests/platform_tests/api/test_sfp.py
Labels: Enhancement, Pytest :snake:
