Repository sonic-net/sonic-mgmt, pull requests merged in 2020-09, with the labels that each got.

#2128 [qos] Add buffer pool watermark tests
  tests/qos/test_qos_sai.py
Labels: Enhancement, Pytest :snake:

#2177 [copp] Skip adding loganalyzer regex when loganalyzer is disabled
  tests/copp/test_copp.py
Labels: Bug :bug:

#2161 [loganalyzer] Forcely-rotate logs before adding marker
  tests/common/plugins/loganalyzer/__init__.py
Labels: Design Review Needed, Pytest :snake:

#2164 [iface_namingmode] Get port_speed from DUT host variables
  tests/iface_namingmode/test_iface_namingmode.py
Labels: Bug :bug:, Pytest :snake:

#2149 Test Completeness enhancements - new diagnose level and helper methods
  tests/common/plugins/test_completeness/README.md
  tests/common/plugins/test_completeness/__init__.py
  tests/platform_tests/test_link_flap.py
Labels: Enhancement, Pytest :snake:

#2176 New 7260cx3 deployment template
  ansible/roles/fanout/templates/arista_7260cx3_deploy.j2
Labels: Testbed

#2182 [bgp_speaker(ipv6)] Fix bug in test_bgp_speaker_announce_routes_v6
  tests/bgp/test_bgp_speaker.py
Labels: Bug :bug:, Pytest :snake:

#2133 [everflow] Refactor Everflow tests to support different config modes
  ansible/roles/test/tasks/everflow_testbed/del_config/acl_rule_persistent-del.json
  tests/everflow/everflow_test_utilities.py
  tests/everflow/files/acl-remove.json
  tests/everflow/files/dscp_test_rules.yaml
  tests/everflow/files/ipv4_test_rules.yaml
  tests/everflow/files/ipv6_test_rules.yaml
  tests/everflow/templates/acl-erspan.json.j2
  tests/everflow/templates/acl_rule_persistent.json.j2
  tests/everflow/templates/acl_rule_v6.json.j2
  tests/everflow/test_everflow_ipv6.py
  tests/everflow/test_everflow_testbed.py
Labels: Cleanup :droplet:, Pytest :snake:

#2188 [pytest] Update plugin path for pytest
  tests/plugins
Labels: Bug :bug:, Pytest :snake:

#2189 [pytest] Move qos ptf_portmap arg to the global conftest
  tests/conftest.py
  tests/qos/args/qos_sai_args.py
Labels: Enhancement, Pytest :snake:

#2202 [broadcom ser] make a backup sshd_config and restore it after test
  tests/platform_tests/broadcom/test_ser.py
Labels: Bug :bug:, Pytest :snake:

#2203 [iface_namingmode] Convert iface_speed to string
  tests/iface_namingmode/test_iface_namingmode.py
Labels: Bug :bug:

#2193 [pytest] Add auto-restart related functions in devices.py
  tests/common/devices.py
Labels: Enhancement, Pytest :snake:

#2190 [pytest] support for integrating platform.json static data retrieval for platform_api tests
  tests/common/devices.py
  tests/platform_tests/api/test_fan_drawer.py
Labels: Enhancement, Pytest :snake:

#2194 [conn graph] add support for multiple graph files
  ansible/files/empty_graph.xml
  ansible/files/graph_files.yml
  ansible/library/conn_graph_facts.py
  ansible/roles/fanout/tasks/rootfanout_connect.yml
Labels: Enhancement

#2208 Continuous warm reboot test parameters changes
  ansible/roles/test/files/ptftests/advanced-reboot.py
  tests/platform_tests/args/cont_warm_reboot_args.py
  tests/platform_tests/test_cont_warm_reboot.py
Labels: Enhancement, Pytest :snake:

#2207 [everflow] Use correct j2 filter for acl.json template
  tests/everflow/templates/acl-erspan.json.j2
Labels: Bug :bug:, Pytest :snake:

#2201 [qos] Move the ptf portmap files to the tests dir
  ansible/roles/test/files/brcm/64_interface_to_front_map.ini
  ansible/roles/test/files/brcm/66_interface_to_front_map.ini
  ansible/roles/test/files/brcm/d108c8_interface_to_front_map.ini
  ansible/roles/test/files/mlnx/default_interface_to_front_map.ini
  tests/qos/files/brcm/64_interface_to_front_map.ini
  tests/qos/files/brcm/66_interface_to_front_map.ini
  tests/qos/files/brcm/d108c8_interface_to_front_map.ini
  tests/qos/files/mellanox/default_interface_to_front_map.ini
Labels: Enhancement, Pytest :snake:

#2210 [Platform API][pytest] Handle both 'str' and 'unicode' string types in Python 2
  tests/platform_tests/api/test_component.py
  tests/platform_tests/api/test_fan.py
  tests/platform_tests/api/test_fan_drawer.py
  tests/platform_tests/api/test_module.py
  tests/platform_tests/api/test_psu.py
  tests/platform_tests/api/test_sfp.py
  tests/platform_tests/api/test_thermal.py
Labels: Bug :bug:, Enhancement, Platform, Pytest :snake:

#2212 [crm] Fix test_crm teardown
  tests/crm/conftest.py
Labels: Bug :bug:, Pytest :snake:

#1769 [pytest] Test the autorestart feature of containers
  tests/autorestart_test/test_container_autorestart.py
Labels: Enhancement, Pytest :snake:

#2214 [reporting] Add testbed and timestamp to JUnit test reports
  test_reporting/junit_xml_parser.py
  test_reporting/tests/files/sample_archive/tr_1.xml
  test_reporting/tests/files/sample_archive/tr_2.xml
  test_reporting/tests/files/sample_tr.xml
  test_reporting/tests/test_junit_xml_parser.py
  tests/conftest.py
Labels: Pytest :snake:

#2144 [framework] Add support for skipping cases according to asic type
  tests/common/helpers/assertions.py
  tests/common/plugins/custom_fixtures/__init__.py
  tests/common/plugins/custom_fixtures/check_dut_asic_type.py
  tests/conftest.py
Labels: Design Review Needed, Enhancement

#2215 [interface util] use "show interface description" instead
  tests/common/platform/interface_utils.py
Labels: Bug :bug:, Pytest :snake:

#2184 [fanouthosts] Support SONiC fanout switches
  tests/common/devices.py
  tests/conftest.py
Labels: Enhancement, Pytest :snake:

#2218 [reporting] Relax test reporting format rules
  test_reporting/junit_xml_parser.py
  test_reporting/tests/files/sample_archive/nested_archive/test_2.xml
  test_reporting/tests/files/sample_archive/test_1.xml
  test_reporting/tests/test_junit_xml_parser.py
Labels: Pytest :snake:

#2223 [Pytest] Fix container autorestart commands
  tests/autorestart_test/test_container_autorestart.py
Labels: Bug :bug:

#2227 Arista-7060CX-32S-Q32 SKU addition in mg facts
  ansible/library/minigraph_facts.py
Labels: Testbed

#2224 [conn graph] refactoring connection graph look up code
  ansible/library/conn_graph_facts.py
Labels: Enhancement

#2238 [qos] Skip loganalyzer update when disabled and expand loganalyzer ignore list
  tests/qos/qos_sai_base.py
Labels: Bug :bug:, Enhancement, Pytest :snake:

#2226 [pytest conn graph] leverage the conn_graph_facts.py lookup capability
  ansible/library/conn_graph_facts.py
  tests/common/fixtures/conn_graph_facts.py
Labels: Enhancement, Spytest

#2222 [reporting] Improve accuracy of generated JSON report
  test_reporting/junit_xml_parser.py
  test_reporting/tests/test_junit_xml_parser.py
Labels: Pytest :snake:

#2225 [reporting] Add DB connector and report uploader script for kusto
  test_reporting/report_data_storage.py
  test_reporting/report_uploader.py
  test_reporting/requirements.txt
Labels: Pytest :snake:

#2243 [qos] Dynamically generate the PTF to interface mapping
  tests/qos/qos_sai_base.py
Labels: Enhancement, Pytest :snake:

#2251 [test_gen_spy_testbed] Fix import error
  tests/testbed_setup/test_gen_spy_testbed.py
Labels: Bug :bug:, Pytest :snake:

#2247 Update paths to reflect new sonic-utilities install location, /usr/local/bin/
  ansible/vars/configlet/t1-64-lag-clet/apply_clet.sh
  tests/scripts/fast-reboot
Labels: Enhancement

#2256 Creds access fix for virtual testbed
  tests/conftest.py
Labels: Bug :bug:, Pytest :snake:

#2254 [qos] Fine tune Th xon params
  tests/qos/files/qos.yml
Labels: Bug :bug:, Pytest :snake:

#2253 [qos] Add qos params for Th 50G 300m
  tests/qos/files/qos.yml
Labels: Enhancement, Pytest :snake:

#2209 [Platform API][Chassis] Compare applicable data against values from platform.json
  tests/platform_tests/api/test_chassis.py
Labels: Enhancement, Platform, Pytest :snake:

#2258 [reporting] Add Kusto scripts for setup and common functions
  test_reporting/kusto/flat_views.kql
  test_reporting/kusto/heat_maps.kql
  test_reporting/kusto/reports.kql
  test_reporting/kusto/setup.kql
Labels: Enhancement

#2259 [Platform API][SFP] Compare applicable data against values from platform.json
  tests/platform_tests/api/test_sfp.py
Labels: Enhancement, Platform, Pytest :snake:

#2264 [pytest] Get critical process list for PMon container
  tests/common/devices.py
Labels: Bug :bug:, Pytest :snake:

#2244 [pfcwd] Support SONiC fanout
  ansible/roles/test/templates/pfc_storm_arista.j2
  ansible/roles/test/templates/pfc_storm_mlnx.j2
  ansible/roles/test/templates/pfc_storm_stop_arista.j2
  ansible/roles/test/templates/pfc_storm_stop_mlnx.j2
  tests/common/devices.py
  tests/common/helpers/pfc_storm.py
  tests/common/templates/pfc_storm_eos.j2
  tests/common/templates/pfc_storm_onyx.j2
  tests/common/templates/pfc_storm_sonic.j2
  tests/common/templates/pfc_storm_stop_eos.j2
  tests/common/templates/pfc_storm_stop_onyx.j2
  tests/common/templates/pfc_storm_stop_sonic.j2
Labels: Enhancement, Pytest :snake:

#2268 [Platform API][Chassis][SFP] Fail applicable tests if unable to retrieve expected data
  tests/platform_tests/api/test_chassis.py
  tests/platform_tests/api/test_sfp.py
Labels: Enhancement, Platform, Pytest :snake:

#2266 [pfcwd] Fix AttributeError due to incorrect var name
  tests/common/helpers/pfc_storm.py
Labels: Bug :bug:, Pytest :snake:

#2267 [Platform API][PSU][Component] Compare applicable data against values from platform.json
  tests/platform_tests/api/test_component.py
  tests/platform_tests/api/test_psu.py
Labels: Enhancement, Platform, Pytest :snake:

#2270 [Mellanox] Fix issue: fan speed tolerance for mellanox platform should be 50 now
  tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
Labels: Enhancement, Platform

#2273 [Platform API][SFP] Add missing 'self.' prefix on class method call
  tests/platform_tests/api/test_sfp.py
Labels: Bug :bug:, Platform, Pytest :snake:

#2219 [Platform API][Fan] Compare applicable data against values from platform.json
  tests/platform_tests/api/test_fan.py
Labels: Enhancement, Platform, Pytest :snake:

#2277 [fanout.yml] Fix SONiC fanout setup
  ansible/roles/fanout/tasks/fanout_sonic.yml
  ansible/roles/fanout/templates/sonic_deploy.j2
Labels: Bug :bug:

#2297 [drop counters] Disable IGMP test for testbeds without proper fanout support
  tests/drop_packets/drop_packets.py
Labels: Bug :bug:, Pytest :snake:

#2296 [acl] Make Config DB recovery more robust
  tests/acl/test_acl.py
  tests/common/fixtures/duthost_utils.py
Labels: Bug :bug:, Pytest :snake:
