Repository sonic-net/sonic-mgmt, pull requests merged in 2020-04, with the labels that each got.

#1504 Enable core uploader service
  ansible/config_sonic_basedon_testbed.yml
Labels: Enhancement, Request for 201811 branch :shipit:

#1515 [version list] add method to get sonic version list
  tests/common/devices.py
Labels: Enhancement

#1516 [swap_syncd] Port swap_syncd task to pytest
  tests/common/broadcom_data.py
  tests/common/system_utils/__init__.py
  tests/common/system_utils/docker.py
Labels: Enhancement

#1488 Convert dip_sip ansible test to pytest
  ansible/roles/test/files/ptftests/dip_sip.py
  ansible/roles/test/tasks/dip_sip.yml
  tests/dip_sip/test_dip_sip.py
Labels: Enhancement

#1537 [pmon daemon check] refactoring pmon daemon state check code
  tests/common/devices.py
  tests/common/platform/daemon_utils.py
  tests/platform/check_daemon_status.py
  tests/platform/test_reboot.py
Labels: Enhancement

#1544 [lgtm] Configure LGTM to analyze test code
  lgtm.yml
Labels: Enhancement

#1524 [Mellanox] Fix issues for thermal control test cases
  tests/platform/files/invalid_value_policy.json
  tests/platform/mellanox/mellanox_thermal_control_test_helper.py
  tests/platform/test_platform_info.py
Labels: Enhancement

#1551 [advanced reboot] Add Paramiko module for device connection (#1542)
  ansible/roles/test/files/ptftests/advanced-reboot.py
  ansible/roles/test/files/ptftests/device_connection.py
  ansible/roles/test/files/ptftests/sad_path.py
  ansible/roles/test/tasks/ptf_runner_reboot.yml
Labels: Enhancement, Included in 201811 branch

#1522 Configure and enable core uploader
  ansible/config_sonic_basedon_testbed.yml
  ansible/group_vars/all/corefile_uploader.yml
Labels: Request for 201811 branch :shipit:

#1558 [ansible] Increase DUT reboot command timeout
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: Enhancement

#1562 changes to make PR#1561 compatible for 201811
  ansible/roles/test/tasks/qos_sai.yml
Labels: Bug, Included in 201811 branch

#1561 Added iptables rules to make sure BGP don't ack back to BGP peer syn messages
  ansible/roles/test/tasks/qos_sai.yml
Labels: Enhancement, Included in 201811 branch, Request for 201811 branch :shipit:

#1566 [fanout switch] build fanout switch list from device_conn map
  tests/common/devices.py
  tests/conftest.py
Labels: Bug, Enhancement

#1575 [pytest/creds]: load groups vars into creds for the dut
  tests/conftest.py
  tests/veos.vtb
Labels: Bug, Pytest

#1565 SPyTest documentation initial version
  spytest/Doc/arch.jpg
  spytest/Doc/install.md
  spytest/Doc/intro.md
  spytest/Doc/ptf.jpg
  spytest/Doc/scapy.gif
  spytest/Doc/tgen.jpg
  spytest/Doc/topo.png
Labels: Spytest

#1573 [link flap] add link flap pytest
  ansible/library/show_interface.py
  tests/common/platform/device_utils.py
  tests/platform/test_link_flap.py
  tests/pytest.ini
Labels: New, Pytest

#1568 [Mellanox] Fix sensor data for 3700
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Bug

#1567 [Mellanox] Fix issue: remove non-exist sensor sysfs files for 4700
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Bug

#1564 [bug fix]SNMP LLDP test failure due to mgmt port not been ruled out
  tests/snmp/test_snmp_lldp.py
Labels: Bug, Pytest

#1546 [test/features] Add test for show features command
  tests/test_features.py
Labels: Enhancement, Pytest

#1592 [pytest assersion] introduce assertion handling code
  tests/common/helpers/assertions.py
Labels: Enhancement, Pytest

#1583 [recovery] introduce adaptive recover method
  tests/common/devices.py
  tests/common/plugins/sanity_check/__init__.py
  tests/common/plugins/sanity_check/constants.py
  tests/common/plugins/sanity_check/recover.py
Labels: Enhancement, Pytest

#1548 [test/procdockerstatsd] Verify daemon is active/running and uploads data successfully
  tests/test_procdockerstatsd.py
Labels: Enhancement

#1530 [tests/telemetry] Verify default config parameters
  tests/telemetry/test_telemetry.py
Labels: Enhancement, Pytest

#1600 [pytest/test_default_route]: support 4.9 kernel 201911/201811 release
  tests/route/test_default_route.py
Labels: Enhancement, Pytest

#1617 [sanity_checks]: add critical process check in sanity checks
  tests/common/devices.py
  tests/common/plugins/sanity_check/checks.py
  tests/common/plugins/sanity_check/constants.py
  tests/common/plugins/sanity_check/recover.py
Labels: Enhancement, Pytest

#1611 [sensors] Fix wrapper for sensors test
  ansible/roles/sonic-common/tasks/sensors_check.yml
  ansible/roles/test/tasks/sensors_check.yml
Labels: Enhancement, Pytest

#1619 [loganalyzer] Fail flag support in context manager and callback execution
  tests/common/plugins/loganalyzer/loganalyzer.py
Labels: Bug :bug:

#1608 Flush ptf rx buffer before ptf send packet.
  ansible/roles/test/files/ptftests/vxlan-decap.py
Labels: InProgress

#1631 [test plans] Moving test plans from sonic-wiki repo to sonic-mgmt repo
  docs/ACL-test-plan.md
  docs/BGP-GR-helper-mode-test-plan.md
  docs/BGP-MP-test-plan.md
  docs/CRM-test-plan.md
  docs/Everflow-test-plan.md
  docs/IPv4-Decapsulation-test.md
  docs/QoS-configuration-in-Config-DB.-ECN-WRED-configuration-utility-test-plan.md
  docs/VLAN-trunk-test-plan.md
Labels: Test Plan

#1580 [Mellanox] Adjust test cases for fan led support
  tests/platform/mellanox/mellanox_thermal_control_test_helper.py
  tests/platform/test_platform_info.py
  tests/platform/thermal_control_test_helper.py
Labels: Enhancement
