Repository sonic-net/sonic-mgmt, pull requests merged in 2020-12, with the labels that each got.

#2605 [copp] Make LLDP disable/enable more robust
  tests/copp/test_copp.py
Labels: Enhancement, Pytest :snake:

#2606 [copp] Update COPP tests to handle coppmgr config format
  tests/copp/copp_utils.py
  tests/copp/scripts/update_copp_config.py
Labels: Enhancement, Pytest :snake:

#2379 [snmp] Add test cases for SONiC physical entity MIB feature
  ansible/library/snmp_facts.py
  tests/snmp/test_snmp_phy_entity.py
Labels: Enhancement

#2615 [autorestart] address log analyzer issues in autorestart test
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
  tests/autorestart/test_container_autorestart.py
Labels: Bug :bug:, Enhancement

#2616 [qos] Fix parameter overwrite issue
  tests/qos/test_qos_sai.py
Labels: Bug :bug:, Pytest :snake:

#2618 [qos] Disable bgpmon and fix loganalyzer regex
  tests/qos/qos_sai_base.py
Labels: Bug :bug:, Pytest :snake:

#2619 [bgp] Fix 'test_bgp_update_timer'
  tests/bgp/conftest.py
  tests/bgp/test_bgp_update_timer.py
Labels: Bug :bug:, Pytest :snake:

#2624 [qos] Replace assert with pytest_assert
  tests/qos/qos_sai_base.py
Labels: Cleanup :droplet:, Pytest :snake:

#2434 [kvm] Enable loganalyzer for KVM tests
  tests/kvmtest.sh
Labels: KVM Testing :test_tube:

#2628 [ser] refacoring Broadcom SER test
  tests/common/devices.py
  tests/platform_tests/broadcom/files/ser_injector.py
Labels: Enhancement, Pytest :snake:

#2632 [bgp] Bind IP directly to interface
  tests/bgp/conftest.py
Labels: Bug :bug:, Pytest :snake:

#2630 [autorestart] ignore more error messages observed in tests
  tests/autorestart/test_container_autorestart.py
Labels: Bug :bug:, Pytest :snake:

#2642 Ignore non-zero return code in get_pmon_daemon_states
  tests/common/devices.py
Labels: Bug :bug:, Platform

#2645 [devutils] add utilities to handle devices
  ansible/devutils
  ansible/inv_helpers.py
Labels: Enhancement, Testbed

#2643 [copp] Send traffic over a set period of time for COPP testing
  ansible/roles/test/files/ptftests/copp_tests.py
  tests/copp/conftest.py
  tests/copp/test_copp.py
Labels: Enhancement, Pytest :snake:

#2650 [ser] add more memory to skip list for TH platform
  tests/platform_tests/broadcom/files/ser_injector.py
Labels: Enhancement

#2672 [pfc] Fix variable return type
  tests/conftest.py
Labels: Bug :bug:, Pytest :snake:

#2662 [ptf] Support alt_password for PTF to DUT SSH connection
  ansible/roles/test/files/ptftests/advanced-reboot.py
  ansible/roles/test/files/ptftests/device_connection.py
  tests/upgrade_path/test_upgrade_path.py
Labels: Pytest :snake:

#2715 [install image] work around for slow disk devices
  ansible/library/reduce_and_add_sonic_images.py
Labels: Enhancement

#2717 [slow disk] pass module into the workaround function
  ansible/library/reduce_and_add_sonic_images.py
Labels: Bug :bug:
