Repository sonic-net/sonic-mgmt, pull requests merged in 2021-08, with the labels that each got.

#3917 Skip snmp default route testcase on T1 backend
  tests/snmp/test_snmp_default_route.py
Labels: Enhancement, Pytest :snake:

#3920 [test_default_route] Fix false pass on backend T1
  tests/route/test_default_route.py
Labels: Bug :bug:, Pytest :snake:

#3796 [t0-56] test_sflow adaptation to t0-56 topology
  ansible/roles/test/files/ptftests/sflow_test.py
  tests/sflow/test_sflow.py
Labels: Request for 201911 branch

#3930 [rdma] Skip warm reboot tests on Td2
  tests/ixia/__init__.py
  tests/ixia/files/__init__.py
  tests/ixia/files/helper.py
  tests/ixia/pfc/test_pfc_pause_lossless.py
  tests/ixia/pfc/test_pfc_pause_lossy.py
  tests/ixia/pfcwd/test_pfcwd_basic.py
Labels: Enhancement, Pytest :snake:

#3946 QoS test cases fixes for TD3 based systems
  tests/qos/files/qos.yml
  tests/qos/qos_sai_base.py
Labels: Master Branch Quality

#3949 [tests/run_tests] Support deselect specific test case
  tests/run_tests.sh
Labels: Enhancement

#3947 TH3 test parameters for Dell Z9332 systems
  ansible/group_vars/sonic/variables
  tests/qos/files/qos.yml
  tests/qos/qos_sai_base.py
Labels: Master Branch Quality

#3975 [everflow] Skip everflow tests on backend topology
  tests/everflow/conftest.py
Labels: Enhancement, Pytest :snake:, backend

#3977 [dhcp_relay] Skip dhcp relay tests on backend topology
  tests/dhcp_relay/conftest.py
Labels: Enhancement, Pytest :snake:, backend

#3983 [pfcwd] Skip pfcwd warm reboot tests on Td2
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: Bug :bug:, Pytest :snake:

#3801 [drop_counters]: Adopt test to t0-56: handle VLAN IGMP flooding
  tests/common/helpers/drop_counters/drop_counters.py
Labels: Bug :bug:

#4005 [memory_checker] Skip testing against DuT of Celestica E1031.
  tests/memory_checker/test_memory_checker.py
Labels: Bug :bug:

#3788 ARP: Modified '/arp/test_neighbor_mac_noptf.py' testcase to skip 'bgp shutdown all' for modular chassis
  tests/arp/test_neighbor_mac_noptf.py
Labels: chassis

#4044 Fix duplicate module name
  tests/common/devices/sonic.py
Labels: Bug :bug:

#4053 [202012] [test_autonegotiation] Skip autoneg testcase on older images - unsupported CLI
  tests/platform_tests/test_auto_negotiation.py
Labels: Bug :bug:

#4087 Skip python coredump check for 201911
  tests/platform_tests/verify_dut_health.py
Labels: Request for 201911 branch

#4036 [qos] Add support for backend topology
  tests/qos/files/qos.yml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/sai_qos_tests.py
Labels: Enhancement, Pytest :snake:

#4055 [platform][test_auto_negotiation] Fix issue where the port selection exceed boundary
  tests/common/devices/eos.py
  tests/common/devices/sonic.py
  tests/platform_tests/test_auto_negotiation.py
Labels: Bug :bug:

#4066 [test_bgp_bounce] Fix BGP template issues
  tests/bgp/templates/bgp_no_export.j2
  tests/bgp/templates/bgp_plain.j2
  tests/bgp/test_bgp_bounce.py
Labels: Bug :bug:, backend
