Repository sonic-net/sonic-mgmt, pull requests merged in 2021-03, with the labels that each got.

#3041 [pdu controller] refactoring snmp pdu controller
  tests/common/plugins/pdu_controller/controller_base.py
  tests/common/plugins/pdu_controller/pdu_manager.py
  tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Labels: Enhancement

#3070 multi-asic support for test_cacl_application.py
  ansible/library/config_facts.py
  tests/cacl/test_cacl_application.py
  tests/common/devices.py
Labels: Control Plane ACL, Enhancement

#3068 [pfcwd] Update topo for warm reboot test
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: Bug :bug:, Pytest :snake:

#3052 Add test for soft-reboot
  tests/common/reboot.py
  tests/platform_tests/test_reboot.py
Labels: Enhancement, Platform, Pytest :snake:

#3008 [rdma] Test if mmu change has impact on pfcwd functionality
  tests/pfcwd/test_pfcwd_function.py
Labels: Enhancement, Pytest :snake:

#3098 [dualtor] Add server traffic utility
  tests/common/devices/vmhost.py
  tests/common/dualtor/server_traffic_utils.py
  tests/common/utilities.py
  tests/conftest.py
Labels: Dual ToR Orchagent Test Dev :o:

#3113 Common timer values for testing watchdog API for DellEMC platforms
  tests/platform_tests/api/watchdog.yml
Labels: Platform

#3120 [Platform API][SFP] Log warnings, don't fail test if newly-added xcvr info fields missing
  tests/platform_tests/api/test_sfp.py
Labels: Platform

#3042 DHCP Relay Testing for Dual ToR
  ansible/roles/test/files/ptftests/dhcp_relay_test.py
  tests/dhcp_relay/test_dhcp_relay.py
Labels: DHCP Relay, Pytest :snake:

#3131 [acl] Use config CLI instead of sonic-cfggen to create ACL table
  tests/acl/templates/acltb_table.j2
  tests/acl/test_acl.py
Labels: Cleanup :droplet:, Pytest :snake:

#3142 [platform_test/api]: fix psu key in test_psu_fans
  tests/platform_tests/api/test_psu_fans.py
Labels: Bug :bug:, Platform

#3139 Add rw file change sanity check for secureboot
  tests/common/plugins/sanity_check/checks.py
Labels: Pytest :snake:

#3166 [tacacs] Check if commands exist on the device before attempting to run them
  tests/tacacs/test_ro_user.py
Labels: Bug :bug:

#3171 [Monit] Increase maximum value of Monit stable time in sanity check.
  tests/common/plugins/sanity_check/checks.py
Labels: Bug :bug:

#3117 Convert tests test_cpu_memory_usage, test_port_toggle to support T2 c…
  tests/common/devices/sonic.py
  tests/platform_tests/cli/test_show_chassis_module.py
  tests/platform_tests/test_cpu_memory_usage.py
  tests/platform_tests/test_port_toggle.py
  tests/platform_tests/test_thermal_state_db.py
Labels: Enhancement, Platform

#3194 [pfcwd] Address the start-limit hit failure for swss restart testcases
  tests/ixia/pfcwd/test_pfcwd_basic.py
Labels: Bug :bug:, Pytest :snake:

#3191 [tacacs] Address race conditions during TACACS server setup/teardown
  tests/common/plugins/tacacs.py
  tests/tacacs/test_rw_user.py
Labels: Bug :bug:, Critical

#3170 [copp_test]Increase the PPS_LIMIT_MAX to absorb the deviation in slower server case
  ansible/roles/test/files/ptftests/copp_tests.py
Labels: Bug :bug:

#3184 [warm-reboot] Fix test to catch reboot errors and verify warmboot finalizer states
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: Bug :bug:, Pytest :snake:

#3221 [ Issue 3061 ] Fix for ptf topo creation
  ansible/roles/vm_set/tasks/add_topo.yml
Labels: Bug :bug:

#3074 [Dynamic Buffer Calc] Enhance dynamic buffer calculation test
  tests/qos/args/buffer_args.py
  tests/qos/conftest.py
  tests/qos/files/dynamic_buffer_param.json
  tests/qos/qos_sai_base.py
  tests/qos/test_buffer.py
Labels: Enhancement
