Repository sonic-net/sonic-mgmt, pull requests merged in 2021-10, with the labels that each got.

#4380 [rdma] Reset-failed for swss dependent services
  tests/ixia/pfcwd/test_pfcwd_basic.py
Labels: Bug :bug:, Pytest :snake:

#4428 [tests/common] Checking device Asic type for Cisco platform
  tests/common/cisco_data.py
Labels: cisco

#4446 Update homebrew ansible modules to use log rotation
  ansible/roles/vm_set/library/ceos_network.py
  ansible/roles/vm_set/library/kickstart.py
  ansible/roles/vm_set/library/sonic_kickstart.py
  ansible/roles/vm_set/library/vm_topology.py
Labels: Testbed

#3762 Changing show chassis-module cli command as per PR 805
  tests/platform_tests/cli/test_show_chassis_module.py
Labels: chassis

#4582 Fix issue: should check remote file existence in ThermalPolicyFileContext
  tests/platform_tests/thermal_control_test_helper.py
Labels: Bug :bug:
