Repository sonic-net/sonic-mgmt, pull requests merged in 2021-05, with the labels that each got.

#3185 Add tests cont_link_flap, system_health, platform_info, reboot to run on T2 topology for VoQ chassis
  tests/common/platform/interface_utils.py
  tests/common/platform/transceiver_utils.py
  tests/platform_tests/conftest.py
  tests/platform_tests/link_flap/test_cont_link_flap.py
  tests/platform_tests/test_platform_info.py
  tests/platform_tests/test_reboot.py
  tests/platform_tests/thermal_control_test_helper.py
  tests/system_health/test_system_health.py
Labels: Enhancement, chassis

#3424 [qos] Enable PG Shared Watermark tests on Th2
  tests/qos/test_qos_sai.py
  tests/saitests/sai_qos_tests.py
  tests/saitests/switch.py
Labels: Enhancement, Pytest :snake:

#3431 [dualtor][orch] Fix TUNNEL config error - use sonic-cfggen to add TUNNEL table to config DB
  tests/common/dualtor/dual_tor_mock.py
Labels: Bug :bug:, Pytest :snake:

#3411 Use supervisorctl to restart the thermalctl processes on pmon docker
  tests/platform_tests/thermal_control_test_helper.py
Labels: Bug :bug:, Platform

#3438 [wr_arp] Fix test_wr_arp - use vxlan_port defined in DUT in the response packet
  tests/arp/files/ferret.py
  tests/arp/test_wr_arp.py
Labels: Bug :bug:, Pytest :snake:

#3436 [dualtor][orch] Fix errors in MUX_CABLE table to config DB: add one-shot config
  tests/common/dualtor/dual_tor_mock.py
Labels: Bug :bug:, Pytest :snake:

#3439 [rdma] Disable loganalyzer for pfc reboot testcases
  tests/ixia/pfc/test_pfc_pause_lossless.py
  tests/ixia/pfc/test_pfc_pause_lossy.py
Labels: Bug :bug:, Pytest :snake:

#3153 Updated test params for QoS/MMU for Arista-7050CX3-32S-C32 & Arista-7050CX3-32S-D48C8
  ansible/group_vars/sonic/variables
  tests/qos/files/qos.yml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: Request for 202012 branch

#3398 [pytest] Test the feature of monitoring critical processes by Monit.
  tests/process_monitoring/test_critical_process_monitoring.py
Labels: New

#3389 [crm] only set ARP cache limit setting when needed
  tests/crm/test_crm.py
Labels: Enhancement

#3447 [psu] share the PSU line pattern across tests
  tests/common/platform/device_utils.py
  tests/platform_tests/cli/test_show_platform.py
  tests/platform_tests/test_platform_info.py
Labels: Bug :bug:

#3446 [advanced-reboot] Add timing data for finalizer, first lag, port init and ASIC views
  tests/platform_tests/conftest.py
  tests/platform_tests/templates/expect_boot_messages
Labels: Enhancement, Pytest :snake:

#3450 [Mellanox] Align PSU fan name convention change with production code
  tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
Labels: Enhancement, Platform

#3373 [Mellanox][platform] Adjust test case according to get_fan_direction update
  tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
Labels: Platform

#3451 [Mellanox] Adjust sensor test to support MSN4700 A0/A1
  ansible/group_vars/sonic/sku-sensors-data.yml
  tests/platform_tests/test_sensors.py
Labels: Platform

#3453 [advance-reboot] Create summarized report of reboot timing data
  ansible/roles/test/files/ptftests/advanced-reboot.py
  tests/platform_tests/conftest.py
  tests/platform_tests/templates/expect_boot_messages
Labels: Pytest :snake:

#3178 Fixed command /usr/bin/thermalctld to /usr/local/bin/thermalctld in platform test
  tests/platform_tests/test_platform_info.py
Labels: Bug :bug:, Platform

#3460 [Mellanox] Fixed validation for test_show_platform_syseeprom
  tests/platform_tests/cli/test_show_platform.py
Labels: Bug :bug:, Platform

#3474 [subport] Make ptf cleanup an autouse fixture
  tests/sub_port_interfaces/conftest.py
Labels: Pytest :snake:

#3464 [test_reporting] Add upload script instructions to README
  test_reporting/README.md
Labels: Documentation

#3501 Fixed issue: Fan fault warning cleared is not present in log
  tests/platform_tests/test_platform_info.py
Labels: Bug :bug:

#3467 [DHCP relay] Add back the unicast mac testcase but skip in multi-vlan settings
  ansible/roles/test/files/ptftests/dhcp_relay_test.py
  tests/dhcp_relay/test_dhcp_relay.py
Labels: DHCP Relay

#3504 [pytest] Update the image version
  tests/process_monitoring/test_critical_process_monitoring.py
Labels: Bug :bug:

#3466 [platform_tests][api] Add hardware revision test case to chassis and psu
  tests/common/helpers/platform_api/chassis.py
  tests/common/helpers/platform_api/psu.py
  tests/platform_tests/api/test_chassis.py
  tests/platform_tests/api/test_psu.py
Labels: Enhancement, Platform

#3416 [Platform API] Use correct key name, 'psus'
  tests/platform_tests/api/test_psu_fans.py
Labels: Bug :bug:, Platform

#3401 Fix log error in check fan fault status
  tests/platform_tests/mellanox/check_sysfs.py
Labels: Bug :bug:, Platform

#3516 [wr-arp] Fix auth errors in test_wr_arp - enable alt_password connection mechanism
  ansible/roles/test/files/ptftests/wr_arp.py
  tests/arp/test_wr_arp.py
Labels: Bug :bug:, Pytest :snake:

#3512 [pfcwd] Fix log message logic to indicate correct db based on buffer model
  tests/pfcwd/test_pfcwd_function.py
Labels: Bug :bug:, Pytest :snake:

#3527 minigraph: Add the ability to set a per-port speed in the minigraph
  ansible/config_sonic_basedon_testbed.yml
  ansible/library/conn_graph_facts.py
  ansible/templates/minigraph_device.j2
Labels: Enhancement, Testbed

#3376 Add test cases for port auto negotiation feature
  tests/common/devices/fanout.py
  tests/common/devices/onyx.py
  tests/common/devices/sonic.py
  tests/conftest.py
  tests/platform_tests/test_auto_negotiation.py
Labels: New

#3547 [Mellanox] update sensor test case for MSN4600 A0 and A1 system
  ansible/group_vars/sonic/sku-sensors-data.yml
  tests/platform_tests/test_sensors.py
Labels: Enhancement, Platform
