Repository sonic-net/sonic-mgmt, pull requests merged in 2021-11, with the labels that each got.

#4574 [platform_tests/api]: Adding Cisco-8000 platform watchdog thresholds
  tests/platform_tests/api/watchdog.yml
Labels: chassis

#4418 everflow_ipv6: fix packet format (change source IP from multicast to unicast)
  tests/everflow/files/ipv6_test_rules.yaml
  tests/everflow/test_everflow_ipv6.py
Labels: cisco

#3764 [rsyslog] Fixing pretest and posttest checks for multiasic boards
  tests/common/devices/multi_asic.py
  tests/test_posttest.py
  tests/test_pretest.py
Labels: chassis

#4596 [pytest][nhop resources] Filter out inband port when run on a chassis
  tests/common/devices/sonic.py
  tests/common/devices/sonic_asic.py
  tests/common/helpers/platform_api/chassis.py
  tests/ipfwd/test_nhop_count.py
  tests/pfcwd/conftest.py
  tests/qos/qos_sai_base.py
Labels: chassis

#4583 [topo]: Fix BGP IPv6 flapping for t0-56-po2vlan
  ansible/vars/topo_t0-56-po2vlan.yml
Labels: Bug :bug:

#4543 Adding support for cisco platform to combined_drop_counters yaml file
  tests/drop_packets/combined_drop_counters.yml
Labels: chassis

#4665 [snmp_pdu_controller] Fix issue: should use 0 to power off Emerson PDU
  tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Labels: Bug :bug:

#4508 sonic-mgmt voq test fix
  ansible/TestbedProcessing.py
  tests/conftest.py
  tests/voq/conftest.py
  tests/voq/test_voq_ipfwd.py
  tests/voq/voq_helpers.py
Labels: chassis

#4688 [link_flap] Check presence of PORTCHANNEL before checking portchannel status
  tests/platform_tests/link_flap/test_cont_link_flap.py
Labels: Bug :bug:

#4752 [container]: Refactor setup container script
  setup-container.sh
Labels: Bug :bug:, Enhancement, Testbed

#4072 Adding support for Nokia Linecard and supervisor card in port_utils
  ansible/module_utils/port_utils.py
Labels: chassis
