Repository sonic-net/sonic-mgmt, pull requests merged in 2021-02, with the labels that each got.

#2904 [everflow] Fix mirror session parsing on 201911 images
  tests/everflow/everflow_test_utilities.py
Labels: Bug :bug:, Pytest :snake:

#2894 [kvmtest] Clear cache before subsequent PR test runs
  tests/kvmtest.sh
Labels: KVM Testing :test_tube:, Pytest :snake:

#2850 [dualtor] Set selected ToR as active.
  tests/common/dualtor/mux_simulator_control.py
  tests/conftest.py
  tests/dualtor/conftest.py
Labels: Dual ToR Test Dev :gemini:

#2909 [acl] Skip IPv6 dataacl tests on 201911 images
  tests/acl/test_acl.py
Labels: Bug :bug:

#2906 [kvmtest]: add multipath relex and bbr to t1-lag kvmtest
  tests/kvmtest.sh
Labels: KVM Testing :test_tube:

#2916 [sonic_upgrade] Clean up previous downloads before downloading new image
  ansible/library/reduce_and_add_sonic_images.py
Labels: Bug :bug:, Testbed

#2913 [kvmtest]: add bgp update_timer/traffic shift tests
  tests/kvmtest.sh
Labels: KVM Testing :test_tube:

#2917 [.gitignore] Add auto-generated files to .gitignore
  .gitignore
Labels: Cleanup :droplet:

#2902 [devutils] add PDU support: status/on/off/reboot
  ansible/devutils
  tests/common/plugins/psu_controller/snmp_psu_controllers.py
Labels: Enhancement

#2810 Warm upgrade and continuous warm reboot modifications for KVM
  ansible/library/reduce_and_add_sonic_images.py
  tests/platform_tests/args/cont_warm_reboot_args.py
  tests/platform_tests/test_cont_warm_reboot.py
  tests/upgrade_path/test_upgrade_path.py
Labels: Enhancement, KVM Testing :test_tube:, Pytest :snake:

#2919 [swap_syncd] Improve log messages and clean-up docker code
  tests/common/system_utils/docker.py
  tests/qos/qos_sai_base.py
Labels: Cleanup :droplet:, Enhancement

#2928 [Platform API] Ignore iptables delete failure in stop_platform_api_service fixture
  tests/platform_tests/api/conftest.py
Labels: Bug :bug:, Platform

#2931 [ci] Fix ownership of workspace directory before checking out sonic-mgmt
  .azure-pipelines/run-test-template.yml
Labels: Bug :bug:, ci

#2932 Fix interface_check failure in test_cont_warm_reboot
  tests/platform_tests/test_cont_warm_reboot.py
Labels: Bug :bug:, Pytest :snake:

#2925 Fix issue: there could be more than 2 thermalctld processes
  tests/platform_tests/thermal_control_test_helper.py
Labels: Bug :bug:, Platform

#2941 [ptf] switch over to generic ptf dockers
  ansible/library/test_facts.py
  ansible/testbed.csv
  docs/testbed/README.testbed.Cli.md
  docs/testbed/README.testbed.Config.md
Labels: Enhancement

#2811 Use cached testbedInfo and host_vars in inventory in dut selection fixtures
  tests/common/helpers/dut_utils.py
  tests/conftest.py
Labels: chassis

#2942 [eos vm] enable ports by default
  ansible/roles/eos/templates/t0-leaf-lag-2.j2
  ansible/roles/eos/templates/t0-leaf.j2
  ansible/roles/eos/templates/t1-64-lag-tor.j2
  ansible/roles/eos/templates/t1-lag-spine.j2
  ansible/roles/eos/templates/t1-lag-tor.j2
Labels: Enhancement

#2700 [multi-dut] Support for gen-mg to work with multi-dut where VM's connect to only a single host and supervisor card
  ansible/config_sonic_basedon_testbed.yml
  ansible/library/topo_facts.py
  ansible/templates/minigraph_cpg.j2
  ansible/templates/minigraph_device.j2
  ansible/templates/minigraph_dpg.j2
  ansible/templates/minigraph_png.j2
  ansible/templates/minigraph_template.j2
Labels: chassis

#2962 [watchdog.yml] Add test values for DellEMC S6100
  tests/platform_tests/api/watchdog.yml
Labels: Platform

#2930 [TACACS] Test that 'sudo pcieutil check' works for read-only user
  tests/tacacs/test_ro_user.py
Labels: Enhancement

#2915 [port toggle] Clean up port toggle library and increase default timeouts
  tests/common/port_toggle.py
Labels: Enhancement, Pytest :snake:

#2933 [qos] Ignore sdk messages during port pause
  tests/qos/qos_sai_base.py
Labels: Enhancement, Pytest :snake:

#2884 [rdma] Add reboot and restart scenarios for pfcwd
  tests/ixia/pfcwd/test_pfcwd_basic.py
Labels: Enhancement, Pytest :snake:

#2975 Fix the bgpmon flakyness
  tests/bgp/test_bgpmon.py
Labels: Bug :bug:

#2974 [report_uploader] Add support for uploading ICMP ping data from devutils
  test_reporting/report_data_storage.py
  test_reporting/report_uploader.py
Labels: Enhancement

#2976 [pdu] flatten the PDU status data
  ansible/devutils
Labels: Enhancement

#2794 Introduce framework for filtering/selecting pluggable components for sonic modular chassis
  tests/platform_tests/cli/test_show_chassis_module.py
  tests/platform_tests/cli/util.py
  tests/platform_tests/test_power_budget_info.py
Labels: chassis

#2978 [device map] fix device map creation issue and caching issue
  tests/common/devices.py
  tests/kvmtest.sh
  tests/test_pretest.py
Labels: Bug :bug:, Enhancement

#2986 [wr_arp] add timeout to thread join
  ansible/roles/test/files/ptftests/wr_arp.py
Labels: Bug :bug:

#2972 Update watchdog.yaml with arista watchdog config
  tests/platform_tests/api/watchdog.yml
Labels: Enhancement, Platform

#2953 Add a fixture to disable thermal policy
  tests/platform_tests/test_platform_info.py
  tests/platform_tests/thermal_control_test_helper.py
  tests/system_health/test_system_health.py
Labels: Bug :bug:, Platform

#2989 [Platform API][Thermal]: Include 0 in range of valid low threshold, temperature values
  tests/platform_tests/api/test_thermal.py
Labels: Bug :bug:, Platform

#2901 DualTor data plane IO test utilities
  ansible/roles/test/files/ptftests/dualtor_sniffer.py
  tests/common/dualtor/data_plane_utils.py
  tests/common/dualtor/dual_tor_io.py
Labels: Dual ToR Test Dev :gemini:, Pytest :snake:

#2990 [nat] skip nat test when image doesn't have nat feature enabled
  tests/nat/conftest.py
Labels: Enhancement

#2895 [kvmtest]: Add dual ToR ARP tests to KVM test suite
  tests/kvmtest.sh
Labels: KVM Testing :test_tube:

#2991 [pfcwd] Disable fake storm on Mellanox platforms
  tests/pfcwd/conftest.py
  tests/pfcwd/test_pfcwd_function.py
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: Bug :bug:

#2887 Parse platform.json, hwsku.json for generate minigraph
  ansible/library/port_alias.py
Labels: Enhancement

#2994 Fix bug which hangs the test if warmboot has an issue
  tests/common/reboot.py
Labels: Bug :bug:, Pytest :snake:

#2822 [testbed.csv] Add new fields
  ansible/library/test_facts.py
  ansible/testbed.csv
  ansible/vtestbed.csv
  docs/testbed/README.new.testbed.Configuration.md
  docs/testbed/README.testbed.Cli.md
  docs/testbed/README.testbed.Config.md
  tests/common/testbed.py
Labels: Testbed

#2996 [rdma] Minor fixes
  tests/ixia/ecn/files/helper.py
  tests/ixia/pfc/files/helper.py
  tests/ixia/pfcwd/files/pfcwd_basic_helper.py
  tests/ixia/pfcwd/files/pfcwd_runtime_traffic_helper.py
  tests/ixia/pfcwd/test_pfcwd_basic.py
Labels: Bug :bug:, Enhancement, Pytest :snake:

#2863 [pfc] Refactor pfc pause test to use existing libs and code cleanup
  ansible/roles/test/files/ptftests/pfc_pause_test.py
  tests/qos/test_pfc_pause.py
Labels: Cleanup :droplet:, Enhancement, Pytest :snake:

#2977 Added bgpmon verification for test_bgp_allowlist
  tests/bgp/bgp_helpers.py
  tests/bgp/conftest.py
  tests/bgp/test_bgp_allow_list.py
  tests/bgp/test_bgpmon.py
  tests/bgp/test_traffic_shift.py
Labels: Enhancement

#3019 Azure pipeline for testing continuous warmboot on KVM image
  tests/pipelines/cont-warmboot.yml
Labels: Pytest :snake:, Testbed

#3029 [port_utils] Add port alias mapping for z9332f
  ansible/module_utils/port_utils.py
Labels: Testbed

#2865 [testplan/console] Add Console Switch Test Plan
  docs/testplan/console/console_test_hld.md
  docs/testplan/console/img/console_switch_wiring_general.png
  docs/testplan/console/img/console_switch_wiring_stress.png
  docs/testplan/console/img/dut_wiring.png
  docs/testplan/console/img/loopback_module.png
Labels: Test Plan

#3026 [Mellanox] make Mellanox SFP related platform API test starting with python2
  tests/platform_tests/api/conftest.py
Labels: Bug :bug:, Platform

#2876 [Platform API] Fixes for platform API test cases
  tests/platform_tests/api/test_fan_drawer.py
  tests/platform_tests/api/test_fan_drawer_fans.py
  tests/platform_tests/api/test_sfp.py
Labels: Bug :bug:, Platform

#2995 [Platform API] Remove bounds check for thermal values
  tests/platform_tests/api/test_thermal.py
Labels: Platform

#2999 [dualtor] Server to T1 traffic verification fixes
  tests/common/dualtor/data_plane_utils.py
  tests/common/dualtor/dual_tor_io.py
Labels: Dual ToR Test Dev :gemini:

#3040 [platform] Update 'show platform psustatus' tests to handle new expanded output
  tests/platform_tests/cli/test_show_platform.py
  tests/platform_tests/test_platform_info.py
Labels: Enhancement, Platform

#3015 [Mellanox] Test case should be marked as failure if cannot get PSU fan speed
  tests/platform_tests/mellanox/test_thermal_control.py
Labels: Bug :bug:, Platform

#3049 [vxlan decap] make sure that count_matched_packets_helper will return
  ansible/roles/test/files/ptftests/vxlan-decap.py
Labels: Bug :bug:
