Repository sonic-net/sonic-mgmt, pull requests merged in 2021-07, with the labels that each got.

#3717 Update sfp api test to generate sfp candidates from platform.json or port_config.ini
  tests/platform_tests/api/test_chassis.py
  tests/platform_tests/api/test_sfp.py
Labels: Enhancement, Platform

#3768 [pytest] Use loganalyzer to check whether a container was stopped
  tests/memory_checker/test_memory_checker.py
Labels: Bug :bug:

#3656 [sanity-check] Improve recovery logic - enable neighbor VM health restore
  tests/common/devices/eos.py
  tests/common/plugins/sanity_check/__init__.py
  tests/common/plugins/sanity_check/recover.py
  tests/platform_tests/conftest.py
  tests/platform_tests/test_advanced_reboot.py
Labels: Enhancement, Pytest :snake:

#3761 [dualtor][orchagent] Change the check time of queue counter
  tests/common/dualtor/tunnel_traffic_utils.py
Labels: Bug :bug:, Pytest :snake:

#3789 Negative testcases for fastboot and wamrboot
  tests/common/fixtures/advanced_reboot.py
  tests/platform_tests/test_advanced_reboot.py
  tests/platform_tests/test_cont_warm_reboot.py
  tests/platform_tests/verify_dut_health.py
Labels: Enhancement, Pytest :snake:

#3808 [ptf_runner] Enhance ptf port mapping
  ansible/roles/test/files/ptftests/remote.py
  tests/arp/test_arpall.py
  tests/common/constants.py
  tests/common/fixtures/ptfhost_utils.py
  tests/fib/test_fib.py
Labels: Enhancement

#3797 Changing ipv6 loopback addresses on the linecards to be on different subnets and adding t2 as a supported topology in veos
  ansible/vars/topo_t2-vs.yml
  ansible/vars/topo_t2.yml
  ansible/veos
Labels: chassis

#3809 [pytest] Fix the fast failure when checking the format of Monit alerting message
  tests/monit/test_monit_status.py
Labels: Bug :bug:

#3803 [advance-reboot] Add health check before and after fast/warm reboot
  tests/platform_tests/test_advanced_reboot.py
Labels: Enhancement, Pytest :snake:

#3913 [rdma] Skip nbrhosts fixture if no VM is present
  tests/conftest.py
Labels: Bug :bug:, Pytest :snake:

#3921 [test_default_route] Skip default route testcases on backend T1
  tests/route/test_default_route.py
Labels: Enhancement, Pytest :snake:
