Repository sonic-net/sonic-mgmt, pull requests merged in 2021-01, with the labels that each got.

#2204 [framework] Add DUT connection by console port
  tests/common/connections/__init__.py
  tests/common/connections/base_console_conn.py
  tests/common/connections/ssh_console_conn.py
  tests/common/connections/telnet_console_conn.py
  tests/conftest.py
Labels: Design Review Needed, Enhancement

#2661 [test_upgrade_path] Support test_upgrade_path on KVM switch on VS testbed
  ansible/library/reduce_and_add_sonic_images.py
  tests/upgrade_path/test_upgrade_path.py
Labels: Pytest :snake:

#2750 [test/cacl/function]: improve reliablibilty of cacl_function test
  ansible/roles/test/files/helpers/config_service_acls.sh
  tests/cacl/test_cacl_function.py
Labels: Pytest :snake:

#2780 [conn_graph] Fix the fanout connection parsing error
  ansible/library/conn_graph_facts.py
Labels: Bug :bug:

#2745 Fix add-topo error RTNETLINK answers: No route to host
  ansible/roles/vm_set/library/vm_topology.py
Labels: Bug :bug:, Testbed

#2751 [testplan]: Add BGP testplans
  docs/testplan/BGP-Allow-List.md
  docs/testplan/BGP-BBR.md
  docs/testplan/BGP-BGPMON.md
  docs/testplan/BGP-TSA.md
  docs/testplan/BGP-Update-Timer.md
Labels: Documentation, Test Plan

#2783 Upgrade path error fix - handle the cleanup only case without image URL
  ansible/library/reduce_and_add_sonic_images.py
Labels: Bug :bug:

#2614 [qos] Headroom pool watermark test
  tests/qos/files/qos.yml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/sai_qos_tests.py
  tests/saitests/switch.py
Labels: Enhancement, Pytest :snake:

#2648 [rdma] Tests traffic behavior with unknown mac
  tests/pfc/test_unknown_mac.py
Labels: Enhancement, Pytest :snake:

#2779 [test_platform_info] Avoid thermal policy affect test case test_show_platform_fanstatus_mocked
  tests/platform_tests/test_platform_info.py
Labels: Bug :bug:, Platform

#2713 [copp] Anchor copp setup to use python2
  tests/copp/copp_utils.py
Labels: Bug :bug:

#2793 [pretest] Add support to update python saithrift package on ptf
  tests/conftest.py
  tests/test_pretest.py
Labels: Enhancement, Pytest :snake:

#2814 [pretest] add a separator for internal pretests
  tests/test_pretest.py
Labels: Cleanup :droplet:

#2821 [Platform API] Test against Python 3 platform API if available on DuT
  tests/common/helpers/platform_api/scripts/platform_api_server.py
  tests/platform_tests/api/conftest.py
Labels: Enhancement, Platform

#2801 [recover_server] Add script to recover lab testbeds
  ansible/recover_server.py
Labels: Testbed

#2798 [Mellanox] Put non swapable fan to a virtual drawer to sync with production code
  tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
Labels: Bug :bug:

#2677 [rdma] Tests pfc behavior on lossless and lossy priorites across reboots
  tests/pfc/__init__.py
  tests/pfc/conftest.py
  tests/pfc/test_pfc_pause_lossless.py
  tests/pfc/test_pfc_pause_lossy.py
Labels: New, Pytest :snake:

#2809 [multi-dut] Making loganalyzer fixture work with multiple DUTs in multi-dut testbed
  tests/autorestart/test_container_autorestart.py
  tests/common/plugins/loganalyzer/__init__.py
  tests/copp/test_copp.py
  tests/dhcp_relay/test_dhcp_relay.py
  tests/drop_packets/drop_packets.py
  tests/drop_packets/test_drop_counters.py
  tests/k8s/conftest.py
  tests/lldp/test_lldp.py
  tests/pc/test_po_cleanup.py
  tests/pc/test_po_update.py
  tests/pfcwd/test_pfcwd_timer_accuracy.py
  tests/qos/qos_sai_base.py
  tests/route/test_route_perf.py
Labels: chassis

#2859 [recovery] Bring up BGP when minigraph is reloaded
  tests/common/config_reload.py
  tests/read_mac/test_read_mac_metadata.py
Labels: Bug :bug:, Pytest :snake:

#2854 [topo] Fix incorrect next hop ips for various topologies
  ansible/vars/topo_t0-16.yml
  ansible/vars/topo_t0-52.yml
  ansible/vars/topo_t1-64-lag-clet.yml
Labels: Bug :bug:

#2832 Adjust 'test_snmp_phy_entity' test case to support any number of lanes
  tests/snmp/test_snmp_phy_entity.py
Labels: Enhancement

#2868 [drop counters] Fix drop count tests to respect multi-DUT setups
  tests/drop_packets/drop_packets.py
  tests/drop_packets/test_drop_counters.py
Labels: Bug :bug:, Pytest :snake:

#2845 Dual tor failure utilities and sample tests
  tests/common/dualtor/mux_simulator_control.py
  tests/common/dualtor/tor_failure_utils.py
  tests/common/reboot.py
Labels: Dual ToR Test Dev :gemini:, Pytest :snake:

#2848 DualToR link failure utilities and fixtures
  tests/common/dualtor/dual_tor_utils.py
  tests/conftest.py
Labels: Dual ToR Test Dev :gemini:, Pytest :snake:

#2882 [ci]: add azure pipeline
  azure-pipelines.yml
Labels: ci

#2812 [acl] Add test cases for IPv6 dataplane ACLs
  tests/acl/templates/acltb_v6_test_rules.j2
  tests/acl/templates/acltb_v6_test_rules_part_1.j2
  tests/acl/templates/acltb_v6_test_rules_part_2.j2
  tests/acl/test_acl.py
Labels: New, Pytest :snake:

#2869 [sanity test] enable sanity check against 201811 images
  ansible/library/show_ip_interface.py
  tests/common/devices.py
  tests/common/plugins/sanity_check/checks.py
Labels: Enhancement

#2844 Use pytest.fail() for vlan non-broadcast tests
  tests/vlan/test_vlan.py
Labels: Bug :bug:, Pytest :snake:

#2885 [crm] Ignore error messages for removing non-empty VLAN
  tests/crm/test_crm.py
Labels: Pytest :snake:

#2880 [pfcwd] Add basic PFC watchdog test
  tests/common/ixia/common_helpers.py
  tests/common/ixia/ixia_helpers.py
  tests/common/ixia/qos_fixtures.py
  tests/ixia/pfcwd/__init__.py
  tests/ixia/pfcwd/conftest.py
  tests/ixia/pfcwd/files/__init__.py
  tests/ixia/pfcwd/files/pfcwd_basic_helper.py
  tests/ixia/pfcwd/test_pfcwd_basic.py
Labels: Enhancement, Pytest :snake:

#2892 [cache] ignore cache attribute error
  tests/common/utilities.py
Labels: Bug :bug:

#2896 [pdu] address SENTRY4 PDU support issues
  tests/common/plugins/psu_controller/snmp_psu_controllers.py
Labels: Bug :bug:
