Repository sonic-net/sonic-mgmt, pull requests merged in 2021-04, with the labels that each got.

#2985 Add tests for new APIs for chassis and convert existing API tests to run on chassis
  tests/common/helpers/platform_api/chassis.py
  tests/common/helpers/platform_api/fan_drawer.py
  tests/common/helpers/platform_api/module.py
  tests/common/helpers/platform_api/psu.py
  tests/common/helpers/platform_api/thermal.py
  tests/platform_tests/api/conftest.py
  tests/platform_tests/api/test_chassis.py
  tests/platform_tests/api/test_chassis_fans.py
  tests/platform_tests/api/test_component.py
  tests/platform_tests/api/test_fan_drawer.py
  tests/platform_tests/api/test_fan_drawer_fans.py
  tests/platform_tests/api/test_module.py
  tests/platform_tests/api/test_psu.py
  tests/platform_tests/api/test_psu_fans.py
  tests/platform_tests/api/test_sfp.py
  tests/platform_tests/api/test_thermal.py
  tests/platform_tests/api/test_watchdog.py
Labels: Enhancement, Platform

#3203 [Mellanox] Fixed test_platform_info.py for SN4600C
  tests/common/mellanox_data.py
Labels: Bug :bug:

#3259 [reporting] Add support for uploading pdu status info from devutils
  test_reporting/report_data_storage.py
  test_reporting/report_uploader.py
Labels: Testbed

#3253 [pfc] Skip pfc pause lossless test
  tests/qos/test_pfc_pause.py
Labels: Pytest :snake:

#3265 [reporting] Fix root for pdu status data upload
  test_reporting/report_data_storage.py
Labels: Bug :bug:

#3268 Fix dhcp relay pytest
  ansible/roles/test/files/ptftests/dhcp_relay_test.py
  tests/dhcp_relay/test_dhcp_relay.py
Labels: Bug :bug:, DHCP Relay

#3202 [Mellanox] Fixed allowed CPU temperature
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Bug :bug:

#3293 [pfcwd] Update dynamic_th value in existing table instead of creating a new one
  tests/pfcwd/test_pfcwd_function.py
Labels: Bug :bug:, Pytest :snake:

#3227 [devutils] add pdu_failure support
  ansible/devutils
Labels: Enhancement

#3305 [sonic] wait for switch become reachable after load minigraph
  ansible/config_sonic_basedon_testbed.yml
Labels: Bug :bug:, Critical

#3312 [Mellanox] Remove check for /var/run/hw-management/config/suspend
  tests/platform_tests/mellanox/check_hw_mgmt_service.py
  tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
Labels: Bug :bug:, Platform

#3310 [Mellanox] Enable mocking regular file
  tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
Labels: Enhancement, Platform

#3325 [lab] Rename devices in sample connection graph
  ansible/files/lab_connection_graph.xml
  ansible/files/sonic_lab_devices.csv
  ansible/files/sonic_lab_links.csv
Labels: Bug :bug:, Testbed

#3329 [warm-reboot] Start finalizer-check after control plane is UP
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: Bug :bug:, Pytest :snake:

#3333 [pdu] address a few PDU/PSU related issues
  tests/platform_tests/test_platform_info.py
  tests/platform_tests/test_reboot.py
Labels: Bug :bug:

#3204 [Platform API][SFP] Enhance test_sfp to deal with SFP xcvrs which can't reset
  tests/platform_tests/api/test_sfp.py
Labels: Enhancement, Platform

#3341 [acl] Skip default deny rule test case for egress ACLs
  tests/acl/test_acl.py
Labels: Bug :bug:

#3364 [port_utils] Update port_utils to match new z9332f port aliases
  ansible/module_utils/port_utils.py
Labels: Bug :bug:

#3365 [start-vms] protect against none type
  ansible/roles/vm_set/library/vm_topology.py
Labels: Bug :bug:

#3371 [advance_reboot] Check for IO variables value before reporting downtime
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: Bug :bug:, Pytest :snake:

#3317 [rdma] Add support to generate minigraph for Tgen testbeds
  ansible/config_sonic_basedon_testbed.yml
Labels: Enhancement, Testbed

#3340 [rdma] Define topologies for Tgen tests
  ansible/vars/topo_tgen_t0-3.yml
  ansible/vars/topo_tgen_t1-3-lag.yml
Labels: Enhancement, Testbed

#3388 [crm] address CRM test issue on multi-dut testbed
  tests/crm/conftest.py
Labels: Bug :bug:

#3384 [copp] Throttle server send-rate so that DUT does not get overwhelmed
  ansible/roles/test/files/ptftests/copp_tests.py
Labels: Bug :bug:

#3375 [advance-reboot] Store timing data into a json file for warm/fast reboot
  tests/platform_tests/conftest.py
Labels: Pytest :snake:

#3390 [sonic fanout] make sure sonic fanout hostname type is str
  tests/common/cache/facts_cache.py
  tests/conftest.py
Labels: Bug :bug:

#3393 [ASCI type] add variation of TD2 lspci signature
  tests/common/devices/sonic.py
  tests/platform_tests/broadcom/files/ser_injector.py
Labels: Enhancement

#3391 [rdma] Rename tgen topologies
  ansible/vars/topo_tgen-t0-3.yml
  ansible/vars/topo_tgen-t1-3-lag.yml
Labels: Bug :bug:, Testbed

#3392 [rdma] Avoid add-topo failure when no VMs are associated with a testbed entry
  ansible/testbed_add_vm_topology.yml
Labels: Enhancement, Testbed

#3403 [rdma] Enable test runs on tgen topology
  ansible/veos
  tests/common/testbed.py
Labels: Enhancement, Testbed

#3413 [rdma] Update connection info for ixia api server
  ansible/group_vars/ixia/creds.yml
  tests/common/ixia/ixia_fixtures.py
Labels: Enhancement, Testbed

#3432 [rdma] Apply tgen marker at file level
  tests/ixia/ecn/test_dequeue_ecn.py
  tests/ixia/ecn/test_red_accuracy.py
  tests/ixia/pfc/test_global_pause.py
  tests/ixia/pfc/test_pfc_pause_lossless.py
  tests/ixia/pfc/test_pfc_pause_lossy.py
  tests/ixia/pfcwd/test_pfcwd_a2a.py
  tests/ixia/pfcwd/test_pfcwd_basic.py
  tests/ixia/pfcwd/test_pfcwd_m2o.py
  tests/ixia/pfcwd/test_pfcwd_runtime_traffic.py
Labels: Bug :bug:, Pytest :snake:

#3433 [rdma] Fix ixia api teardown failure if Session is None
  tests/common/ixia/ixia_fixtures.py
Labels: Bug :bug:, Pytest :snake:
