Repository sonic-net/sonic-mgmt, pull requests merged in 2021-06, with the labels that each got.

#3559 [pytest] Skip testing the format of alerting message from Monit on 202012 image
  tests/monit/test_monit_status.py
Labels: Bug :bug:

#3568 topo: Add test topology for 7050QX-32S-S4Q31
  ansible/vars/topo_t0-35.yml
Labels: Enhancement, Request for 201811 branch :shipit:, Testbed

#3572 [apiserver] Replace dot notation with bracket notation for dict variables
  ansible/roles/vm_set/tasks/add_topo.yml
Labels: Bug :bug:, Testbed

#3570 [201811] Port changes for 7050QX-32S-S4Q31 into 201811 branch
  ansible/config_sonic_basedon_testbed.yml
  ansible/templates/minigraph_device.j2
  ansible/vars/topo_t0-35.yml
Labels: Request for 201811 branch :shipit:

#3583 minigraph: Fix issue of alias name vs sonic name being used
  ansible/templates/minigraph_device.j2
Labels: Bug :bug:, Request for 201911 branch

#3584 [201811] minigraph: Fix issue of alias name vs sonic name being used for populating the speed
  ansible/templates/minigraph_device.j2
Labels: Bug :bug:

#3628 [port_utils] Update the 10G breakout ports for Arista-7050-QX-32S in the port alias map
  ansible/module_utils/port_utils.py
Labels: Enhancement, Pytest :snake:, Request for 201911 branch

#3629 [interface_facts] Fix import error due to multi_asic module not present in certain branches
  ansible/library/interface_facts.py
Labels: Enhancement

#3631 [rdma] Add new tgen topology for breakout 7050 SKU
  ansible/vars/topo_tgen-t0-35-3.yml
Labels: Enhancement, Request for 201911 branch, Testbed

#3632 [rdma] Enable minigraph generation for breakout 7050
  ansible/group_vars/sonic/breakout_speed.yml
  ansible/templates/minigraph_device.j2
Labels: Enhancement, Request for 201911 branch, Testbed

#3579 [Platform API] Fix the thermal get_name platform API test
  tests/platform_tests/api/test_thermal.py
Labels: Bug :bug:, Platform

#3660 [test_bgp_update_timer] Enable dualtor
  tests/bgp/conftest.py
  tests/bgp/test_bgp_update_timer.py
  tests/common/helpers/bgp.py
  tests/dualtor/test_orchagent_slb.py
Labels: Bug :bug:

#3658 [qos] Add qos params for breakout 7050 and enable test run
  tests/qos/files/qos.yml
  tests/qos/test_qos_sai.py
Labels: Enhancement, Request for 201911 branch

#3659 [qos] Enable pytest qos runs on 201811
  tests/qos/qos_sai_base.py
  tests/saitests/sai_qos_tests.py
Labels: Enhancement, Pytest :snake:

#3654 [pfc] test_unknown_mac use correct MAC when sending packet
  tests/pfc/test_unknown_mac.py
Labels: Bug :bug:, Request for 201911 branch

#3676 [test_cpu_memory_usage] More descriptive failure messages
  tests/platform_tests/test_cpu_memory_usage.py
Labels: Enhancement

#3680 [201811] Revert ansible syntax changes and clean up t0-35 topo definition
  ansible/config_sonic_basedon_testbed.yml
  ansible/vars/topo_t0-35.yml
Labels: Bug :bug:

#3582 [pytest] Test the feature of memory checker.
  tests/memory_checker/test_memory_checker.py
Labels: New, Request for 201911 branch

#3657 Modifying tests to adapt to new config reload system checks
  tests/common/config_reload.py
  tests/common/plugins/sanity_check/constants.py
  tests/common/plugins/sanity_check/recover.py
  tests/k8s/test_config_reload.py
  tests/nat/nat_helpers.py
  tests/platform_tests/test_reload_config.py
  tests/vlan/test_vlan.py
  tests/vxlan/test_vnet_route_leak.py
Labels: Enhancement

#3662 Test cases for RADV IPv6 router advertisement
  ansible/roles/test/files/ptftests/radv_ipv6_ra_test.py
  tests/radv/test_radv_ipv6_ra.py
Labels: New

#3698 Fixing generic config reload option to use force if supported
  tests/common/config_reload.py
Labels: Bug :bug:

#3321 [test_vlan] teardown: Handle cleanup for DUT and PTF separately
  tests/vlan/test_vlan.py
Labels: Bug :bug:, Pytest :snake:

#3709 Add pcied regression test
  tests/common/devices/sonic.py
  tests/platform_tests/daemon/__init__.py
  tests/platform_tests/daemon/test_pcied.py
Labels: New, Platform

#3648 [platform/sfp] Add test cases for SFP error status
  tests/common/helpers/platform_api/sfp.py
  tests/platform_tests/api/test_sfp.py
  tests/platform_tests/sfp/test_sfputil.py
Labels: Enhancement, Platform
