Repository sonic-net/sonic-mgmt, pull requests merged in 2022-06, with the labels that each got.

#5751 Update FDB learning enable regex in template file
  tests/platform_tests/templates/expect_boot_messages
Labels: Request for 202012 branch

#5699 [advanced-reboot] Verify critical reboot stages and occurrence count
  tests/common/fixtures/advanced_reboot.py
  tests/platform_tests/conftest.py
  tests/platform_tests/reboot_timing_constants.py
  tests/platform_tests/templates/expect_boot_messages
Labels: Request for 202012 branch

#5723 [MASIC] Make test_bgp_bounce.py support for multi-asic platforms
  tests/bgp/bgp_helpers.py
  tests/common/devices/multi_asic.py
Labels: Request for 202012 branch

#5759 [platform] Support PDU reboot when DUT crash after OOM reboot
  tests/platform_tests/test_memory_exhaustion.py
Labels: Request for 202012 branch

#5768 [CRM] Improved stability of CRM tests - by doing get CRM resources right before setting thresholds
  tests/crm/test_crm.py
Labels: Request for 202012 branch

#5621 [snmp][chassis]: Modify snmp interfaces test case to support running on supervisor
  tests/snmp/test_snmp_interfaces.py
Labels: chassis

#5774 [test_po_update] Allow slightly packet loss during portchannel members add/removal
  tests/pc/test_po_update.py
Labels: Request for 202012 branch

#5755 update qos.yml for cisco-8000 platform
  tests/qos/files/qos.yml
Labels: Request for 202012 branch

#5777 [xfail] remove xfail for some testcases
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202012 branch

#5788 [MASIC] Update bgp/conftest.py on usage of "show ip int"
  tests/bgp/conftest.py
Labels: Request for 202012 branch

#5791 [platform_test] Skip test_get_high_critical_threshold for Nokia 7215
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202012 branch

#5719 Cisco platform : platform fan speed set/tolerance test skips
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202012 branch

#5771 [dualtor] Fix `test_link_failure`
  tests/common/dualtor/data_plane_utils.py
  tests/common/dualtor/dual_tor_utils.py
Labels: Bug :bug:, Request for 202012 branch

#5706 Added code to check swss on all asics if dut is_multi_asic
  tests/common/config_reload.py
Labels: chassis

#5812 [platform] revert skip oom test for celestica-dx010 and force10-s6000
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202012 branch

#5807 skip encapsulation protocol when hashing ip_proto
  ansible/roles/test/files/ptftests/hash_test.py
Labels: Request for 202012 branch

#5829 [Vxlan ECMP] Increase wait time to check BGP session status
  tests/vxlan/test_vxlan_ecmp.py
Labels: Request for 202012 branch

#5823 [memory_checker] Log syslog message if container was not created
  tests/memory_checker/test_memory_checker.py
Labels: New, Request for 202012 branch

#5841 [pfc] Fix compatable issue in unknown_mac
  tests/pfc/test_unknown_mac.py
Labels: Request for 202012 branch

#5834 [test-gap] Test IPinIP decap after VXLAN setup and teardown
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/common/utilities.py
  tests/decap/conftest.py
  tests/decap/test_decap.py
Labels: Test gap, Request for 202012 branch

#5852 [ACL]Always load_minigraph after acl test
  tests/acl/test_acl.py
Labels: Request for 202012 branch

#5589 Added version check to the num_fans_drawer_fans setup function
  tests/platform_tests/api/test_fan_drawer_fans.py
Labels: Request for 202012 branch

#5857 Updated QoS test params as per changes in buffer profiles for TD3 based HWSKUs
  tests/qos/files/qos.yml
Labels: Request for 202012 branch

#5865 [log analyzer] Support ignoring syslog temporarily by setting ignore markers
  ansible/roles/test/files/tools/loganalyzer/loganalyzer.py
  tests/common/config_reload.py
  tests/common/plugins/loganalyzer/loganalyzer.py
  tests/common/plugins/loganalyzer/utils.py
  tests/pc/test_po_update.py
Labels: Request for 202012 branch

#5846 [pc/test_lag_2.py & enum_dut_portchannel] Support different completeness_level to reduce test time
  tests/conftest.py
  tests/pc/test_lag_2.py
Labels: Request for 202012 branch

#5889 Modified code to discount PSU voltage value after turn-off
  tests/snmp/test_snmp_phy_entity.py
Labels: Bug :bug:, Request for 202012 branch, 202012 issue

#4703 New T0 Test case to check connectivity of statically added arp entries
  tests/vlan/test_vlan_ping.py
Labels: Request for 202012 branch
