Repository sonic-net/sonic-mgmt, pull requests merged in 2022-10, with the labels that each got.

#6333 [test_sfp] fix missing TestSfpApi in skip
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202012 branch

#6100 Skipping test_reboot in api/test_module.py[Cisco-8000]
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202205 branch

#6417 [MASIC][chassis] test_bgp_update_timer change to support for multi-asic
  tests/bgp/conftest.py
  tests/bgp/test_bgp_update_timer.py
  tests/common/devices/sonic_asic.py
  tests/common/helpers/bgp.py
Labels: chassis, Request for 202012 branch, multi-ASIC

#6451 Individual tx channel disable for test_tx_disable_channel test
  tests/platform_tests/api/test_sfp.py
Labels: Test gap

#6337 QoS test params for J2C+ based HWSKUs
  tests/qos/files/qos.yml
Labels: chassis, Request for 202205 branch

#5707 [T2-ACL] Adding support for T2-profile in ACL script
  tests/acl/templates/acltb_test_rules.j2
  tests/acl/templates/acltb_test_rules_part_2.j2
  tests/acl/templates/acltb_v6_test_rules.j2
  tests/acl/templates/acltb_v6_test_rules_part_2.j2
  tests/acl/test_acl.py
Labels: P0, chassis

#6404 Skip test_chassis_fans.py::TestChassisFans::test_set_fans_led
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202205 branch

#6470 [kvm test] skip PR testcase test_load_minigraph_with_traffic_shift_away
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch

#6472 [T2] Skip Vxlan decap test on T2
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: chassis, Request for 202205 branch

#6452 update pfc xoff_1 and xoff_2 threshold for td3/topo-t1-lag/100000_300m
  tests/qos/files/qos.yml
Labels: Request for 202012 branch, Request for 202205 branch

#6463 Add default ASIC for ser_injector.py
  tests/platform_tests/broadcom/files/ser_injector.py
Labels: Arista-720DT-48S, Request for 202205 branch

#6464 sonic-mgmt: Fix test_show_platform_syseeprom on Arista devices
  tests/platform_tests/cli/test_show_platform.py
Labels: Arista-720DT-48S, Request for 202205 branch

#6486 [autorestart] Ignore known autorestart error logs and fix all_critical_process_status bug in sonic.py
  tests/autorestart/test_container_autorestart.py
  tests/common/devices/sonic.py
Labels: Request for 202012 branch, Request for 202205 branch

#6490 Skip test_fwutil due to not found fixture
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202012 branch, Request for 202205 branch

#6496 [gcu] Refactor generic_config_updater/test_vlan_interface.py
  tests/generic_config_updater/test_vlan_interface.py
Labels: Request for 202205 branch

#6508 [grpc] update GRPC configuration with sed
  ansible/config_sonic_basedon_testbed.yml
Labels: Request for 202205 branch

#6509 [dualtor] increase MUX toggling wait time to 2 minutes
  tests/common/dualtor/mux_simulator_control.py
Labels: Request for 202012 branch, Request for 202205 branch

#4304 Add Eveverflow test plan for VOQ system
  docs/testplan/Chassis-everflow-test-plan.md
Labels: chassis

#6504 Update Cisco-8102-C64 port alias mapping
  ansible/module_utils/port_utils.py
Labels: Request for 202012 branch

#6413 [sanity check] Fix and improve recovery
  tests/common/plugins/sanity_check/__init__.py
  tests/common/plugins/sanity_check/recover.py
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch

#6381 [dhcpv6_relay_test] Add dhcp6relay dual tor test
  ansible/roles/test/files/ptftests/py3/dhcpv6_relay_test.py
  tests/dhcp_relay/test_dhcpv6_relay.py
Labels: Request for 202012 branch, Request for 202205 branch

#6225 Everflow T2 topo support and ipv6 egress tests
  tests/everflow/conftest.py
  tests/everflow/everflow_test_utilities.py
  tests/everflow/test_everflow_ipv6.py
  tests/everflow/test_everflow_per_interface.py
  tests/everflow/test_everflow_testbed.py
Labels: P0, chassis, Request for 202205 branch

#6507 [dhcpv6_relay] Change interface binding check regex
  tests/dhcp_relay/test_dhcpv6_relay.py
Labels: Request for 202012 branch, Request for 202205 branch

#6531 Fix test_snmp_memory
  tests/snmp/test_snmp_memory.py
Labels: Bug :bug:, Request for 202205 branch

#6521 Changes to fix flaky TSA test on KVM
  tests/bgp/test_traffic_shift.py
Labels: Request for 202205 branch

#6546 Only fails critical process check when process name in critical process list
  tests/common/devices/sonic.py
Labels: Request for 202012 branch, Request for 202205 branch

#6453 Password hardening test fix
  tests/passw_hardening/conftest.py
  tests/passw_hardening/passw_hardening_utils.py
  tests/passw_hardening/sample/passw_hardening_digits/common-password
  tests/passw_hardening/sample/passw_hardening_history/common-password
  tests/passw_hardening/sample/passw_hardening_lower_letter/common-password
  tests/passw_hardening/sample/passw_hardening_min_len/common-password
  tests/passw_hardening/sample/passw_hardening_reject_user_passw_match/common-password
  tests/passw_hardening/sample/passw_hardening_special_letter/common-password
  tests/passw_hardening/sample/passw_hardening_upper_letter/common-password
  tests/passw_hardening/test_passw_hardening.py
Labels: Request for 202205 branch

#6431 [test_iface_namingmode] Adjusted the test according to the new buffer queue/pg counters optimization
  tests/common/helpers/sonic_db.py
  tests/iface_namingmode/test_iface_namingmode.py
  tests/snmp/__init__.py
Labels: Request for 202205 branch

#6548 Fix get service container status and critical process bug in sonic.py and improve script
  tests/common/devices/sonic.py
Labels: Request for 202012 branch, Request for 202205 branch

#6556 [sub_port] [backend] Update acl template based on the test ports
  tests/sub_port_interfaces/conftest.py
  tests/sub_port_interfaces/sub_ports_helpers.py
  tests/sub_port_interfaces/templates/backend_acl_update_config.j2
Labels: Enhancement, Request for 202012 branch, Request for 202205 branch

#6561 everflow test case fix
  tests/everflow/conftest.py
Labels: Request for 202205 branch

#6568 [dualtor][active-active] Fix `nic_simulator` control utilities
  tests/common/dualtor/nic_simulator_control.py
Labels: Request for 202205 branch

#6498 [m0] Add support in test_vlan_ping for M0 topo
  tests/vlan/test_vlan_ping.py
Labels: Request for 202012 branch, Request for 202205 branch

#6577 Revert "Fix loganalyzer.py UnicodeDecodeError issue"
  ansible/library/extract_log.py
  ansible/roles/test/files/tools/loganalyzer/loganalyzer.py
Labels: Request for 202205 branch

#6437 Add testcase to verify vlan header in bounced back traffic
  tests/dualtor/test_ipinip.py
Labels: Request for 202012 branch, Request for 202205 branch

#6430 [m0] Refactor announce routes for m0
  ansible/library/announce_routes.py
  ansible/roles/eos/templates/m0-m1.j2
  ansible/roles/eos/templates/m0-mx.j2
  ansible/vars/topo_m0.yml
  docs/testbed/READ.testbed.AnnounceRoutes.Internal.md
  docs/testbed/README.testbed.Routing.md
  docs/testbed/img/announce_routes_m0.png
Labels: Request for 202012 branch, Request for 202205 branch

#6586 Do not ignore FLEX_COUNTER_TABLE configdb key
  tests/common/plugins/sanity_check/__init__.py
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch

#6465 [arp]: Extend proxy_arp to cover dualtor scenario
  .azure-pipelines/pr_test_scripts.yaml
  tests/arp/conftest.py
  tests/arp/test_arp_dualtor.py
  tests/arp/test_arp_extended.py
  tests/common/fixtures/ptfhost_utils.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/kvmtest.sh
  tests/scripts/garp_service.py
Labels: Request for 202012 branch, Request for 202205 branch

#6206 Add multi-asic and T2 topology support for bgpmon and bgp_traffic_shift suites
  tests/bgp/bgp_helpers.py
  tests/bgp/conftest.py
  tests/bgp/test_bgpmon.py
  tests/bgp/test_traffic_shift.py
  tests/common/devices/sonic_asic.py
  tests/common/helpers/generators.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: chassis

#6587 [m0] Add support for m0 in test_route_flap
  tests/route/test_route_flap.py
Labels: Request for 202205 branch

#6600 Stop exabgp before stopping and removing PTF container in cleanup
  ansible/roles/vm_set/templates/cleanup.sh.j2
Labels: Request for 202012 branch, Request for 202205 branch

#6599 Improve the logic of generating running golden config.
  ansible/config_sonic_basedon_testbed.yml
  tests/conftest.py
  tests/test_pretest.py
Labels: Request for 202012 branch, Request for 202205 branch

#6604 Select the last port in the last LAG to run qos remap test
  tests/qos/test_tunnel_qos_remap.py
Labels: Request for 202012 branch, Request for 202205 branch

#6598 Dual TOR QoS testcase fix: force use lower TOR as target DUT
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch

#6566 Add start bgp step in bgp bounce test
  tests/bgp/test_bgp_bounce.py
Labels: Request for 202205 branch

#6614 [route] Fix random loss of arp info in test_static_route_ecmp
  tests/route/test_static_route.py
Labels: Request for 202205 branch

#6632 Revert T2 everflow
  tests/everflow/conftest.py
  tests/everflow/everflow_test_utilities.py
  tests/everflow/test_everflow_ipv6.py
  tests/everflow/test_everflow_per_interface.py
  tests/everflow/test_everflow_testbed.py
Labels: Request for 202205 branch

#6397 [chassis] test device's fanout switch(es)'s link down when reboot happens
  tests/common/devices/eos.py
  tests/common/devices/fanout.py
  tests/common/devices/multi_asic.py
  tests/common/devices/sonic.py
  tests/platform_tests/test_link_down.py
Labels: chassis, multi-ASIC

#6098 Run telemetry tests on all DUT types in a multi-dut setup
  tests/telemetry/test_telemetry.py
Labels: chassis, Request for 202205 branch

#6555 [dualtor]: Fix loopback route removal
  tests/dualtor/test_orchagent_standby_tor_downstream.py
Labels: Request for 202012 branch, Request for 202205 branch

#5331 Added support for one portChannel and one routed interface if two por…
  tests/crm/conftest.py
Labels: chassis, Request for 202205 branch

#6076 Use config_reload when recovering from internal interfaces that are in down state
  tests/common/plugins/sanity_check/recover.py
Labels: chassis, Request for 202205 branch

#6607 Added python fixture for resetting config changes to fix nightly backend snmp test failures
  tests/snmp/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch

#6635 [mx] Enhance announce routes to support MX topo
  ansible/library/announce_routes.py
Labels: Request for 202205 branch

#6519 Added xfail markers to certain platform API tests due to known issues
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202205 branch

#6643 [dualtor][grpc] Add retries and timeout to gRPC calls
  tests/common/dualtor/nic_simulator_control.py
  tests/dualtor_io/test_link_drop.py
Labels: Request for 202205 branch

#6345 Add muli-asics support to test_radv_restart
  tests/radv/test_radv_restart.py
Labels: chassis, Request for 202205 branch
