Repository sonic-net/sonic-mgmt, pull requests merged in 2022-05, with the labels that each got.

#5579 [enum_dut_feature_container] Only retrieves `enabled` container names
  tests/conftest.py
Labels: Request for 201911 branch, Request for 202012 branch

#5515 Dual ToR QoS test case fixes
  tests/qos/files/qos.yml
  tests/qos/qos_sai_base.py
Labels: Request for 202012 branch

#5583 [FDB]: Fix dummy mac for FDB test.
  ansible/library/fdb_facts.py
  tests/fdb/test_fdb.py
Labels: Request for 202012 branch

#5552 [Qos] [MASIC] supporting Qos changes in PR #5452 on multi-asic
  tests/common/devices/multi_asic.py
  tests/qos/qos_sai_base.py
Labels: Request for 202012 branch, multi-ASIC

#5563 [VNET_VXLAN] Fixed vnet_vxlan_3k test "Neighbor is unreachable" by reapplying config
  tests/vxlan/test_vnet_vxlan.py
Labels: Request for 202012 branch

#5572 [loganalyzer] add err msg of bgpcfgd to ignore list
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202012 branch

#5602 [autorestart] Ignore known swss/syncd/teamd log
  tests/autorestart/test_container_autorestart.py
Labels: Request for 201911 branch, Request for 202012 branch

#5555 Marking pfc/test_unknown_mac.py as skip for cisco-8000
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202012 branch

#5619 [loganalyzer] move some log errors to ignore list
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202012 branch

#5594 [tacacs]: Update test to use SONiC reboot
  tests/tacacs/test_ro_disk.py
Labels: chassis

#5623 Revert "Everflow packets TTL check for cisco platform"
  tests/everflow/everflow_test_utilities.py
Labels: Request for 202012 branch

#5629 [autorestart] Do the safe `config_reload(...)` during teardown
  tests/autorestart/test_container_autorestart.py
Labels: Request for 201911 branch, Request for 202012 branch

#5631 [memory_checker] Skip testing Monit's inability to reset internal counter in 20191130 image
  tests/memory_checker/test_memory_checker.py
Labels: Bug :bug:, Request for 201911 branch, Request for 202012 branch

#5634 Check gnxi path and get correct path value before test
  tests/telemetry/test_telemetry.py
Labels: Request for 202012 branch

#5512 Enabling testQosSaiBufferPoolWatermark Testcase for cisco-8000 platform
  tests/qos/test_qos_sai.py
  tests/saitests/sai_qos_tests.py
  tests/saitests/switch.py
Labels: Request for 202012 branch

#5642 [ErrLog] ignore ERR syncd#syncd: :- updateSupportedBufferPoolCounters…
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202012 branch

#5541 fix to validate all db device keys are populated after pcied restart
  tests/platform_tests/daemon/test_pcied.py
Labels: Request for 202012 branch

#4305 Add fabric test plan
  docs/testplan/Chassis-fabric-test-plan.md
Labels: chassis

#5537 Changes to testQosSaiPfcXonLimit for cisco-8000
  tests/qos/test_qos_sai.py
  tests/saitests/sai_qos_tests.py
Labels: Request for 202012 branch

#5514 changes for testQosSaiLossyQueue on cisco-8000
  tests/saitests/sai_qos_tests.py
Labels: Request for 202012 branch

#5628 New Testcase testQosSaiPgDrop specific for cisco-8000 platform
  tests/qos/test_qos_sai.py
  tests/saitests/sai_qos_tests.py
Labels: Request for 202012 branch

#5660 use get_rx_port utility for lag members to select dst_port_id for testQosSaiPGDrop testcase
  tests/qos/test_qos_sai.py
  tests/saitests/sai_qos_tests.py
Labels: Request for 202012 branch

#5536 changes to testQosSaiPfcXoffLimit on cisco-8000
  tests/qos/test_qos_sai.py
  tests/saitests/sai_qos_tests.py
Labels: Request for 202012 branch

#5590 New Testcase for cisco-8000 platforms replacing testQosSaiHeadroomPoolSize
  tests/qos/test_qos_sai.py
  tests/saitests/sai_qos_tests.py
Labels: Request for 202012 branch

#5513 Changes for testQosSaiPgSharedWatermark on cisco-8000 platform
  tests/saitests/sai_qos_tests.py
  tests/saitests/switch.py
Labels: Request for 202012 branch

#5668 [MASIC] [Everflow] Update test_everflow_per_interface.py to support masic
  tests/everflow/test_everflow_per_interface.py
Labels: Request for 202012 branch

#5656 Log Analyzer improvements
  tests/common/plugins/loganalyzer/loganalyzer.py
Labels: Request for 202012 branch

#5700 [test_po_update] Recover portchannel by commands if test cases passed rather than reload; Reduce test time to avoid scapy performance influence
  tests/pc/test_po_update.py
Labels: Request for 202012 branch

#5688 [advanced-reboot] Quick fix to update MAC jumping regex for MLNX devices
  tests/platform_tests/reboot_timing_constants.py
Labels: Request for 202012 branch

#5709 [dualtor] Fix `test_downstream_emcp_nexthops[ipv6]`
  tests/common/dualtor/dual_tor_utils.py
  tests/dualtor/test_orchagent_active_tor_downstream.py
Labels: Request for 202012 branch

#5456 [chasiss] Fib and Decap Test cases
  ansible/roles/test/files/ptftests/IP_decap_test.py
  ansible/roles/test/files/ptftests/fib_test.py
  ansible/roles/test/files/ptftests/hash_test.py
  tests/bgp/test_bgp_speaker.py
  tests/common/devices/sonic.py
  tests/common/fixtures/fib_utils.py
  tests/common/fixtures/ptfhost_utils.py
  tests/common/plugins/sanity_check/checks.py
  tests/conftest.py
  tests/decap/test_decap.py
  tests/fib/test_fib.py
Labels: chassis

#5710 Skip test_memory_exhaustion for Force10-S6000
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202012 branch

#5640 [loganalyzer] [Qos] Ignore brcm_sai_set_switch_attribute error in syslog
  tests/qos/test_qos_sai.py
Labels: Request for 202012 branch

#5705 [chassis]: Modify minigraph_dpg_asic template to generate unique port channel index
  ansible/templates/minigraph_dpg_asic.j2
Labels: chassis

#5718 Cisco platform hwsku change
  ansible/group_vars/sonic/variables
  ansible/module_utils/port_utils.py
Labels: Request for 202012 branch

#5724 [platform] Spend more time waiting for DUT reboot after OOM
  tests/platform_tests/test_memory_exhaustion.py
Labels: Request for 202012 branch

#5415 [advanced-reboot] Fix bgpd.log handling, lacp_session check and log collection
  tests/common/fixtures/advanced_reboot.py
  tests/platform_tests/conftest.py
Labels: Request for 202012 branch

#5735 [dualtor][icmp_responder] Fix icmp responder
  tests/scripts/icmp_responder.py
Labels: Request for 202012 branch

#5745 Update regex for FDB learning to work on both 201911 and 202012
  tests/platform_tests/reboot_timing_constants.py
Labels: Request for 202012 branch
