Repository sonic-net/sonic-mgmt, pull requests merged in 2022-02, with the labels that each got.

#5056 Fixed bug with reboot history queue that was causing false failures
  tests/common/reboot.py
  tests/platform_tests/test_reboot.py
Labels: Bug :bug:

#5030 [chassis] run test_bgp_shutdown test on linecards only
  tests/log_fidelity/test_bgp_shutdown.py
Labels: chassis

#3758 Modified iface_namingmode testcases to get spine ports for T2 topology
  tests/iface_namingmode/test_iface_namingmode.py
Labels: chassis

#5102 [platform][Mellanox] Fix issue: the PSU capability for Mellanox ACS-MSN3420 is wrong
  tests/common/mellanox_data.py
Labels: Bug :bug:, Platform

#3756 Enhancements platform api tests and change in psustatus_json to use enum_supervisor_dut_hostname
  tests/platform_tests/api/test_chassis.py
  tests/platform_tests/api/test_psu.py
  tests/platform_tests/cli/test_show_platform.py
Labels: chassis

#5146 [qos] Add support to run buffer deployment testcase on non Mellanox platforms
  tests/qos/test_buffer.py
Labels: Bug :bug:, Pytest :snake:

#4542 Changing voq tests to use sonic-db-cli instead of redis-cli
  tests/common/devices/sonic.py
  tests/common/devices/sonic_asic.py
  tests/common/fixtures/fib_utils.py
  tests/common/helpers/sonic_db.py
  tests/common/helpers/voq_lag.py
  tests/voq/test_voq_init.py
  tests/voq/test_voq_intfs.py
  tests/voq/test_voq_nbr.py
  tests/voq/voq_helpers.py
Labels: chassis

#5152 [platform API][masic] Skip platform API tests on multi ASIC platforms running 201911
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Platform

#5198 [qos] Identify buffer type before yielding from setup for non Mellanox platforms
  tests/qos/test_buffer.py
Labels: Bug :bug:, Pytest :snake:

#5050 [chassis-packet] fixed test_mtu.py
  tests/arp/conftest.py
  tests/common/devices/sonic.py
  tests/common/devices/sonic_asic.py
  tests/ipfwd/conftest.py
  tests/ipfwd/test_mtu.py
  tests/test_interfaces.py
Labels: chassis-packet

#5223 Fixes the PTF Port Index Mapping where index in port config.ini is not valid representation.
  ansible/module_utils/port_utils.py
Labels: Request for 202012 branch

#5174 [advanced-reboot] Fix capturing first lacpdu frame after reboot
  ansible/roles/test/files/ptftests/advanced-reboot.py
  ansible/roles/test/files/ptftests/arista.py
Labels: Request for 202012 branch

#5216 [advanced-reboot] Add MAC jump MLNX regex to fix test_warm_reboot_mac_jump
  tests/platform_tests/conftest.py
  tests/platform_tests/reboot_timing_constants.py
  tests/platform_tests/templates/expect_boot_messages
Labels: Request for 202012 branch

#5228 tacacs: test_ro_disk: Increase wait time
  tests/tacacs/test_ro_disk.py
Labels: Request for 202012 branch

#5224 Configlet: AddRack: Use port name, instead of hardcoded value, which is a copy/paste error
  tests/configlet/util/common.py
  tests/configlet/util/configlet.py
Labels: Request for 202012 branch

#5233 Load minigraph after wr_arp with vnet test to restore config_db.json
  tests/vxlan/test_vnet_vxlan.py
Labels: Request for 202012 branch

#5230 Always remove docker-py package
  ansible/roles/vm_set/tasks/docker.yml
  ansible/roles/vm_set/tasks/main.yml
Labels: Request for 202012 branch

#5237 Use different flask versions for pip and pip3
  ansible/roles/vm_set/tasks/control_mux_simulator.yml
Labels: Request for 202012 branch
