Repository sonic-net/sonic-mgmt, pull requests merged in 2022-11, with the labels that each got.

#6642 [dual_tor_io] Improve && fix `dual_tor_io`
  tests/common/dualtor/dual_tor_io.py
  tests/common/utilities.py
  tests/templates/dual_tor_sniffer.conf.j2
Labels: Request for 202205 branch

#6506 Add support to include routed interfaces from the same asic only
  tests/bgp/conftest.py
Labels: chassis, Request for 202205 branch

#6702 refine pfctest output message to report test failures clearly
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch

#6683 Correct frame DMAC addr of traffic to using vlan interface address for PFC xoff dual T0 scenario
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch

#6704 compensate random packet leak out for all Arista device which use Bro…
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch

#6713 [bugfix] Fix KeyError in FLEX_COUNTER_STATUS
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch

#6695 [dualtor]: Wait for neighbor to become reachable
  tests/common/dualtor/dual_tor_mock.py
  tests/dualtor/test_orchagent_active_tor_downstream.py
Labels: Request for 202012 branch, Request for 202205 branch

#6725 [m0] Add support for m0 in test_dhcp_pkt_fwd
  tests/dhcp_relay/test_dhcp_pkt_fwd.py
Labels: Request for 202012 branch, Request for 202205 branch

#6562 Test lossy (non-pfc) queue for cisco-8000 platform
  tests/qos/files/qos.yml
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202012 branch

#6329 Support for sai-thrift calls in ixia ecn scripts.
  tests/ixia/ecn/conftest.py
  tests/ixia/ecn/test_dequeue_ecn.py
  tests/ixia/ptf_utils.py
  tests/saitests/sai_rpc_caller.py
Labels: Request for 202012 branch

#6684 Skip config db diff comparison for advanced-reboot/upgrade tests
  tests/platform_tests/test_advanced_reboot.py
  tests/upgrade_path/test_upgrade_path.py
Labels: Request for 202012 branch, Request for 202205 branch

#6686 [backend] [vlan] Update acl template based on test ports
  tests/common/helpers/backend_acl.py
  tests/common/templates/backend_acl_update_config.j2
  tests/vlan/test_vlan.py
Labels: Request for 202012 branch, Request for 202205 branch

#6738 Modify test_container_autorestart config reload source to golden config
  tests/autorestart/test_container_autorestart.py
  tests/common/config_reload.py
Labels: Request for 202012 branch, Request for 202205 branch

#6752 Ignore known error logs in test_container_autorestart
  tests/autorestart/test_container_autorestart.py
Labels: Request for 202205 branch

#6415 [autorestart] skip loganalizer error
  tests/autorestart/test_container_autorestart.py
Labels: Request for 202012 branch

#6757 Correct bgp sanity check timeout value
  tests/common/plugins/sanity_check/checks.py
Labels: Request for 202012 branch, Request for 202205 branch

#5715 Run pfcwd on frontend nodes of a T2 chassis
  tests/common/fixtures/conn_graph_facts.py
  tests/pfcwd/conftest.py
  tests/pfcwd/test_pfc_config.py
  tests/pfcwd/test_pfcwd_all_port_storm.py
  tests/pfcwd/test_pfcwd_function.py
  tests/pfcwd/test_pfcwd_timer_accuracy.py
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: chassis, Request for 202205 branch

#6758 Fix `test_active_tor_reboot_downstream`
  tests/common/dualtor/nic_simulator_control.py
Labels: Request for 202205 branch

#6390 Adjusting ACL test cases for DNX (J2c+) chipset on a T2 VoQ Chassis
  tests/acl/templates/acltb_v6_test_rules.j2
  tests/acl/templates/acltb_v6_test_rules_part_2.j2
  tests/acl/test_acl.py
Labels: chassis, Request for 202205 branch

#6751 DEFAULT_ASIC_SERVICES list based on Feature Table status on device
  tests/common/devices/multi_asic.py
Labels: chassis, Request for 202205 branch

#6780 [BGP] Stablize `test_bgp_update_timer` on dualtor testbeds
  tests/bgp/conftest.py
  tests/bgp/test_bgp_update_timer.py
Labels: Request for 202205 branch

#6649 [Mellanox] Add new cases for eeprom
  tests/platform_tests/mellanox/test_check_sfp_eeprom.py
  tests/platform_tests/mellanox/util.py
Labels: Request for 202012 branch, Request for 202205 branch

#6737 Update WRR test to support qos remapping
  tests/qos/files/qos.yml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch

#6777 Fix CRM testcase for multi-asic.
  tests/crm/conftest.py
Labels: Request for 202205 branch

#6690 Set vlan_mac and loopback ip for dual tor
  ansible/roles/test/files/ptftests/advanced-reboot.py
  tests/common/fixtures/advanced_reboot.py
Labels: Request for 202012 branch, Request for 202205 branch

#6800 [autorestart]: Enable autorestart for all features before test begins
  tests/autorestart/test_container_autorestart.py
Labels: Request for 202205 branch

#6041 Adding new ecn testcases for cisco-8000 platform.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/ixia/ecn/files/helper.py
  tests/ixia/ecn/test_dequeue_ecn.py
  tests/ixia/ecn/test_ecn_markings_cisco_8000.py
  tests/ixia/ecn/test_red_accuracy.py
Labels: Request for 202012 branch, Request for 202205 branch

#6790 Fix port mapping between PTF docker and DUT for chassis
  tests/pfcwd/files/pfcwd_helper.py
Labels: chassis, Request for 202205 branch

#6687 [backend] Modify sub port testcases to use common acl helpers
  tests/sub_port_interfaces/conftest.py
  tests/sub_port_interfaces/sub_ports_helpers.py
Labels: Request for 202012 branch, Request for 202205 branch

#6808 Add remove vlan function in sonic.py
  tests/common/devices/sonic.py
Labels: Request for 202205 branch

#6809 fix dhcp relay test failure with backgound traffic
  ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py
  tests/dhcp_relay/test_dhcp_relay.py
Labels: Request for 202012 branch, Request for 202205 branch

#6688 [arp]: Add tests for dualtor failed neighbors
  tests/arp/test_arp_dualtor.py
  tests/common/dualtor/dual_tor_utils.py
  tests/common/fixtures/ptfhost_utils.py
Labels: Request for 202012 branch, Request for 202205 branch

#6802 [snmp]: Fix test_snmp_phy_entity psu test
  tests/snmp/test_snmp_phy_entity.py
Labels: Request for 202205 branch

#6841 Support ignoring table entries in DUT health check
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch

#6461 Fix verify_no_packet_any call in fib_test
  ansible/roles/test/files/ptftests/fib_test.py
Labels: Request for 202012 branch, Request for 202205 branch

#6527 Enhancing core_dump_and_config_check to be multi-asic aware
  ansible/config_sonic_basedon_testbed.yml
  tests/conftest.py
  tests/test_pretest.py
Labels: Request for 202205 branch

#6483 [bgp]Fix the test case test_TSA failure when check the routes on the eos host
  tests/bgp/test_traffic_shift.py
Labels: Request for 202012 branch, Request for 202205 branch

#6878 [202012][arp]: Add tests for dualtor failed neighbors
  tests/arp/test_arp_dualtor.py
  tests/common/dualtor/dual_tor_utils.py
  tests/common/fixtures/ptfhost_utils.py
Labels: Request for 202012 branch

#6391 Adding support for calculating balancing in multi-lc/multi-asic case (Test_fib.py)
  ansible/roles/test/files/ptftests/fib_test.py
  ansible/roles/test/files/ptftests/py3/hash_test.py
  tests/fib/test_fib.py
Labels: Request for 202205 branch

#6832 Fix decap error when running on chassis
  tests/decap/test_decap.py
Labels: Request for 202205 branch

#6910 Fix show_techsupport test for QOS file copy on 720DT-48S
  tests/show_techsupport/test_techsupport.py
Labels: Arista-720DT-48S, Request for 202205 branch

#6919 enabled bfd tests
  tests/vxlan/conftest.py
Labels: Included in 202012 branch, Included in 202205 branch

#6911 Fix typo in run_tests.sh for checking sanity check RC
  tests/run_tests.sh
Labels: Request for 202012 branch, Request for 202205 branch

#6721 Moving check for reboot cause after interface status check
  tests/platform_tests/test_reboot.py
Labels: Request for 202205 branch

#6885 [chassis][multi-asic] update the loganalyser regex for multi asic
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202205 branch

#6925 [acl][m0] Remove skip for m0 egress acl test
  tests/acl/test_acl.py
Labels: Request for 202012 branch, Request for 202205 branch

#6922 Skip bgp speaker test on backend topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch

#6776 Adding watchdog timeout values for Cisco 8808 Supervisor and Different LCs
  tests/platform_tests/api/watchdog.yml
Labels: Request for 202205 branch
