Repository sonic-net/sonic-mgmt, pull requests merged in 2022-04, with the labels that each got.

#5417 [drop_ctrs]: Cisco 8000 platform does not drop packets with zero ip address.
  tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
Labels: Request for 202012 branch

#5402 [copp] Enhance the copp test case
  ansible/roles/test/files/ptftests/copp_tests.py
Labels: Request for 202012 branch

#5445 Allow IPinIP tunnel packet to EOS for ovs bridge rules
  ansible/roles/vm_set/library/vm_topology.py
Labels: Request for 202012 branch

#5452 [qos] Disable FDB aging before start of test
  tests/qos/qos_sai_base.py
  tests/saitests/sai_qos_tests.py
Labels: Enhancement, Request for 202012 branch

#5438 [VNET_VXLAN] Fix 'Neighbor is unreachable' failure in test_vnet_vxlan
  tests/vxlan/test_vnet_vxlan.py
Labels: Request for 202012 branch

#5453 Update test_po_cleanup.py
  tests/pc/test_po_cleanup.py
Labels: Bug :bug:, 202012 issue, 201911 issue

#5423 add run_arp_responder fixture for test_tunnel_memory_leak
  tests/dualtor/conftest.py
  tests/dualtor/test_tunnel_memory_leak.py
Labels: Request for 202012 branch

#5422 enable test_copp on t0
  tests/copp/test_copp.py
Labels: Request for 202012 branch

#5482 AddRack skipped for multi-asic
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202012 branch

#5442 Add SAI_FDB_EVENT_MOVE to Sairedis patterns
  tests/platform_tests/reboot_timing_constants.py
Labels: Request for 202012 branch

#5377 [BGP] Adding checks for bgp sessions and routes on VMs
  tests/bgp/test_traffic_shift.py
Labels: Bug :bug:

#5428 Added code to account for the absence of platform.json
  tests/platform_tests/api/test_psu_fans.py
Labels: Request for 202012 branch

#5489 [fdb] Send some more pkts in retry
  tests/fdb/test_fdb.py
Labels: Request for 202012 branch

#5435 Fix loganalyzer no common config issue and re-balance PR testing
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
  tests/common/helpers/parallel.py
  tests/common/plugins/loganalyzer/__init__.py
  tests/common/plugins/loganalyzer/loganalyzer.py
  tests/kvmtest.sh
Labels: Request for 202012 branch

#5462 Xfail dhcpv6_relay test cases on cisco platform dualtor
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202012 branch

#5385 adding start index for cisco-8000 to respond to arp request
  tests/arp/files/ferret.py
Labels: Request for 202012 branch

#5461 Disable log analyzer for test_bgp_slb which performed advanced reboot
  tests/bgp/test_bgp_slb.py
Labels: Request for 202012 branch

#5491 Support Vertiv PDU in snmpPduController
  tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Labels: Request for 202012 branch

#5499 Temporarily ignore some error syslog to reduce test noise
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202012 branch

#5484 Fix dest_port calculation for T0 Everflow downstream test
  tests/everflow/everflow_test_utilities.py
Labels: Request for 202012 branch

#5517 [reboot] Remove restriction on test_reboot.py
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
  tests/platform_tests/test_reboot.py
Labels: Request for 202012 branch

#5510 Cisco Platform:skip configurable_drop_counters sip_link_local tests
  tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
Labels: Request for 202012 branch

#5479 Everflow packets TTL check for cisco platform
  tests/everflow/everflow_test_utilities.py
Labels: Request for 202012 branch

#5535 [console] add printing err
  tests/console/test_console_loopback.py
  tests/console/test_console_reversessh.py
Labels: Request for 202012 branch

#5529 [MASIC] disable thermalctld when running test_fan_drawer_fans.py
  tests/platform_tests/api/test_fan_drawer_fans.py
Labels: Request for 202012 branch, multi-ASIC

#5554 fix the bug of missing monit results in sanity check
  tests/common/plugins/sanity_check/checks.py
Labels: Request for 202012 branch

#5557 Remove DATAACL table before `test_acl`
  tests/acl/test_acl.py
Labels: Request for 202012 branch

#5549 Temporarily ignore error messages and disable loganalyzer for cases performed reload
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
  tests/dualtor_io/test_normal_op.py
  tests/dualtor_io/test_tor_failure.py
Labels: Request for 202012 branch

#3776 [arp] Allow use of discontiguous ports with ARP tests.
  tests/arp/conftest.py
Labels: chassis

#5553 [Mellanox] Mock all thermal zone to normal temperature before testing dynamic minimum algorithm
  tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
  tests/platform_tests/mellanox/test_thermal_control.py
Labels: Bug :bug:

#5547 [Mellanox][watchdog]Add missing ':' in watchdog.yml
  tests/platform_tests/api/watchdog.yml
Labels: Bug :bug:

#5560 Fix timeout logic for wr_arp ptf test
  ansible/roles/test/files/ptftests/wr_arp.py
Labels: Request for 202012 branch

#5262 Fix test_cancelled_warm_reboot - move exit to before OA pause
  tests/platform_tests/verify_dut_health.py
Labels: Request for 202012 branch
