Repository sonic-net/sonic-mgmt, pull requests merged in 2023-02, with the labels that each got.

#7362 [dualtor] Improve toggle fixtures
  tests/common/dualtor/mux_simulator_control.py
Labels: Request for 202205 branch

#7361 [dualtor] Restart icmp_responder only if it is running
  tests/common/fixtures/ptfhost_utils.py
Labels: Request for 202205 branch

#7373 Skip test_trap_config_save_after_reboot for 202012 branch
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202012 branch, Request for 202205 branch

#7372 Skip test case test_show_platform_syseeprom for arista 7060
  tests/platform_tests/cli/test_show_platform.py
Labels: Request for 202012 branch, Request for 202205 branch

#7378 [acl][mx] Fix test_stress_acl failed on mx
  tests/acl/test_stress_acl.py
Labels: Request for 202205 branch

#7261 changing routes added from 10 to 64 in test_crm.py script
  tests/crm/test_crm.py
Labels: Request for 202012 branch, Request for 202205 branch

#7379 acl test support for new topo t1-56-lag
  ansible/veos
  ansible/veos_vtb
  tests/acl/test_acl.py
Labels: Request for 202205 branch

#7343 [chassis] Everflow enhancement
  tests/common/utilities.py
  tests/everflow/everflow_test_utilities.py
Labels: Request for 202205 branch

#7371 [chassis] ensure test_thermal_state_db to run on sup only
  tests/platform_tests/test_thermal_state_db.py
Labels: chassis, Request for 202205 branch

#7265 Fix failures in everflow tests for T2 topology
  tests/everflow/conftest.py
  tests/everflow/everflow_test_utilities.py
  tests/everflow/test_everflow_testbed.py
Labels: P0, Request for 202205 branch

#7303 Fixes - Platform API tests for test_module & test_watchdog - Changes for PR #4909
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
  tests/platform_tests/api/test_module.py
Labels: chassis, Request for 202205 branch

#7376 [Framework] Add ACL counter related methods to `SonicHost`
  docs/api_wiki/README.md
  docs/api_wiki/sonichost_methods/clear_acl_counters.md
  docs/api_wiki/sonichost_methods/get_acl_counter.md
  tests/common/devices/constants.py
  tests/common/devices/sonic.py
Labels: Request for 202205 branch

#7381 [dualtor] Fix test_standby_tor_downstream_loopback_route_readded
  tests/dualtor/test_orchagent_standby_tor_downstream.py
Labels: Request for 202012 branch, Request for 202205 branch

#7387 [acl] Remove typo in shell of test_stress_acl
  tests/acl/templates/acltb_test_stress_acl.sh
Labels: Request for 202012 branch

#6318 Ingoring local asic ping of ipv6 interfaces when one side is down
  tests/voq/test_voq_ipfwd.py
Labels: chassis, Request for 202205 branch

#6176 Fix the syslog to use default route from default table
  tests/syslog/test_syslog.py
Labels: Request for 202205 branch

#7370 [Snappi] Increase number of calls for ARP wait
  tests/snappi/pfc/files/helper.py
  tests/snappi/pfcwd/files/pfcwd_basic_helper.py
  tests/snappi/pfcwd/files/pfcwd_burst_storm_helper.py
  tests/snappi/pfcwd/files/pfcwd_multi_node_helper.py
  tests/snappi/pfcwd/files/pfcwd_runtime_traffic_helper.py
  tests/snappi/test_snappi.py
Labels: Request for 202012 branch, Request for 202205 branch

#7398 support HwSKU Arista-7050QX32S-Q32
  ansible/group_vars/sonic/variables
Labels: Request for 202012 branch, Request for 202205 branch

#7394 support t1-56-lag
  ansible/library/test_facts.py
  ansible/roles/test/tasks/bgp_gr_helper.yml
  ansible/roles/test/tasks/bgp_gr_helper/get_vm_info.yml
  ansible/roles/test/tasks/bgp_multipath_relax.yml
  ansible/roles/test/tasks/everflow_testbed/get_general_port_info.yml
  ansible/roles/test/tasks/everflow_testbed/run_test.yml
  ansible/roles/test/tasks/shared-fib.yml
  ansible/roles/test/templates/fib.j2
  ansible/roles/test/vars/testcases.yml
  ansible/testbed-new.yaml
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/pfcwd/conftest.py
  tests/qos/qos_sai_base.py
  tests/vxlan/test_vxlan_ecmp.py
Labels: Request for 202205 branch

#7389 [bgp] Fix overwrite in bgp conftest
  tests/bgp/conftest.py
Labels: Request for 202205 branch

#7284 changing max packets in sai_qos_tests.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202012 branch, Request for 202205 branch

#7393 Support SONiC fanout in test_pfc_counters
  tests/qos/qos_helpers.py
  tests/qos/test_pfc_counters.py
Labels: Request for 202012 branch, Request for 202205 branch

#7354 Ignore IP flags in generate_hashed_packet_to_server in tests/common/dualtor/dual_tor_utils.py
  tests/common/dualtor/dual_tor_utils.py
Labels: Request for 202205 branch

#7096 [multi-asic] Updated Log Analyzer ignore syslog messages
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: chassis, Request for 202205 branch

#7402 Make traffic shift tests work on devices with different route-maps
  ansible/roles/eos/templates/t2-leaf.j2
  tests/bgp/test_traffic_shift.py
  tests/configlet/util/common.py
Labels: Request for 202205 branch

#7413 ADD_TOPO: Enhancements to support large number of CEOS VMs required for scaled T2 Topology
  ansible/library/exabgp.py
  ansible/roles/eos/tasks/ceos.yml
  ansible/roles/vm_set/tasks/add_topo.yml
  ansible/roles/vm_set/tasks/announce_routes.yml
  ansible/roles/vm_set/templates/exabgp.conf.j2
Labels: Request for 202205 branch

#7428 [show_techsupport] Fix duplate adding of docker list in test_auto_techsupport
  tests/show_techsupport/test_auto_techsupport.py
Labels: Request for 202205 branch

#7259 Update EXPECTED_XCVR_THRESHOLD_INFO_KEYS list in test_sfp.py
  tests/platform_tests/api/test_sfp.py
Labels: Bug :bug:

#7433 [Testbed] Update ansible playbook for deploying SONiC 202205 fanout switches
  ansible/roles/fanout/tasks/sonic/fanout_sonic_202205.yml
  ansible/roles/fanout/templates/sonic_deploy_202205.j2
Labels: Request for 202205 branch

#7437 [chassis] [autorestart] add ignore some syslog errors
  tests/autorestart/test_container_autorestart.py
Labels: Request for 202205 branch

#7401 Use same device hostname fixture in cont-reboot and advanced_reboot
  tests/platform_tests/test_cont_warm_reboot.py
Labels: Request for 202012 branch, Request for 202205 branch

#7431 [dualtor] Improve `test_toggle_mux`
  tests/dualtor/test_toggle_mux.py
Labels: Request for 202012 branch, Request for 202205 branch

#7404 [Mellanox] Support disabling timers on LAG members for QoS test in dual ToR DSCP remapping scenario
  tests/qos/files/mellanox/packets_aging.py
Labels: Enhancement, Request for 202205 branch

#7448 [dualtor] Fix `test_bgp_update_timer`
  tests/bgp/test_bgp_update_timer.py
  tests/common/dualtor/mux_simulator_control.py
Labels: Request for 202012 branch, Request for 202205 branch

#7384 [cisco gb asic]: fill up the first expected nexthop ip addr after ecmp order scheme performs
  tests/ipfwd/test_nhop_group.py
Labels: Request for 202012 branch, Request for 202205 branch

#7079 [J2C+] QoS/PFC test fixes for SONIC chassis
  tests/common/fixtures/duthost_utils.py
  tests/common/fixtures/ptfhost_utils.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/conftest.py
  tests/qos/files/qos.yml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_base_test.py
  tests/saitests/py3/sai_qos_tests.py
Labels: P0, chassis, Request for 202205 branch

#7341 [Chassis] Modify sleep_time from 60s to 90s for ZR interfaces in platform and voq tests
  tests/platform_tests/link_flap/link_flap_utils.py
  tests/platform_tests/sfp/test_sfputil.py
  tests/voq/test_voq_nbr.py
Labels: Request for 202205 branch

#7319 [Chassis] Remove skip to allow the test_reboot_supervisor to run on chassis
  tests/voq/test_voq_disrupts.py
Labels: Request for 202205 branch

#7477 [dualtor] call set drop once
  tests/common/dualtor/nic_simulator_control.py
Labels: Request for 202205 branch

#7485 Add t0-56-po2vlan topo to ansible reboot test
  ansible/roles/test/vars/testcases.yml
Labels: Request for 202012 branch, Request for 202205 branch

#7494 refine sai_thrift_read_port_counters
  tests/common/fixtures/pfc_asym.py
  tests/saitests/pfc_asym.py
  tests/saitests/py3/sai_qos_tests.py
  tests/saitests/py3/switch.py
Labels: Request for 202205 branch

#7501 [pdu controller] update pdu type determining logics
  tests/common/plugins/pdu_controller/pdu_manager.py
  tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Labels: Request for 202012 branch, Request for 202205 branch

#7490 Temporary remove test_advanced_reboot.py since it stably fails.
  .azure-pipelines/pr_test_scripts.yaml
Labels: Request for 202012 branch, Request for 202205 branch

#7472 Modified copp test case to run it on marvell asic
  tests/copp/test_copp.py
Labels: Request for 202205 branch

#7504 [Qos]Fix saitest issue: asic_type' is not defined.
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch

#7502 [dualtor] fix `KeyError` caught in `verify_db` in control plane common utilities
  tests/common/dualtor/control_plane_utils.py
Labels: Request for 202012 branch, Request for 202205 branch

#7516 [Bugfix] Shutdown all exabgp processes correctly while removing topo
  ansible/roles/vm_set/tasks/announce_routes.yml
Labels: Request for 202012 branch, Request for 202205 branch

#7326 Changed the bidirectional traffic-flow check to unidirection in ixia pfcwd script for cisco-8000
  tests/ixia/pfcwd/conftest.py
  tests/ixia/pfcwd/files/pfcwd_multi_node_helper.py
  tests/ixia/pfcwd/test_pfcwd_a2a.py
  tests/ixia/pfcwd/test_pfcwd_m2o.py
Labels: Request for 202012 branch, Request for 202205 branch

#6796 Update watchdog.yml
  tests/platform_tests/api/watchdog.yml
Labels: Request for 202205 branch

#7515 [dualtor] Check before restore drop ports
  tests/common/dualtor/nic_simulator_control.py
Labels: Request for 202205 branch

#6520 Adding skip condition for platform_tests/mellanox if asic_type is not mellanox
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202205 branch

#7521 Add an ansible-playbook to collect `show tech` result of a specific testbed
  ansible/collect_show_tech.yml
  ansible/testbed-cli.sh
Labels: Request for 202012 branch, Request for 202205 branch

#7496 Modified the crm test case to run it on marvell asic
  tests/crm/test_crm.py
Labels: Request for 202205 branch

#7526 [Bugfix] Fix COPP testcases for non-marvell platform
  tests/copp/test_copp.py
Labels: Request for 202205 branch

#7385 Enhanced duts_running_config_facts() and duts_minigraph_facts() to handle when asics_present are not contnuous
  tests/common/fixtures/fib_utils.py
  tests/common/fixtures/ptfhost_utils.py
  tests/common/plugins/sanity_check/checks.py
  tests/conftest.py
  tests/copp/test_copp.py
  tests/decap/test_decap.py
  tests/drop_packets/test_configurable_drop_counters.py
  tests/everflow/conftest.py
  tests/fib/test_fib.py
  tests/platform_tests/test_link_down.py
Labels: multi-ASIC, Request for 202205 branch

#7503 Skip VOQ test cases for Non-voq platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: chassis, chassis-packet, Request for 202205 branch

#7456 [chassis] increase timeout for fixture shutdown_ebgp
  tests/common/fixtures/duthost_utils.py
Labels: Request for 202205 branch

#7512 Fix the local variable 'dut_port' referenced before assignment
  tests/common/fixtures/ptfhost_utils.py
Labels: Request for 202205 branch

#7513 [QoS] Do not enlarge PFC WD polling timer if it is shorter in QoS testPfcStormWithSharedHeadroomOccupancy
  tests/qos/test_qos_sai.py
Labels: Request for 202205 branch

#7457 [Everflow, Voq, chassis] Avoid need to configure IP address for Recycle port
  tests/everflow/conftest.py
Labels: chassis, Request for 202205 branch

#7537 Fix portstat parser to accommodate new reminder message in portstat output
  tests/common/portstat_utilities.py
Labels: chassis, Request for 202205 branch

#7535 Fix to retrieve asic host if asic_index is not continuous
  tests/common/devices/multi_asic.py
Labels: chassis, Request for 202205 branch

#7518 [nic_simulator_control] Add backoff for retries
  tests/common/dualtor/nic_simulator_control.py
Labels: Request for 202205 branch

#7544 [t1] [t2] skip Fast and warm reboot testcases for t1 and t2
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: chassis, Request for 202012 branch, Request for 202205 branch

#7488 Fixed KeyError: 'platform_asic' issue observed while running egress a…
  tests/acl/test_acl.py
Labels: Request for 202205 branch

#6774 Skip everflow/test_everflow_interfaces for multi-asic due to sonic-buildimage issue#11776
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: chassis, Request for 202205 branch

#7538 [snmp] Add sleep to test_snmp_fdb during sending packet and verifying
  tests/snmp/test_snmp_fdb.py
Labels: Request for 202205 branch

#7542 Update port utils for Arista 7050QX
  ansible/module_utils/port_utils.py
Labels: Request for 202012 branch, Request for 202205 branch

#7333 [packet-chassis]: Fixes required to run test_snmp_lldp test on packet chassis
  ansible/library/minigraph_facts.py
  ansible/library/snmp_facts.py
  ansible/templates/minigraph_dpg_asic.j2
Labels: chassis

#7553 [container_autorestart] Ignore error logs
  tests/autorestart/test_container_autorestart.py
Labels: Request for 202205 branch

#7506 Fix flaky traffic_shift test - Ignore same aspath routes during validation
  tests/bgp/test_traffic_shift.py
Labels: Request for 202205 branch

#7236 DscpToPgMapping qos test fails intermittently due to tcp/lacp messages received
  tests/saitests/py3/sai_qos_tests.py
Labels: chassis, Request for 202205 branch

#7367 [Snappi] Modifications to pfcwd a2a test design for mlnx 4600c
  tests/snappi/pfcwd/files/pfcwd_multi_node_helper.py
Labels: Request for 202012 branch, Request for 202205 branch

#7547 VoQ chassis : skip test_ser.py tests on DNX based devices.
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: chassis, Request for 202205 branch

#7543 fix the issue which timeout is too short for bgp shut
  tests/common/fixtures/duthost_utils.py
Labels: Request for 202205 branch

#7581 [m0][bgp] Add support for m0 in bgp test to simulate both t0 and t1 scenario
  tests/bgp/conftest.py
  tests/conftest.py
Labels: Request for 202205 branch

#7586 [fixbug-7582]: A new parameter is added for neighbor_vm_restore but the usage in advanceboot_neighbor_restore is not updated
  tests/common/plugins/sanity_check/recover.py
Labels: Request for 202205 branch

#7587 Stop exabgp processes before remove PTF container (for both old and new exabgp process naming convention)
  ansible/roles/vm_set/tasks/announce_routes.yml
Labels: Request for 202012 branch, Request for 202205 branch

#7584 [tacacs] Remove useless params in test_ro_disk
  tests/tacacs/test_ro_disk.py
Labels: Request for 202205 branch

#7571 [Voq, chassis] Fix the issue where Ethernet-Rec is considered as an interface with IP address
  tests/voq/test_voq_ipfwd.py
  tests/voq/test_voq_nbr.py
Labels: Request for 202205 branch
