Repository sonic-net/sonic-mgmt, pull requests merged in 2023-12, with the labels that each got.

#10396 Skip error messages for https://github.com/sonic-net/sonic-buildimage…
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202305 branch

#10918 [action] [PR:10911] [dualtor-io] Increase stop wait to 90s
  tests/templates/dual_tor_sniffer.conf.j2
Labels: automerge

#10924 [dualtor] Fix mux config manual leftover
  tests/common/dualtor/mux_simulator_control.py
Labels: Request for 202205 branch, Request for 202305 branch

#10931 [action] [PR:10924] [dualtor] Fix mux config manual leftover
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#10929 [action] [PR:10878] Update sysfs node name/path according to production code change
  tests/common/mellanox_data.py
  tests/platform_tests/mellanox/check_sysfs.py
  tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
  tests/system_health/mellanox/mellanox_device_mocker.py
Labels: automerge

#10928 [topo]: Change dualtor IPv6 loopback addresses
  ansible/vars/topo_dualtor-120.yml
  ansible/vars/topo_dualtor-56.yml
  ansible/vars/topo_dualtor-64.yml
  ansible/vars/topo_dualtor-aa-120.yml
  ansible/vars/topo_dualtor-aa-56.yml
  ansible/vars/topo_dualtor-aa-64.yml
  ansible/vars/topo_dualtor-aa.yml
  ansible/vars/topo_dualtor-mixed-120.yml
  ansible/vars/topo_dualtor-mixed-56.yml
  ansible/vars/topo_dualtor-mixed.yml
  ansible/vars/topo_dualtor.yml
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#10942 [action] [PR:10144] Set port->ptf_index map empty before construction
  tests/common/devices/sonic.py
Labels: automerge

#10943 [sanity_check] Use golden config to reboot for `adaptive_recover`
  tests/common/plugins/sanity_check/recover.py
Labels: Request for 202205 branch, Request for 202305 branch

#10948 [action] [PR:10938] Enhance the test route flap
  tests/route/test_route_flap.py
Labels: automerge

#10947 [action] [PR:10943] [sanity_check] Use golden config to reboot for `adaptive_recover`
  tests/common/plugins/sanity_check/recover.py
Labels: automerge

#10921 Fix http_ready false issue
  tests/bgp/test_bgp_speaker.py
Labels: Request for 202305 branch

#10962 [action] [PR:10865] Improve TACACS UT by add retry and print syslog when login failed for debug.
  tests/tacacs/test_accounting.py
  tests/tacacs/test_authorization.py
Labels: automerge

#10965 [dualtor-120] Reduce `test_fdb` runtime
  tests/fdb/test_fdb.py
Labels: Request for 202205 branch, Request for 202305 branch

#10963 [GCU][test_vlan_interface] Update fixture to accommodate dualtor testbed
  tests/generic_config_updater/test_vlan_interface.py
Labels: Request for 202305 branch

#10958 Exclude supervisor from the dut list - BGP/test_bgp_authentication
  tests/bgp/test_bgp_authentication.py
Labels: Request for 202205 branch

#10909 Remove the redundant log analyzer in next hop group test
  tests/ipfwd/test_nhop_group.py
Labels: Request for 202305 branch

#10651 Add docker0's IPv6 address since it was removed when disabling IPv6
  tests/qos/qos_sai_base.py
Labels: Request for 202205 branch, Request for 202305 branch

#10834 Make bgp/test_bgp_queue.py aware of multi-asic
  tests/bgp/test_bgp_queue.py
Labels: Request for 202205 branch

#10954 Make stable for testcase test_counterpoll_watermark.py
  tests/platform_tests/counterpoll/test_counterpoll_watermark.py
Labels: Request for 202305 branch

#10975 [action] [PR:10954] Make stable for testcase test_counterpoll_watermark.py
  tests/platform_tests/counterpoll/test_counterpoll_watermark.py
Labels: automerge

#10974 [action] [PR:10827] Improve watchdog UT to use LogAnalyzer
  tests/system_health/test_watchdog.py
Labels: automerge

#10982 [action] [PR:10867] Fix issue with test_syslog_rate_limit
  tests/syslog/test_syslog_rate_limit.py
Labels: automerge

#10981 [action] [PR:10958] Exclude supervisor from the dut list - BGP/test_bgp_authentication
  tests/bgp/test_bgp_authentication.py
Labels: automerge

#10980 [action] [PR:10958] Exclude supervisor from the dut list - BGP/test_bgp_authentication
  tests/bgp/test_bgp_authentication.py
Labels: automerge

#10978 [action] [PR:10834] Make bgp/test_bgp_queue.py aware of multi-asic
  tests/bgp/test_bgp_queue.py
Labels: automerge

#10852 [Nvidia] Change bfd_responder support python3
  ansible/roles/test/files/ptftests/py3/bfd_responder.py
  tests/vxlan/vxlan_ecmp_utils.py
Labels: Request for 202305 branch

#9111 Add x86_64-mlnx_msn2700-r0 A1 support
  ansible/group_vars/sonic/sku-sensors-data.yml
  tests/common/mellanox_data.py
  tests/platform_tests/test_sensors.py
Labels: Request for 202305 branch

#10988 [action] [PR:10967] Fix test_show_platform_ssdhealth test for 7050QX-32S
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: automerge

#10996 [bgp] Skip bgp slb fast reboot test on dualtor
  tests/bgp/test_bgp_slb.py
Labels: Request for 202205 branch, Request for 202305 branch

#10995 Move public functions from `upgrade_image.py` to `common.py`.
  .azure-pipelines/common.py
  .azure-pipelines/upgrade_image.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#10999 [action] [PR:10996] [bgp] Skip bgp slb fast reboot test on dualtor
  tests/bgp/test_bgp_slb.py
Labels: automerge

#10993 crm/test_crm.py: Skip namespace check on single asic systems
  tests/crm/test_crm.py
Labels: Request for 202205 branch, Request for 202305 branch

#11003 [action] [PR:10993] crm/test_crm.py: Skip namespace check on single asic systems
  tests/crm/test_crm.py
Labels: automerge

#11002 [action] [PR:10993] crm/test_crm.py: Skip namespace check on single asic systems
  tests/crm/test_crm.py
Labels: automerge

#10998 [action] [PR:10996] [bgp] Skip bgp slb fast reboot test on dualtor
  tests/bgp/test_bgp_slb.py
Labels: automerge

#11004 check in topo_t1-56-lag.yml for O8C48
  ansible/vars/topo_t1-56-lag.yml
Labels: Request for 202205 branch, Request for 202305 branch

#11005 [action] [PR:10970] [conditional mark] skip test_decap for 7260cx3 in 202305 release
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10894 Allow fewer PORT_READY messages than expected
  tests/platform_tests/conftest.py
Labels: Request for 202305 branch

#11006 [nic_simulator] Add missing attribute in the slot
  ansible/dualtor/nic_simulator/nic_simulator.py
Labels: Request for 202205 branch, Request for 202305 branch

#11017 [action] [PR:10530] Fix flaky testcase test_reload_configuration_checks so slow device or device without clock chip can pass the test
  tests/common/reboot.py
  tests/platform_tests/test_reload_config.py
Labels: automerge

#11016 [action] [PR:10530] Fix flaky testcase test_reload_configuration_checks so slow device or device without clock chip can pass the test
  tests/common/reboot.py
  tests/platform_tests/test_reload_config.py
Labels: automerge

#10966 Add github issue skip to link_flap test
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch

#10887 Increase SSH shutdown timeout for memory exhaustion test
  tests/platform_tests/test_memory_exhaustion.py
Labels: Request for 202205 branch, Request for 202305 branch

#11025 [action] [PR:7629] Skipping Everflow Policer tests on dnx platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#11024 [action] [PR:10887] Increase SSH shutdown timeout for memory exhaustion test
  tests/platform_tests/test_memory_exhaustion.py
Labels: automerge

#11023 [action] [PR:10887] Increase SSH shutdown timeout for memory exhaustion test
  tests/platform_tests/test_memory_exhaustion.py
Labels: automerge

#11026 wait for CRM stats init complete before start nhop test
  tests/ipfwd/test_nhop_group.py
Labels: Request for 202205 branch, Request for 202305 branch

#11031 [action] [PR:11026] wait for CRM stats init complete before start nhop test
  tests/ipfwd/test_nhop_group.py
Labels: automerge

#11030 [action] [PR:11026] wait for CRM stats init complete before start nhop test
  tests/ipfwd/test_nhop_group.py
Labels: automerge

#11011 [Override config table] exclude supervisor from override config tests
  tests/override_config_table/test_override_config_table.py
  tests/override_config_table/test_override_config_table_masic.py
Labels: Request for 202205 branch

#10944 Update the pfcwd warm reboot test for "create_only_config_db_buffers"
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: Request for 202205 branch, Request for 202305 branch

#10883 Fix test issues in the advanced-reboot test
  ansible/roles/test/files/ptftests/py3/advanced-reboot.py
Labels: Request for 202305 branch

#10945 [test gap] Add test script to verify if HASH_SEED and OFFSET_ECMP value is correct
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/ecmp/test_ecmp_sai_value.py
Labels: Request for 202305 branch

#11040 [test_route_flap] ignore the missed_FRR_routes for test_route_flap
  tests/route/test_route_flap.py
Labels: Request for 202305 branch

#11042 [action] [PR:11040] [test_route_flap] ignore the missed_FRR_routes for test_route_flap
  tests/route/test_route_flap.py
Labels: automerge

#11041 [action] [PR:10945] [test gap] Add test script to verify if HASH_SEED and OFFSET_ECMP value is correct
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/ecmp/test_ecmp_sai_value.py
Labels: automerge

#11028 Ignore unimplemented Broadcom SAI in loganalyzer
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202305 branch, Approved for 202305 branch

#11032 Update test_pktgen.py
  ansible/library/show_interface.py
  tests/test_pktgen.py
Labels: Request for 202305 branch

#10915 Implement Cisco qos parameter autogenerator for 8111
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/files/qos_params.gr.yaml
Labels: Request for 202205 branch, Request for 202305 branch

#11051 [action] [PR:10082] [Platform_tests/test_watchdog]: Added platform check to disarm watchdog for nokia_ixs7215
  tests/platform_tests/api/test_watchdog.py
Labels: automerge

#11050 [action] [PR:9558] [Mellanox] Fix the issue in check sysfs on SN5600 platform
  tests/common/mellanox_data.py
Labels: automerge

#11048 [action] [PR:8921] [Nvidia][reboot_cause] Remove cpu reset cause from test
  tests/common/reboot.py
  tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
  tests/platform_tests/mellanox/test_reboot_cause.py
Labels: automerge

#11047 [action] [PR:8051] Update conftest of crm test
  tests/crm/conftest.py
Labels: automerge

#11046 [action] [PR:10082] [Platform_tests/test_watchdog]: Added platform check to disarm watchdog for nokia_ixs7215
  tests/platform_tests/api/test_watchdog.py
Labels: automerge

#11065 [action] [PR:10883] Fix test issues in the advanced-reboot test
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: automerge

#11064 [action] [PR:10852] [Nvidia] Change bfd_responder support python3
  ansible/roles/test/files/ptftests/py3/bfd_responder.py
  tests/vxlan/vxlan_ecmp_utils.py
Labels: automerge

#11063 [action] [PR:10835] [Snappi] Changed lag port config for latest snappi version
  tests/common/snappi_tests/snappi_fixtures.py
Labels: automerge

#11062 [action] [PR:10835] [Snappi] Changed lag port config for latest snappi version
  tests/common/snappi_tests/snappi_fixtures.py
Labels: automerge

#11061 [action] [PR:10814] [Route flap] add module_ignore_errors to shell command to let it return empty output
  tests/route/test_route_flap.py
Labels: automerge

#11060 [action] [PR:10706] remove inter test case dependency in VxLAN tests
  tests/vxlan/test_vxlan_ecmp.py
Labels: automerge

#11058 [action] [PR:10509] Update the expected key for the transceiver info test
  tests/platform_tests/api/test_sfp.py
Labels: automerge

#11056 [action] [PR:10393] [Mellanox] Fix test_incremental_qos_config_updates issue
  tests/generic_config_updater/test_incremental_qos.py
Labels: automerge

#11055 [action] [PR:10152] Add conditional skip for the vnet_route_leak by bug
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#11054 [action] [PR:10152] Add conditional skip for the vnet_route_leak by bug
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#11053 [action] [PR:10100] [sonic-mgmt snmp] Fix test_snmp_queue.py multi-asic support for multiple linecards
  tests/snmp/test_snmp_queue.py
Labels: automerge

#11052 [action] [PR:10100] [sonic-mgmt snmp] Fix test_snmp_queue.py multi-asic support for multiple linecards
  tests/snmp/test_snmp_queue.py
Labels: automerge

#11079 [action] [PR:11011] [Override config table] exclude supervisor from override config tests
  tests/override_config_table/test_override_config_table.py
  tests/override_config_table/test_override_config_table_masic.py
Labels: automerge

#11078 [action] [PR:11011] [Override config table] exclude supervisor from override config tests
  tests/override_config_table/test_override_config_table.py
  tests/override_config_table/test_override_config_table_masic.py
Labels: automerge

#11077 [action] [PR:10965] [dualtor-120] Reduce `test_fdb` runtime
  tests/fdb/test_fdb.py
Labels: automerge

#11076 [action] [PR:10965] [dualtor-120] Reduce `test_fdb` runtime
  tests/fdb/test_fdb.py
Labels: automerge

#11074 [action] [PR:10944] Update the pfcwd warm reboot test for "create_only_config_db_buffers"
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: automerge

#11073 [action] [PR:10944] Update the pfcwd warm reboot test for "create_only_config_db_buffers"
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: automerge

#11072 [action] [PR:10928] [topo]: Change dualtor IPv6 loopback addresses
  ansible/vars/topo_dualtor-120.yml
  ansible/vars/topo_dualtor-56.yml
  ansible/vars/topo_dualtor-64.yml
  ansible/vars/topo_dualtor-aa-120.yml
  ansible/vars/topo_dualtor-aa-56.yml
  ansible/vars/topo_dualtor-aa-64.yml
  ansible/vars/topo_dualtor-aa.yml
  ansible/vars/topo_dualtor-mixed-120.yml
  ansible/vars/topo_dualtor-mixed-56.yml
  ansible/vars/topo_dualtor-mixed.yml
  ansible/vars/topo_dualtor.yml
Labels: automerge

#11071 [action] [PR:10928] [topo]: Change dualtor IPv6 loopback addresses
  ansible/vars/topo_dualtor-120.yml
  ansible/vars/topo_dualtor-56.yml
  ansible/vars/topo_dualtor-64.yml
  ansible/vars/topo_dualtor-aa-120.yml
  ansible/vars/topo_dualtor-aa-56.yml
  ansible/vars/topo_dualtor-aa-64.yml
  ansible/vars/topo_dualtor-aa.yml
  ansible/vars/topo_dualtor-mixed-120.yml
  ansible/vars/topo_dualtor-mixed-56.yml
  ansible/vars/topo_dualtor-mixed.yml
  ansible/vars/topo_dualtor.yml
Labels: automerge

#11070 [action] [PR:10921] Fix http_ready false issue
  tests/bgp/test_bgp_speaker.py
Labels: automerge

#11069 [action] [PR:10909] Remove the redundant log analyzer in next hop group test
  tests/ipfwd/test_nhop_group.py
Labels: automerge

#11067 [action] [PR:11032] Update test_pktgen.py
  ansible/library/show_interface.py
  tests/test_pktgen.py
Labels: automerge

#11066 [action] [PR:10894] Allow fewer PORT_READY messages than expected
  tests/platform_tests/conftest.py
Labels: automerge

#10830 [action] [PR:9323] Updating LossyQueueVoq test for Cisco-8111 platform
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10821 [Arista] skip testing sfp interfaces on Arista-7050QX-32S-S4Q31
  tests/platform_tests/conftest.py
Labels: Request for 202205 branch, Request for 202305 branch

#10983 Ignoring loganalyzer error 'Failed to get port by bridge port ID'
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202305 branch

#11075 [action] [PR:10963] [GCU][test_vlan_interface] Update fixture to accommodate dualtor testbed
  tests/generic_config_updater/test_vlan_interface.py
Labels: automerge

#11059 [action] [PR:10626] [tests/stress]: Increase sleep time before checking for crm resources
  tests/stress/test_stress_routes.py
Labels: automerge

#11049 [action] [PR:9111] [Mellanox] Add x86_64-mlnx_msn2700-r0 A1 support
  ansible/group_vars/sonic/sku-sensors-data.yml
  tests/common/mellanox_data.py
  tests/platform_tests/test_sensors.py
Labels: automerge

#10864 Fixing the syntax error from pkt_gen show cpu output.
  tests/test_pktgen.py
Labels: Request for 202305 branch

#11095 [action] [PR:10864] Fixing the syntax error from pkt_gen show cpu output.
  tests/test_pktgen.py
Labels: automerge

#11045 [link_flap] Increase redis memory threshold for m0 and mx
  tests/platform_tests/link_flap/test_cont_link_flap.py
  tests/platform_tests/link_flap/test_link_flap.py
Labels: Request for 202205 branch, Request for 202305 branch

#11097 [action] [PR:11045] [link_flap] Increase redis memory threshold for m0 and mx
  tests/platform_tests/link_flap/test_cont_link_flap.py
  tests/platform_tests/link_flap/test_link_flap.py
Labels: automerge

#11068 [action] [PR:10915] Implement Cisco qos parameter autogenerator for 8111
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/files/qos_params.gr.yaml
Labels: automerge

#11096 Modify incorrect pytest.mark.topology format
  tests/ecmp/test_ecmp_sai_value.py
Labels: Request for 202305 branch, Approved for 202305 branch

#11080 check in topo t1-56-lag template for O8C48
  ansible/roles/eos/templates/t1-56-lag-spine.j2
  ansible/roles/eos/templates/t1-56-lag-tor.j2
Labels: Request for 202205 branch, Request for 202305 branch

#11102 [action] [PR:11080] check in topo t1-56-lag template for O8C48
  ansible/roles/eos/templates/t1-56-lag-spine.j2
  ansible/roles/eos/templates/t1-56-lag-tor.j2
Labels: automerge

#11101 [action] [PR:11080] check in topo t1-56-lag template for O8C48
  ansible/roles/eos/templates/t1-56-lag-spine.j2
  ansible/roles/eos/templates/t1-56-lag-tor.j2
Labels: automerge

#11100 [action] [PR:11096] Modify incorrect pytest.mark.topology format
  tests/ecmp/test_ecmp_sai_value.py
Labels: automerge

#11105 [action] [PR:10821] [Arista] skip testing sfp interfaces on Arista-7050QX-32S-S4Q31
  tests/platform_tests/conftest.py
Labels: automerge

#11027 Remove some skip condition for test_iface_loopback_action
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch, Request for 202305 branch

#11033 Define new topology t0-56-o8v48
  ansible/vars/topo_t0-56-o8v48.yml
Labels: Request for 202305 branch

#11086 Fix timeout waiting for escalation prompt issue
  ansible/devutil/devices/ansible_hosts.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#11113 [action] [PR:11086] Fix timeout waiting for escalation prompt issue
  ansible/devutil/devices/ansible_hosts.py
Labels: automerge

#10860 Loganalyzer regex correction for test_po_update
  tests/pc/test_po_update.py
Labels: Request for 202205 branch, Request for 202305 branch

#10665 Skip test_get_transceiver_threshold_info testcase if transceiver vend…
  tests/platform_tests/api/test_sfp.py
Labels: Request for 202205 branch, Request for 202305 branch

#11117 Fix flakiness of test_monitoring_critical_processes
  tests/process_monitoring/test_critical_process_monitoring.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#11118 [action] [PR:9403] [GCU E2E Testing] Update test_update_speed and test_replace_fec to consider StateDB validator
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/generic_config_updater/test_eth_interface.py
Labels: automerge

#11119 Add missing import time in test_counterpoll_watermark
  tests/platform_tests/counterpoll/test_counterpoll_watermark.py
Labels: Request for 202305 branch

#11123 [action] [PR:11117] Fix flakiness of test_monitoring_critical_processes
  tests/process_monitoring/test_critical_process_monitoring.py
Labels: automerge

#11122 [action] [PR:11117] Fix flakiness of test_monitoring_critical_processes
  tests/process_monitoring/test_critical_process_monitoring.py
Labels: automerge

#11121 [action] [PR:10665] Skip test_get_transceiver_threshold_info testcase if transceiver vend…
  tests/platform_tests/api/test_sfp.py
Labels: automerge

#11120 [action] [PR:10665] Skip test_get_transceiver_threshold_info testcase if transceiver vend…
  tests/platform_tests/api/test_sfp.py
Labels: automerge

#10886 platform_tests: Fix skip_modules check in test_power_budget_info.py
  tests/platform_tests/test_power_budget_info.py
Labels: Request for 202205 branch, Request for 202305 branch

#11108 Send packet to portchannel to improve test_vlan
  tests/vlan/test_vlan.py
Labels: Request for 202205 branch, Request for 202305 branch

#11126 update expected port broadcom platforms in test_nhop_group_member_order_capability
  tests/ipfwd/test_nhop_group.py
Labels: Request for 202305 branch

#10986 [syslog] enable/disable syslog rate limit feature in fixture
  tests/syslog/test_syslog_rate_limit.py
  tests/test_pretest.py
Labels: Request for 202305 branch

#10851 Move fixture skip_when_buffer_is_dynamic_model to conftest file
  tests/generic_config_updater/conftest.py
  tests/generic_config_updater/test_incremental_qos.py
  tests/generic_config_updater/test_mmu_dynamic_threshold_config_update.py
Labels: Request for 202305 branch

#10853 Add skip for test_custom_acl_table.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch

#11137 [action] [PR:11108] Send packet to portchannel to improve test_vlan
  tests/vlan/test_vlan.py
Labels: automerge

#11132 [action] [PR:11126] update expected port broadcom platforms in test_nhop_group_member_order_capability
  tests/ipfwd/test_nhop_group.py
Labels: automerge

#11141 fix pktgen cpu utilization checking
  tests/test_pktgen.py
Labels: Request for 202305 branch, Approved for 202305 branch

#11133 update pcbb xoff test threshold for 7050 dualtor
  tests/qos/files/qos_params.td3.yaml
Labels: Request for 202305 branch

#11142 [action] [PR:11141] fix pktgen cpu utilization checking
  tests/test_pktgen.py
Labels: automerge

#11144 [action] [PR:11133] update pcbb xoff test threshold for 7050 dualtor
  tests/qos/files/qos_params.td3.yaml
Labels: automerge

#11145 Select the right PDU controller in Dual-TOR testbed
  tests/platform_tests/test_platform_info.py
Labels: Platform, Request for 202305 branch

#11147 [action] [PR:11145] Select the right PDU controller in Dual-TOR testbed
  tests/platform_tests/test_platform_info.py
Labels: automerge

#11146 Support new HWSKU and topology for SN4700 and SN2700A1
  ansible/group_vars/sonic/variables
  tests/qos/qos_sai_base.py
Labels: Request for 202305 branch

#10559 Adding skip for TestConfigInterface and test_decap valan testcases for 8111 platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch

#11155 [action] [PR:10559] Adding skip for TestConfigInterface and test_decap valan testcases for 8111 platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10047 Add platform test for kdump
  tests/common/reboot.py
  tests/platform_tests/test_kdump.py
Labels: chassis, Request for 202205 branch, Request for 202305 branch

#11160 [dualtor] use 'get_pdu_controller' to ensure same dut in test_power_off_reboot
  tests/platform_tests/test_power_off_reboot.py
Labels: Request for 202305 branch
