Repository sonic-net/sonic-mgmt, pull requests merged in 2023-03, with the labels that each got.

#7591 Fix test_default_route.py for t2_min topology
  tests/common/devices/sonic.py
  tests/route/test_default_route.py
Labels: Request for 202205 branch

#7595 [qos] skip testQosSaiHeadroomPoolWatermark on mellanox platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch

#7606 assign None to platform_asic as default value when it not exist in test params
  tests/saitests/py3/sai_base_test.py
Labels: Request for 202205 branch

#6905 Add test case `test_custom_acl` to verify custom ACL table
  tests/acl/custom_acl_table/acl_rules.json
  tests/acl/custom_acl_table/custom_acl_table.json
  tests/acl/custom_acl_table/test_custom_acl_table.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch

#7563 [T2 Logical Chassis] Enhanced platform_tests/test_thermal_state_db.py to handle logical chassis by skipping thermal sensors that are not part of the logical chassis
  tests/platform_tests/cli/util.py
  tests/platform_tests/test_thermal_state_db.py
Labels: Request for 202205 branch

#7617 [CACL] Run cacl test case on one dut per hwsku
  ansible/templates/minigraph_dpg.j2
  tests/cacl/test_cacl_function.py
  tests/cacl/test_ebtables_application.py
Labels: chassis, Request for 202205 branch

#7628 Fix key Error in tunnel qos test
  tests/qos/test_tunnel_qos_remap.py
  tests/qos/tunnel_qos_remap_base.py
  tests/saitests/py3/sai_base_test.py
Labels: Request for 202205 branch

#7436 Add support for Cisco-8000 400G
  tests/qos/files/qos.yml
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch

#7479 Modified the everflow policer script for Marvell ASIC
  ansible/roles/test/files/acstests/everflow_policer_test.py
  tests/everflow/everflow_test_utilities.py
  tests/everflow/test_everflow_testbed.py
Labels: Request for 202205 branch

#7633 [pr checks] [masic] fix multi_asic PR tests
  .azure-pipelines/pr_test_scripts.yaml
Labels: Request for 202205 branch

#7602 [dualtor_io][active-active] increase `wait_until` timeout for rebooting active-active dualtor DUT
  tests/common/dualtor/control_plane_utils.py
  tests/dualtor_io/test_tor_failure.py
Labels: Request for 202205 branch

#7649 [system_health] Fix test_system_health failed due to change of log format
  tests/system_health/test_system_health.py
Labels: Request for 202205 branch

#7574 Skip po_update test for asic if no portchannel configured
  tests/pc/test_po_update.py
Labels: Request for 202205 branch

#7654 Fix test_voq_intfs
  tests/voq/test_voq_intfs.py
Labels: Request for 202205 branch

#6856 Ignore expected swss, syncd error messages for J2C+ duts during autorestart feature testing
  tests/autorestart/test_container_autorestart.py
Labels: Request for 202205 branch

#7661 Update port_utils for DellEMC-Z9332f-C32
  ansible/module_utils/port_utils.py
Labels: Request for 202012 branch, Request for 202205 branch

#7668 [config_facts] Add port list `member` to `PORTCHANNEL`
  ansible/library/config_facts.py
Labels: Request for 202205 branch

#7669 Fix Cisco-8000 platform file writing
  tests/common/cisco_data.py
Labels: Request for 202012 branch, Request for 202205 branch

#7622 [connection graph] add baud rate config to console_links.csv
  ansible/files/lab_connection_graph.xml
  ansible/files/sonic_lab_console_links.csv
  ansible/library/conn_graph_facts.py
Labels: Request for 202012 branch, Request for 202205 branch

#7614 [dualtor][active-active][test plan] Add testcases to active-active dualtor I/O test plan
  docs/testplan/dual_tor/dual_tor_active_active_test_plan.md
Labels: Request for 202205 branch

#7681 [system_health] Add support for check_system_health_info both old and new format
  tests/system_health/test_system_health.py
Labels: Request for 202205 branch

#7679 [Chassis] Fix QoS Key Error in qos/test_qos_sai.py
  tests/common/fixtures/duthost_utils.py
  tests/conftest.py
Labels: chassis, Request for 202205 branch

#7641 Cisco voq test updates and fixes
  tests/common/cisco_data.py
  tests/conftest.py
  tests/qos/conftest.py
  tests/qos/files/qos.yml
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch

#7566 [DSCP Remapping] Ignore IP flags in the encapsulated packet in dscp remapping test
  tests/qos/tunnel_qos_remap_base.py
Labels: Request for 202205 branch

#7647 [DualTor][Mellanox]Fix dualtor mac move test for Mellanox platforms
  tests/dualtor/test_orchagent_mac_move.py
Labels: Request for 202205 branch

#7701 fix dhcpv6 malformed packet option range
  ansible/roles/test/files/ptftests/py3/dhcpv6_counter_test.py
Labels: Request for 202012 branch, Request for 202205 branch

#7719 keyerror caused by empty interface_to_front_mapping in ptf
  tests/common/fixtures/ptfhost_utils.py
  tests/saitests/py3/sai_base_test.py
Labels: Request for 202205 branch

#7570 Fix for snmp_memory_load testcase for DUTs with lower CPU speed
  tests/snmp/test_snmp_memory.py
Labels: Request for 202205 branch

#7730 [mx][ipfwd] Fix test_dir_bcast failed in mx topo
  tests/ipfwd/test_dir_bcast.py
Labels: Request for 202205 branch

#7673 New T0 LAG topo with 8 uplinks (2 ports per LAG)
  ansible/roles/eos/templates/t0-8-lag-leaf.j2
  ansible/vars/topo_t0-8-lag.yml
Labels: Request for 201911 branch, Request for 202012 branch, Request for 202205 branch

#7712 [Snappi] Modified pfcwd tests to add warm-up traffic
  tests/common/snappi/common_helpers.py
  tests/snappi/pfcwd/files/pfcwd_basic_helper.py
  tests/snappi/pfcwd/files/pfcwd_burst_storm_helper.py
  tests/snappi/pfcwd/files/pfcwd_multi_node_helper.py
  tests/snappi/pfcwd/files/pfcwd_runtime_traffic_helper.py
Labels: Request for 202012 branch, Request for 202205 branch

#6952 [chassis][voq] remove conditional mark for voq tests
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/snmp/test_snmp_lldp.py
  tests/snmp/test_snmp_phy_entity.py
  tests/snmp/test_snmp_queue.py
  tests/voq/test_voq_ipfwd.py
  tests/voq/test_voq_nbr.py
Labels: P0, chassis-voq, Request for 202205 branch

#7660 [chassis] Fix fib & decap test
  tests/common/fixtures/fib_utils.py
Labels: Request for 202205 branch

#7750 [Logical Chassis] Skip checking module status for logical LC that is not part of the logical chassis
  tests/platform_tests/cli/test_show_chassis_module.py
  tests/platform_tests/cli/util.py
Labels: chassis, Request for 202205 branch

#7718 [Snappi] Disable skip PFC watchdog tests for switches with broadcom ASICs
  tests/snappi/pfcwd/files/helper.py
  tests/snappi/pfcwd/test_pfcwd_a2a_with_snappi.py
  tests/snappi/pfcwd/test_pfcwd_basic_with_snappi.py
  tests/snappi/pfcwd/test_pfcwd_m2o_with_snappi.py
Labels: Request for 202012 branch, Request for 202205 branch

#7741 Add skips for unsupported qos tests
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: chassis, Request for 202205 branch

#7511 [log-analyzer] Check both syslog and syslog.1 files when looking for marker
  ansible/roles/test/files/tools/loganalyzer/loganalyzer.py
Labels: Request for 202205 branch

#7760 Use enum_rand_one_per_hwsku_hostname so that it has the correct enum_f…
  tests/platform_tests/test_sequential_restart.py
Labels: chassis, Request for 202205 branch

#7743 [drop_packets]: Skip test_dst_ip_link_local and test_dst_ip_is_loopback
  tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
Labels: chassis-packet, Request for 202205 branch

#7728 restart syncd after copp test
  tests/copp/copp_utils.py
Labels: Request for 202205 branch

#7555 Fix ACLs not being installed on Ethernet ports on single ASIC systems
  tests/acl/test_acl.py
Labels: Request for 202205 branch

#7759 [test plan][standalone tunnel route] remove cases in orchagent test plan
  docs/testplan/dual_tor/dual_tor_orch_test_plan.md
Labels: Request for 202205 branch

#7772 Ignore the status in the output of show ACL table
  tests/generic_config_updater/test_cacl.py
Labels: Request for 202205 branch

#7778 [ansible] Consider tacacs when deploying fanout
  ansible/group_vars/fanout/secrets.yml
  ansible/roles/fanout/tasks/fanout_eos.yml
  ansible/roles/fanout/tasks/fanout_mlnx.yml
  ansible/roles/fanout/tasks/fanout_sonic.yml
  ansible/roles/fanout/tasks/main.yml
Labels: Request for 202012 branch, Request for 202205 branch

#7754 [chassis] fix ip decap and fib failure.
  tests/common/fixtures/ptfhost_utils.py
Labels: chassis, Request for 202205 branch

#7787 [macsec]: Fix inserting none packet
  .flake8
  ansible/roles/test/files/ptftests/macsec.py
  tests/macsec/macsec_helper.py
Labels: Request for 202205 branch

#7766 Fix KeyError: 'members' issue for ecmp inner_hashing cases
  tests/ecmp/inner_hashing/conftest.py
Labels: Request for 202205 branch

#7804 [snmp] Fix test_snmp_memory_load failed
  tests/snmp/test_snmp_memory.py
Labels: Request for 202205 branch

#7788 Fix issue in testPfcStormWithSharedHeadroomOccupancy
  tests/qos/test_qos_sai.py
Labels: Request for 202205 branch

#7797 [chassis] [single-asic] Generate correct minigraph for single-asic card
  ansible/library/port_alias.py
Labels: Request for 202205 branch

#7724 [QoS 202205] remove xfail condition for always pass qos cases
  tests/common/plugins/conditional_mark/tests_mark_conditions_202205.yaml
Labels: Request for 202205 branch

#7708 [reboot] Changed logic in reboot validation to do reboot check using UTC timestamps
  tests/common/devices/sonic.py
  tests/common/reboot.py
Labels: Request for 202205 branch

#7801 [qos 202012] Refresh ARP entry with mac address of PTF port instead of DUT VLAN interface
  tests/saitests/sai_qos_tests.py
Labels: Request for 202012 branch

#7809 [dualtor] create dualtor default tunnel during presetup based on asic type
  tests/common/devices/sonic.py
  tests/common/dualtor/dual_tor_mock.py
Labels: Request for 202205 branch

#7802 Skip test_fwutil on other platforms except Mellanox
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202012 branch, Request for 202205 branch

#7800 [qos master/202205] Refresh ARP entry with mac address of PTF port instead of DUT VLAN interface
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch

#7834 [Test case] Fix test_authorization does not wait long enough before running 'show aaa'
  tests/tacacs/test_authorization.py
Labels: Request for 202012 branch, Request for 202205 branch

#7818 fix empty qos config processing to avoid exception
  tests/common/fixtures/duthost_utils.py
Labels: Request for 202205 branch

#7823 [voq][chassis] Use system port name for BUFFER_QUEUE_TABLE in a voq chassis.
  tests/qos/qos_sai_base.py
Labels: chassis, Request for 202205 branch

#7830 [dualtor] add test utilities for verifying tunnel routes
  tests/common/dualtor/control_plane_utils.py
  tests/dualtor_io/test_normal_op.py
Labels: Request for 202205 branch

#7742 [drop_packet]: Change to run test case without error when loganalyzer is disabled
  tests/drop_packets/drop_packets.py
Labels: chassis, Request for 202205 branch

#7840 Skip IPv6 everflow per interface test on unsupported ASICs
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/everflow/test_everflow_per_interface.py
Labels: Request for 202012 branch, Request for 202205 branch

#7825 [chassis] Fix test_default_route.py for chassis
  tests/route/test_default_route.py
Labels: Request for 202205 branch

#7764 [cacl]: Fix to add eth1-midplane rule for chassis
  tests/cacl/test_cacl_application.py
Labels: chassis, Request for 202205 branch

#7845 [TACACS] Remove unsupported command from TACACS RO user test case.
  tests/tacacs/test_ro_user.py
Labels: Request for 202012 branch, Request for 202205 branch

#7820 [QoS] stop radvd/arp_update service to reduce background traffic during testing
  tests/qos/qos_sai_base.py
Labels: Request for 202012 branch, Request for 202205 branch

#7807 [tunnel qos remap] download syncd rpc image from public_docker_registry
  tests/qos/tunnel_qos_remap_base.py
Labels: Request for 202012 branch, Request for 202205 branch

#7828 Add a test case to check /etc/resolv.conf
  .azure-pipelines/pr_test_scripts.yaml
  tests/common/constants.py
  tests/dns/test_dns_resolv_conf.py
  tests/kvmtest.sh
Labels: Request for 202205 branch

#7873 Fix `test_custom_acl_table` on dualtor testbed
  tests/acl/custom_acl_table/test_custom_acl_table.py
Labels: Request for 202205 branch

#7870 ignore error for update service
  tests/qos/qos_sai_base.py
Labels: Request for 202012 branch, Request for 202205 branch

#7871 fix show counter issue
  tests/saitests/sai_qos_tests.py
Labels: Request for 202012 branch

#7862 Use dynamic outer dscp for test_tor_ecn
  tests/dualtor/test_tor_ecn.py
Labels: Request for 202012 branch, Request for 202205 branch

#7879 Skipping test_drop_counters.py::test_dst_ip_absent for cisco platform
  tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
Labels: Request for 202205 branch

#7784 Skip warm-reboot cases for T2.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: chassis, Request for 202205 branch

#7898 fix test static route unstable issue
  tests/route/test_static_route.py
Labels: Request for 202012 branch, Request for 202205 branch

#7564 [CRM]Fix the failure of crm route test caused by fdb learning during the test
  tests/crm/test_crm.py
Labels: Request for 202205 branch

#7923 Fix a bug in script `test_fdb_mac_move.py`.
  tests/fdb/test_fdb_mac_move.py
Labels: Request for 202012 branch, Request for 202205 branch

#7715 skipping unknown mac test for cisco 8k
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: chassis-packet, Request for 202205 branch

#7889 Added Cisco qos param generator
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/files/qos.yml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: Request for 202205 branch

#7910 [snmp]: Use pgrep to kill memory hog process
  tests/snmp/test_snmp_memory.py
Labels: Request for 201911 branch, Request for 202012 branch, Request for 202205 branch
