Repository sonic-net/sonic-mgmt, pull requests merged in 2023-07, with the labels that each got.

#8737 use `enum_rand_one_per_hwsku_frontend_hostname` for CRM collector module fixture
  tests/crm/conftest.py
Labels: Request for 202205 branch

#8790 Updated Cisco T2 SKU Name
  ansible/module_utils/port_utils.py
Labels: Request for 202205 branch

#8787 Fix false alert for pmon services check in sanity check
  tests/common/devices/sonic.py
Labels: Request for 202012 branch, Request for 202205 branch

#8761 [Dual-Tor][Active-Active] Add semicolons back to the proto files
  ansible/dualtor/nic_simulator/nic_simulator_grpc_mgmt_service.proto
  ansible/dualtor/nic_simulator/nic_simulator_grpc_service.proto
Labels: Request for 202205 branch

#8793 fixes to run macsec on t2 testbed with ceos as macsec neigbor
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/macsec/__init__.py
Labels: Request for 202205 branch

#8729 Skip broadcast test for dual TOR
  tests/vlan/test_vlan.py
Labels: Request for 202205 branch

#8803 [dualtor] Add mux direction checks to toggle fixtures
  tests/common/dualtor/mux_simulator_control.py
Labels: Request for 202205 branch

#8739 ACL test fix for 8111
  tests/acl/test_acl.py
Labels: Request for 202205 branch

#8800 [Snappi] Config reload to stabilize DUT after container restart
  tests/snappi/pfcwd/test_pfcwd_basic_with_snappi.py
Labels: Request for 202012 branch, Request for 202205 branch

#8615 [Chassis] Test cases to validate TSA/B from supervisor on T2
  tests/bgp/test_traffic_shift.py
  tests/bgp/test_traffic_shift_sup.py
Labels: Request for 202205 branch

#8808 improve dhcpv6 test packets to cover option parse cases
  ansible/roles/test/files/ptftests/py3/dhcpv6_relay_test.py
Labels: Request for 202012 branch, Request for 202205 branch

#8829 [action] [PR:8729] Skip broadcast test for dual TOR
  tests/vlan/test_vlan.py
Labels: automerge

#8779 [chassis] update the T3 device type in the minigraph
  ansible/templates/minigraph_png.j2
Labels: chassis-voq, Request for 202205 branch

#8825 [MASIC] [chassis] change internal interfaces keywords to lowercase search in sanity check
  tests/common/plugins/sanity_check/recover.py
Labels: Request for 202205 branch

#8833 Remove xfail condition mark for test_system_health
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202012 branch, Request for 202205 branch

#8836 [m0][gcu] Fix log analyzer error in gcu/test_vlan_interface
  tests/generic_config_updater/test_vlan_interface.py
Labels: Request for 202205 branch

#8845 Change reload source in module `autorestart/test_container_autorestart.py`.
  tests/autorestart/test_container_autorestart.py
Labels: Request for 202012 branch, Request for 202205 branch

#8852 [action] [PR:8845] Change reload source in module `autorestart/test_container_autorestart.py`.
  tests/autorestart/test_container_autorestart.py
Labels: automerge

#8851 [action] [PR:8845] Change reload source in module `autorestart/test_container_autorestart.py`.
  tests/autorestart/test_container_autorestart.py
Labels: automerge

#8850 [action] [PR:8784] Remove key `WARM_RESTART` after module `bgp/test_bgp_slb.py` running.
  tests/bgp/templates/del_warm_restart_config.json
  tests/bgp/test_bgp_slb.py
Labels: automerge

#8849 [action] [PR:8784] Remove key `WARM_RESTART` after module `bgp/test_bgp_slb.py` running.
  tests/bgp/templates/del_warm_restart_config.json
  tests/bgp/test_bgp_slb.py
Labels: automerge

#8848 [action] [PR:8762] Remove key `ACL_TABLE_TYPE` in running config after module `acl/test_stress_acl.py` running.
  tests/acl/templates/del_acltb_test_stress_acl_table.j2
  tests/acl/test_stress_acl.py
Labels: automerge

#8847 [action] [PR:8762] Remove key `ACL_TABLE_TYPE` in running config after module `acl/test_stress_acl.py` running.
  tests/acl/templates/del_acltb_test_stress_acl_table.j2
  tests/acl/test_stress_acl.py
Labels: automerge

#8846 [action] [PR:8744] Add a function to compare running config.
  tests/conftest.py
Labels: automerge

#8854 [action] [PR:8781] Disable service warm_restart after test_service_warm_restart running
  tests/platform_tests/test_service_warm_restart.py
Labels: automerge

#8855 Enable `icmp_responder` on session level for `dualtor` topology
  tests/common/fixtures/ptfhost_utils.py
Labels: Request for 202205 branch

#8842 Vxlan ECMP test failure in python3 env.
  tests/vxlan/vxlan_ecmp_utils.py
Labels: Request for 202012 branch, Request for 202205 branch

#8861 increase ptf timeout for tunnel_qos_remap
  tests/qos/tunnel_qos_remap_base.py
Labels: Request for 202205 branch

#8875 [action] [PR:8855] Enable `icmp_responder` on session level for `dualtor` topology
  tests/common/fixtures/ptfhost_utils.py
Labels: automerge

#8873 [action] [PR:8836] [m0][gcu] Fix log analyzer error in gcu/test_vlan_interface
  tests/generic_config_updater/test_vlan_interface.py
Labels: automerge

#8872 [action] [PR:8825] [MASIC] [chassis] change internal interfaces keywords to lowercase search in sanity check
  tests/common/plugins/sanity_check/recover.py
Labels: automerge

#8871 [action] [PR:8793] fixes to run macsec on t2 testbed with ceos as macsec neigbor
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/macsec/__init__.py
Labels: automerge

#8870 [action] [PR:8787] Fix false alert for pmon services check in sanity check
  tests/common/devices/sonic.py
Labels: automerge

#8869 [action] [PR:8787] Fix false alert for pmon services check in sanity check
  tests/common/devices/sonic.py
Labels: automerge

#8868 [action] [PR:8779] [chassis] update the T3 device type in the minigraph
  ansible/templates/minigraph_png.j2
Labels: automerge

#8867 [action] [PR:8739] ACL test fix for 8111
  tests/acl/test_acl.py
Labels: automerge

#8866 [action] [PR:8737] use `enum_rand_one_per_hwsku_frontend_hostname` for CRM collector module fixture
  tests/crm/conftest.py
Labels: automerge

#8865 [action] [PR:8615] [Chassis] Test cases to validate TSA/B from supervisor on T2
  tests/bgp/test_traffic_shift.py
  tests/bgp/test_traffic_shift_sup.py
Labels: automerge

#8864 [action] [PR:8582] Added a conditional skip by bug to vnet_vxlan test
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#8863 [action] [PR:8582] Added a conditional skip by bug to vnet_vxlan test
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#8881 [action] [PR:8842] Vxlan ECMP test failure in python3 env.
  tests/vxlan/vxlan_ecmp_utils.py
Labels: automerge

#8874 [action] [PR:8842] Vxlan ECMP test failure in python3 env.
  tests/vxlan/vxlan_ecmp_utils.py
Labels: automerge

#8805 [202205][m0][route] Add support for m0-2vlan in test_route_perf
  tests/route/test_route_perf.py
Labels: Request for 202205 branch

#8884 Set key "asic0" in single-asic scenerio to keep consistent with multi-asic in function `core_dump_and_config_check`.
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch

#8885 [action] [PR:8884] Set key "asic0" in single-asic scenerio to keep consistent with multi-asic in function `core_dump_and_config_check`.
  tests/conftest.py
Labels: automerge

#8862 fix test_tunnel_decap_dscp_to_pg_mapping failure caused by unknonw asic name
  tests/common/devices/sonic.py
  tests/qos/test_tunnel_qos_remap.py
Labels: Request for 202205 branch

#8791 Vxlan ecmp primary/secondary switchover tests.
  tests/vxlan/test_vxlan_ecmp.py
  tests/vxlan/vxlan_ecmp_utils.py
Labels: Request for 202205 branch

#8903 Fix `os.mkdir` failure in test_ro_disk
  tests/tacacs/test_ro_disk.py
Labels: Request for 202012 branch, Request for 202205 branch

#8898 Qos RPC Tunnel remove fix
  tests/common/devices/sonic.py
Labels: Request for 202205 branch

#8915 Use common function to recover configuration after tests.
  tests/bgp/templates/del_bgp_bbr_config.json
  tests/bgp/templates/del_warm_restart_config.json
  tests/bgp/test_bgp_bbr.py
  tests/bgp/test_bgp_slb.py
  tests/common/utilities.py
  tests/show_techsupport/templates/del_keys.json
  tests/show_techsupport/test_techsupport_no_secret.py
  tests/tacacs/templates/del_tacacs_config.json
  tests/tacacs/utils.py
  tests/vlan/test_host_vlan.py
Labels: Request for 202012 branch, Request for 202205 branch

#8807 Modified the test script to fix the issue because of PR: 7816
  tests/crm/test_crm.py
Labels: Request for 202205 branch

#8908 Reg: test_route_flap_voq_chassis_update
  tests/common/devices/multi_asic.py
  tests/route/test_route_flap.py
Labels: Request for 202205 branch

#8688 Fix missing namespace option in interface restart code
  tests/platform_tests/conftest.py
Labels: Request for 202205 branch

#8844 Add output all and drop all HTTP API in mux simulator in dualtor_io testcase
  ansible/roles/vm_set/files/mux_simulator.md
  ansible/roles/vm_set/files/mux_simulator.py
  tests/common/dualtor/mux_simulator_control.py
  tests/dualtor_io/test_link_drop.py
Labels: Request for 202205 branch

#8954 [action] [PR:8903] Fix `os.mkdir` failure in test_ro_disk
  tests/tacacs/test_ro_disk.py
Labels: automerge

#8951 [action] [PR:8823] Get peer fanout from the first interface on the dut connected to the …
  tests/drop_packets/drop_packets.py
Labels: automerge

#8950 [action] [PR:8822] [sonic-mgmt/route/test_route_flap.py] Skip over routes for the IB interface when selecting the route to ping.
  tests/route/test_route_flap.py
Labels: automerge

#8949 [action] [PR:8807] Modified the test script to fix the issue because of PR: 7816
  tests/crm/test_crm.py
Labels: automerge

#8948 [action] [PR:8714] [Dual-Tor][Nvidia] Update the mocked tunnel configuration for Nvidia platforms
  tests/common/dualtor/dual_tor_mock.py
Labels: automerge

#8947 [action] [PR:8688] Fix missing namespace option in interface restart code
  tests/platform_tests/conftest.py
Labels: automerge

#8955 [action] [PR:8903] Fix `os.mkdir` failure in test_ro_disk
  tests/tacacs/test_ro_disk.py
Labels: automerge

#8953 [action] [PR:8901] Delete interfaces admin_state after module `vlan/test_autostate_disabled.py` running.
  tests/common/utilities.py
  tests/vlan/test_autostate_disabled.py
Labels: automerge

#8952 [action] [PR:8862] fix test_tunnel_decap_dscp_to_pg_mapping failure caused by unknonw asic name
  tests/common/devices/sonic.py
  tests/qos/test_tunnel_qos_remap.py
Labels: automerge

#8960 [fib] Fix test_fib failed in Nokia 7215
  tests/fib/test_fib.py
Labels: Request for 202012 branch, Request for 202205 branch

#8968 [autorestart][mx] Fix test_container_autorestart failed in mx
  tests/autorestart/test_container_autorestart.py
Labels: Request for 202205 branch

#8938 [plt_reboot_dict] auto use fixture set_max_for_interfaces in reboot tests
  tests/platform_tests/test_power_off_reboot.py
  tests/platform_tests/test_reboot.py
Labels: Request for 202205 branch

#8922 Add config reload at the end of TC `test_masked_services`
  tests/minigraph/test_masked_services.py
Labels: Request for 202012 branch, Request for 202205 branch

#8971 [202205 cherry pick] test_route_flap for voq_chassis
  tests/common/devices/multi_asic.py
  tests/route/test_route_flap.py
Labels: chassis

#8931 Add param timeout to ansible library shell_cmds
  ansible/library/shell_cmds.py
  docs/api_wiki/ansible_methods/shell_cmds.md
  tests/common/devices/sonic.py
Labels: Request for 202205 branch

#8446 [copp tables] validate copp tables during in/cross-branch upgrades
  tests/upgrade_path/test_upgrade_path.py
  tests/upgrade_path/upgrade_helpers.py
Labels: Request for 202205 branch

#8907 increase tolerance for TunnelDscpToPgMapping test
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch

#8909 [dualtor] Leave `icmp_responder` running on `dualtor` topology
  tests/common/fixtures/ptfhost_utils.py
Labels: Request for 202205 branch

#9017 [chassis] [multi-asic] skip override_config_table test for multi-asic platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch

#9020 [acl][m0] Fix test_acl failed in m0-2vlan
  tests/acl/templates/acltb_test_rules.j2
  tests/acl/templates/acltb_test_rules_part_2.j2
  tests/acl/test_acl.py
Labels: Request for 202205 branch

#9025 Fit dualtor scenario when deleting config `VLAN|mac` in module `vlan/test_host_vlan.py`
  tests/vlan/test_host_vlan.py
Labels: Request for 202012 branch, Request for 202205 branch

#9002 Fib IP range length is function instead of attribute
  ansible/roles/test/files/ptftests/IP_decap_test.py
Labels: Request for 202012 branch, Request for 202205 branch

#9042 [action] [PR:6887] stress test for restapi read/write for overlay ecmp routes.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/restapi/conftest.py
  tests/restapi/restapi_operations.py
  tests/restapi/test_restapi_vxlan_ecmp.py
Labels: automerge

#9016 Stabilize auto techsupport test
  tests/show_techsupport/test_auto_techsupport.py
Labels: Request for 202205 branch

#9070 [action] [PR:9017] [chassis] [multi-asic] skip override_config_table test for multi-asic platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#9068 [action] [PR:9002] Fib IP range length is function instead of attribute
  ansible/roles/test/files/ptftests/IP_decap_test.py
Labels: automerge

#9066 [action] [PR:8960] [fib] Fix test_fib failed in Nokia 7215
  tests/fib/test_fib.py
Labels: automerge

#9065 [action] [PR:8938] [plt_reboot_dict] auto use fixture set_max_for_interfaces in reboot tests
  tests/platform_tests/test_power_off_reboot.py
  tests/platform_tests/test_reboot.py
Labels: automerge

#9063 [action] [PR:8907] increase tolerance for TunnelDscpToPgMapping test
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#9062 [action] [PR:8488] [pfcwd][gcu] Add GCU testcases for pfcwd enable/disable scenario
  tests/generic_config_updater/test_pfcwd_status.py
Labels: automerge

#9061 [action] [PR:8018] Fix session flaps
  tests/bgp/test_bgp_session_flap.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#9071 [action] [PR:9020] [acl][m0] Fix test_acl failed in m0-2vlan
  tests/acl/templates/acltb_test_rules.j2
  tests/acl/templates/acltb_test_rules_part_2.j2
  tests/acl/test_acl.py
Labels: automerge

#9077 [action] [PR:9002] Fib IP range length is function instead of attribute
  ansible/roles/test/files/ptftests/IP_decap_test.py
Labels: automerge

#9069 [action] [PR:9016] Stabilize auto techsupport test
  tests/show_techsupport/test_auto_techsupport.py
Labels: automerge

#9076 [action] [PR:6887] stress test for restapi read/write for overlay ecmp routes.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/restapi/conftest.py
  tests/restapi/restapi_operations.py
  tests/restapi/test_restapi_vxlan_ecmp.py
Labels: automerge

#9085 [platform][reboot] Fix test_power_off_reboot failed in 7215
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202205 branch

#9080 Modify testbed-cli.sh related vm_topology.py to be compatible with both Python2/3
  ansible/roles/vm_set/library/vm_topology.py
Labels: Request for 202012 branch, Request for 202205 branch

#9074 Stabilize snmp memory load test
  tests/snmp/memory.py
  tests/snmp/test_snmp_memory.py
Labels: Request for 202012 branch, Request for 202205 branch

#9037 Increase wait time for restapi service startup
  tests/restapi/helper.py
Labels: Request for 202012 branch, Request for 202205 branch

#8993 [advanced-reboot] Enhance IO: start traffic when teamd goes down and run until FINALIZER is active
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: Request for 202012 branch, Request for 202205 branch

#8617 Fix issue 8497: PTF test collected a huge number of unexpected pkt when test failed
  tests/macsec/macsec_helper.py
Labels: Request for 202205 branch

#8733 Call duthost_console fixture for test_escape_character test case
  tests/dut_console/test_escape_character.py
Labels: Request for 202205 branch

#9067 [chassis] [test_platform_info.py] accommodate PSU 'NOT PRESENT' case
  tests/platform_tests/test_platform_info.py
Labels: chassis, Request for 202205 branch

#9089 Update `icmp_responder` to only respond only linkmgrd requests
  tests/scripts/icmp_responder.py
Labels: Request for 202205 branch

#9023 Fix to use non RegionalHub T3 peers when selecting port.
  tests/voq/test_voq_ipfwd.py
Labels: Request for 202205 branch

#8859 Fix/optimize PFC WD test-case for multi-asic/chassis systems.
  tests/pfcwd/conftest.py
  tests/pfcwd/test_pfcwd_function.py
Labels: Request for 202205 branch

#8856 [chassis] add check on every linecard as well after every reboot on chassis sup
  tests/platform_tests/test_reboot.py
Labels: chassis, Request for 202205 branch

#8919 VSNet Virtual Sonic Helper
  spytest/vsnet/autorun.sh
  spytest/vsnet/requirements.sh
  spytest/vsnet/sonic_import_img.sh
  spytest/vsnet/test.sh
  spytest/vsnet/vsnet
Labels: Spytest

#8926 bundle datatable libraries used in spytest reports
  spytest/utilities/web/datatables.min.css
  spytest/utilities/web/datatables.min.js
Labels: Spytest

#9006 fix tests/bgp/test_traffic_shift_sup.py failure
  tests/bgp/test_traffic_shift_sup.py
Labels: Request for 202205 branch

#8149 Enhance qos tests to support single-asic, multi-asic, and multi-dut testing
  tests/common/devices/sonic.py
  tests/common/devices/sonic_asic.py
  tests/common/fixtures/duthost_utils.py
  tests/common/fixtures/ptfhost_utils.py
  tests/conftest.py
  tests/qos/files/mellanox/qos_param_generator.py
  tests/qos/qos_helpers.py
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/qos/test_tunnel_qos_remap.py
  tests/qos/tunnel_qos_remap_base.py
  tests/saitests/py3/sai_base_test.py
  tests/saitests/py3/sai_qos_tests.py
  tests/saitests/py3/switch.py
  tests/test_pretest.py
Labels: chassis

#9117 [dualtor] Disable running `icmp_responder` at session-level
  tests/common/fixtures/ptfhost_utils.py
Labels: Request for 202205 branch

#9120 [action] [PR:9117] [dualtor] Disable running `icmp_responder` at session-level
  tests/common/fixtures/ptfhost_utils.py
Labels: automerge

#8824 [IPv6][SNMP]: Remove skip of IPv6 loopback testing
  tests/common/helpers/snmp_helpers.py
  tests/snmp/test_snmp_loopback.py
Labels: Request for 202205 branch

#9121 enable bfd test for 8101
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch

#9123 Recover docker's available mem threshold after module `show_techsupport/test_auto_techsupport.py` running.
  tests/show_techsupport/test_auto_techsupport.py
Labels: Request for 202205 branch

#9130 x86_64-8101_32fh_o-r0 only support bfd_multihop
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch

#9142 [action] [PR:9123] Recover docker's available mem threshold after module `show_techsupport/test_auto_techsupport.py` running.
  tests/show_techsupport/test_auto_techsupport.py
Labels: automerge

#9139 [action] [PR:9037] Increase wait time for restapi service startup
  tests/restapi/helper.py
Labels: automerge

#9138 [action] [PR:9023] Fix to use non RegionalHub T3 peers when selecting port.
  tests/voq/test_voq_ipfwd.py
Labels: automerge

#9137 [action] [PR:9006] fix tests/bgp/test_traffic_shift_sup.py failure
  tests/bgp/test_traffic_shift_sup.py
Labels: automerge

#9136 [action] [PR:8699] [sonic-mgmt/qos] Fixed initialization of qosConfig to address KeyError seen
  tests/qos/test_qos_sai.py
Labels: automerge

#9135 [action] [PR:8617] Fix issue 8497: PTF test collected a huge number of unexpected pkt when test failed
  tests/macsec/macsec_helper.py
Labels: automerge

#9134 [action] [PR:8576] Check if BGP has Loopback0 IP as its router ID
  tests/common/fixtures/advanced_reboot.py
  tests/common/fixtures/duthost_utils.py
  tests/common/plugins/sanity_check/checks.py
Labels: automerge

#9133 [action] [PR:8508] skip active forwarding check on cisco platforms
  tests/dualtor/test_orchagent_mac_move.py
Labels: automerge

#9132 [action] [PR:8418] Improvements to vSONiC deployment
  ansible/roles/sonic/tasks/vsonic.yml
  ansible/roles/sonic/templates/configdb-t0-64-32-leaf.j2
  ansible/roles/sonic/templates/configdb-t2-core.j2
  ansible/roles/sonic/templates/configdb-t2-leaf.j2
  ansible/roles/sonic/templates/configdb.j2
Labels: automerge

#9144 [202012，CI/CD] Use remote PR test template from sonic-mgmt master to run PR test
  azure-pipelines.yml
Labels: Created PR to 202012 branch

#9143 [202205, CI/CD] Use remote PR test template from sonic-mgmt master to run PR test
  azure-pipelines.yml
Labels: Created PR to 202205 branch

#9150 Restart container no matter if restore monit config files is success in module `memory_checker/test_memory_checker.py`.
  tests/memory_checker/test_memory_checker.py
Labels: Request for 202012 branch, Request for 202205 branch

#9148 [action] [PR:8917] Re-organize files under `ansible/devutil` to have better structure for future enhancements
  .azure-pipelines/upgrade_image.py
  ansible/devutil/devices/__init__.py
  ansible/devutil/devices/ansible_hosts.py
  ansible/devutil/devices/factory.py
  ansible/devutil/devices/sonic.py
  ansible/upgrade_sonic.py
Labels: automerge

#9147 [action] [PR:8917] Re-organize files under `ansible/devutil` to have better structure for future enhancements
  .azure-pipelines/upgrade_image.py
  ansible/devutil/devices/__init__.py
  ansible/devutil/devices/ansible_hosts.py
  ansible/devutil/devices/factory.py
  ansible/devutil/devices/sonic.py
  ansible/upgrade_sonic.py
Labels: automerge

#9141 [action] [PR:9121] enable bfd test for 8101
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#8927 update the utilities used in spytest
  .pre-commit-config.yaml
  spytest/utilities/common.py
  spytest/utilities/ctrl_chars.py
  spytest/utilities/excel.py
  spytest/utilities/exceptions.py
  spytest/utilities/inet.py
  spytest/utilities/json_helpers.py
  spytest/utilities/parallel.py
  spytest/utilities/rest.py
  spytest/utilities/services.py
  spytest/utilities/tracer.py
  spytest/utilities/utils.py
Labels: Spytest

#9128 [voq] refine eos fanout function to check fanout link oper status
  tests/common/devices/eos.py
Labels: Request for 202205 branch

#9167 [action] [PR:9130] x86_64-8101_32fh_o-r0 only support bfd_multihop
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#9165 [action] [PR:9046] Skip unsupported testcases on M0/Mx topology
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: automerge

#9164 [action] [PR:9040] Support init localhost ansible host object without supplying inventory
  ansible/devutil/devices/ansible_hosts.py
  ansible/devutil/devices/factory.py
Labels: automerge

#9163 [action] [PR:8801] [voq][neighbors_clear_one] Ignore nbr-state check for other neighbors
  tests/voq/test_voq_nbr.py
Labels: automerge

#9166 [action] [PR:9128] [voq] refine eos fanout function to check fanout link oper status
  tests/common/devices/eos.py
Labels: automerge

#9149 [202205][platform][reboot] Fix test_power_off_reboot failed in 7215 (#9085)
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202205 branch

#9140 [action] [PR:9067] [chassis] [test_platform_info.py] accommodate PSU 'NOT PRESENT' case
  tests/platform_tests/test_platform_info.py
Labels: automerge

#9102 [platform_tests] add test to make sure cpuidle is off for m0 and mx
  tests/platform_tests/test_idle_driver.py
Labels: Request for 202012 branch, Request for 202205 branch

#9168 Recover telemetry settings when error happens in module `telemetry/test_telemetry.py`.
  tests/telemetry/test_telemetry.py
Labels: Request for 202205 branch

#9179 [action] [PR:9040] Support init localhost ansible host object without supplying inventory
  ansible/devutil/devices/ansible_hosts.py
  ansible/devutil/devices/factory.py
Labels: automerge

#9190 [action] [PR:9150] Restart container no matter if restore monit config files is success in module `memory_checker/test_memory_checker.py`.
  tests/memory_checker/test_memory_checker.py
Labels: automerge

#9188 [action] [PR:9037] Increase wait time for restapi service startup
  tests/restapi/helper.py
Labels: automerge

#9187 [action] [PR:9170] [acl][fanout] Optimize skip condition for SONiC fanout in test_acl_outer_vlan
  tests/acl/test_acl_outer_vlan.py
Labels: automerge

#9189 [action] [PR:9102] [platform_tests] add test to make sure cpuidle is off for m0 and mx
  tests/platform_tests/test_idle_driver.py
Labels: automerge

#9186 [action] [PR:9102] [platform_tests] add test to make sure cpuidle is off for m0 and mx
  tests/platform_tests/test_idle_driver.py
Labels: automerge

#9175 [testfix] test_vxlan_ecmp cleanup of routes after test runs.
  tests/vxlan/test_vxlan_ecmp.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch
