Repository sonic-net/sonic-mgmt, pull requests merged in 2023-09, with the labels that each got.

#9796 [action] [PR:9781] [Snappi] PFCWD runtime traffic bug fix
  tests/snappi_tests/pfcwd/files/pfcwd_runtime_traffic_helper.py
Labels: automerge

#9795 [action] [PR:9781] [Snappi] PFCWD runtime traffic bug fix
  tests/snappi_tests/pfcwd/files/pfcwd_runtime_traffic_helper.py
Labels: automerge

#9797 update port utils for cisco 8000
  ansible/module_utils/port_utils.py
Labels: Request for 202205 branch, Request for 202305 branch

#9793 Skip test_dir_bcast test on t0-backend
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9803 [action] [PR:9659] [Snappi] Validate PFC frame bug fix
  tests/common/snappi_tests/common_helpers.py
  tests/common/snappi_tests/pfc_packet.py
  tests/common/snappi_tests/read_pcap.py
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/pfc/files/helper.py
Labels: automerge

#9802 [action] [PR:9659] [Snappi] Validate PFC frame bug fix
  tests/common/snappi_tests/common_helpers.py
  tests/common/snappi_tests/pfc_packet.py
  tests/common/snappi_tests/read_pcap.py
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/pfc/files/helper.py
Labels: automerge

#9550 [PTF python3 migration] Modify test_advanced_reboot PTF script
  ansible/roles/test/files/ptftests/arista.py
  ansible/roles/test/files/ptftests/py3/advanced-reboot.py
  ansible/roles/test/files/ptftests/py3/arista.py
  ansible/roles/test/files/ptftests/py3/host_device.py
  ansible/roles/test/files/ptftests/py3/sad_path.py
  ansible/roles/test/files/ptftests/sonic.py
  tests/common/fixtures/advanced_reboot.py
Labels: Request for 202305 branch

#7796 [DPU, CRM] Added testplan for SONiC DASH CRM tests
  docs/testplan/dash/DASH-crm-test-plan.md
Labels: Test Plan

#9820 [conditional mark] Xfail techsupport for 202305
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch

#9821 Skip checking expected core dump in module `bgp/test_traffic_shift.py`.
  tests/bgp/test_traffic_shift.py
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9818 Ignore 'Failed to get port by bridge port ID' in test_vlan.py
  tests/vlan/test_vlan.py
Labels: Request for 202012 branch, Request for 202205 branch, Approved for 202012 branch, Approved for 202205 branch, Request for 202305 branch, Approved for 202305 branch

#9831 [action] [PR:9818] Ignore 'Failed to get port by bridge port ID' in test_vlan.py
  tests/vlan/test_vlan.py
Labels: automerge

#9799 [platform_tests] fix getting current idle driver error
  tests/platform_tests/test_idle_driver.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9833 [action] [PR:9818] Ignore 'Failed to get port by bridge port ID' in test_vlan.py
  tests/vlan/test_vlan.py
Labels: automerge

#9832 [action] [PR:9818] Ignore 'Failed to get port by bridge port ID' in test_vlan.py
  tests/vlan/test_vlan.py
Labels: automerge

#9830 [action] [PR:9826] [show techsupport] Added fix for show_test_techsupport
  tests/show_techsupport/test_techsupport.py
Labels: automerge

#9809 Add portstat to debug FDB packet delay
  tests/fdb/test_fdb.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9840 Specific field CustomMsg to distinguish config reload or core dump.
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch, Approved for 202012 branch, Approved for 202205 branch, Request for 202305 branch, Approved for 202305 branch

#9854 [dualtor-aa] Add `dualtor-aa-64` topology
  ansible/vars/topo_dualtor-aa-64.yml
  ansible/veos_vtb
Labels: Request for 202205 branch, Request for 202305 branch

#9852 [action] [PR:9840] Specific field CustomMsg to distinguish config reload or core dump.
  tests/conftest.py
Labels: automerge

#9851 [action] [PR:9840] Specific field CustomMsg to distinguish config reload or core dump.
  tests/conftest.py
Labels: automerge

#9850 [action] [PR:9840] Specific field CustomMsg to distinguish config reload or core dump.
  tests/conftest.py
Labels: automerge

#9858 [action] [PR:9854] [dualtor-aa] Add `dualtor-aa-64` topology
  ansible/vars/topo_dualtor-aa-64.yml
  ansible/veos_vtb
Labels: automerge

#9824 Fix issue: fix typo and remove unused sensor for 4600C
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Request for 202205 branch, Request for 202305 branch

#8906 [dualtor] fixing test_downstream_ecmp_nexthops
  tests/common/dualtor/dual_tor_utils.py
  tests/dualtor/test_orchagent_active_tor_downstream.py
Labels: Request for 202012 branch, Request for 202205 branch

#9905 [action] [PR:9654] [platform][s6100] increase timeout in wait_for to 10 seconds to invoke platform API server
  tests/platform_tests/api/conftest.py
Labels: automerge

#9910 Fix bgp suppress fib test
  tests/bgp/test_bgp_suppress_fib.py
Labels: Request for 202305 branch

#9860 cisco: Update qos.yaml params for GB topo-t2.
  tests/qos/files/qos_params.gb.yaml
Labels: Request for 202205 branch

#9922 [dualtor] update skip logic of test_wr_arp for dualtor
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch, Request for 202305 branch

#9926 [action] [PR:9922] [dualtor] update skip logic of test_wr_arp for dualtor
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#9925 [action] [PR:9922] [dualtor] update skip logic of test_wr_arp for dualtor
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#9872 [action] [PR:9845] Add the PTF neighbor into the DEVICE_NEIGHBOR_METADATA table
  ansible/roles/sonic/templates/configdb.j2
Labels: automerge

#9828 Add GNMI Support and imrovements
  spytest/apis/switching/mac.py
Labels: Spytest

#9557 Apis routing arp
  spytest/apis/routing/arp.py
  spytest/apis/routing/ip_bgp.py
  spytest/apis/routing/ip_rest.py
  spytest/apis/routing/route_map.py
Labels: Spytest

#9935 [action] [PR:9910] Fix bgp suppress fib test
  tests/bgp/test_bgp_suppress_fib.py
Labels: automerge

#9877 [Testbed] Fix the MAC address of br1 on server during add/remove topo
  ansible/roles/vm_set/tasks/main.yml
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9927 Fix testcase failure for test_check_sfp_using_ethtool
  tests/platform_tests/mellanox/test_check_sfp_using_ethtool.py
Labels: Bug :bug:, Request for 202305 branch

#9778 Updated qos params for gb 400000_120000m
  tests/qos/files/qos_params.gb.yaml
Labels: Request for 202205 branch

#9946 [action] [PR:9793] Skip test_dir_bcast test on t0-backend
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#9945 [action] [PR:9793] Skip test_dir_bcast test on t0-backend
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#9941 [action] [PR:9842] Fix dual-tor dhcpv6 relay test cases failure in latest image
  ansible/roles/test/files/ptftests/py3/dhcpv6_counter_test.py
  ansible/roles/test/files/ptftests/py3/dhcpv6_relay_test.py
  tests/dhcp_relay/test_dhcpv6_relay.py
Labels: automerge

#9951 [action] [PR:9940] [PR test issue]Fix br1 mac issue
  ansible/setup-management-network.sh
Labels: automerge

#9949 [action] [PR:9940] [PR test issue]Fix br1 mac issue
  ansible/setup-management-network.sh
Labels: automerge

#9956 [action] [PR:9947] [Feat]Support to remove existed br1 by parameter
  ansible/setup-management-network.sh
Labels: automerge

#9955 [action] [PR:9947] [Feat]Support to remove existed br1 by parameter
  ansible/setup-management-network.sh
Labels: automerge

#9954 [action] [PR:9947] [Feat]Support to remove existed br1 by parameter
  ansible/setup-management-network.sh
Labels: automerge

#9942 Add is_host_service_running for sonic device
  tests/common/devices/sonic.py
Labels: Request for 202305 branch

#9855 [configlet] Remove transciver check
  tests/configlet/util/common.py
Labels: Request for 202305 branch

#9774 [GCU] Add GCU testcase for PG headroom modification
  tests/generic_config_updater/test_pg_headroom_update.py
Labels: Request for 202305 branch

#9952 To xfail pfcwd_warm_reboot on 7050cx3 in 202305
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch

#9979 [action] [PR:9799] [platform_tests] fix getting current idle driver error
  tests/platform_tests/test_idle_driver.py
Labels: automerge

#9978 [action] [PR:9799] [platform_tests] fix getting current idle driver error
  tests/platform_tests/test_idle_driver.py
Labels: automerge

#9976 [action] [PR:9952] To xfail pfcwd_warm_reboot on 7050cx3 in 202305
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#9980 [dualtor-io] Change the health expectation for bgp shutdown case
  tests/dualtor_io/test_tor_bgp_failure.py
Labels: Request for 202205 branch, Request for 202305 branch

#9571 remove stale code
  spytest/apis/common/asic.py
  spytest/reporting/tcmap.csv
  spytest/tests/routing/test_l3_scale_ecmp_paths.py
Labels: Spytest

#9957 Fix acl outer vlan test
  ansible/roles/test/files/helpers/arp_responder.py
  tests/acl/test_acl_outer_vlan.py
Labels: Request for 202305 branch

#9805 Stabilize counterpoll watermark test
  tests/platform_tests/counterpoll/test_counterpoll_watermark.py
Labels: Request for 202305 branch

#9992 [action] [PR:9009] Ignore pmon error for getting sensor data
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#9953 [Python3 migration] Migrate test_advanced_reboot's PTF script advanced-reboot.py to Python3
  ansible/roles/test/files/ptftests/arista.py
  ansible/roles/test/files/ptftests/py3/advanced-reboot.py
  ansible/roles/test/files/ptftests/py3/arista.py
  ansible/roles/test/files/ptftests/py3/host_device.py
  ansible/roles/test/files/ptftests/py3/sad_path.py
  ansible/roles/test/files/ptftests/sonic.py
  tests/common/fixtures/advanced_reboot.py
  tests/platform_tests/conftest.py
Labels: Request for 202305 branch

#10028 [action] [PR:9860] cisco: Update qos.yaml params for GB topo-t2.
  tests/qos/files/qos_params.gb.yaml
Labels: automerge

#10024 [action] [PR:9639] [TACACS] Retry reboot in ro-disk UT when DUT not reachable.
  tests/tacacs/test_ro_disk.py
Labels: automerge

#10023 [action] [PR:9639] [TACACS] Retry reboot in ro-disk UT when DUT not reachable.
  tests/tacacs/test_ro_disk.py
Labels: automerge

#10022 [action] [PR:9638] Skipping test_nhop_group_member_order_capability for all release before 2022305
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10021 [action] [PR:9265] [ansible] Update shell_cmds.py to print exact failed service
  ansible/library/shell_cmds.py
Labels: automerge

#10019 [action] [PR:8417] Ip inip delay
  tests/dualtor/test_ipinip.py
Labels: automerge

#10018 [action] [PR:9980] [dualtor-io] Change the health expectation for bgp shutdown case
  tests/dualtor_io/test_tor_bgp_failure.py
Labels: automerge

#10016 [action] [PR:9942] Add is_host_service_running for sonic device
  tests/common/devices/sonic.py
Labels: automerge

#10015 [action] [PR:9927] Fix testcase failure for test_check_sfp_using_ethtool
  tests/platform_tests/mellanox/test_check_sfp_using_ethtool.py
Labels: automerge

#10014 [action] [PR:9855] [configlet] Remove transciver check
  tests/configlet/util/common.py
Labels: automerge

#10013 [action] [PR:9824] [Mellanox] Fix issue: fix typo and remove unused sensor for 4600C
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: automerge

#10012 [action] [PR:9821] Skip checking expected core dump in module `bgp/test_traffic_shift.py`.
  tests/bgp/test_traffic_shift.py
  tests/conftest.py
Labels: automerge

#10011 [action] [PR:9809] Add portstat to debug FDB packet delay
  tests/fdb/test_fdb.py
Labels: automerge

#10010 [action] [PR:9809] Add portstat to debug FDB packet delay
  tests/fdb/test_fdb.py
Labels: automerge

#10009 [action] [PR:9805] Stabilize counterpoll watermark test
  tests/platform_tests/counterpoll/test_counterpoll_watermark.py
Labels: automerge

#10008 [action] [PR:9797] update port utils for cisco 8000
  ansible/module_utils/port_utils.py
Labels: automerge

#10007 [action] [PR:9781] [Snappi] PFCWD runtime traffic bug fix
  tests/snappi_tests/pfcwd/files/pfcwd_runtime_traffic_helper.py
Labels: automerge

#10006 [action] [PR:9774] [GCU] Add GCU testcase for PG headroom modification
  tests/generic_config_updater/test_pg_headroom_update.py
Labels: automerge

#10005 [action] [PR:9757] [crm]: Skip 'available' CRM check on broadcom
  tests/crm/test_crm.py
Labels: automerge

#10003 [action] [PR:9747] Skip test_secure_upgrade.py if current image is not secured.
  tests/platform_tests/test_secure_upgrade.py
Labels: automerge

#10002 [action] [PR:9745] [HLX] Stop cpu_wdt service before doing watchdog reboot
  tests/platform_tests/test_reboot.py
Labels: automerge

#10030 [action] [PR:9865] Modified prefixes from 3.3.3.0,3.3.3.1 to 5.5.5.0,5.5.5.1
  tests/crm/test_crm.py
Labels: automerge

#10029 [action] [PR:9860] cisco: Update qos.yaml params for GB topo-t2.
  tests/qos/files/qos_params.gb.yaml
Labels: automerge

#10027 [action] [PR:9778] Updated qos params for gb 400000_120000m
  tests/qos/files/qos_params.gb.yaml
Labels: automerge

#10026 [action] [PR:9778] Updated qos params for gb 400000_120000m
  tests/qos/files/qos_params.gb.yaml
Labels: automerge

#10025 [action] [PR:9639] [TACACS] Retry reboot in ro-disk UT when DUT not reachable.
  tests/tacacs/test_ro_disk.py
Labels: automerge

#10000 [action] [PR:9651] [platform_tests/sfp]: Fix test_check_sfputil_reset test error when pmon_daemon_control.json file is not present.
  tests/platform_tests/sfp/conftest.py
Labels: automerge

#9999 [action] [PR:9645] [test_snmp_memory_load] reserver 256M free memory
  tests/snmp/memory.py
Labels: automerge

#9998 [action] [PR:9623] [TACACS] Fix tacacs authorization and accounting UT randomly failed issue.
  tests/tacacs/test_accounting.py
  tests/tacacs/test_authorization.py
  tests/tacacs/utils.py
Labels: automerge

#9997 [action] [PR:9604] [GCU] Update syslog ignore regex
  tests/generic_config_updater/conftest.py
Labels: automerge

#9996 [action] [PR:9587] [Nvidia] Fix qos sai test for supporting LAG port
  tests/qos/qos_sai_base.py
  tests/qos/test_tunnel_qos_remap.py
  tests/saitests/py3/sai_base_test.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#9995 [action] [PR:9318] New PCBB dualtor watermark storm tests
  tests/qos/test_tunnel_qos_remap.py
  tests/qos/tunnel_qos_remap_base.py
Labels: automerge

#9994 [action] [PR:9264] Cisco-8000 psu led support
  tests/common/platform/device_utils.py
  tests/platform_tests/cli/test_show_platform.py
Labels: automerge

#9993 [action] [PR:9264] Cisco-8000 psu led support
  tests/common/platform/device_utils.py
  tests/platform_tests/cli/test_show_platform.py
Labels: automerge

#9977 [action] [PR:9799] [platform_tests] fix getting current idle driver error
  tests/platform_tests/test_idle_driver.py
Labels: automerge

#9975 [action] [PR:9785] skip test_trap_config_save_after_reboot on 7050qx and 7060 for 202305 branch
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10037 [action] [PR:9986] Always cleanup cEOS mount dir before creating cEOS
  ansible/roles/eos/tasks/ceos_config.yml
Labels: automerge

#10035 [action] [PR:9987] Conditionally install env-python3 in setup-container.sh
  setup-container.sh
Labels: automerge

#10033 [action] [PR:9987] Conditionally install env-python3 in setup-container.sh
  setup-container.sh
Labels: automerge

#10034 [action] [PR:9987] Conditionally install env-python3 in setup-container.sh
  setup-container.sh
Labels: automerge

#10031 Add t1-64-lag topo for test_lag_2.py::test_lag_db_status_with_po_update
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202012 branch, Request for 202205 branch, Approved for 202012 branch, Approved for 202205 branch, Request for 202305 branch, Approved for 202305 branch

#10043 [action] [PR:10031] Add t1-64-lag topo for test_lag_2.py::test_lag_db_status_with_po_update
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10042 [action] [PR:10031] Add t1-64-lag topo for test_lag_2.py::test_lag_db_status_with_po_update
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#9982 add vnet route cleanup and re-setup after test_vxlan_remove_route2
  tests/vxlan/test_vxlan_ecmp.py
Labels: Request for 202205 branch, Request for 202305 branch

#9969 [testfix]Fixed failures caused by python 3 conversion.
  ansible/roles/test/files/ptftests/py3/vxlan_traffic.py
  tests/vxlan/test_vxlan_ecmp.py
Labels: Request for 202305 branch

#10020 [action] [PR:8906] [dualtor] fixing test_downstream_ecmp_nexthops
  tests/common/dualtor/dual_tor_utils.py
  tests/dualtor/test_orchagent_active_tor_downstream.py
Labels: automerge

#10017 [action] [PR:9957] Fix acl outer vlan test
  ansible/roles/test/files/helpers/arp_responder.py
  tests/acl/test_acl_outer_vlan.py
Labels: automerge

#10004 [action] [PR:9756] Fix permission of /tmp to unblock copp test
  tests/copp/copp_utils.py
Labels: automerge

#10001 [action] [PR:9659] [Snappi] Validate PFC frame bug fix
  tests/common/snappi_tests/common_helpers.py
  tests/common/snappi_tests/pfc_packet.py
  tests/common/snappi_tests/read_pcap.py
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/pfc/files/helper.py
Labels: automerge

#9991 [action] [PR:8097] Add a test case to verify that BGP packets use queue7
  docs/testplan/BGP-queue-test-plan.md
  tests/bgp/test_bgp_queue.py
Labels: automerge

#9974 bug fix: TypeError: separated_dscp_to_tc_map_on_uplink() takes 1 posi…
  tests/qos/test_qos_sai.py
Labels: Request for 202205 branch, Request for 202305 branch

#9767 Add support for GNMI
  spytest/apis/routing/vrf.py
Labels: Spytest

#9783 Add GNMI support and enhancement to existing APIs
  spytest/apis/routing/ip.py
Labels: Spytest

#9787 Add support for GNMI for NAT
  spytest/apis/routing/nat.py
Labels: Spytest

#9788 Add GNMI support for SAG APIs
  spytest/apis/routing/sag.py
Labels: Spytest

#9829 Add GNMI support and enhancements;
  spytest/apis/switching/portchannel.py
Labels: Spytest

#9838 Add GNMI support for STP
  spytest/apis/switching/pvst.py
Labels: Spytest

#9841 Add GNMI support to VLAN APIs
  spytest/apis/switching/vlan.py
Labels: Spytest

#9880 Add GNMI support for radius APIs
  spytest/apis/security/radius.py
  spytest/apis/switching/portchannel_rest.py
Labels: Spytest

#9882 Add GNMI support for TACACS
  spytest/apis/security/tacacs.py
Labels: Spytest

#9884 Add GNMI support for SFLOW
  spytest/apis/system/sflow.py
Labels: Spytest

#9886 Add GNMI support for BGP and some minor fixes
  spytest/apis/routing/bgp.py
Labels: Spytest

#9889 Add GNMI support for COS
  spytest/apis/qos/cos.py
Labels: Spytest

#9928 Add GNMI support for port APIs
  spytest/apis/system/port.py
Labels: Spytest

#9568 [dualtor-io] show mux port flaps
  ansible/dualtor/nic_simulator/nic_simulator.py
  ansible/dualtor/nic_simulator/nic_simulator_grpc_mgmt_service.proto
  ansible/dualtor/nic_simulator/nic_simulator_grpc_mgmt_service_pb2.py
  ansible/dualtor/nic_simulator/nic_simulator_grpc_mgmt_service_pb2_grpc.py
  ansible/dualtor/nic_simulator/nic_simulator_grpc_service.proto
  ansible/dualtor/nic_simulator/nic_simulator_grpc_service_pb2.py
  ansible/dualtor/nic_simulator/nic_simulator_grpc_service_pb2_grpc.py
  tests/common/dualtor/dual_tor_utils.py
  tests/common/dualtor/mux_simulator_control.py
  tests/common/dualtor/nic_simulator_control.py
  tests/dualtor_io/conftest.py
  tests/dualtor_io/test_grpc_server_failure.py
  tests/dualtor_io/test_heartbeat_failure.py
  tests/dualtor_io/test_link_drop.py
  tests/dualtor_io/test_link_failure.py
  tests/dualtor_io/test_normal_op.py
  tests/dualtor_io/test_tor_bgp_failure.py
  tests/dualtor_io/test_tor_failure.py
Labels: Request for 202205 branch, Request for 202305 branch

#9966 [test_reload_config] Fix `test_reload_configuration_checks`
  tests/common/config_reload.py
  tests/platform_tests/test_reload_config.py
Labels: Request for 202205 branch, Request for 202305 branch

#9716 reduce the burst rate for " test_po_update_io_no_loss"
  tests/pc/test_po_update.py
Labels: Request for 202205 branch, Request for 202305 branch

#10062 [qos] fix keyerror dst
  tests/saitests/py3/sai_base_test.py
Labels: Request for 202305 branch

#9897 [chassis] fix flakiness in test_chassisd.py
  tests/platform_tests/daemon/test_chassisd.py
Labels: Request for 202205 branch

#10080 Stabilize acl_outer_vlan test
  tests/acl/test_acl_outer_vlan.py
Labels: Request for 202305 branch

#10075 Xfail reboot cases
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch

#10086 Add missing skip section in ctests_mark_conditions.yaml
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch, Approved for 202205 branch

#10089 [action] [PR:10086] Add missing skip section in ctests_mark_conditions.yaml
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10092 [action] [PR:8732] Added missed topo mark for test_route_flow_counters
  tests/route/test_route_flow_counter.py
Labels: automerge

#10085 Stabilize test_memory_checker
  tests/memory_checker/test_memory_checker.py
Labels: Request for 202305 branch

#10049 [testfix] test cleanup and bfd_responder fix.
  ansible/roles/test/files/ptftests/bfd_responder.py
  tests/vxlan/test_vxlan_ecmp.py
Labels: Request for 202305 branch

#10084 Verify ACL bind to portchannel
  tests/acl/test_acl_outer_vlan.py
Labels: Request for 202205 branch, Request for 202305 branch

#10081 [testfix] test_cpu_memory_usage_counterpoll threshold change.
  tests/platform_tests/test_cpu_memory_usage.py
Labels: Request for 202305 branch

#10098 [action] [PR:9969] [testfix]Fixed failures caused by python 3 conversion.
  ansible/roles/test/files/ptftests/py3/vxlan_traffic.py
  tests/vxlan/test_vxlan_ecmp.py
Labels: automerge

#10102 [M0/Mx] Skip unsupported testcases on M0/Mx topology
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch

#10103 [action] [PR:10102] [M0/Mx] Skip unsupported testcases on M0/Mx topology
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#9810 Cisco: Skip Watermark test for multi-DUT cases.
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: Request for 202205 branch, Request for 202305 branch

#9893 test_ro_disk: Enhancement for reboot of supervisor card
  tests/tacacs/test_ro_disk.py
Labels: Request for 202205 branch

#9896 Adding COUNTER_MARGIN to Ingress drop counters for qos tests
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch

#10091 Fix test_gnmi_configdb_incremental_01 failure
  tests/gnmi/test_gnmi_configdb.py
Labels: Request for 202305 branch

#10124 [dualtor_io] Add server to server I/O normal op test
  tests/common/dualtor/data_plane_utils.py
  tests/common/dualtor/dual_tor_io.py
  tests/dualtor_io/test_normal_op.py
Labels: Request for 202205 branch, Request for 202305 branch

#10128 [action] [PR:10049] [testfix] test cleanup and bfd_responder fix.
  ansible/roles/test/files/ptftests/bfd_responder.py
  tests/vxlan/test_vxlan_ecmp.py
Labels: automerge

#10135 Ignore Failed to parse lldp age error log
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202012 branch, Request for 202205 branch, Approved for 202012 branch, Approved for 202205 branch, Request for 202305 branch, Approved for 202305 branch

#10136 [action] [PR:10135] Ignore Failed to parse lldp age error log
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#10143 [action] [PR:10125] Increase max timeout to 400s for checking critical services during safe reload
  tests/common/reboot.py
Labels: automerge

#10142 [action] [PR:10125] Increase max timeout to 400s for checking critical services during safe reload
  tests/common/reboot.py
Labels: automerge
