Repository sonic-net/sonic-mgmt, pull requests merged in 2023-08, with the labels that each got.

#9199 Recover default acl rules if necessary in module `crm/test_crm.py`.
  tests/crm/templates/acl.json
  tests/crm/test_crm.py
Labels: Request for 202012 branch, Request for 202205 branch

#8555 [Nvidia] Update too_big_timeout for test_arm_too_big_timeout
  tests/platform_tests/api/watchdog.yml
Labels: Request for 202205 branch

#9176 [snmp] Fix snmpget command to run from duthost
  tests/snmp/test_snmp_memory.py
Labels: Request for 202205 branch

#9207 Modify import path in script `get_dut_version.py`.
  .azure-pipelines/get_dut_version.py
Labels: Request for 202012 branch, Request for 202205 branch

#9209 Skip test_module for non T2 topology
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202012 branch, Request for 202205 branch

#9217 [action] [PR:9207] Modify import path in script `get_dut_version.py`.
  .azure-pipelines/get_dut_version.py
Labels: automerge

#9216 [action] [PR:9207] Modify import path in script `get_dut_version.py`.
  .azure-pipelines/get_dut_version.py
Labels: automerge

#9224 [action] [PR:9175] [testfix] test_vxlan_ecmp cleanup of routes after test runs.
  tests/vxlan/test_vxlan_ecmp.py
Labels: automerge

#9226 [action] [PR:9199] Recover default acl rules if necessary in module `crm/test_crm.py`.
  tests/crm/templates/acl.json
  tests/crm/test_crm.py
Labels: automerge

#9222 [action] [PR:9175] [testfix] test_vxlan_ecmp cleanup of routes after test runs.
  tests/vxlan/test_vxlan_ecmp.py
Labels: automerge

#9221 [action] [PR:9184] [master] Change tool scripts to use Python3 explicitly
  .azure-pipelines/get_dut_version.py
  .azure-pipelines/upgrade_image.py
  ansible/TestbedProcessing.py
  ansible/devutils
  ansible/files/check_testbed_and_inventory_file.py
  ansible/files/creategraph.py
  ansible/health_checker.py
  ansible/linkstate/testbed_inv.py
  ansible/recover_server.py
  ansible/restart_nightly_ptf.py
  ansible/upgrade_sonic.py
Labels: automerge

#9228 [action] [PR:9185] [ansible] update default ceos image to newer version
  ansible/group_vars/all/ceos.yml
Labels: automerge

#9225 [action] [PR:9199] Recover default acl rules if necessary in module `crm/test_crm.py`.
  tests/crm/templates/acl.json
  tests/crm/test_crm.py
Labels: automerge

#9223 [action] [PR:9175] [testfix] test_vxlan_ecmp cleanup of routes after test runs.
  tests/vxlan/test_vxlan_ecmp.py
Labels: automerge

#9220 [action] [PR:9207] Modify import path in script `get_dut_version.py`.
  .azure-pipelines/get_dut_version.py
Labels: automerge

#8970 fix syntax error in device_mocker_factory
  tests/system_health/device_mocker.py
Labels: Request for 202205 branch

#9234 [action] [PR:8970] fix syntax error in device_mocker_factory
  tests/system_health/device_mocker.py
Labels: automerge

#9241 Update topo_dualtor-64 to enable port 0
  ansible/vars/topo_dualtor-64.yml
Labels: Request for 202205 branch, Request for 202305 branch

#9232 Fix import issue of tests/snappi_tests in python3
  .azure-pipelines/pytest-collect-only.yml
  tests/snappi_tests/bgp/test_bgp_convergence_performance.py
  tests/snappi_tests/bgp/test_bgp_local_link_failover.py
  tests/snappi_tests/bgp/test_bgp_remote_link_failover.py
  tests/snappi_tests/bgp/test_bgp_rib_in_capacity.py
  tests/snappi_tests/bgp/test_bgp_rib_in_convergence.py
  tests/snappi_tests/bgp/test_bgp_scalability.py
  tests/snappi_tests/ecn/conftest.py
  tests/snappi_tests/ecn/test_dequeue_ecn_with_snappi.py
  tests/snappi_tests/ecn/test_red_accuracy_with_snappi.py
  tests/snappi_tests/lacp/test_add_remove_link_from_dut.py
  tests/snappi_tests/lacp/test_add_remove_link_physically.py
  tests/snappi_tests/lacp/test_lacp_timers_effect.py
  tests/snappi_tests/pfc/test_global_pause_with_snappi.py
  tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/pfc/test_pfc_pause_lossy_with_snappi.py
  tests/snappi_tests/pfc/test_pfc_pause_response_with_snappi.py
  tests/snappi_tests/pfc/test_pfc_pause_unset_bit_enable_vector.py
  tests/snappi_tests/pfc/test_pfc_pause_zero_mac.py
  tests/snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py
  tests/snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py
  tests/snappi_tests/pfcwd/test_pfcwd_burst_storm_with_snappi.py
  tests/snappi_tests/pfcwd/test_pfcwd_m2o_with_snappi.py
  tests/snappi_tests/pfcwd/test_pfcwd_runtime_traffic_with_snappi.py
  tests/snappi_tests/qos/test_ipip_packet_reorder_with_snappi.py
Labels: Request for 202305 branch

#9075 [chassis] accomodate test_memory_exhaustion.py if random dut is chassis sup
  tests/common/platform/processes_utils.py
  tests/platform_tests/test_memory_exhaustion.py
Labels: chassis, Request for 202205 branch

#9235 [action] [PR:8970] fix syntax error in device_mocker_factory
  tests/system_health/device_mocker.py
Labels: automerge

#9246 [action] [PR:9232] Fix import issue of tests/snappi_tests in python3
  .azure-pipelines/pytest-collect-only.yml
  tests/snappi_tests/bgp/test_bgp_convergence_performance.py
  tests/snappi_tests/bgp/test_bgp_local_link_failover.py
  tests/snappi_tests/bgp/test_bgp_remote_link_failover.py
  tests/snappi_tests/bgp/test_bgp_rib_in_capacity.py
  tests/snappi_tests/bgp/test_bgp_rib_in_convergence.py
  tests/snappi_tests/bgp/test_bgp_scalability.py
  tests/snappi_tests/ecn/conftest.py
  tests/snappi_tests/ecn/test_dequeue_ecn_with_snappi.py
  tests/snappi_tests/ecn/test_red_accuracy_with_snappi.py
  tests/snappi_tests/lacp/test_add_remove_link_from_dut.py
  tests/snappi_tests/lacp/test_add_remove_link_physically.py
  tests/snappi_tests/lacp/test_lacp_timers_effect.py
  tests/snappi_tests/pfc/test_global_pause_with_snappi.py
  tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/pfc/test_pfc_pause_lossy_with_snappi.py
  tests/snappi_tests/pfc/test_pfc_pause_response_with_snappi.py
  tests/snappi_tests/pfc/test_pfc_pause_unset_bit_enable_vector.py
  tests/snappi_tests/pfc/test_pfc_pause_zero_mac.py
  tests/snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py
  tests/snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py
  tests/snappi_tests/pfcwd/test_pfcwd_burst_storm_with_snappi.py
  tests/snappi_tests/pfcwd/test_pfcwd_m2o_with_snappi.py
  tests/snappi_tests/pfcwd/test_pfcwd_runtime_traffic_with_snappi.py
  tests/snappi_tests/qos/test_ipip_packet_reorder_with_snappi.py
Labels: automerge

#9250 Issue #6657 - 'systemctl restart ferret' failure in test_decap testcase
  tests/arp/files/ferret.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9255 [action] [PR:9088] Add dualtor standby drop test and check dhcpmon count based on number of dhcp servers configured
  tests/dhcp_relay/test_dhcp_relay.py
Labels: automerge

#9254 Fix bsl test
  tests/common/fixtures/duthost_utils.py
  tests/common/helpers/portchannel_to_vlan.py
  tests/fdb/test_fdb.py
Labels: Request for 202205 branch, Request for 202305 branch

#9038 Update BufferPoolWatermarkTest for cisco-8000 hbm
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch

#9054 Leave 1 ACL rule in test_crm.py::test_acl_entry
  tests/crm/test_crm.py
Labels: Request for 202205 branch

#9160 Watchdog reset skip
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
  tests/platform_tests/test_reboot.py
Labels: Request for 202205 branch, Request for 202305 branch

#9256 Remove pg lossless settings of port speed in module `iface_namingmode/test_iface_namingmode.py`.
  tests/iface_namingmode/test_iface_namingmode.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9259 Fix potential KeyError of fixtures like vmhost, ptfhost, fanouthosts.
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9048 test_radv_ipv6_ra is unnecessarily skipped on non-dualtor topology
  tests/radv/test_radv_ipv6_ra.py
Labels: Request for 202205 branch

#9291 [action] [PR:8555] [Nvidia] Update too_big_timeout for test_arm_too_big_timeout
  tests/platform_tests/api/watchdog.yml
Labels: automerge

#9286 [action] [PR:9256] Remove pg lossless settings of port speed in module `iface_namingmode/test_iface_namingmode.py`.
  tests/iface_namingmode/test_iface_namingmode.py
Labels: automerge

#9285 [action] [PR:9254] Fix bsl test
  tests/common/fixtures/duthost_utils.py
  tests/common/helpers/portchannel_to_vlan.py
  tests/fdb/test_fdb.py
Labels: automerge

#9284 [action] [PR:9250] Issue #6657 - 'systemctl restart ferret' failure in test_decap testcase
  tests/arp/files/ferret.py
Labels: automerge

#9283 [action] [PR:9250] Issue #6657 - 'systemctl restart ferret' failure in test_decap testcase
  tests/arp/files/ferret.py
Labels: automerge

#9281 [action] [PR:9197] Qos enablement cisco-8111 platform
  ansible/group_vars/sonic/variables
  tests/qos/qos_sai_base.py
Labels: automerge

#9278 [action] [PR:9209] Skip test_module for non T2 topology
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: automerge

#9277 [action] [PR:9209] Skip test_module for non T2 topology
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: automerge

#9275 [action] [PR:9196] Define dualtor-64 topology
  ansible/roles/eos/templates/dualtor-64-leaf.j2
  ansible/vars/topo_dualtor-64.yml
Labels: automerge

#9274 [action] [PR:9196] Define dualtor-64 topology
  ansible/roles/eos/templates/dualtor-64-leaf.j2
  ansible/vars/topo_dualtor-64.yml
Labels: automerge

#9271 [action] [PR:9054] Leave 1 ACL rule in test_crm.py::test_acl_entry
  tests/crm/test_crm.py
Labels: automerge

#9295 [action] [PR:9075] [chassis] accomodate test_memory_exhaustion.py if random dut is chassis sup
  tests/common/platform/processes_utils.py
  tests/platform_tests/test_memory_exhaustion.py
Labels: automerge

#9292 [action] [PR:9060] Adding watchdog parameter for cisco-8111 platform
  tests/platform_tests/api/watchdog.yml
Labels: automerge

#9287 [action] [PR:9256] Remove pg lossless settings of port speed in module `iface_namingmode/test_iface_namingmode.py`.
  tests/iface_namingmode/test_iface_namingmode.py
Labels: automerge

#9293 [action] [PR:9089] Update `icmp_responder` to only respond only linkmgrd requests
  tests/scripts/icmp_responder.py
Labels: automerge

#9282 [action] [PR:9250] Issue #6657 - 'systemctl restart ferret' failure in test_decap testcase
  tests/arp/files/ferret.py
Labels: automerge

#9276 [action] [PR:9259] Fix potential KeyError of fixtures like vmhost, ptfhost, fanouthosts.
  tests/conftest.py
Labels: automerge

#9272 [action] [PR:9054] Leave 1 ACL rule in test_crm.py::test_acl_entry
  tests/crm/test_crm.py
Labels: automerge

#9273 [action] [PR:9160] Watchdog reset skip
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
  tests/platform_tests/test_reboot.py
Labels: automerge

#9310 [mx][acl] Fix test_acl_outer_vlan failed at mx
  tests/acl/test_acl_outer_vlan.py
Labels: Request for 202205 branch, Request for 202305 branch

#9313 [action] [PR:9310] [mx][acl] Fix test_acl_outer_vlan failed at mx
  tests/acl/test_acl_outer_vlan.py
Labels: automerge

#9239 fix bgp slb test case dual tor issue
  tests/bgp/test_bgp_slb.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9218 [chassis] test_memory_checker.py use same random dut for fixtures and functions
  tests/memory_checker/test_memory_checker.py
Labels: Request for 202205 branch

#9320 [regression] fix regression in test_memory_exhaustion.py
  tests/platform_tests/test_memory_exhaustion.py
Labels: Request for 202205 branch

#9324 Get core dump files from dut if new core dump generates.
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9326 [PTF python3 migration] Modify test_copp PTF script
  ansible/roles/test/files/ptftests/py3/copp_tests.py
  tests/copp/test_copp.py
Labels: Request for 202205 branch, Request for 202305 branch

#9330 [action] [PR:9320] [regression] fix regression in test_memory_exhaustion.py
  tests/platform_tests/test_memory_exhaustion.py
Labels: automerge

#9329 [action] [PR:9075] [chassis] accomodate test_memory_exhaustion.py if random dut is chassis sup
  tests/common/platform/processes_utils.py
  tests/platform_tests/test_memory_exhaustion.py
Labels: automerge

#9125 Adding dut & dut_asic namespace to getSchedulerParam in qos_sai_base
  tests/qos/qos_sai_base.py
Labels: chassis

#9340 fixed bugs causing failures.
  tests/vxlan/test_vxlan_ecmp.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9333 workaround PFCWD T1 related cases after PR 8859
  tests/pfcwd/conftest.py
Labels: Request for 202205 branch

#9334 [acl][m0] Test second vlan for m0-2vlan in test_acl
  tests/acl/templates/acltb_v6_test_rules.j2
  tests/acl/templates/acltb_v6_test_rules_part_2.j2
  tests/acl/test_acl.py
  tests/conftest.py
Labels: Request for 202205 branch, Request for 202305 branch

#9335 [acl] Optimize acl xfail condition
  tests/common/plugins/conditional_mark/tests_mark_conditions_acl.yaml
Labels: Request for 202205 branch, Request for 202305 branch

#9337 [arp_responder] Fix error in generate_neigh_adv
  tests/scripts/arp_responder.py
Labels: Request for 202305 branch

#9346 Revert the change to template acl.json.
  tests/crm/templates/acl.json
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9349 [action] [PR:9335] [acl] Optimize acl xfail condition
  tests/common/plugins/conditional_mark/tests_mark_conditions_acl.yaml
Labels: automerge

#9339 [action] [PR:9320] [regression] fix regression in test_memory_exhaustion.py
  tests/platform_tests/test_memory_exhaustion.py
Labels: automerge

#9347 [PTF python3 migration] Modify test_decap PTF script
  ansible/roles/test/files/ptftests/py3/IP_decap_test.py
  tests/decap/test_decap.py
Labels: Request for 202205 branch, Request for 202305 branch

#9351 [action] [PR:9337] [arp_responder] Fix error in generate_neigh_adv
  tests/scripts/arp_responder.py
Labels: automerge

#9338 [action] [PR:9208] [tests/crm] Fix python3 syntax error in `test_acl_entry`
  tests/crm/test_crm.py
Labels: automerge

#9354 [action] [PR:9335] [acl] Optimize acl xfail condition
  tests/common/plugins/conditional_mark/tests_mark_conditions_acl.yaml
Labels: automerge

#9353 [arp_responder] Fix response icmpv6 packet error
  tests/scripts/arp_responder.py
Labels: Request for 202305 branch

#9356 [dhcp_relay][m0] Add support for in test_dhcp_pkt_fwd for m0-2vlan
  tests/dhcp_relay/test_dhcp_pkt_fwd.py
Labels: Request for 202205 branch, Request for 202305 branch

#9359 [action] [PR:9353] [arp_responder] Fix response icmpv6 packet error
  tests/scripts/arp_responder.py
Labels: automerge

#9156 spytest framework - device access improvements
  spytest/spytest/access/connection.py
  spytest/spytest/access/linux_connection.py
  spytest/spytest/access/netmiko_connection.py
  spytest/spytest/access/paramiko_connection.py
  spytest/spytest/access/sonic_connection.py
  spytest/spytest/access/utils.py
Labels: Spytest

#9172 [Chassis T2] Added initial JR2 Qos params for T2 testing
  tests/qos/files/qos_params.jr2.yaml
Labels: Request for 202205 branch

#9312 Refactor fixture `recover_acl_rule` and and use it in module `cacl/test_cacl_function.py`.
  tests/cacl/test_cacl_function.py
  tests/common/templates/default_acl_rules.json
  tests/conftest.py
  tests/crm/conftest.py
  tests/crm/test_crm.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9383 [action] [PR:9346] Revert the change to template acl.json.
  tests/crm/templates/acl.json
Labels: automerge

#9375 [action] [PR:9248] Improve docker registry related logging
  tests/common/system_utils/docker.py
  tests/tacacs/conftest.py
Labels: automerge

#9374 [action] [PR:9248] Improve docker registry related logging
  tests/common/system_utils/docker.py
  tests/tacacs/conftest.py
Labels: automerge

#9355 Add support of setting docker_inram_size during upgrade image
  .azure-pipelines/upgrade_image.py
  ansible/devutil/devices/sonic.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9393 [action] [PR:9324] Get core dump files from dut if new core dump generates.
  tests/conftest.py
Labels: automerge

#9390 [action] [PR:9311] ignore memory threshold check for 7050qx in qos sai test
  tests/qos/test_qos_sai.py
Labels: automerge

#9385 [action] [PR:9172] [Chassis T2] Added initial JR2 Qos params for T2 testing
  tests/qos/files/qos_params.jr2.yaml
Labels: automerge

#9384 [action] [PR:9347] [PTF python3 migration] Modify test_decap PTF script
  ansible/roles/test/files/ptftests/py3/IP_decap_test.py
  tests/decap/test_decap.py
Labels: automerge

#9381 [action] [PR:9346] Revert the change to template acl.json.
  tests/crm/templates/acl.json
Labels: automerge

#9380 [action] [PR:9340] Ignore a SWSS error log for test_vxlan_ecmp
  tests/vxlan/test_vxlan_ecmp.py
Labels: automerge

#9373 [action] [PR:9239] fix bgp slb test case dual tor issue
  tests/bgp/test_bgp_slb.py
Labels: automerge

#9360 [action] [PR:9356] [dhcp_relay][m0] Add support for in test_dhcp_pkt_fwd for m0-2vlan
  tests/dhcp_relay/test_dhcp_pkt_fwd.py
Labels: automerge

#9331 Add try-finally to recovery DUT in module `acl/test_stress_acl.py`.
  tests/acl/test_stress_acl.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9358 [PTF python3 migration] Modify test_pfcwd PTF script
  ansible/roles/test/files/ptftests/py3/pfc_wd.py
  tests/pfcwd/test_pfcwd_function.py
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: Request for 202205 branch, Request for 202305 branch

#9400 [action] [PR:9355] Add support of setting docker_inram_size during upgrade image
  .azure-pipelines/upgrade_image.py
  ansible/devutil/devices/sonic.py
Labels: automerge

#9397 [action] [PR:9345] Run check_bgp_router_id post reboot
  tests/common/fixtures/advanced_reboot.py
Labels: automerge

#9395 [action] [PR:9333] workaround PFCWD T1 related cases after PR 8859
  tests/pfcwd/conftest.py
Labels: automerge

#9394 [action] [PR:9333] workaround PFCWD T1 related cases after PR 8859
  tests/pfcwd/conftest.py
Labels: automerge

#9388 [action] [PR:9218] [chassis] test_memory_checker.py use same random dut for fixtures and functions
  tests/memory_checker/test_memory_checker.py
Labels: automerge

#9387 [action] [PR:9218] [chassis] test_memory_checker.py use same random dut for fixtures and functions
  tests/memory_checker/test_memory_checker.py
Labels: automerge

#9386 [action] [PR:9172] [Chassis T2] Added initial JR2 Qos params for T2 testing
  tests/qos/files/qos_params.jr2.yaml
Labels: automerge

#9402 [action] [PR:9355] Add support of setting docker_inram_size during upgrade image
  .azure-pipelines/upgrade_image.py
  ansible/devutil/devices/sonic.py
Labels: automerge

#9401 [action] [PR:9355] Add support of setting docker_inram_size during upgrade image
  .azure-pipelines/upgrade_image.py
  ansible/devutil/devices/sonic.py
Labels: automerge

#9367 Stabilize `test_create_vrf`
  tests/restapi/test_restapi.py
Labels: Request for 202205 branch, Request for 202305 branch

#9398 Fix iface_loopback_action test
  tests/iface_loopback_action/iface_loopback_action_helper.py
Labels: Request for 202305 branch

#9392 [action] [PR:9324] Get core dump files from dut if new core dump generates.
  tests/conftest.py
Labels: automerge

#9379 [action] [PR:9340] Ignore a SWSS error log for test_vxlan_ecmp
  tests/vxlan/test_vxlan_ecmp.py
Labels: automerge

#9376 [action] [PR:9248] Improve docker registry related logging
  tests/common/system_utils/docker.py
  tests/tacacs/conftest.py
Labels: automerge

#9348 [action] [PR:9334] [acl][m0] Test second vlan for m0-2vlan in test_acl
  tests/acl/templates/acltb_v6_test_rules.j2
  tests/acl/templates/acltb_v6_test_rules_part_2.j2
  tests/acl/test_acl.py
  tests/conftest.py
Labels: automerge

#9378 [action] [PR:9326] [PTF python3 migration] Modify test_copp PTF script
  ansible/roles/test/files/ptftests/py3/copp_tests.py
  tests/copp/test_copp.py
Labels: automerge

#9408 ARP resolution during get_rx_port to avoid flaky LAG ID
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch

#9364 spytest tgen improvements
  spytest/spytest/tgen/init.py
  spytest/spytest/tgen/scapy/afpacket.py
  spytest/spytest/tgen/scapy/bgp.py
  spytest/spytest/tgen/scapy/bgp_exabgp.py
  spytest/spytest/tgen/scapy/dhcps.py
  spytest/spytest/tgen/scapy/dicts.py
  spytest/spytest/tgen/scapy/dot1x.py
  spytest/spytest/tgen/scapy/driver.py
  spytest/spytest/tgen/scapy/emulation.py
  spytest/spytest/tgen/scapy/exabgp_http_api.py
  spytest/spytest/tgen/scapy/exabgp_routes.py
  spytest/spytest/tgen/scapy/funcs.py
  spytest/spytest/tgen/scapy/interface.py
  spytest/spytest/tgen/scapy/lock.py
  spytest/spytest/tgen/scapy/logger.py
  spytest/spytest/tgen/scapy/or_event.py
  spytest/spytest/tgen/scapy/packet.py
  spytest/spytest/tgen/scapy/port.py
  spytest/spytest/tgen/scapy/protocol.py
  spytest/spytest/tgen/scapy/pyro-service.py
  spytest/spytest/tgen/scapy/rpyc-service.py
  spytest/spytest/tgen/scapy/server.py
  spytest/spytest/tgen/scapy/service.py
  spytest/spytest/tgen/scapy/service.sh
  spytest/spytest/tgen/scapy/stats.py
  spytest/spytest/tgen/scapy/unit_test.py
  spytest/spytest/tgen/scapy/ut_streams.py
  spytest/spytest/tgen/scapy/utils.py
  spytest/spytest/tgen/scapy/yabgp.ini
  spytest/spytest/tgen/tg.py
  spytest/spytest/tgen/tg_scapy.py
  spytest/spytest/tgen/tg_stubs.py
  spytest/spytest/tgen/tgen_utils.py
  spytest/spytest/tgen_api.py
Labels: Spytest

#9391 [action] [PR:9311] ignore memory threshold check for 7050qx in qos sai test
  tests/qos/test_qos_sai.py
Labels: automerge

#9377 [action] [PR:9324] Get core dump files from dut if new core dump generates.
  tests/conftest.py
Labels: automerge

#9382 [action] [PR:9346] Revert the change to template acl.json.
  tests/crm/templates/acl.json
Labels: automerge

#9389 [action] [PR:9309] update ser timeout ignore memory for th2
  tests/platform_tests/broadcom/files/ser_injector.py
Labels: automerge

#9268 [SNMP]: Add snmp test case using link local as snmpagent address
  .azure-pipelines/pr_test_scripts.yaml
  tests/snmp/test_snmp_link_local.py
Labels: Request for 202205 branch, Request for 202305 branch

#9418 Decrease the PFC frame counter in PFC watchdog warmboot test
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: Request for 202205 branch, Request for 202305 branch

#9405 [PTF python3 migration] Modify populate_fdb PTF script
  ansible/roles/test/files/ptftests/py3/populate_fdb.py
  tests/common/fixtures/populate_fdb.py
Labels: Request for 202205 branch, Request for 202305 branch

#9447 Fix port selection in ptfhost_utils.py
  tests/common/fixtures/ptfhost_utils.py
Labels: Request for 202305 branch

#9414 Fix EVERFLOW egress mirroring test in dualtor setup
  tests/everflow/everflow_test_utilities.py
Labels: Request for 202305 branch

#9449 [PTF python3 migration] Modify test_voq_nbr and test_voq_ipfwd PTF script
  ansible/roles/test/files/ptftests/py3/voq.py
  tests/voq/test_voq_ipfwd.py
  tests/voq/test_voq_nbr.py
Labels: Request for 202205 branch, Request for 202305 branch

#9450 [PTF python3 migration] Modify test_mtu PTF script
  ansible/roles/test/files/ptftests/py3/mtu_test.py
  tests/ipfwd/test_mtu.py
Labels: Request for 202205 branch, Request for 202305 branch

#9451 [PTF python3 migration] Modify test_vrf PTF script
  ansible/roles/test/files/ptftests/py3/vrf_test.py
  tests/vrf/test_vrf.py
  tests/vrf/test_vrf_attr.py
Labels: Request for 202205 branch, Request for 202305 branch

#9419 Sensor test update
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: Request for 202205 branch, Request for 202305 branch

#9452 Fix wrong bool argument parsing in upgrade_image.py script
  .azure-pipelines/upgrade_image.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9456 [action] [PR:9452] Fix wrong bool argument parsing in upgrade_image.py script
  .azure-pipelines/upgrade_image.py
Labels: automerge

#9423 fix bgp update timer failure on dual tor
  tests/bgp/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9454 [action] [PR:9452] Fix wrong bool argument parsing in upgrade_image.py script
  .azure-pipelines/upgrade_image.py
Labels: automerge

#8814 [VM]Add BGPSentinel testcase and testplan
  docs/testplan/BGP-BGPSentinel.md
  tests/bgp/bgp_helpers.py
  tests/bgp/test_bgp_sentinel.py
Labels: Test Plan

#9467 [action] [PR:8858] update traffic disruption validating logic for dualtor_io tests
  tests/common/dualtor/data_plane_utils.py
Labels: automerge

#9455 [action] [PR:9452] Fix wrong bool argument parsing in upgrade_image.py script
  .azure-pipelines/upgrade_image.py
Labels: automerge

#9470 Revert "Set key "asic0" in single-asic scenerio to keep consistent with multi-asic in function `core_dump_and_config_check`."
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9453 [Fix] Fix multi-asic flaky lldp not ready issue
  tests/common/plugins/sanity_check/constants.py
  tests/common/plugins/sanity_check/recover.py
  tests/common/reboot.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#9472 [action] [PR:9446] fix tcpdump issue in bgp update timer testing
  tests/bgp/test_bgp_update_timer.py
Labels: automerge

#9471 [action] [PR:9446] fix tcpdump issue in bgp update timer testing
  tests/bgp/test_bgp_update_timer.py
Labels: automerge

#9396 [action] [PR:9345] Run check_bgp_router_id post reboot
  tests/common/fixtures/advanced_reboot.py
Labels: automerge

#9476 [action] [PR:9453] [Fix] Fix multi-asic flaky lldp not ready issue
  tests/common/plugins/sanity_check/constants.py
  tests/common/plugins/sanity_check/recover.py
  tests/common/reboot.py
Labels: automerge

#9483 [action] [PR:8068] Add 'any' topology mark to pre and post test
  tests/test_posttest.py
  tests/test_pretest.py
Labels: automerge

#9462 Add config save after TSB to reset device state
  tests/bgp/test_traffic_shift_sup.py
Labels: Request for 202205 branch

#9509 [action] [PR:9470] Revert "Set key "asic0" in single-asic scenerio to keep consistent with multi-asic in function `core_dump_and_config_check`."
  tests/conftest.py
Labels: automerge

#9503 [action] [PR:9418] Decrease the PFC frame counter in PFC watchdog warmboot test
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: automerge

#9500 [action] [PR:9415] Remove Arista products from sku-sensors-data.yml
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: automerge

#9498 [action] [PR:9398] Fix iface_loopback_action test
  tests/iface_loopback_action/iface_loopback_action_helper.py
Labels: automerge

#9497 [action] [PR:9367] Stabilize `test_create_vrf`
  tests/restapi/test_restapi.py
Labels: automerge

#9496 [action] [PR:9367] Stabilize `test_create_vrf`
  tests/restapi/test_restapi.py
Labels: automerge

#9495 [action] [PR:9358] [PTF python3 migration] Modify test_pfcwd PTF script
  ansible/roles/test/files/ptftests/py3/pfc_wd.py
  tests/pfcwd/test_pfcwd_function.py
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: automerge

#9494 [action] [PR:9331] Add try-finally to recovery DUT in module `acl/test_stress_acl.py`.
  tests/acl/test_stress_acl.py
Labels: automerge

#9491 [action] [PR:9303] cisco change for ecn-config-update
  tests/generic_config_updater/test_ecn_config_update.py
Labels: automerge

#9475 [PTF python3 migration] Modify test_vxlan_decap PTF script
  ansible/roles/test/files/ptftests/device_connection.py
  ansible/roles/test/files/ptftests/py3/device_connection.py
  ansible/roles/test/files/ptftests/py3/vxlan-decap.py
  tests/vxlan/test_vxlan_decap.py
Labels: Request for 202205 branch, Request for 202305 branch

#8775 Optimizing testQosSaiHeadroomPoolSize runtime
  tests/saitests/py3/sai_qos_tests.py
Labels: chassis, Request for 202205 branch

#9466 [Snappi] RDMA headroom test fix for 7050CX3
  tests/test_pretest.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch
