Repository sonic-net/sonic-mgmt, pull requests merged in 2023-06, with the labels that each got.

#8470 Fix test_pfcwd_mmu_change
  tests/pfcwd/test_pfcwd_function.py
Labels: Request for 202012 branch, Request for 202205 branch

#8471 [Snappi] Update imports on test_ipip_packet_reorder_with_snappi.py
  tests/snappi/qos/test_ipip_packet_reorder_with_snappi.py
Labels: Request for 202012 branch, Request for 202205 branch

#8472 [dhcp_relay] Refactor test_dhcpv6_relay
  tests/dhcp_relay/test_dhcpv6_relay.py
Labels: Request for 202205 branch

#8473 fix print syntax issue in python2
  tests/saitests/sai_base_test.py
Labels: Request for 202012 branch

#8474 [po2vlan] Skip po2vlan on dualtor testbeds
  tests/common/helpers/portchannel_to_vlan.py
Labels: Request for 202205 branch

#8477 [ansible][nic_simulator] Re-generate gRPC python dependencies in deployment
  ansible/roles/vm_set/tasks/control_nic_simulator.yml
Labels: Request for 202205 branch

#8462 Enhanced bgp_fact to validate NEIGH_STATE_TABLE element 'peerType'
  tests/bgp/test_bgp_fact.py
Labels: Request for 202205 branch

#8485 Enhance cleanup.sh process
  ansible/roles/vm_set/templates/cleanup.sh.j2
Labels: Request for 202012 branch, Request for 202205 branch

#8493 [action] [PR:8354] [action] Enable auto cherry pick.
  .github/workflows/automerge_scan.yml
  .github/workflows/pr_cherrypick_poststep.yml
  .github/workflows/pr_cherrypick_prestep.yml
Labels: automerge

#8492 [action] [PR:8354] [action] Enable auto cherry pick.
  .github/workflows/automerge_scan.yml
  .github/workflows/pr_cherrypick_poststep.yml
  .github/workflows/pr_cherrypick_prestep.yml
Labels: automerge

#8464 Enhance get_crm_resources_fdb_and_ip_route for multi-asic Issue #8425
  tests/crm/test_crm.py
Labels: Request for 202205 branch

#8499 Fix test_replace_mtu failure on topologies without portchannel
  tests/generic_config_updater/test_eth_interface.py
Labels: Request for 202205 branch

#8510 [dualtor-aa][test_host_vlan] fix test set up failure caused by mux toggle on active-active topology
  tests/common/dualtor/mux_simulator_control.py
Labels: Request for 202205 branch

#8519 [action] [PR:8426] [dualtor][active-active][vlan] Fix test setup error on dualtor-aa topo testbed
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#8518 [action] [PR:7333] [packet-chassis]: Fixes required to run test_snmp_lldp test on packet chassis
  ansible/library/minigraph_facts.py
  ansible/library/snmp_facts.py
  ansible/templates/minigraph_dpg_asic.j2
Labels: automerge

#8532 [action] [PR:8471] [Snappi] Update imports on test_ipip_packet_reorder_with_snappi.py
  tests/snappi/qos/test_ipip_packet_reorder_with_snappi.py
Labels: automerge

#8530 [action] [PR:8463] [Snappi] Update MAC address for portchannel interfaces
  tests/common/snappi/snappi_fixtures.py
Labels: automerge

#8529 [action] [PR:8510] [dualtor-aa][test_host_vlan] fix test set up failure caused by mux toggle on active-active topology
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#8527 [action] [PR:8477] [ansible][nic_simulator] Re-generate gRPC python dependencies in deployment
  ansible/roles/vm_set/tasks/control_nic_simulator.yml
Labels: automerge

#8526 [action] [PR:8474] [po2vlan] Skip po2vlan on dualtor testbeds
  tests/common/helpers/portchannel_to_vlan.py
Labels: automerge

#8525 [action] [PR:8472] [dhcp_relay] Refactor test_dhcpv6_relay
  tests/dhcp_relay/test_dhcpv6_relay.py
Labels: automerge

#8524 [action] [PR:8471] [Snappi] Update imports on test_ipip_packet_reorder_with_snappi.py
  tests/snappi/qos/test_ipip_packet_reorder_with_snappi.py
Labels: automerge

#8523 [action] [PR:8470] Fix test_pfcwd_mmu_change
  tests/pfcwd/test_pfcwd_function.py
Labels: automerge

#8522 [action] [PR:8466] Add code owners for "tests/qos" folder
  .github/CODEOWNERS
Labels: automerge

#8521 [action] [PR:8464] Enhance get_crm_resources_fdb_and_ip_route for multi-asic Issue #8425
  tests/crm/test_crm.py
Labels: automerge

#8520 [action] [PR:8463] [Snappi] Update MAC address for portchannel interfaces
  tests/common/snappi/snappi_fixtures.py
Labels: automerge

#8531 [action] [PR:8466] Add code owners for "tests/qos" folder
  .github/CODEOWNERS
Labels: automerge

#8528 [action] [PR:8499] Fix test_replace_mtu failure on topologies without portchannel
  tests/generic_config_updater/test_eth_interface.py
Labels: automerge

#8512 Watchdog reboot skip
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
  tests/platform_tests/test_reboot.py
Labels: Request for 202012 branch, Request for 202205 branch

#8537 Fix conditional mark query Github failed issue
  tests/common/plugins/conditional_mark/__init__.py
  tests/common/plugins/conditional_mark/issue.py
Labels: Request for 202012 branch, Request for 202205 branch

#8543 Ignore MAC learning event before disabling MAC learning
  tests/platform_tests/conftest.py
Labels: Request for 202205 branch

#8542 [minigraph] Add cloud type to the minigraph
  ansible/templates/minigraph_meta.j2
Labels: Request for 202205 branch

#8441 [pretest] add gbsyncd in DEFAULT_ASIC_SERVICES
  tests/common/devices/multi_asic.py
  tests/common/devices/sonic.py
Labels: Request for 202205 branch

#8548 [action] [PR:8543] Ignore MAC learning event before disabling MAC learning
  tests/platform_tests/conftest.py
Labels: automerge

#8547 [action] [PR:8509] Stabilize `test_po_update`
  tests/common/devices/sonic_asic.py
  tests/pc/test_po_update.py
Labels: automerge

#8566 [dualtor][active-active] Fix `validate_active_active_dualtor_setup`
  tests/common/dualtor/dual_tor_utils.py
  tests/common/fixtures/ptfhost_utils.py
Labels: Request for 202205 branch

#8578 [topo][m0] Add m0-2vlan topo
  ansible/roles/eos/templates/m0-2vlan-m1.j2
  ansible/roles/eos/templates/m0-2vlan-mx.j2
  ansible/vars/topo_m0-2vlan.yml
  ansible/veos
Labels: Request for 202205 branch

#8488 [pfcwd][gcu] Add GCU testcases for pfcwd enable/disable scenario
  tests/generic_config_updater/test_pfcwd_interval.py
  tests/generic_config_updater/test_pfcwd_status.py
Labels: Test gap, generic-config-updater

#8590 [action] [PR:8578] [topo][m0] Add m0-2vlan topo
  ansible/roles/eos/templates/m0-2vlan-m1.j2
  ansible/roles/eos/templates/m0-2vlan-mx.j2
  ansible/vars/topo_m0-2vlan.yml
  ansible/veos
Labels: automerge

#7981 Handle MegaBits speed for show int status <interface> output in test_update_speed testcase
  tests/generic_config_updater/test_eth_interface.py
Labels: Request for 202205 branch

#8589 [action] [PR:8566] [dualtor][active-active] Fix `validate_active_active_dualtor_setup`
  tests/common/dualtor/dual_tor_utils.py
  tests/common/fixtures/ptfhost_utils.py
Labels: automerge

#7294 Wait until DB_KEYS are restored after PMON-PSUD process restart
  tests/platform_tests/daemon/test_psud.py
Labels: Request for 202205 branch

#8515 [Snappi] Validate that switch ignores PFC frame received with no bit set in the class enable vector
  tests/common/snappi/common_helpers.py
  tests/snappi/pfc/files/helper.py
  tests/snappi/pfc/test_pfc_pause_unset_bit_enable_vector.py
Labels: Request for 202012 branch, Request for 202205 branch

#8614 [action] [PR:5305] Chassis: Get minimum and maximum temperature from platform.json
  tests/platform_tests/api/test_thermal.py
Labels: automerge

#8613 [action] [PR:8396] Increase the wait time for http server to come up
  tests/mvrf/test_mgmtvrf.py
Labels: automerge

#8611 [Snappi] Update PFC helper.py
  tests/snappi/pfc/files/helper.py
Labels: Request for 202012 branch, Request for 202205 branch

#8623 [route flap] [multi-asic] [chassis] change filter method to filter out external nexthops
  tests/route/test_route_flap.py
Labels: regression, Request for 202205 branch

#8636 [action] [PR:8623] [route flap] [multi-asic] [chassis] change filter method to filter out external nexthops
  tests/route/test_route_flap.py
Labels: automerge

#8635 [action] [PR:8515] [Snappi] Validate that switch ignores PFC frame received with no bit set in the class enable vector
  tests/common/snappi/common_helpers.py
  tests/snappi/pfc/files/helper.py
  tests/snappi/pfc/test_pfc_pause_unset_bit_enable_vector.py
Labels: automerge

#8634 [action] [PR:8515] [Snappi] Validate that switch ignores PFC frame received with no bit set in the class enable vector
  tests/common/snappi/common_helpers.py
  tests/snappi/pfc/files/helper.py
  tests/snappi/pfc/test_pfc_pause_unset_bit_enable_vector.py
Labels: automerge

#8633 [action] [PR:8408] fix dual tor issue of test_bgp_dual_asn.py
  tests/bgp/test_bgp_dual_asn.py
Labels: automerge

#8641 [acl] Skip acl egress ipv6 for 7215
  tests/common/plugins/conditional_mark/tests_mark_conditions_acl.yaml
Labels: Request for 202205 branch

#8601 Skip test_replace_fec on M0/Mx topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch

#8654 Enabling bfd anmd vxlan ecmp tests for Mlnx 2700
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/vxlan/test_vxlan_ecmp.py
Labels: Request for 202205 branch

#8667 [CI/CD,Elastictest] specify specific_param for macsec pr tests
  .azure-pipelines/pr_test_scripts.yaml
Labels: Request for 202205 branch

#8602 Adding additonal new portSpeedCableLength to qos yaml
  tests/qos/files/qos.yml
Labels: chassis, Request for 202205 branch

#8646 [T2 chassis] platform and snmp tests that uses pdu_controller to run on sup for chassis
  tests/common/plugins/pdu_controller/__init__.py
  tests/common/utilities.py
  tests/platform_tests/test_platform_info.py
  tests/platform_tests/test_power_off_reboot.py
  tests/platform_tests/test_reboot.py
Labels: Request for 202205 branch

#8681 [action] [PR:8641] [acl] Skip acl egress ipv6 for 7215
  tests/common/plugins/conditional_mark/tests_mark_conditions_acl.yaml
Labels: automerge

#8679 [action] [PR:8601] Skip test_replace_fec on M0/Mx topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#8678 [action] [PR:8585] EOS-T2-Config-Template: Fix Portchannel min-links config
  ansible/roles/eos/templates/t2-core.j2
  ansible/roles/eos/templates/t2-leaf.j2
  ansible/roles/eos/templates/t2-vs-core.j2
  ansible/roles/eos/templates/t2-vs-leaf.j2
Labels: automerge

#8677 [action] [PR:8586] Defined new T2 Scaled Topology (5LC, 96 Neighbors)
  ansible/vars/topo_t2_5lc-mixed-96.yml
Labels: automerge

#8676 [action] [PR:7597] Add regex for syslog timestamp in extract_log
  ansible/library/extract_log.py
Labels: automerge

#8675 [action] [PR:7597] Add regex for syslog timestamp in extract_log
  ansible/library/extract_log.py
Labels: automerge

#8680 [action] [PR:8628] modify the percentage threshold for snmp memory load case
  tests/snmp/test_snmp_memory.py
Labels: automerge

#8626 [GCU E2E Test] skip test_eth_interface.py::test_replace_fec and test_update_speed
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/generic_config_updater/test_eth_interface.py
Labels: Request for 202205 branch

#8468 Stability of Voq tests (#4951, #4953)
  tests/common/devices/fanout.py
  tests/common/devices/sonic.py
  tests/common/helpers/voq_lag.py
  tests/voq/test_voq_ipfwd.py
  tests/voq/test_voq_nbr.py
Labels: Request for 202205 branch

#8690 [RDMA] Added ixia checker to prevent dualtor settings on ixia testbeds
  ansible/config_sonic_basedon_testbed.yml
Labels: Request for 202012 branch, Request for 202205 branch

#7781 Fix for PID assertion issue - PSUD and CHASSID platform cases
  tests/platform_tests/daemon/test_chassisd.py
  tests/platform_tests/daemon/test_psud.py
Labels: Request for 202205 branch

#6880 Adapting tests to run on T2 chassis by changing rand_one_dut_hostname…
  tests/scp/test_scp_copy.py
Labels: Request for 202205 branch

#8719 [mx] Add xfail condition for mx egress test in 7215 mx
  tests/acl/test_acl.py
  tests/common/plugins/conditional_mark/tests_mark_conditions_acl.yaml
Labels: Request for 202205 branch

#8722 [gcu][m0] Fix gcu/test_vlan_interface failed at m0-2vlan
  tests/generic_config_updater/test_vlan_interface.py
Labels: Request for 202205 branch

#8721 [m0] Optimize test_mark_conditions for m0-2vlan topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch

#8715 [m0][topo] Fix vlan interface error in m0-2vlan topo
  ansible/vars/topo_m0-2vlan.yml
Labels: Request for 202205 branch

#8696 [chassis] skip qos test on other dnx linecards platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: chassis-voq, Request for 202205 branch

#8674 [chassis] accommodate snmp test that uses pdu controller for chassis
  tests/snmp/test_snmp_phy_entity.py
Labels: Request for 202205 branch

#8726 Use systemctl to restart radv
  tests/radv/test_radv_run.py
Labels: Request for 202205 branch

#8716 Restore crm polling interval after module `crm/test_crm.py` running.
  tests/crm/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch

#8718 [acl][m0] Add support for m0-2vlan in test_null_route_helper
  tests/acl/null_route/test_null_route_helper.py
Labels: Request for 202205 branch

#8568 iface_namingmode: Modify show ip route test case using a dummy static route
  .azure-pipelines/pr_test_scripts.yaml
  tests/iface_namingmode/test_iface_namingmode.py
Labels: Request for 202205 branch

#8725 [platform_tests] Fix test_reboot reboot_type passed as interfaces_wait_time
  tests/platform_tests/test_reboot.py
Labels: Request for 202205 branch

#8348 Update ansible tmp path at cfg file
  ansible/ansible.cfg
Labels: Enhancement, Testbed

#8710 Adding additonal new portSpeedCableLength to qos yaml #8602
  tests/qos/files/qos.yml
Labels: chassis

#8760 [action] [PR:8218] Remove skip for test_non_routable_igmp_pkts[vlan_members]
  tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
Labels: automerge

#8757 [action] [PR:8716] Restore crm polling interval after module `crm/test_crm.py` running.
  tests/crm/conftest.py
Labels: automerge

#8756 [action] [PR:8716] Restore crm polling interval after module `crm/test_crm.py` running.
  tests/crm/conftest.py
Labels: automerge

#8755 [action] [PR:8683] update rx_action of pfcwd for the device which enabled tunnel_qos_remap
  tests/pfcwd/test_pfcwd_function.py
Labels: automerge

#8754 [action] [PR:8683] update rx_action of pfcwd for the device which enabled tunnel_qos_remap
  tests/pfcwd/test_pfcwd_function.py
Labels: automerge

#8753 [action] [PR:8670] fix get psu status issue
  tests/platform_tests/test_platform_info.py
Labels: automerge

#8752 [action] [PR:8348] Update ansible tmp path at cfg file
  ansible/ansible.cfg
Labels: automerge

#8751 [action] [PR:8348] Update ansible tmp path at cfg file
  ansible/ansible.cfg
Labels: automerge

#8750 [action] [PR:8690] [RDMA] Added ixia checker to prevent dualtor settings on ixia testbeds
  ansible/config_sonic_basedon_testbed.yml
Labels: automerge

#8759 [action] [PR:8172] TestAclReboot test fix for Nokia-400G-T2 chassis
  tests/acl/test_acl.py
Labels: automerge

#8758 [action] [PR:7927] Check stress package existence on dut and do apt update followed by stress package install
  tests/memory_checker/test_memory_checker.py
Labels: automerge

#8771 [action] [PR:8725] [platform_tests] Fix test_reboot reboot_type passed as interfaces_wait_time
  tests/platform_tests/test_reboot.py
Labels: automerge

#8768 [action] [PR:8715] [m0][topo] Fix vlan interface error in m0-2vlan topo
  ansible/vars/topo_m0-2vlan.yml
Labels: automerge

#8767 [action] [PR:8718] [acl][m0] Add support for m0-2vlan in test_null_route_helper
  tests/acl/null_route/test_null_route_helper.py
Labels: automerge

#8766 [action] [PR:8674] [chassis] accommodate snmp test that uses pdu controller for chassis
  tests/snmp/test_snmp_phy_entity.py
Labels: automerge

#8765 [action] [PR:8626] [GCU E2E Test] skip test_eth_interface.py::test_replace_fec and test_update_speed
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/generic_config_updater/test_eth_interface.py
Labels: automerge

#8770 [action] [PR:8722] [gcu][m0] Fix gcu/test_vlan_interface failed at m0-2vlan
  tests/generic_config_updater/test_vlan_interface.py
Labels: automerge

#8769 [action] [PR:8719] [mx] Add xfail condition for mx egress test in 7215 mx
  tests/acl/test_acl.py
  tests/common/plugins/conditional_mark/tests_mark_conditions_acl.yaml
Labels: automerge

#8736 Fix for issue 8704
  tests/common/devices/sonic_asic.py
Labels: Request for 202205 branch

#8772 [action] [PR:8726] Use systemctl to restart radv
  tests/radv/test_radv_run.py
Labels: automerge

#8781 Disable service warm_restart after test_service_warm_restart running
  tests/platform_tests/test_service_warm_restart.py
Labels: Request for 202205 branch

#8744 Add a function to compare running config.
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch

#8784 Remove key `WARM_RESTART` after module `bgp/test_bgp_slb.py` running.
  tests/bgp/templates/del_warm_restart_config.json
  tests/bgp/test_bgp_slb.py
Labels: Request for 202012 branch, Request for 202205 branch

#8665 [test_add_rack] Skip clet test
  tests/configlet/test_add_rack.py
Labels: Request for 202205 branch
