Repository sonic-net/sonic-mgmt, pull requests merged in 2023-11, with the labels that each got.

#10537 [action] [PR:10211] [testfix] stress_test_routes. Added syslog ignore
  tests/stress/test_stress_routes.py
Labels: automerge

#10539 [BUGFIX] Fix the wait time for `config_reload` function
  tests/common/config_reload.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#10551 [action] [PR:10227] Handle eth1-midplane being a kernel intf altname
  tests/cacl/test_cacl_application.py
Labels: automerge

#10549 [action] [PR:10237] New Testcases for route_consistency
  tests/route/test_route_consistency.py
Labels: automerge

#10548 [action] [PR:10342] Fix for test_crm_acl_entry test and py3 fix for API: port_on_asic()
  tests/common/devices/sonic_asic.py
  tests/crm/test_crm.py
Labels: automerge

#10547 [action] [PR:10345] test_snmp_link_local_ip : wait for interfaces to be up after config reload
  tests/snmp/test_snmp_link_local.py
Labels: automerge

#10545 [action] [PR:9417] Skip certain voq tests when ports to T3 VM's are not available in t2 min topology
  tests/voq/test_voq_ipfwd.py
Labels: automerge

#10542 [action] [PR:10539] [BUGFIX] Fix the wait time for `config_reload` function
  tests/common/config_reload.py
Labels: automerge

#10536 Ignore orchagent stuck error log in route perf test
  tests/route/test_route_perf.py
Labels: Request for 202305 branch, Approved for 202305 branch

#10562 [action] [PR:10555] [dualtor] Improve sanity check
  tests/common/devices/sonic.py
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#10560 [action] [PR:10536] Ignore orchagent stuck error log in route perf test
  tests/route/test_route_perf.py
Labels: automerge

#10512 Fix nightly test for EXO
  tests/acl/test_acl_outer_vlan.py
Labels: Request for 202305 branch

#10558 hdrm size test case changes, after generate new hdrm size test param
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch, Request for 202305 branch

#10567 [action] [PR:10540] ignore DEBUG systemd message in show_techsupport case module
  tests/show_techsupport/conftest.py
Labels: automerge

#10566 [action] [PR:10525] [Mellanox] Fix testQosSaiDwrr issue
  tests/saitests/py3/sai_base_test.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10568 [action] [PR:10512] Fix nightly test for EXO
  tests/acl/test_acl_outer_vlan.py
Labels: automerge

#10590 [action] [PR:10248] Cisco-8000: Return from cisco qos param gen if the current platform doesn't support param gen yet.
  tests/qos/files/cisco/qos_param_generator.py
Labels: automerge

#10588 [action] [PR:10245] enable pfc-wd testing for profiles using static_th
  tests/pfcwd/test_pfcwd_function.py
Labels: automerge

#10587 [action] [PR:10236] Enable Parallel announcement/withdrawal of routes for T2 topologies
  ansible/library/announce_routes.py
Labels: automerge

#10585 [action] [PR:10230] [test_chassisd] wait critical processes to come up in test setup
  tests/platform_tests/daemon/test_chassisd.py
Labels: automerge

#10584 [action] [PR:10224] [Snappi] Enable safe reboot on snappi_tests reboot cases
  tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/pfc/test_pfc_pause_lossy_with_snappi.py
  tests/snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py
Labels: automerge

#10583 [action] [PR:10221] [Snappi] Allow snappi_tests to run from master branch on other branch images
  tests/common/snappi_tests/common_helpers.py
Labels: automerge

#10609 [action] [PR:10482] Fix the portchannel_on_asic() method to handle asic with no portchannels
  tests/common/devices/sonic_asic.py
Labels: automerge

#10607 [action] [PR:10365] Select only ports belonging to same asic - chassis-packet
  ansible/roles/test/files/ptftests/fib_test.py
  ansible/roles/test/files/ptftests/py3/hash_test.py
Labels: automerge

#10606 [action] [PR:10363] Skip override config multi-asic testing for single-asic platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10603 [action] [PR:10349] Fix voq test for py3
  ansible/roles/test/files/ptftests/py3/voq.py
Labels: automerge

#10602 [action] [PR:10338] Update class LossyQueueVoqTest to handle dst_port in port-channel
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10601 [action] [PR:10329] Fix the commented import
  tests/dualtor_io/test_normal_op.py
Labels: automerge

#10599 [action] [PR:10305] Enhance PFC watchdog log analyzer to check debug information on a per-vendor basis
  tests/pfcwd/files/pfcwd_helper.py
  tests/pfcwd/test_pfcwd_all_port_storm.py
  tests/pfcwd/test_pfcwd_function.py
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: automerge

#10598 [action] [PR:10304] Fix test_bgpmon_v6 to use asic router_mac
  tests/bgp/test_bgpmon_v6.py
Labels: automerge

#10593 [action] [PR:10271] Make acl test more robust in checking syslog
  tests/acl/test_acl.py
Labels: automerge

#10592 [action] [PR:10252] Skip dualtor in test_acl_outer_vlan
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10589 [action] [PR:10247] [tests/route]: Use minigraph_ptf_indices to get ptf port indices
  tests/route/test_route_perf.py
Labels: automerge

#10580 [action] [PR:10218] New Test Cases for Chassis DB cleanup when asic comes up PR (sonic-buildimage/pull/16213)
  tests/voq/test_voq_chassis_app_db_consistency.py
Labels: automerge

#10577 [action] [PR:10162] Fixed log handling issues on fast/warm upgrade test
  tests/platform_tests/conftest.py
Labels: automerge

#10576 [action] [PR:10146] Updating ingress drop counters for 100G_120k profile in qos
  tests/qos/files/qos_params.j2c.yaml
Labels: automerge

#10575 [action] [PR:10116] [TACACS] Ensure tacacs server running after UT stop it.
  tests/tacacs/test_accounting.py
  tests/tacacs/test_authorization.py
  tests/tacacs/utils.py
Labels: automerge

#10574 [action] [PR:10115] [qos]Fix issue: 'dict' object has no attribute 'append'
  tests/qos/qos_sai_base.py
Labels: automerge

#10608 Use golden config to recover testbed when sanity check failed
  tests/common/plugins/sanity_check/recover.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#10615 [action] [PR:8199] [tests/copp]: Update copp mgmt tests to support new rate-limits
  ansible/roles/test/files/ptftests/py3/copp_tests.py
  tests/copp/test_copp.py
Labels: automerge

#10611 [action] [PR:10522] skip box tb in setup of test_override_config_table_masic
  tests/override_config_table/test_override_config_table_masic.py
Labels: automerge

#10570 [action] [PR:10558] hdrm size test case changes, after generate new hdrm size test param
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10563 Fix tunnel dscp to pg mapping test
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202305 branch

#10613 [sanity-check][dualtor] Retrieve the mux status in each retry
  tests/common/plugins/sanity_check/checks.py
Labels: Request for 202205 branch, Request for 202305 branch

#10616 [action] [PR:10563] Fix tunnel dscp to pg mapping test
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10164 New testcase for pktgen testing
  ansible/library/show_interface.py
  tests/test_pktgen.py
Labels: Request for 202205 branch

#10600 [action] [PR:10314] [chassis] skip test_route_flow_counter.py for t2
  tests/flow_counter/flow_counter_utils.py
Labels: automerge

#10595 [action] [PR:10273] Updated BGP test template
  tests/bgp/templates/bgp_no_export.j2
Labels: automerge

#10610 [action] [PR:10522] skip box tb in setup of test_override_config_table_masic
  tests/override_config_table/test_override_config_table_masic.py
Labels: automerge

#10623 [action] [PR:9060] Adding watchdog parameter for cisco-8111 platform
  tests/platform_tests/api/watchdog.yml
Labels: automerge

#10622 [override_config] Remove skip for override config tests in tests_mark_conditions.yaml
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch, Request for 202305 branch

#10624 [action] [PR:10612] Enhance restore_bgp_suppress_fib to check status first
  tests/bgp/test_bgp_suppress_fib.py
Labels: automerge

#10627 Fix key Error in get_queue_scheduler_name
  tests/saitests/py3/sai_base_test.py
Labels: Request for 202205 branch, Request for 202305 branch

#10550 [action] [PR:10237] New Testcases for route_consistency
  tests/route/test_route_consistency.py
Labels: automerge

#10636 [action] [PR:10627] Fix key Error in get_queue_scheduler_name
  tests/saitests/py3/sai_base_test.py
Labels: automerge

#10605 [action] [PR:10363] Skip override config multi-asic testing for single-asic platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10597 [action] [PR:10304] Fix test_bgpmon_v6 to use asic router_mac
  tests/bgp/test_bgpmon_v6.py
Labels: automerge

#10596 [action] [PR:10273] Updated BGP test template
  tests/bgp/templates/bgp_no_export.j2
Labels: automerge

#10591 [action] [PR:10248] Cisco-8000: Return from cisco qos param gen if the current platform doesn't support param gen yet.
  tests/qos/files/cisco/qos_param_generator.py
Labels: automerge

#10582 [action] [PR:10221] [Snappi] Allow snappi_tests to run from master branch on other branch images
  tests/common/snappi_tests/common_helpers.py
Labels: automerge

#10579 [action] [PR:10218] New Test Cases for Chassis DB cleanup when asic comes up PR (sonic-buildimage/pull/16213)
  tests/voq/test_voq_chassis_app_db_consistency.py
Labels: automerge

#10578 [action] [PR:10162] Fixed log handling issues on fast/warm upgrade test
  tests/platform_tests/conftest.py
Labels: automerge

#10573 [action] [PR:10115] [qos]Fix issue: 'dict' object has no attribute 'append'
  tests/qos/qos_sai_base.py
Labels: automerge

#10572 [action] [PR:10105] use a custom table type for stress test
  tests/acl/templates/acltb_test_stress_acl_table.j2
Labels: automerge

#10561 [action] [PR:10555] [dualtor] Improve sanity check
  tests/common/devices/sonic.py
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#10553 [action] [PR:10206] [chassis] [MA] Route flap fix
  tests/common/devices/multi_asic.py
  tests/route/test_route_flap.py
Labels: automerge

#10552 [action] [PR:10227] Handle eth1-midplane being a kernel intf altname
  tests/cacl/test_cacl_application.py
Labels: automerge

#10546 [action] [PR:10345] test_snmp_link_local_ip : wait for interfaces to be up after config reload
  tests/snmp/test_snmp_link_local.py
Labels: automerge

#10543 [action] [PR:10539] [BUGFIX] Fix the wait time for `config_reload` function
  tests/common/config_reload.py
Labels: automerge

#10604 [action] [PR:10349] Fix voq test for py3
  ansible/roles/test/files/ptftests/py3/voq.py
Labels: automerge

#10635 [action] [PR:10627] Fix key Error in get_queue_scheduler_name
  tests/saitests/py3/sai_base_test.py
Labels: automerge

#10594 [action] [PR:10271] Make acl test more robust in checking syslog
  tests/acl/test_acl.py
Labels: automerge

#10637 Ignore telemetry container in loganalyzer check
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202305 branch

#10642 [action] [PR:8097] Add a test case to verify that BGP packets use queue7
  docs/testplan/BGP-queue-test-plan.md
  tests/bgp/test_bgp_queue.py
Labels: automerge

#10634 Fix `Unknown header type` in drop counter test
  tests/drop_packets/drop_packets.py
  tests/drop_packets/test_drop_counters.py
Labels: Request for 202205 branch, Request for 202305 branch

#10647 [action] [PR:10634] Fix `Unknown header type` in drop counter test
  tests/drop_packets/drop_packets.py
  tests/drop_packets/test_drop_counters.py
Labels: automerge

#10656 [test_qos_sai] Start the mux on the upper ToR in teardown
  tests/qos/qos_sai_base.py
Labels: Request for 202205 branch, Request for 202305 branch

#10663 [action] [PR:10656] [test_qos_sai] Start the mux on the upper ToR in teardown
  tests/qos/qos_sai_base.py
Labels: automerge

#10657 [dualtor] Add `mux` to the critical service list to enable sanity check
  tests/common/devices/multi_asic.py
Labels: Request for 202205 branch, Request for 202305 branch

#10668 [action] [PR:10657] [dualtor] Add `mux` to the critical service list to enable sanity check
  tests/common/devices/multi_asic.py
Labels: automerge

#10667 [action] [PR:10657] [dualtor] Add `mux` to the critical service list to enable sanity check
  tests/common/devices/multi_asic.py
Labels: automerge

#10673 Fix Python3 syntax issue in test_custom_acl_table.py
  tests/acl/custom_acl_table/test_custom_acl_table.py
Labels: Request for 202305 branch

#10677 Remove scapy mask on chksum for IPv6 Header
  ansible/roles/test/files/ptftests/py3/hash_test.py
Labels: Request for 202205 branch, Approved for 202205 branch, Request for 202305 branch, Approved for 202305 branch

#10671 [warmboot][teardown] force reset warmboot system flag after warmboot tests
  tests/common/fixtures/advanced_reboot.py
Labels: Request for 202305 branch

#10684 [dualtor] fix command to get dualtor_ports
  tests/common/devices/multi_asic.py
Labels: Request for 202205 branch, Request for 202305 branch

#10675 Skip test_pktgen.py in non-Cisco platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch, Request for 202305 branch

#10688 [action] [PR:10675] Skip test_pktgen.py in non-Cisco platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10687 [action] [PR:10673] Fix Python3 syntax issue in test_custom_acl_table.py
  tests/acl/custom_acl_table/test_custom_acl_table.py
Labels: automerge

#10681 [action] [PR:10677] Remove scapy mask on chksum for IPv6 Header
  ansible/roles/test/files/ptftests/py3/hash_test.py
Labels: automerge

#10680 [action] [PR:10677] Remove scapy mask on chksum for IPv6 Header
  ansible/roles/test/files/ptftests/py3/hash_test.py
Labels: automerge

#10691 [dualtor] Add toggle retries
  tests/common/dualtor/mux_simulator_control.py
Labels: Request for 202205 branch, Request for 202305 branch

#10686 Fix TypeError in check_sysfs
  tests/platform_tests/mellanox/check_sysfs.py
Labels: Request for 202205 branch, Approved for 202205 branch, Request for 202305 branch, Approved for 202305 branch

#10697 Fix suppress fib failure
  tests/bgp/test_bgp_suppress_fib.py
Labels: Request for 202305 branch, Approved for 202305 branch

#10701 [action] [PR:10686] Fix TypeError in check_sysfs
  tests/platform_tests/mellanox/check_sysfs.py
Labels: automerge

#10700 [action] [PR:10691] [dualtor] Add toggle retries
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#10641 [action] [PR:8097] Add a test case to verify that BGP packets use queue7
  docs/testplan/BGP-queue-test-plan.md
  tests/bgp/test_bgp_queue.py
Labels: automerge

#10581 [action] [PR:10221] [Snappi] Allow snappi_tests to run from master branch on other branch images
  tests/common/snappi_tests/common_helpers.py
Labels: automerge

#10703 [action] [PR:10697] Fix suppress fib failure
  tests/bgp/test_bgp_suppress_fib.py
Labels: automerge

#10689 [dualtor_io] wait for `pmon` docker before verification in ToR failure cases
  tests/common/dualtor/tor_failure_utils.py
  tests/dualtor_io/test_tor_failure.py
Labels: Request for 202305 branch

#10709 [action] [PR:10684] [dualtor] fix command to get dualtor_ports
  tests/common/devices/multi_asic.py
Labels: automerge

#10708 [action] [PR:10684] [dualtor] fix command to get dualtor_ports
  tests/common/devices/multi_asic.py
Labels: automerge

#10679 [dualtor-io] cleanup and collect pcap file
  tests/common/dualtor/data_plane_utils.py
  tests/common/dualtor/dual_tor_io.py
  tests/dualtor_io/conftest.py
Labels: Request for 202205 branch, Request for 202305 branch

#10710 [action] [PR:10679] [dualtor-io] cleanup and collect pcap file
  tests/common/dualtor/data_plane_utils.py
  tests/common/dualtor/dual_tor_io.py
  tests/dualtor_io/conftest.py
Labels: automerge

#10711 [action] [PR:10679] [dualtor-io] cleanup and collect pcap file
  tests/common/dualtor/data_plane_utils.py
  tests/common/dualtor/dual_tor_io.py
  tests/dualtor_io/conftest.py
Labels: automerge

#10728 [action] [PR:10207] COPP: Update the PPS max limit to allow bit more tolerance
  ansible/roles/test/files/ptftests/py3/copp_tests.py
  tests/copp/test_copp.py
Labels: automerge

#10057 Add QOS Params for Cisco 8111 Platform
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/files/qos_params.gr.yaml
Labels: Request for 202205 branch, Request for 202305 branch

#10527 [Mellanox] Fix qos sai issues on dualtor setup
  tests/qos/files/mellanox/qos_param_generator.py
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: Request for 202305 branch

#10734 [action] [PR:10695] [lag] Fix `test_lag_2` route_check failures
  tests/pc/test_lag_2.py
Labels: automerge

#10732 Macsec fix for portchannel workaround only for Broadcom dnx platforms
  tests/macsec/macsec_config_helper.py
Labels: Request for 202205 branch, Request for 202305 branch

#10715 Add wait until in stress acl test
  tests/acl/test_stress_acl.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#10742 [action] [PR:10163] ARP in sai_qos_tests.py for all test port IDs
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10746 [action] [PR:10057] Add QOS Params for Cisco 8111 Platform
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/files/qos_params.gr.yaml
Labels: automerge

#10745 [action] [PR:10477] Adding the new function: sai_thrift_read_pg_occupancy.
  tests/saitests/py3/switch.py
Labels: automerge

#10751 [action] [PR:10715] Add wait until in stress acl test
  tests/acl/test_stress_acl.py
Labels: automerge

#10747 Intermittent Failure due to coredump_gen_handler process execution time on test_auto_techsupport.py Test Case test_rate_limit_interval
  tests/show_techsupport/test_auto_techsupport.py
Labels: Request for 202205 branch, Request for 202305 branch

#10707 [memory_checker/test_memory_checker] - Increase timeout for memory checker test
  tests/memory_checker/test_memory_checker.py
Labels: Request for 202205 branch, Request for 202305 branch

#10739 [dualtor] Add retry logic for `mux_simulator_control` post requests
  tests/common/dualtor/mux_simulator_control.py
Labels: Request for 202305 branch

#10756 [GCU Testing] Fix is_valid_platform_and_version
  tests/generic_config_updater/gu_utils.py
Labels: Request for 202305 branch

#10743 enhance test_max_numbers_of_sub_ports for python3
  tests/sub_port_interfaces/test_sub_port_interfaces.py
Labels: Request for 202305 branch

#10759 [action] [PR:10747] Intermittent Failure due to coredump_gen_handler process execution time on test_auto_techsupport.py Test Case test_rate_limit_interval
  tests/show_techsupport/test_auto_techsupport.py
Labels: automerge

#10757 [action] [PR:10707] [memory_checker/test_memory_checker] - Increase timeout for memory checker test
  tests/memory_checker/test_memory_checker.py
Labels: automerge

#10765 [sanity check] Fix list clear attribute error
  tests/common/plugins/sanity_check/checks.py
Labels: Request for 202305 branch

#10731 fix ip_inip testcase ignore ttl condition
  ansible/roles/test/files/ptftests/py3/hash_test.py
Labels: Request for 202205 branch, Request for 202305 branch

#10775 [action] [PR:9812] Macsec type7 support for CAK keys
  tests/macsec/macsec_config_helper.py
  tests/macsec/profile.json
Labels: automerge

#10762 [202205][bgp] Skip test_bgp_queue for m0/mx
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Approved for 202205 branch

#10797 [action] [PR:10765] [sanity check] Fix list clear attribute error
  tests/common/plugins/sanity_check/checks.py
Labels: automerge

#10795 [action] [PR:10743] enhance test_max_numbers_of_sub_ports for python3
  tests/sub_port_interfaces/test_sub_port_interfaces.py
Labels: automerge

#10794 [action] [PR:10739] [dualtor] Add retry logic for `mux_simulator_control` post requests
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#10792 [action] [PR:10732] Macsec fix for portchannel workaround only for Broadcom dnx platforms
  tests/macsec/macsec_config_helper.py
Labels: automerge

#10793 [action] [PR:10732] Macsec fix for portchannel workaround only for Broadcom dnx platforms
  tests/macsec/macsec_config_helper.py
Labels: automerge

#10791 [action] [PR:10731] fix ip_inip testcase ignore ttl condition
  ansible/roles/test/files/ptftests/py3/hash_test.py
Labels: automerge

#10789 [action] [PR:10689] [dualtor_io] wait for `pmon` docker before verification in ToR failure cases
  tests/common/dualtor/tor_failure_utils.py
  tests/dualtor_io/test_tor_failure.py
Labels: automerge

#10788 [action] [PR:10671] [warmboot][teardown] force reset warmboot system flag after warmboot tests
  tests/common/fixtures/advanced_reboot.py
Labels: automerge

#10787 [action] [PR:10622] [override_config] Remove skip for override config tests in tests_mark_conditions.yaml
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10786 [action] [PR:10622] [override_config] Remove skip for override config tests in tests_mark_conditions.yaml
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10785 [action] [PR:10620] Fix setup_env() from test_override_config_table.py and test_override_config_table_masic.py to run for each duthost
  tests/override_config_table/test_override_config_table.py
  tests/override_config_table/test_override_config_table_masic.py
Labels: automerge

#10784 [action] [PR:10620] Fix setup_env() from test_override_config_table.py and test_override_config_table_masic.py to run for each duthost
  tests/override_config_table/test_override_config_table.py
  tests/override_config_table/test_override_config_table_masic.py
Labels: automerge

#10783 [action] [PR:10527] [Mellanox] Fix qos sai issues on dualtor setup
  tests/qos/files/mellanox/qos_param_generator.py
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: automerge

#10782 [action] [PR:10503] [Mellanox]Update sensors data for x86_64-mlnx_msn4600c-r0
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: automerge

#10781 [action] [PR:10250] Update the fwutil test case
  tests/platform_tests/fwutil/conftest.py
Labels: automerge

#10780 [action] [PR:10250] Update the fwutil test case
  tests/platform_tests/fwutil/conftest.py
Labels: automerge

#10779 [action] [PR:10250] Update the fwutil test case
  tests/platform_tests/fwutil/conftest.py
Labels: automerge

#10778 [action] [PR:10164] New testcase for pktgen testing
  ansible/library/show_interface.py
  tests/test_pktgen.py
Labels: automerge

#10777 [action] [PR:9072] Add cisco HwSkus to qos-sai, gb list.
  ansible/group_vars/sonic/variables
Labels: automerge

#10804 [action] [PR:9897] [chassis] fix flakiness in test_chassisd.py
  tests/platform_tests/daemon/test_chassisd.py
Labels: automerge

#10803 [action] [PR:9824] [Mellanox] Fix issue: fix typo and remove unused sensor for 4600C
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: automerge

#10802 [action] [PR:9637] Skip test_everflow_per_interface.py for ipv6 variant on broadcom-dnx
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10801 [action] [PR:9637] Skip test_everflow_per_interface.py for ipv6 variant on broadcom-dnx
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10800 [action] [PR:9126] TestbedProcessing script fixes and improvements
  ansible/TestbedProcessing.py
Labels: automerge

#10799 [action] [PR:6554] Bgp authentication
  .gitignore
  docs/testplan/BGP-Authentication.md
  tests/bgp/test_bgp_authentication.py
Labels: automerge
