Repository sonic-net/sonic-mgmt, pull requests merged in 2023-10, with the labels that each got.

#10168 Fix Cacl test fixes issue 9864
  tests/cacl/test_cacl_application.py
Labels: Request for 202205 branch

#9847 [Snappi] Update test PFC pause frame functionality to include DUT counter polling
  tests/common/snappi_tests/common_helpers.py
  tests/common/snappi_tests/snappi_test_params.py
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/pfc/files/helper.py
  tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#10146 Updating ingress drop counters for 100G_120k profile in qos
  tests/qos/files/qos_params.j2c.yaml
Labels: chassis, Request for 202205 branch, Request for 202305 branch

#10229 Fix mux-simulator script not starting due to Werkzeug update
  ansible/roles/vm_set/tasks/control_mux_simulator.yml
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#10231 [action] [PR:10229] Fix mux-simulator script not starting due to Werkzeug update
  ansible/roles/vm_set/tasks/control_mux_simulator.yml
Labels: automerge

#10232 [action] [PR:10229] Fix mux-simulator script not starting due to Werkzeug update
  ansible/roles/vm_set/tasks/control_mux_simulator.yml
Labels: automerge

#10076 Fix test issues in verify_dut_health.py
  tests/platform_tests/verify_dut_health.py
Labels: Request for 202205 branch, Request for 202305 branch

#10224 [Snappi] Enable safe reboot on snappi_tests reboot cases
  tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/pfc/test_pfc_pause_lossy_with_snappi.py
  tests/snappi_tests/pfcwd/test_pfcwd_basic_with_snappi.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#10192 [qos] reduce execution time of ping command
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202305 branch

#10172 [QoS] DSCP Queue IP-IP Packet Mapping Logging Fix
  tests/common/config_reload.py
  tests/common/helpers/ptf_tests_helper.py
  tests/common/snappi_tests/common_helpers.py
  tests/common/utilities.py
  tests/qos/test_qos_dscp_mapping.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#10200 [qos] support t0-120 qos sai test
  tests/qos/qos_sai_base.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch, Request for 202305 branch

#10226 limit the modification of pg_num to only occur on the specific platform to fix testQosSaiHeadroomPoolWatermark failure
  tests/qos/test_qos_sai.py
Labels: Request for 202205 branch, Request for 202305 branch

#10215 [action] [PR:10201] Skip verify_dhcp_relay_pkt_with_no_padding on dualtor testbed
  ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py
Labels: automerge

#9543 Add qos params for cisco Q100 linecard
  tests/qos/files/qos_params.gb.yaml
  tests/qos/files/qos_params.pac.yaml
Labels: Request for 202205 branch, Request for 202305 branch

#10054 Update qos params and add sleep for pgdrop, decrease pkts_num_egr_mem…
  tests/qos/files/qos_params.gb.yaml
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch, Request for 202305 branch

#8479 Add fabric test data for 7800R3AK-36DM2-C36 cards
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC3.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC4.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC5.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC6.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC10.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC3.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC4.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC5.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC6.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC7.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC8.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC9.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC3.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC4.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC5.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC6.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC10.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC3.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC4.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC5.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC6.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC7.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC8.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC9.yaml
  tests/voq/test_fabric_reach.py
Labels: Request for 202205 branch, Request for 202305 branch

#10247 [tests/route]: Use minigraph_ptf_indices to get ptf port indices
  tests/route/test_route_perf.py
Labels: Request for 202305 branch

#10254 [action] [PR:10124] [dualtor_io] Add server to server I/O normal op test
  tests/common/dualtor/data_plane_utils.py
  tests/common/dualtor/dual_tor_io.py
  tests/dualtor_io/test_normal_op.py
Labels: automerge

#10243 Exit pytest with error code 15 if duthosts fixture fails
  tests/conftest.py
  tests/run_tests.sh
Labels: Request for 202012 branch, Request for 202205 branch, Approved for 202012 branch, Approved for 202205 branch, Request for 202305 branch, Approved for 202305 branch

#10262 [action] [PR:10243] Exit pytest with error code 15 if duthosts fixture fails
  tests/conftest.py
  tests/run_tests.sh
Labels: automerge

#10270 [action] [PR:10158] Revert "Cisco-8000 psu led support"
  tests/common/platform/device_utils.py
  tests/platform_tests/cli/test_show_platform.py
Labels: automerge

#10269 [action] [PR:10158] Revert "Cisco-8000 psu led support"
  tests/common/platform/device_utils.py
  tests/platform_tests/cli/test_show_platform.py
Labels: automerge

#10218 New Test Cases for Chassis DB cleanup when asic comes up PR (sonic-buildimage/pull/16213)
  tests/voq/test_voq_chassis_app_db_consistency.py
Labels: Chassis Test Gap, Request for 202205 branch, Request for 202305 branch

#10234 [chassis] make sure test_pfcwd_mmu_change and the fixture it called use same dut
  tests/common/devices/multi_asic.py
  tests/common/dualtor/dual_tor_utils.py
Labels: Request for 202205 branch, Request for 202305 branch

#10259 [dualtor-io][test plan] Add server to server traffic testcases
  docs/testplan/dual_tor/dual_tor_active_active_test_plan.md
  docs/testplan/dual_tor/img/dualtor_server_to_server_traffic.jpeg
Labels: Request for 202205 branch, Request for 202305 branch

#10279 [action] [PR:10259] [dualtor-io][test plan] Add server to server traffic testcases
  docs/testplan/dual_tor/dual_tor_active_active_test_plan.md
  docs/testplan/dual_tor/img/dualtor_server_to_server_traffic.jpeg
Labels: automerge

#10261 [action] [PR:10243] Exit pytest with error code 15 if duthosts fixture fails
  tests/conftest.py
  tests/run_tests.sh
Labels: automerge

#10258 [action] [PR:10081] [testfix] test_cpu_memory_usage_counterpoll threshold change.
  tests/platform_tests/test_cpu_memory_usage.py
Labels: automerge

#10252 Skip dualtor in test_acl_outer_vlan
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch

#10273 Updated BGP test template
  tests/bgp/templates/bgp_no_export.j2
Labels: Request for 202205 branch, Request for 202305 branch

#10278 [action] [PR:10259] [dualtor-io][test plan] Add server to server traffic testcases
  docs/testplan/dual_tor/dual_tor_active_active_test_plan.md
  docs/testplan/dual_tor/img/dualtor_server_to_server_traffic.jpeg
Labels: automerge

#10162 Fixed log handling issues on fast/warm upgrade test
  tests/platform_tests/conftest.py
Labels: Request for 202205 branch, Request for 202305 branch

#9902 [Mellanox] add mock for temperature threshold in psu power threshold
  tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
  tests/platform_tests/mellanox/test_psu_power_threshold.py
Labels: Request for 202305 branch

#9813 fix auto-negotiation test unstable issue
  tests/platform_tests/test_auto_negotiation.py
Labels: Request for 202205 branch, Request for 202305 branch

#7524 Test plan for feature Generic Hash
  docs/testplan/Generic-Hash-test-plan.md
Labels: Test Plan

#10285 [action] [PR:6456] [wr_arp] avoid timeout of connection during wr
  ansible/roles/test/files/ptftests/wr_arp.py
Labels: automerge

#10288 [action] [PR:10229] Fix mux-simulator script not starting due to Werkzeug update
  ansible/roles/vm_set/tasks/control_mux_simulator.yml
Labels: automerge

#10289 [m0][mx] Skip test_acl_outer_vlan for m0/mx
  tests/acl/test_acl_outer_vlan.py
Labels: Request for 202205 branch, Request for 202305 branch

#10297 [action] [PR:10289] [m0][mx] Skip test_acl_outer_vlan for m0/mx
  tests/acl/test_acl_outer_vlan.py
Labels: automerge

#10296 [action] [PR:10289] [m0][mx] Skip test_acl_outer_vlan for m0/mx
  tests/acl/test_acl_outer_vlan.py
Labels: automerge

#10230 [test_chassisd] wait critical processes to come up in test setup
  tests/platform_tests/daemon/test_chassisd.py
Labels: Request for 202205 branch, Request for 202305 branch

#10271 Make acl test more robust in checking syslog
  tests/acl/test_acl.py
Labels: Request for 202205 branch

#10290 [console] Skip test_console_baud_rate in non-ssh console
  tests/dut_console/test_console_baud_rate.py
Labels: Request for 202305 branch

#10302 [action] [PR:10290] [console] Skip test_console_baud_rate in non-ssh console
  tests/dut_console/test_console_baud_rate.py
Labels: automerge

#10313 [action] [PR:9482] Fix dualtor inventory parse error
  tests/common/dualtor/mux_simulator_control.py
  tests/common/dualtor/nic_simulator_control.py
Labels: automerge

#10309 [action] [PR:10197] Exclude unsupported DSCP values
  ansible/roles/test/files/ptftests/py3/IP_decap_test.py
  tests/decap/test_decap.py
Labels: automerge

#10312 [action] [PR:9482] Fix dualtor inventory parse error
  tests/common/dualtor/mux_simulator_control.py
  tests/common/dualtor/nic_simulator_control.py
Labels: automerge

#10304 Fix test_bgpmon_v6 to use asic router_mac
  tests/bgp/test_bgpmon_v6.py
Labels: chassis-packet, Request for 202205 branch, Request for 202305 branch

#10248 Cisco-8000: Return from cisco qos param gen if the current platform doesn't support param gen yet.
  tests/qos/files/cisco/qos_param_generator.py
Labels: Request for 202205 branch, Request for 202305 branch

#9655 Cisco-8000: Modifications to Xoff for Cisco-Q100 platform.
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch, Request for 202305 branch

#10292 [dualtor-io] Add server to server testcases
  tests/common/dualtor/data_plane_utils.py
  tests/common/dualtor/dual_tor_io.py
  tests/dualtor_io/test_normal_op.py
Labels: Request for 202205 branch, Request for 202305 branch

#10324 [action] [PR:10292] [dualtor-io] Add server to server testcases
  tests/common/dualtor/data_plane_utils.py
  tests/common/dualtor/dual_tor_io.py
  tests/dualtor_io/test_normal_op.py
Labels: automerge

#10323 [action] [PR:10054] Update qos params and add sleep for pgdrop, decrease pkts_num_egr_mem…
  tests/qos/files/qos_params.gb.yaml
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10322 [action] [PR:10054] Update qos params and add sleep for pgdrop, decrease pkts_num_egr_mem…
  tests/qos/files/qos_params.gb.yaml
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10320 [action] [PR:9543] Add qos params for cisco Q100 linecard
  tests/qos/files/qos_params.gb.yaml
  tests/qos/files/qos_params.pac.yaml
Labels: automerge

#10321 [action] [PR:9543] Add qos params for cisco Q100 linecard
  tests/qos/files/qos_params.gb.yaml
  tests/qos/files/qos_params.pac.yaml
Labels: automerge

#10325 Revert "Skipping test_nhop_group_member_order_capability for all rele…
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch, Request for 202305 branch

#9921 [syslog/test_logrotate]: Fixed test_logrotate testcase failing due to…
  tests/syslog/test_logrotate.py
Labels: Request for 202305 branch

#10332 [action] [PR:10325] Revert "Skipping test_nhop_group_member_order_capability for all rele…
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10331 [action] [PR:9924] Using uplink ports for qossai testing for O8c48 hwsku
  tests/qos/qos_sai_base.py
Labels: automerge

#10330 [action] [PR:9921] [syslog/test_logrotate]: Fixed test_logrotate testcase failing due to…
  tests/syslog/test_logrotate.py
Labels: automerge

#10314 [chassis] skip test_route_flow_counter.py for t2
  tests/flow_counter/flow_counter_utils.py
Labels: Request for 202205 branch

#8186 [Snappi] Adding Multidut Global Pause RDMA Testcase
  tests/common/snappi_tests/multi_dut_params.py
  tests/common/snappi_tests/snappi_test_params.py
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/multidut/pfc/__init__.py
  tests/snappi_tests/multidut/pfc/files/__init__.py
  tests/snappi_tests/multidut/pfc/files/multidut_helper.py
  tests/snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py
Labels: chassis

#10213 [dualtor][TestWrArp] force reset warmboot flag to `false` in test class teardown
  tests/arp/test_wr_arp.py
Labels: Request for 202205 branch

#10265 [Snappi] Validate ECN marking occurs on DUTs
  tests/common/snappi_tests/common_helpers.py
  tests/common/snappi_tests/read_pcap.py
  tests/common/snappi_tests/snappi_test_params.py
  tests/common/snappi_tests/traffic_flow_config.py
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/ecn/files/helper.py
  tests/snappi_tests/ecn/test_dequeue_ecn_with_snappi.py
  tests/snappi_tests/ecn/test_red_accuracy_with_snappi.py
  tests/snappi_tests/files/helper.py
  tests/snappi_tests/pfc/files/helper.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch

#10340 [action] [PR:10213] [dualtor][TestWrArp] force reset warmboot flag to `false` in test class teardown
  tests/arp/test_wr_arp.py
Labels: automerge

#10339 [action] [PR:10213] [dualtor][TestWrArp] force reset warmboot flag to `false` in test class teardown
  tests/arp/test_wr_arp.py
Labels: automerge

#9572 avoid reading data map while importing
  spytest/utilities/utils.py
Labels: Spytest

#9573 move cache utility apis from profile apis
  spytest/spytest/batch.py
  spytest/spytest/main.py
  spytest/spytest/ordyaml.py
  spytest/spytest/testbed.py
  spytest/utilities/cache.py
  spytest/utilities/profile.py
Labels: Spytest

#10329 Fix the commented import
  tests/dualtor_io/test_normal_op.py
Labels: Request for 202305 branch

#10055 [test_bgp_update_timer] Log the update packets
  tests/bgp/test_bgp_update_timer.py
Labels: Request for 202205 branch, Request for 202305 branch

#10352 Revert "Revert "Cisco-8000 psu led support""
  tests/common/platform/device_utils.py
  tests/platform_tests/cli/test_show_platform.py
Labels: Request for 202205 branch, Request for 202305 branch

#10355 [action] [PR:10161] [Mellanox] skip test_check_sfp_using_ethtool for 202305 release
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10359 Support HWSKU Mellanox-SN4700-O8C48
  ansible/group_vars/sonic/variables
Labels: Request for 202305 branch

#10361 [action] [PR:10352] Revert "Revert "Cisco-8000 psu led support""
  tests/common/platform/device_utils.py
  tests/platform_tests/cli/test_show_platform.py
Labels: automerge

#10360 [action] [PR:10352] Revert "Revert "Cisco-8000 psu led support""
  tests/common/platform/device_utils.py
  tests/platform_tests/cli/test_show_platform.py
Labels: automerge

#10368 [action] [PR:10200] [qos] support t0-120 qos sai test
  tests/qos/qos_sai_base.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10367 [action] [PR:10200] [qos] support t0-120 qos sai test
  tests/qos/qos_sai_base.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10370 [dualtor-io] Remove mux flap check for grpc server failure tests
  tests/dualtor_io/test_grpc_server_failure.py
Labels: Request for 202205 branch, Request for 202305 branch

#10371 [action] [PR:10370] [dualtor-io] Remove mux flap check for grpc server failure tests
  tests/dualtor_io/test_grpc_server_failure.py
Labels: automerge

#10374 [action] [PR:10062] [qos] fix keyerror dst
  tests/saitests/py3/sai_base_test.py
Labels: automerge

#10372 [action] [PR:10370] [dualtor-io] Remove mux flap check for grpc server failure tests
  tests/dualtor_io/test_grpc_server_failure.py
Labels: automerge

#10378 [action] [PR:10192] [qos] reduce execution time of ping command
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10376 [action] [PR:10226] limit the modification of pg_num to only occur on the specific platform to fix testQosSaiHeadroomPoolWatermark failure
  tests/qos/test_qos_sai.py
Labels: automerge

#10338 Update class LossyQueueVoqTest to handle dst_port in port-channel
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202205 branch, Request for 202305 branch, included in internal-2022205

#10369 Fix test_memory_exhaustion failure: DUT did not startup
  tests/platform_tests/test_memory_exhaustion.py
Labels: Request for 202205 branch, Request for 202305 branch

#10373 skip warm reboot related cases on 202305 branch for 7060
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch

#9417 Skip certain voq tests when ports to T3 VM's are not available in t2 min topology
  tests/voq/test_voq_ipfwd.py
Labels: Request for 202205 branch

#10389 [action] [PR:10146] Updating ingress drop counters for 100G_120k profile in qos
  tests/qos/files/qos_params.j2c.yaml
Labels: automerge

#10387 [action] [PR:10168] Fix Cacl test fixes issue 9864
  tests/cacl/test_cacl_application.py
Labels: automerge

#10385 [action] [PR:9416] PFCWD - Test fixes for t2-chassis
  tests/common/helpers/pfc_gen_t2.py
  tests/common/helpers/pfc_storm.py
  tests/common/templates/pfc_storm_sonic_t2.j2
  tests/common/templates/pfc_storm_stop_sonic_t2.j2
  tests/pfcwd/test_pfcwd_function.py
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#10395 Skip non t2 for voq test
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch, Request for 202305 branch

#9610 ecn-config-update modifications
  tests/generic_config_updater/test_ecn_config_update.py
Labels: Request for 202205 branch, Request for 202305 branch

#10390 [action] [PR:9896] Adding COUNTER_MARGIN to Ingress drop counters for qos tests
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10386 [action] [PR:9893] test_ro_disk: Enhancement for reboot of supervisor card
  tests/tacacs/test_ro_disk.py
Labels: automerge

#10388 [action] [PR:10168] Fix Cacl test fixes issue 9864
  tests/cacl/test_cacl_application.py
Labels: automerge

#10405 [action] [PR:5966] Add rand_one_dut_hostname for fixtures in test_critical_process_monitoring
  tests/process_monitoring/test_critical_process_monitoring.py
Labels: automerge

#10403 [dualtor-io] Add the miss toggle
  tests/dualtor_io/test_link_drop.py
Labels: Request for 202205 branch, Request for 202305 branch

#10406 [action] [PR:10403] [dualtor-io] Add the miss toggle
  tests/dualtor_io/test_link_drop.py
Labels: automerge

#10407 [action] [PR:10403] [dualtor-io] Add the miss toggle
  tests/dualtor_io/test_link_drop.py
Labels: automerge

#10401 [action] [PR:10373] xail warm reboot related cases on 202305 branch for 7060
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10410 [action] [PR:10359] Support HWSKU Mellanox-SN4700-O8C48
  ansible/group_vars/sonic/variables
Labels: automerge

#10411 [action] [PR:10400] xfail warm reboot for 6100 and 7260
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10412 [action] [PR:9876] dhcpv6 per-interface counter automation script coverage
  tests/dhcp_relay/test_dhcpv6_relay.py
Labels: automerge

#10423 [action] [PR:10369] Fix test_memory_exhaustion failure: DUT did not startup
  tests/platform_tests/test_memory_exhaustion.py
Labels: automerge

#10422 [action] [PR:10369] Fix test_memory_exhaustion failure: DUT did not startup
  tests/platform_tests/test_memory_exhaustion.py
Labels: automerge

#10428 [test_qos_sai] Fix toggle failures on dualtor testbed
  tests/common/dualtor/mux_simulator_control.py
  tests/qos/qos_sai_base.py
Labels: Request for 202205 branch, Request for 202305 branch

#10366 Fix BufferPoolWatermarkTest failure for cisco long-link
  tests/qos/files/qos_params.gb.yaml
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: included in internal-2022205

#10434 [dualtor-io] Ignore BGPMON errors in bgp failure tests
  tests/dualtor_io/test_tor_bgp_failure.py
Labels: Request for 202305 branch

#10465 [action] [PR:10080] Stabilize acl_outer_vlan test
  tests/acl/test_acl_outer_vlan.py
Labels: automerge

#10464 [action] [PR:10076] Fix test issues in verify_dut_health.py
  tests/platform_tests/verify_dut_health.py
Labels: automerge

#10463 [action] [PR:10066] Update regex used for warmboot loganalyzer for 202305 branch
  tests/common/fixtures/advanced_reboot.py
  tests/platform_tests/conftest.py
  tests/platform_tests/reboot_timing_constants.py
  tests/platform_tests/templates/expect_boot_messages
Labels: automerge

#10462 [action] [PR:10063] Fix a wrong variable name in TunnelDscpToPgMapping test case
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10461 [action] [PR:10063] Fix a wrong variable name in TunnelDscpToPgMapping test case
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10460 [action] [PR:10055] [test_bgp_update_timer] Log the update packets
  tests/bgp/test_bgp_update_timer.py
Labels: automerge

#10459 [action] [PR:9982] add vnet route cleanup and re-setup after test_vxlan_remove_route2
  tests/vxlan/test_vxlan_ecmp.py
Labels: automerge

#10457 [action] [PR:9966] [test_reload_config] Fix `test_reload_configuration_checks`
  tests/common/config_reload.py
  tests/platform_tests/test_reload_config.py
Labels: automerge

#10456 [action] [PR:9958] Fix test_route_flow_counter
  tests/route/test_route_flow_counter.py
Labels: automerge

#10455 [action] [PR:9958] Fix test_route_flow_counter
  tests/route/test_route_flow_counter.py
Labels: automerge

#10454 [action] [PR:9923] [MA] [chassis] [new testcase] test override config for multi-asic devices and chassis
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/override_config_table/test_override_config_table.py
  tests/override_config_table/test_override_config_table_masic.py
  tests/override_config_table/utilities.py
Labels: automerge

#10453 [action] [PR:9923] [MA] [chassis] [new testcase] test override config for multi-asic devices and chassis
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/override_config_table/test_override_config_table.py
  tests/override_config_table/test_override_config_table_masic.py
  tests/override_config_table/utilities.py
Labels: automerge

#10452 [action] [PR:9902] [Mellanox] add mock for temperature threshold in psu power threshold
  tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
  tests/platform_tests/mellanox/test_psu_power_threshold.py
Labels: automerge

#10451 [action] [PR:9848] Add telemetry container restart and check before test_memory_checker
  tests/memory_checker/test_memory_checker.py
Labels: automerge

#10448 [action] [PR:9810] Cisco: Skip Watermark test for multi-DUT cases.
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: automerge

#10446 [action] [PR:9766] RCA is When we are deleting the agent-id, hsflowd is referring to eth0
  tests/sflow/test_sflow.py
Labels: automerge

#10445 [action] [PR:9655] Cisco-8000: Modifications to Xoff for Cisco-Q100 platform.
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10444 [action] [PR:9610] ecn-config-update modifications
  tests/generic_config_updater/test_ecn_config_update.py
Labels: automerge

#10443 [action] [PR:9610] ecn-config-update modifications
  tests/generic_config_updater/test_ecn_config_update.py
Labels: automerge

#10442 [action] [PR:9583] [Mellanox] Update QoS test cases for SN5600
  tests/qos/files/mellanox/qos_param_generator.py
  tests/qos/files/mellanox/special_qos_config.yml
  tests/qos/qos_sai_base.py
Labels: automerge

#10441 [action] [PR:9579] Give more time for routes to programmed into ASIC for order ecmp testcase
  tests/ipfwd/test_nhop_group.py
Labels: automerge

#10440 [action] [PR:9540] Add skip for 400G for PGDrop.
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: automerge

#10439 [action] [PR:8946] [Mellanox] Adjust PSU power exceeding test
  tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
  tests/platform_tests/mellanox/test_psu_power_threshold.py
Labels: automerge

#10437 [action] [PR:8555] [Nvidia] Update too_big_timeout for test_arm_too_big_timeout
  tests/platform_tests/api/watchdog.yml
Labels: automerge

#10480 [action] [PR:10434] [dualtor-io] Ignore BGPMON errors in bgp failure tests
  tests/dualtor_io/test_tor_bgp_failure.py
Labels: automerge

#10436 [action] [PR:8479] Add fabric test data for 7800R3AK-36DM2-C36 cards
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC3.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC4.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC5.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC6.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC10.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC3.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC4.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC5.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC6.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC7.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC8.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC9.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC3.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC4.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC5.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC6.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC10.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC3.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC4.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC5.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC6.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC7.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC8.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC9.yaml
  tests/voq/test_fabric_reach.py
Labels: automerge

#10435 [action] [PR:8479] Add fabric test data for 7800R3AK-36DM2-C36 cards
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC3.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC4.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC5.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7804R3-FM_LC6.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC10.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC3.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC4.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC5.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC6.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC7.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC8.yaml
  tests/voq/fabric_data/Arista-7800R3A-36DM2-C36_Arista-7808R3A-FM_LC9.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC3.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC4.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC5.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7804R3-FM_LC6.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC10.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC3.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC4.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC5.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC6.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC7.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC8.yaml
  tests/voq/fabric_data/Arista-7800R3AK-36DM2-C36_Arista-7808R3A-FM_LC9.yaml
  tests/voq/test_fabric_reach.py
Labels: automerge

#10433 [action] [PR:10356] Fix SharedResSize lossy drop flaky failure
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#10431 [action] [PR:10428] [test_qos_sai] Fix toggle failures on dualtor testbed
  tests/common/dualtor/mux_simulator_control.py
  tests/qos/qos_sai_base.py
Labels: automerge

#10429 [action] [PR:10375] enlarge sleep time in test_pfcwd_timer_accuracy
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#10227 Handle eth1-midplane being a kernel intf altname
  tests/cacl/test_cacl_application.py
Labels: Request for 202205 branch, Request for 202305 branch

#10342 Fix for test_crm_acl_entry test and py3 fix for API: port_on_asic()
  tests/common/devices/sonic_asic.py
  tests/crm/test_crm.py
Labels: Request for 202205 branch, Request for 202305 branch

#10483 skip warm reboot cases for 7050qx
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch

#10484 [action] [PR:10483] skip warm reboot cases for 7050qx
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#10236 Enable Parallel announcement/withdrawal of routes for T2 topologies
  ansible/library/announce_routes.py
Labels: Request for 202205 branch, Request for 202305 branch

#10237 New Testcases for route_consistency
  tests/route/test_route_consistency.py
Labels: Request for 202205 branch, Request for 202305 branch

#10241 [GCU] Add check to ensure operation is valid in RDMA validator
  tests/generic_config_updater/gu_utils.py
  tests/generic_config_updater/test_ecn_config_update.py
  tests/generic_config_updater/test_incremental_qos.py
  tests/generic_config_updater/test_pfcwd_interval.py
  tests/generic_config_updater/test_pfcwd_status.py
  tests/generic_config_updater/test_pg_headroom_update.py
Labels: Request for 202305 branch

#10491 Use xunit1 as default junit family version
  tests/pytest.ini
Labels: Request for 202012 branch, Request for 202205 branch, Approved for 202012 branch, Approved for 202205 branch, Request for 202305 branch, Approved for 202305 branch

#10485 Fix failure case number in test result summary incorrect issue
  test_reporting/junit_xml_parser.py
Labels: Request for 202012 branch, Request for 202205 branch, Approved for 202012 branch, Approved for 202205 branch, Request for 202305 branch, Approved for 202305 branch

#10495 [action] [PR:10485] Fix failure case number in test result summary incorrect issue
  test_reporting/junit_xml_parser.py
Labels: automerge

#10492 [action] [PR:10491] Use xunit1 as default junit family version
  tests/pytest.ini
Labels: automerge
