Repository sonic-net/sonic-mgmt, pull requests merged in 2024-08, with the labels that each got.

#13902 update detect time in test_pfcwd_timer_accuracy
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: Request for 202311 branch

#13788 [Snappi] change duthost/port mapping for multidut PFC test cases.
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/multidut_helper.py
Labels: Request for 202405 branch, IXIA_CHASSIS

#13913 [action] [PR:13788] [Snappi] change duthost/port mapping for multidut PFC test cases.
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/multidut_helper.py
Labels: automerge

#13910 [action] [PR:13902] update detect time in test_pfcwd_timer_accuracy
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#13909 [action] [PR:13902] update detect time in test_pfcwd_timer_accuracy
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#13921 [action] [PR:13867] Enforcing py3 to be used for fib tests
  tests/fib/test_fib.py
Labels: automerge

#13920 [action] [PR:13867] Enforcing py3 to be used for fib tests
  tests/fib/test_fib.py
Labels: automerge

#11178 Include hostname and tracking ID when uploading warm-reboot results to Kusto
  test_reporting/kusto/setup.kql
  test_reporting/report_data_storage.py
  test_reporting/report_uploader.py
  tests/platform_tests/conftest.py
Labels: Request for 202311 branch, Request for 202405 branch

#13917 update hwsku definitions in the port_utils.py file
  ansible/module_utils/port_utils.py
Labels: Request for 202405 branch

#13763 [Snappi] support T2 testbed definition for multidut test cases
  tests/common/fixtures/conn_graph_facts.py
  tests/common/snappi_tests/port.py
  tests/conftest.py
  tests/snappi_tests/multidut/ecn/test_multidut_dequeue_ecn_with_snappi.py
  tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_lossless_response_to_external_pause_storms.py
  tests/snappi_tests/multidut/pfc/test_lossless_response_to_throttling_pause_storms.py
  tests/snappi_tests/multidut/pfc/test_m2o_fluctuating_lossless.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless_lossy.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossy.py
  tests/snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_a2a_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_burst_storm_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_m2o_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py
Labels: Request for 202405 branch, IXIA_CHASSIS

#13847 [Snappi] Support to enable PFCWD in Forward Mode
  tests/common/snappi_tests/common_helpers.py
Labels: Request for 202405 branch

#13922 [Nokia-7215] Set timeout = 180s for config reload cmd
  tests/platform_tests/test_reload_config.py
Labels: Request for 202311 branch, Request for 202405 branch

#13934 [action] [PR:12549] [test_dhcp_pkt_recv] Exclude disabled interfaces in test case
  tests/dhcp_relay/test_dhcp_pkt_recv.py
Labels: automerge

#13933 [action] [PR:12549] [test_dhcp_pkt_recv] Exclude disabled interfaces in test case
  tests/dhcp_relay/test_dhcp_pkt_recv.py
Labels: automerge

#13930 [action] [PR:13917] update hwsku definitions in the port_utils.py file
  ansible/module_utils/port_utils.py
Labels: automerge

#13929 [action] [PR:13280] Fix Test_syslog_source_ip issue
  tests/syslog/test_syslog_source_ip.py
Labels: automerge

#13935 [action] [PR:13764] [configlet] Improve test if folder already exists
  tests/configlet/util/base_test.py
Labels: automerge

#13918 feat: support BGP peer shutdown test on T2
  tests/bgp/test_bgp_peer_shutdown.py
Labels: Request for 202405 branch

#13940 [action] [PR:13763] [Snappi] support T2 testbed definition for multidut test cases
  tests/common/fixtures/conn_graph_facts.py
  tests/common/snappi_tests/port.py
  tests/conftest.py
  tests/snappi_tests/multidut/ecn/test_multidut_dequeue_ecn_with_snappi.py
  tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_lossless_response_to_external_pause_storms.py
  tests/snappi_tests/multidut/pfc/test_lossless_response_to_throttling_pause_storms.py
  tests/snappi_tests/multidut/pfc/test_m2o_fluctuating_lossless.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless_lossy.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossy.py
  tests/snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_a2a_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_burst_storm_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_m2o_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py
Labels: automerge

#13939 [action] [PR:13847] [Snappi] Support to enable PFCWD in Forward Mode
  tests/common/snappi_tests/common_helpers.py
Labels: automerge

#13942 [action] [PR:12519] Add support to test_sensors for Dynamic changes of PSUs
  docs/testplan/sensors-test-plan.md
  tests/platform_tests/sensors_utils/psu_data.yaml
  tests/platform_tests/sensors_utils/psu_sensor_utils.py
  tests/platform_tests/sensors_utils/psu_sensors.json
  tests/platform_tests/test_sensors.py
Labels: automerge

#13941 [action] [PR:12519] Add support to test_sensors for Dynamic changes of PSUs
  docs/testplan/sensors-test-plan.md
  tests/platform_tests/sensors_utils/psu_data.yaml
  tests/platform_tests/sensors_utils/psu_sensor_utils.py
  tests/platform_tests/sensors_utils/psu_sensors.json
  tests/platform_tests/test_sensors.py
Labels: automerge

#13943 [action] [PR:13922] [Nokia-7215] Set timeout = 180s for config reload cmd
  tests/platform_tests/test_reload_config.py
Labels: automerge

#13274 [action] [PR:13264] [dualtor] Skip advanced reboot cases on dualtor-aa
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#13953 [action] [PR:13368] Multi_asic support for sonic-mgmt syslog test_logrotate.py
  tests/syslog/test_logrotate.py
Labels: automerge

#13950 [action] [PR:13547] Fix dhcp process name when called by supervisorctl
  tests/process_monitoring/test_critical_process_monitoring.py
Labels: automerge

#13948 [action] [PR:13568] [config_check] Ignore linkmgrd logger key
  tests/conftest.py
Labels: automerge

#13949 [action] [PR:13568] [config_check] Ignore linkmgrd logger key
  tests/conftest.py
Labels: automerge

#13947 [action] [PR:13671] Fix: Fix NTP config long jump test failure issue
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/ntp/test_ntp.py
Labels: automerge

#13946 [action] [PR:13695] add http_proxy/https_proxy testbed setup information
  docs/testbed/README.testbed.Setup.md
  docs/testbed/README.testbed.VsSetup.md
  docs/testbed/README.testbed.WANSetup.md
  docs/testbed/sai_quality/DeploySAITestTopologyWithSONiC-MGMT.md
Labels: automerge

#13965 [action] [PR:11178] Include hostname and tracking ID when uploading warm-reboot results to Kusto
  test_reporting/kusto/setup.kql
  test_reporting/report_data_storage.py
  test_reporting/report_uploader.py
  tests/platform_tests/conftest.py
Labels: automerge

#13964 [action] [PR:11178] Include hostname and tracking ID when uploading warm-reboot results to Kusto
  test_reporting/kusto/setup.kql
  test_reporting/report_data_storage.py
  test_reporting/report_uploader.py
  tests/platform_tests/conftest.py
Labels: automerge

#13963 [action] [PR:12178] Add more information log in pfcwd accuracy case for further debug
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#13962 [action] [PR:12178] Add more information log in pfcwd accuracy case for further debug
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#13960 [action] [PR:12956] Optimize loganalyzer regex matching by using match() instead of findall()
  ansible/roles/test/files/tools/loganalyzer/loganalyzer.py
Labels: automerge

#13961 [action] [PR:12956] Optimize loganalyzer regex matching by using match() instead of findall()
  ansible/roles/test/files/tools/loganalyzer/loganalyzer.py
Labels: automerge

#13957 [action] [PR:13279] Fix dualtor_mgmt/test_toggle_mux.py
  tests/dualtor_mgmt/test_toggle_mux.py
Labels: automerge

#13956 [action] [PR:13293] Fix voq fabric tests to use yaml.safe_load instead of yaml.load
  tests/voq/test_fabric_reach.py
  tests/voq/test_voq_fabric_status_all.py
Labels: automerge

#13954 [action] [PR:13363] Fix test_qos_sai teardown for dualtor
  tests/qos/qos_sai_base.py
Labels: automerge

#13951 [action] [PR:13547] Fix dhcp process name when called by supervisorctl
  tests/process_monitoring/test_critical_process_monitoring.py
Labels: automerge

#13967 [action] [PR:13825] Add Cisco GR2 hwsku, setup test markings for appropriate support
  ansible/group_vars/sonic/variables
  ansible/module_utils/port_utils.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/qos/qos_sai_base.py
Labels: automerge

#13966 [action] [PR:13825] Add Cisco GR2 hwsku, setup test markings for appropriate support
  ansible/group_vars/sonic/variables
  ansible/module_utils/port_utils.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/qos/qos_sai_base.py
Labels: automerge

#13938 [action] [PR:13918] feat: support BGP peer shutdown test on T2
  tests/bgp/test_bgp_peer_shutdown.py
Labels: automerge

#13955 [action] [PR:13363] Fix test_qos_sai teardown for dualtor
  tests/qos/qos_sai_base.py
Labels: automerge

#13973 [action] [PR:13840] Deprecate ceosimage_saskey for downloading cEOS image
  ansible/group_vars/all/ceos.yml
  ansible/roles/vm_set/tasks/add_ceos_list.yml
  ansible/roles/vm_set/tasks/probe_ceos_image_url.yml
  ansible/vars/azure_storage.yml
  docs/testbed/README.testbed.VsSetup.md
Labels: automerge

#13972 [action] [PR:13840] Deprecate ceosimage_saskey for downloading cEOS image
  ansible/group_vars/all/ceos.yml
  ansible/roles/vm_set/tasks/add_ceos_list.yml
  ansible/roles/vm_set/tasks/probe_ceos_image_url.yml
  ansible/vars/azure_storage.yml
  docs/testbed/README.testbed.VsSetup.md
Labels: automerge

#13971 [action] [PR:13840] Deprecate ceosimage_saskey for downloading cEOS image
  ansible/group_vars/all/ceos.yml
  ansible/roles/vm_set/tasks/add_ceos_list.yml
  ansible/roles/vm_set/tasks/probe_ceos_image_url.yml
  ansible/vars/azure_storage.yml
  docs/testbed/README.testbed.VsSetup.md
Labels: automerge

#13970 [action] [PR:13840] Deprecate ceosimage_saskey for downloading cEOS image
  ansible/group_vars/all/ceos.yml
  ansible/roles/vm_set/tasks/add_ceos_list.yml
  ansible/roles/vm_set/tasks/probe_ceos_image_url.yml
  ansible/vars/azure_storage.yml
  docs/testbed/README.testbed.VsSetup.md
Labels: automerge

#13974 [test_ro_disk] Recover DUT to RW state by power-cycle when reboot doesn't work
  tests/common/utilities.py
  tests/tacacs/test_ro_disk.py
Labels: Request for 202311 branch, Request for 202405 branch

#13958 [action] [PR:13167] Modified the checking of line[0] of the output of show int transceiver lpmode
  tests/platform_tests/sfp/util.py
Labels: automerge

#13914 [dhcp_server_test] wait lease to be wrote in state_db before check and ignore log error
  tests/dhcp_server/dhcp_server_test_common.py
  tests/dhcp_server/test_dhcp_server.py
Labels: Request for 202311 branch, Request for 202405 branch

#12788 [Cherry-pick]QoSHdrmPoolsize _tx_disable_enable for all destination ports in lag (…
  tests/saitests/py3/sai_qos_tests.py
Labels: chassis

#13985 [action] [PR:13974] [test_ro_disk] Recover DUT to RW state by power-cycle when reboot doesn't work
  tests/common/utilities.py
  tests/tacacs/test_ro_disk.py
Labels: automerge

#13984 [action] [PR:12290] [tests/configlet] Update configlet test to align with swss update
  tests/configlet/util/common.py
Labels: automerge

#13988 [action] [PR:13510] remove skip of bgp/test_bgp_queue.py on Mellanox platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#13996 [action] [PR:13995] Fix table of content
  docs/testbed/README.md
Labels: automerge

#13993 [action] [PR:13779] Documentation review verification
  ansible/verify_config.py
  docs/testbed/README.new.testbed.Configuration.md
  docs/testbed/README.testbed.Config.md
Labels: automerge

#14000 [action] [PR:13794] [dualtor-aa] Fix flakiness of arp/test_unknown_mac.py
  tests/arp/test_unknown_mac.py
Labels: automerge

#13999 [action] [PR:13794] [dualtor-aa] Fix flakiness of arp/test_unknown_mac.py
  tests/arp/test_unknown_mac.py
Labels: automerge

#13982 [snmp] Add wait portchannel up in test_snmp_fdb
  tests/snmp/test_snmp_fdb.py
Labels: Request for 202311 branch, Request for 202405 branch

#13005 [dhcp_server_test] Add stress test on dhcp server with multiple dhcp clients
  tests/dhcp_server/conftest.py
  tests/dhcp_server/test_dhcp_server_stress.py
Labels: Request for 202311 branch, Request for 202405 branch

#13980 Add definition of topology dualtor-64-breakout and dualtor-aa-64-breakout for hwsku Mellanox-SN4700-V64
  ansible/group_vars/sonic/variables
  ansible/module_utils/port_utils.py
  ansible/roles/eos/templates/dualtor-64-breakout-leaf.j2
  ansible/roles/eos/templates/dualtor-aa-64-breakout-leaf.j2
  ansible/roles/test/vars/testcases.yml
  ansible/vars/topo_dualtor-64-breakout.yml
  ansible/vars/topo_dualtor-aa-64-breakout.yml
  tests/qos/qos_sai_base.py
Labels: Approved for 202311 branch, Request for 202311 branch, Approved for 202405 branch, Request for 202405 branch

#14030 [action] [PR:13980] Add definition of topology dualtor-64-breakout and dualtor-aa-64-breakout for hwsku Mellanox-SN4700-V64
  ansible/group_vars/sonic/variables
  ansible/module_utils/port_utils.py
  ansible/roles/eos/templates/dualtor-64-breakout-leaf.j2
  ansible/roles/eos/templates/dualtor-aa-64-breakout-leaf.j2
  ansible/roles/test/vars/testcases.yml
  ansible/vars/topo_dualtor-64-breakout.yml
  ansible/vars/topo_dualtor-aa-64-breakout.yml
  tests/qos/qos_sai_base.py
Labels: automerge

#14020 Added Nokia-7215-A1 hwsku to port_utils
  ansible/module_utils/port_utils.py
Labels: Request for 202311 branch, Request for 202405 branch

#14034 [action] [PR:13799] Skip ROUTE_TABLE and NEIGH_RESOLVE_TABLE entries for test_add_rack.py
  tests/configlet/util/common.py
Labels: automerge

#14038 [action] [PR:13914] [dhcp_server_test] wait lease to be wrote in state_db before check and ignore log error
  tests/dhcp_server/dhcp_server_test_common.py
  tests/dhcp_server/test_dhcp_server.py
Labels: automerge

#14044 [action] [PR:14020] Added Nokia-7215-A1 hwsku to port_utils
  ansible/module_utils/port_utils.py
Labels: automerge

#14043 [action] [PR:14020] Added Nokia-7215-A1 hwsku to port_utils
  ansible/module_utils/port_utils.py
Labels: automerge

#13629 [decap] Fix `test_decap` by using new db schema
  ansible/roles/test/templates/decap_conf.j2
Labels: Approved for 202405 branch, Request for 202405 branch

#14047 [action] [PR:13982] [snmp] Add wait portchannel up in test_snmp_fdb
  tests/snmp/test_snmp_fdb.py
Labels: automerge

#14049 [action] [PR:13629] [decap] Fix `test_decap` by using new db schema
  ansible/roles/test/templates/decap_conf.j2
Labels: automerge

#14048 [action] [PR:13982] [snmp] Add wait portchannel up in test_snmp_fdb
  tests/snmp/test_snmp_fdb.py
Labels: automerge

#14045 [action] [PR:13005] [dhcp_server_test] Add stress test on dhcp server with multiple dhcp clients
  tests/dhcp_server/conftest.py
  tests/dhcp_server/test_dhcp_server_stress.py
Labels: automerge

#14046 [action] [PR:13005] [dhcp_server_test] Add stress test on dhcp server with multiple dhcp clients
  tests/dhcp_server/conftest.py
  tests/dhcp_server/test_dhcp_server_stress.py
Labels: automerge

#14052 Test_ntp_ipv6_only flaky issue
  tests/common/config_reload.py
Labels: Request for 202311 branch, Request for 202405 branch

#14055 [action] [PR:14024] fix for intermittent failures in vxlan ecmp test suite
  ansible/roles/test/files/ptftests/py3/vxlan_traffic.py
Labels: automerge

#14054 [action] [PR:14024] fix for intermittent failures in vxlan ecmp test suite
  ansible/roles/test/files/ptftests/py3/vxlan_traffic.py
Labels: automerge

#14061 [action] [PR:14052] Test_ntp_ipv6_only flaky issue
  tests/common/config_reload.py
Labels: automerge

#14060 [action] [PR:14052] Test_ntp_ipv6_only flaky issue
  tests/common/config_reload.py
Labels: automerge

#14051 [dualtor] Improve `test_orchagent_slb`
  tests/common/dualtor/server_traffic_utils.py
  tests/dualtor/test_orchagent_slb.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#14056 [sanity check] Fix dualtor sanity check issue
  tests/common/plugins/sanity_check/checks.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#14069 [action] [PR:14056] [sanity check] Fix dualtor sanity check issue
  tests/common/plugins/sanity_check/checks.py
Labels: automerge

#14068 [action] [PR:14056] [sanity check] Fix dualtor sanity check issue
  tests/common/plugins/sanity_check/checks.py
Labels: automerge

#14067 [action] [PR:14051] [dualtor] Improve `test_orchagent_slb`
  tests/common/dualtor/server_traffic_utils.py
  tests/dualtor/test_orchagent_slb.py
Labels: automerge

#14066 [action] [PR:14051] [dualtor] Improve `test_orchagent_slb`
  tests/common/dualtor/server_traffic_utils.py
  tests/dualtor/test_orchagent_slb.py
Labels: automerge

#14012 [dhcp_relay] Refactor dhcp_relay for dualtor
  ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/dhcp_relay/test_dhcp_relay.py
Labels: Request for 202311 branch, Request for 202405 branch

#14084 [action] [PR:12346] [test_po_cleanup] Do a safe config reload
  tests/pc/test_po_cleanup.py
Labels: automerge

#14041 Update test scripts in PFCwd
  tests/pfcwd/files/pfcwd_helper.py
  tests/pfcwd/test_pfcwd_function.py
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: Request for 202311 branch, Request for 202405 branch

#13976 Degrade PFC storm detection in PFCWD all ports storm test
  tests/pfcwd/files/pfc_detect_mellanox.lua
  tests/pfcwd/test_pfcwd_all_port_storm.py
Labels: Request for 202311 branch, Request for 202405 branch

#14093 [action] [PR:13976] Degrade PFC storm detection in PFCWD all ports storm test
  tests/pfcwd/files/pfc_detect_mellanox.lua
  tests/pfcwd/test_pfcwd_all_port_storm.py
Labels: automerge

#14096 [action] [PR:13041] [QoS]Sai-thrift support for Credit_WD enable disable code changes in sonic-mgmt qos_test
  tests/saitests/py3/sai_base_test.py
  tests/saitests/py3/switch.py
Labels: automerge

#14099 [action] [PR:13511] Add a sonic-mgmt test case to validate FEC stat counters
  tests/platform_tests/test_intf_fec.py
Labels: automerge

#14104 [action] [PR:12186] crm_stats_ipv6_route_available counter was not decremented
  tests/crm/test_crm.py
Labels: automerge

#14103 [action] [PR:14002] Enhance test dhcp_relay/test_dhcp_pkt_recv.py for dualtor
  tests/dhcp_relay/test_dhcp_pkt_recv.py
Labels: automerge

#14102 [action] [PR:14002] Enhance test dhcp_relay/test_dhcp_pkt_recv.py for dualtor
  tests/dhcp_relay/test_dhcp_pkt_recv.py
Labels: automerge

#13989 Fixed copp/test_policer testcase for DHCP, DHCP6, LLDP and UDLD scenarios for marvell based platforms
  ansible/roles/test/files/ptftests/py3/copp_tests.py
Labels: Request for 202311 branch, Request for 202405 branch

#14105 [action] [PR:14015] [test gap] add a new test case for bgp session check
  .azure-pipelines/pr_test_scripts.yaml
  tests/bgp/test_bgp_session.py
Labels: automerge

#14115 [action] [PR:13924] Fix flaky test_set_fans_speed when target speed is low
  tests/platform_tests/api/test_chassis_fans.py
Labels: automerge

#14114 [action] [PR:13989] Fixed copp/test_policer testcase for DHCP, DHCP6, LLDP and UDLD scenarios for marvell based platforms
  ansible/roles/test/files/ptftests/py3/copp_tests.py
Labels: automerge

#14121 [action] [PR:13410] Fix arp/test_unknown_mac by disabling arp_update
  tests/arp/test_unknown_mac.py
Labels: automerge

#14134 [action] [PR:13989] Fixed copp/test_policer testcase for DHCP, DHCP6, LLDP and UDLD scenarios for marvell based platforms
  ansible/roles/test/files/ptftests/py3/copp_tests.py
Labels: automerge

#14136 [action] [PR:14076] [BGP] stress bgp link flap case
  .azure-pipelines/pr_test_scripts.yaml
  tests/bgp/test_bgp_stress_link_flap.py
Labels: automerge

#14135 [action] [PR:13924] Fix flaky test_set_fans_speed when target speed is low
  tests/platform_tests/api/test_chassis_fans.py
Labels: automerge

#14131 Set device type to BackEnd if enable_compute_ai_deployment is true
  ansible/templates/minigraph_png.j2
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#14148 [action] [PR:14131] Set device type to BackEnd if enable_compute_ai_deployment is true
  ansible/templates/minigraph_png.j2
Labels: automerge

#14146 [action] [PR:14131] Set device type to BackEnd if enable_compute_ai_deployment is true
  ansible/templates/minigraph_png.j2
Labels: automerge

#14147 [action] [PR:14131] Set device type to BackEnd if enable_compute_ai_deployment is true
  ansible/templates/minigraph_png.j2
Labels: automerge

#14120 [dhcp_server_test] fix test failure due to lease was not updated to state db
  tests/dhcp_server/dhcp_server_test_common.py
  tests/dhcp_server/test_dhcp_server.py
Labels: Request for 202311 branch, Request for 202405 branch

#14064 [Mellanox] skip test_reboot_cause.py on sn4280
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202405 branch

#14062 [Mellanox] Add platform data and sensors data for x86_64-nvidia_sn4280-r0
  ansible/group_vars/sonic/sku-sensors-data.yml
  tests/common/mellanox_data.py
Labels: Request for 202405 branch

#14166 [action] [PR:12932] Fix add-topo failure when deploying topology with empty VM list.
  ansible/roles/vm_set/library/vm_topology.py
  ansible/templates/minigraph_dpg.j2
Labels: automerge

#14170 [action] [PR:14062] [Mellanox] Add platform data and sensors data for x86_64-nvidia_sn4280-r0
  ansible/group_vars/sonic/sku-sensors-data.yml
  tests/common/mellanox_data.py
Labels: automerge

#14169 [action] [PR:14064] [Mellanox] skip test_reboot_cause.py on sn4280
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: automerge

#14168 [action] [PR:14162] [dualtor] Fix `test_stress_route`
  tests/stress/conftest.py
Labels: automerge

#13975 Enhance pfc_gen script to support multi-processing
  tests/common/helpers/pfc_gen.py
  tests/common/templates/pfc_storm_stop_eos.j2
  tests/pfcwd/files/pfcwd_helper.py
Labels: Request for 202311 branch, Request for 202405 branch

#14174 [action] [PR:13975] Enhance pfc_gen script to support multi-processing
  tests/common/helpers/pfc_gen.py
  tests/common/templates/pfc_storm_stop_eos.j2
  tests/pfcwd/files/pfcwd_helper.py
Labels: automerge

#14157 [action] [PR:14120] [dhcp_server_test] fix test failure due to lease was not updated to state db
  tests/dhcp_server/dhcp_server_test_common.py
  tests/dhcp_server/test_dhcp_server.py
Labels: automerge

#13664 Align the test case to use mask in dotted decimal notation
  tests/hash/generic_hash_helper.py
Labels: Request for 202311 branch, Request for 202405 branch

#13298 Enhance show_techsupport script
  tests/show_techsupport/test_auto_techsupport.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#14176 [dualtor] Fix `test_console_baud_rate`
  tests/dut_console/test_console_baud_rate.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#13928 Use config load_minigraph -y command for images which does not support "--override_config"
  ansible/config_sonic_basedon_testbed.yml
Labels: Request for 202311 branch, Request for 202405 branch

#14185 [action] [PR:14176] [dualtor] Fix `test_console_baud_rate`
  tests/dut_console/test_console_baud_rate.py
Labels: automerge

#14184 [action] [PR:14176] [dualtor] Fix `test_console_baud_rate`
  tests/dut_console/test_console_baud_rate.py
Labels: automerge

#13845 [Snappi] Fix for crash in enable_packet_aging_after_test called during test cleanup
  tests/common/snappi_tests/common_helpers.py
Labels: Request for 202405 branch, IXIA_CHASSIS

#14127 [Fix]: Enhancement of port selection criteria for multidut RDMA cases based on testbed informaition
  tests/common/snappi_tests/snappi_fixtures.py
  tests/snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
  tests/snappi_tests/variables.py
Labels: Request for 202405 branch, IXIA_CHASSIS

#14188 [action] [PR:13845] [Snappi] Fix for crash in enable_packet_aging_after_test called during test cleanup
  tests/common/snappi_tests/common_helpers.py
Labels: automerge

#14180 [action] [PR:13837] increase wait time for verifying dynamic bgp neigh
  tests/bgp/test_bgp_speaker.py
Labels: automerge

#14175 [action] [PR:13975] Enhance pfc_gen script to support multi-processing
  tests/common/helpers/pfc_gen.py
  tests/common/templates/pfc_storm_stop_eos.j2
  tests/pfcwd/files/pfcwd_helper.py
Labels: automerge

#14198 [dualtor] Improve the toggle fixture
  tests/common/dualtor/mux_simulator_control.py
Labels: Request for 202311 branch, Request for 202405 branch

#14186 [action] [PR:13928] Use config load_minigraph -y command for images which does not support "--override_config"
  ansible/config_sonic_basedon_testbed.yml
Labels: automerge

#14181 [action] [PR:13837] increase wait time for verifying dynamic bgp neigh
  tests/bgp/test_bgp_speaker.py
Labels: automerge

#14190 feat: improved wording for skipped test case
  tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
  tests/drop_packets/drop_packets.py
Labels: Request for 202405 branch

#14211 [action] [PR:12969] Add pkts_num_hysteresis for new rx cgm profile
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/files/qos_params.gb.yaml
  tests/qos/files/qos_params.pac.yaml
Labels: automerge

#14223 [action] [PR:14198] [dualtor] Improve the toggle fixture
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#14222 [action] [PR:14198] [dualtor] Improve the toggle fixture
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#12976 [Nvidia] Enable vxlan_ecmp tests on Nvidia 4700 and 4280 platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202311 branch, Request for 202405 branch

#13878 Align the sonic-mgmt code based on the typo "neighbhor" fix in the image
  tests/route/test_route_flow_counter.py
  tests/stress/utils.py
Labels: Request for 202405 branch

#13863 Move the skip for expired ttl test case logic to the conditional yaml file
  tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
  tests/drop_packets/drop_packets.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#13860 Update the dualtor condition in test_vlan_ping.py
  tests/vlan/test_vlan_ping.py
Labels: Request for 202405 branch

#13278 [Mellanox] Split test_device_checker into to two cases
  tests/system_health/test_system_health.py
Labels: Request for 202311 branch, Request for 202405 branch

#14189 [chassis]: Update test_snmp_lldp.py: skip lldpLocManAddrTable for LC
  tests/snmp/test_snmp_lldp.py
Labels: Request for 202405 branch

#14238 [action] [PR:13278] [Mellanox] Split test_device_checker into to two cases
  tests/system_health/test_system_health.py
Labels: automerge

#14236 [action] [PR:13863] Move the skip for expired ttl test case logic to the conditional yaml file
  tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
  tests/drop_packets/drop_packets.py
Labels: automerge

#14235 [action] [PR:13878] Align the sonic-mgmt code based on the typo "neighbhor" fix in the image
  tests/route/test_route_flow_counter.py
  tests/stress/utils.py
Labels: automerge

#14217 Fix flaky test_set_fans_speed (test_fan_drawer_fans.py) when target s…
  tests/platform_tests/api/test_fan_drawer_fans.py
Labels: Request for 202311 branch, Request for 202405 branch

#14230 [8122] change device type to BackEndLeafRouter
  ansible/config_sonic_basedon_testbed.yml
Labels: Request for 202311 branch, Request for 202405 branch

#13991 [action] [PR:13492] Add debug message for debugging script `test_stress_routes.py`.
  ansible/library/announce_routes.py
  tests/stress/test_stress_routes.py
Labels: automerge

#14225 [Feat] Initialize neighbor ansible_hosts with multi thread way
  tests/conftest.py
Labels: Approved for 202405 branch, Request for 202405 branch

#14253 [action] [PR:14217] Fix flaky test_set_fans_speed (test_fan_drawer_fans.py) when target s…
  tests/platform_tests/api/test_fan_drawer_fans.py
Labels: automerge

#14026 [Snappi]: Adding support for breakout links
  tests/common/snappi_tests/snappi_helpers.py
Labels: Request for 202405 branch
