Repository sonic-net/sonic-mgmt, pull requests merged in 2024-10, with the labels that each got.

#14715 Fix error in qos_param_generator
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/qos_sai_base.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#14806 [action] [PR:13729] Avoid KeyError in script `test_generic_hash.py` on kvm testbed.
  tests/hash/generic_hash_helper.py
Labels: automerge

#14808 [action] [PR:14715] Fix error in qos_param_generator
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/qos_sai_base.py
Labels: automerge

#14812 [action] [PR:14704] [tests-cacl] Add acl-loader test and validation function
  tests/cacl/test_cacl_application.py
Labels: automerge

#14746 MIGSMSFT-647 improve qos/test_qos_sai.py to have different longlink/shortlink combinations
  tests/qos/qos_sai_base.py
Labels: Request for 202405 branch

#14821 [action] [PR:14746] MIGSMSFT-647 improve qos/test_qos_sai.py to have different longlink/shortlink combinations
  tests/qos/qos_sai_base.py
Labels: automerge

#14823 [action] [PR:14348] Wait for acl delete rule/table message in syslog
  tests/acl/test_acl.py
Labels: automerge

#14787 [VOQ Chassis] Separate out Route Consistency between upstream and downstream LC's
  tests/route/test_route_consistency.py
Labels: Request for 202205 branch, Request for 202405 branch

#14831 [action] [PR:14787] [VOQ Chassis] Separate out Route Consistency between upstream and downstream LC's
  tests/route/test_route_consistency.py
Labels: automerge

#14799 refactor: batch control interfaces in BFD
  tests/bfd/bfd_helpers.py
  tests/bfd/conftest.py
  tests/bfd/test_bfd_static_route.py
Labels: Request for 202405 branch

#14833 [action] [PR:14799] refactor: batch control interfaces in BFD
  tests/bfd/bfd_helpers.py
  tests/bfd/conftest.py
  tests/bfd/test_bfd_static_route.py
Labels: automerge

#14832 [action] [PR:14533] feat: add support for parallel run
  tests/common/devices/duthosts.py
  tests/common/helpers/parallel_utils.py
  tests/common/plugins/sanity_check/__init__.py
  tests/conftest.py
  tests/test_parallel_modes.json
Labels: automerge

#14804 [T2] [Chassis] Route flap fix on upstream LC for AZNG route changes
  tests/conftest.py
  tests/route/test_route_flap.py
Labels: Request for 202205 branch, Request for 202405 branch

#14839 [action] [PR:14494] Refactor shared functions from `test_traffic_shift.py` to common
  tests/bgp/constants.py
  tests/bgp/route_checker.py
  tests/bgp/test_seq_idf_isolation.py
  tests/bgp/test_startup_tsa_tsb_service.py
  tests/bgp/test_traffic_shift.py
  tests/bgp/test_traffic_shift_sup.py
  tests/bgp/traffic_checker.py
Labels: automerge

#14845 Fix python-setuptools package name for bookwork
  tests/copp/copp_utils.py
Labels: Request for 202405 branch

#14857 [action] [PR:14845] Fix python-setuptools package name for bookwork
  tests/copp/copp_utils.py
Labels: automerge

#14789 Fix the Fib/ipdecap test case for new change where AZNG routes on ups…
  ansible/roles/test/files/ptftests/fib_test.py
  ansible/roles/test/files/ptftests/py3/IP_decap_test.py
  ansible/roles/test/files/ptftests/py3/hash_test.py
Labels: Request for 202205 branch, Request for 202405 branch

#13569 Adding port mapping for new Arista Hardware SKUs
  ansible/module_utils/port_utils.py
Labels: Request for 202405 branch

#14743 Fix sai_thrift_read_port_counters for DNX
  tests/saitests/py3/switch.py
Labels: Request for 202405 branch

#14841 change ptf container memory in restart-ptf to 16G as same as add-topo
  ansible/roles/vm_set/tasks/renumber_topo.yml
Labels: Request for 202405 branch

#14416 [Fix] Adding dut counter verification for PFC Oversubscription cases
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
Labels: Request for 202405 branch

#14742 [Snappi] multidut test case changes to support T0/T1 testbed.
  tests/snappi_tests/multidut/ecn/test_multidut_dequeue_ecn_with_snappi.py
  tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_lossless_response_to_external_pause_storms.py
  tests/snappi_tests/multidut/pfc/test_lossless_response_to_throttling_pause_storms.py
  tests/snappi_tests/multidut/pfc/test_m2o_fluctuating_lossless.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless_lossy.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossy.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_a2a_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_burst_storm_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_m2o_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py
  tests/snappi_tests/test_multidut_snappi.py
Labels: Request for 202405 branch

#14628 skip test_bgp_suppress_fib in 202405 release
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch

#14869 [action] [PR:14699] Added adding static route before startup interfaces
  tests/ecmp/test_fgnhg.py
Labels: automerge

#14870 [action] [PR:14699] Added adding static route before startup interfaces
  tests/ecmp/test_fgnhg.py
Labels: automerge

#14868 [action] [PR:14699] Added adding static route before startup interfaces
  tests/ecmp/test_fgnhg.py
Labels: automerge

#14867 [action] [PR:14743] Fix sai_thrift_read_port_counters for DNX
  tests/saitests/py3/switch.py
Labels: automerge

#14065 Update pretest script to provide asic type value for generic hash test script
  tests/common/devices/sonic.py
  tests/test_pretest.py
Labels: Request for 202311 branch, Request for 202405 branch

#14846 Support hget_all in SonicDbCli
  tests/common/helpers/sonic_db.py
Labels: Request for 202405 branch

#14873 [action] [PR:14742] [Snappi] multidut test case changes to support T0/T1 testbed.
  tests/snappi_tests/multidut/ecn/test_multidut_dequeue_ecn_with_snappi.py
  tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_lossless_response_to_external_pause_storms.py
  tests/snappi_tests/multidut/pfc/test_lossless_response_to_throttling_pause_storms.py
  tests/snappi_tests/multidut/pfc/test_m2o_fluctuating_lossless.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless_lossy.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossy.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_a2a_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_burst_storm_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_m2o_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py
  tests/snappi_tests/test_multidut_snappi.py
Labels: automerge

#14872 [action] [PR:14416] [Fix] Adding dut counter verification for PFC Oversubscription cases
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
Labels: automerge

#14871 [action] [PR:14841] change ptf container memory in restart-ptf to 16G as same as add-topo
  ansible/roles/vm_set/tasks/renumber_topo.yml
Labels: automerge

#14739 [dhcp_relay] Add delay in checking dhcp_relay status
  tests/dhcp_relay/dhcp_relay_utils.py
Labels: Request for 202311 branch, Request for 202405 branch

#14879 [action] [PR:14303] Reproduce XOFF counter increase
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#14876 [action] [PR:14846] Support hget_all in SonicDbCli
  tests/common/helpers/sonic_db.py
Labels: automerge

#14875 [dut_console/test_console_baud_rate] Configure expected baudrate in inventory files
  tests/dut_console/test_console_baud_rate.py
Labels: Request for 202405 branch

#14777 [platform_tests/counterpoll]: Support multi-asic for counterpoll watermark tests
  tests/common/devices/sonic_asic.py
  tests/platform_tests/counterpoll/test_counterpoll_watermark.py
Labels: Request for 202405 branch

#14862 Extended the SingleHop BFD skip to other cisco platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch

#14882 [Snappi] enable safe reboot for multidut snappi cases.
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
Labels: Request for 202405 branch

#14894 Wait for service to fix flaky memory_checker test
  tests/memory_checker/test_memory_checker.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#14334 Support for Cisco-8122 test_qos_sai.py
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202405 branch

#14881 Add GCU timeout for qualification
  tests/common/gu_utils.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#9527 [test plan] Macsec docker restart
  docs/testplan/MACsec-test-plan.md
  tests/macsec/test_docker_restart.py
Labels: Test Plan

#14920 [action] [PR:14883] Fix SyntaxError for test_lldp_syncd
  tests/common/helpers/sonic_db.py
Labels: automerge

#14902 [action] [PR:14789] Fix the Fib/ipdecap test case for new change where AZNG routes on ups…
  ansible/roles/test/files/ptftests/fib_test.py
  ansible/roles/test/files/ptftests/py3/IP_decap_test.py
  ansible/roles/test/files/ptftests/py3/hash_test.py
Labels: automerge

#14901 [action] [PR:14110] [hash/test_generic_hash] xfail new case which failed on other platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14900 [action] [PR:14777] [platform_tests/counterpoll]: Support multi-asic for counterpoll watermark tests
  tests/common/devices/sonic_asic.py
  tests/platform_tests/counterpoll/test_counterpoll_watermark.py
Labels: automerge

#14898 [action] [PR:14882] [Snappi] enable safe reboot for multidut snappi cases.
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
Labels: automerge

#14886 Workaround python_sai_thrift path issue
  tests/test_pretest.py
Labels: Request for 202405 branch

#14889 Fix for test_dhcp_relay failures on hwsku of Cisco-8111-O64
  tests/dhcp_relay/conftest.py
Labels: Request for 202405 branch

#14923 Fix test_vlan_ping
  tests/vlan/test_vlan_ping.py
Labels: Approved for 202405 branch, Request for 202405 branch

#14930 [action] [PR:14739] [dhcp_relay] Add delay in checking dhcp_relay status
  tests/dhcp_relay/dhcp_relay_utils.py
Labels: automerge

#14929 [action] [PR:14739] [dhcp_relay] Add delay in checking dhcp_relay status
  tests/dhcp_relay/dhcp_relay_utils.py
Labels: automerge

#14935 [action] [PR:14075] Fix IndexError: Bad index 'None' type in fixture check_dut_asic_type
  tests/common/plugins/custom_fixtures/check_dut_asic_type.py
Labels: automerge

#14934 [action] [PR:14923] Fix test_vlan_ping
  tests/vlan/test_vlan_ping.py
Labels: automerge

#14933 [action] [PR:14889] Fix for test_dhcp_relay failures on hwsku of Cisco-8111-O64
  tests/dhcp_relay/conftest.py
Labels: automerge

#14931 [action] [PR:14886] Workaround python_sai_thrift path issue
  tests/test_pretest.py
Labels: automerge

#14912 [Bugfix]Adding conditions to longer matching entries in conditional marks
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#9984 SmartSwitch High-Availability Test plan
  docs/testplan/smart-switch/high-availability/images/ha_dpuloss_multiple_ha_sets.svg
  docs/testplan/smart-switch/high-availability/images/ha_dpuloss_not_local.svg
  docs/testplan/smart-switch/high-availability/images/ha_dpuloss_test.svg
  docs/testplan/smart-switch/high-availability/images/ha_linkloss_multiple_ha_sets.svg
  docs/testplan/smart-switch/high-availability/images/ha_linkloss_test.svg
  docs/testplan/smart-switch/high-availability/images/ha_linkloss_test_not_local.svg
  docs/testplan/smart-switch/high-availability/images/ha_test_cps_ha_not_enabled.svg
  docs/testplan/smart-switch/high-availability/images/ha_test_perfect_sync.svg
  docs/testplan/smart-switch/high-availability/images/ha_test_topology.svg
  docs/testplan/smart-switch/high-availability/images/ha_testbed.svg
  docs/testplan/smart-switch/high-availability/images/ha_torloss_not_local.svg
  docs/testplan/smart-switch/high-availability/images/ha_torloss_test.svg
  docs/testplan/smart-switch/high-availability/images/smartswitch_ha_topology.svg
  docs/testplan/smart-switch/high-availability/keysight_ha_testplan.md
Labels: Test Plan

#14925 select shortlink linecard to run single_asic and single_dut_multi_asic
  tests/qos/qos_sai_base.py
Labels: Request for 202405 branch

#14937 [action] [PR:14627] [COPP][720DT] Fix copp test failure for 720dt
  ansible/roles/test/files/ptftests/py3/copp_tests.py
  tests/copp/test_copp.py
Labels: automerge

#14946 [action] [PR:14925] select shortlink linecard to run single_asic and single_dut_multi_asic
  tests/qos/qos_sai_base.py
Labels: automerge

#14680 [dualtor][test gap] Add testcases to cover the faulty ycable
  tests/dualtor/files/y_cable_simulated.py.j2
  tests/dualtor/test_switchover_faulty_ycable.py
Labels: Test gap, Request for 202311 branch, Request for 202405 branch

#14967 [action] [PR:13660] [QoS JR2] Clone J2C+ changes for new vsq thresholds
  tests/qos/files/qos_params.jr2.yaml
Labels: automerge

#14954 [action] [PR:14347] Always run postboot_setup in runRebootTest
  tests/common/fixtures/advanced_reboot.py
Labels: automerge

#14953 [action] [PR:14347] Always run postboot_setup in runRebootTest
  tests/common/fixtures/advanced_reboot.py
Labels: automerge

#14905 [action] [PR:14894] Wait for service to fix flaky memory_checker test
  tests/memory_checker/test_memory_checker.py
Labels: automerge

#14959 [dhcp_relay] Skip dhcp_relay test via feature status rather than topo
  tests/dhcp_relay/conftest.py
Labels: Request for 202311 branch, Request for 202405 branch

#14974 [action] [PR:14959] [dhcp_relay] Skip dhcp_relay test via feature status rather than topo
  tests/dhcp_relay/conftest.py
Labels: automerge

#14973 [action] [PR:14959] [dhcp_relay] Skip dhcp_relay test via feature status rather than topo
  tests/dhcp_relay/conftest.py
Labels: automerge

#14904 [action] [PR:14894] Wait for service to fix flaky memory_checker test
  tests/memory_checker/test_memory_checker.py
Labels: automerge

#14964 Skipping EverflowV4 EgressAcl EgressMirror for Cisco-8000
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch

#14978 [action] [PR:14964] Skipping EverflowV4 EgressAcl EgressMirror for Cisco-8000
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14979 [action] [PR:13579] stop_and_start_lldpmgrd should be tested for lldp0/lldp1 since lldp was removed from the host
  tests/monit/test_monit_status.py
Labels: automerge

#14988 [action] [PR:14875] [dut_console/test_console_baud_rate] Configure expected baudrate in inventory files
  tests/dut_console/test_console_baud_rate.py
Labels: automerge

#14824 sonic-mgmt / IXIA test for cisco platforms to verify ECN Counter operation.
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/ecn/files/ecnhelper.py
  tests/snappi_tests/ecn/test_ecn_marking_cisco8000.py
Labels: Request for 202405 branch

#14987 chore: change link toggle command in BFD
  tests/bfd/bfd_helpers.py
Labels: Request for 202405 branch

#14990 [action] [PR:14332] Fix Python3 str.decode issues
  tests/common/helpers/sonic_db.py
  tests/voq/test_voq_init.py
Labels: automerge

#14989 [action] [PR:14849] Change behaviour of reboot wait and timeout assignment for T2 devices
  tests/common/reboot.py
Labels: automerge

#14993 [action] [PR:14824] sonic-mgmt / IXIA test for cisco platforms to verify ECN Counter operation.
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/ecn/files/ecnhelper.py
  tests/snappi_tests/ecn/test_ecn_marking_cisco8000.py
Labels: automerge

#14994 [action] [PR:14987] chore: change link toggle command in BFD
  tests/bfd/bfd_helpers.py
Labels: automerge

#14731 Skip error message due to missing feature
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202405 branch

#15003 Update dst_path for switch_sai_thrift library
  tests/test_pretest.py
Labels: Request for 202405 branch

#15006 [action] [PR:15003] Update dst_path for switch_sai_thrift library
  tests/test_pretest.py
Labels: automerge

#15009 [action] [PR:14952] refactor: switch to use fixture for error handling
  tests/common/devices/duthosts.py
  tests/common/helpers/parallel_utils.py
  tests/common/plugins/sanity_check/__init__.py
Labels: automerge

#14601 Update nexthop rewrite for flows based on default hash offset for cisco platform
  tests/ipfwd/test_nhop_group.py
Labels: Request for 202405 branch

#15018 [action] [PR:13096] Improve test_bgpmon - use `ip route replace` instead of `ip route add`
  tests/bgp/test_bgpmon.py
Labels: automerge

#14884 [dualtor][sanity] Restart mux simulator if sanity fails to get mux status
  tests/common/dualtor/mux_simulator_control.py
  tests/common/plugins/sanity_check/checks.py
Labels: Request for 202311 branch, Request for 202405 branch

#14890 convert bgp stress link flap test to use asyncio
  tests/bgp/test_bgp_stress_link_flap.py
Labels: Request for 202405 branch

#15019 [action] [PR:14601] Update nexthop rewrite for flows based on default hash offset for cisco platform
  tests/ipfwd/test_nhop_group.py
Labels: automerge

#15001 Adjust fixture order in arp test unknown mac
  tests/arp/test_unknown_mac.py
Labels: Request for 202311 branch, Request for 202405 branch

#15020 [action] [PR:14884] [dualtor][sanity] Restart mux simulator if sanity fails to get mux status
  tests/common/dualtor/mux_simulator_control.py
  tests/common/plugins/sanity_check/checks.py
Labels: automerge

#15022 [action] [PR:13438] Skip forced mgmt route test if intf is invalid
  tests/route/test_forced_mgmt_route.py
Labels: automerge

#15024 [action] [PR:14409] Subject: sonic-mgmt: fix tagged-arp test for large topos
  tests/arp/test_tagged_arp.py
Labels: automerge

#15023 [action] [PR:14409] Subject: sonic-mgmt: fix tagged-arp test for large topos
  tests/arp/test_tagged_arp.py
Labels: automerge

#15007 Relocate log_custom_msg to assure test results to be logged
  tests/common/helpers/constants.py
  tests/common/helpers/custom_msg_utils.py
  tests/common/plugins/sanity_check/__init__.py
  tests/conftest.py
Labels: Request for 202405 branch

#15030 [action] [PR:14027] added arm64 platform check to skip /proc/dma command check
  tests/show_techsupport/test_techsupport.py
Labels: automerge

#15031 [action] [PR:14027] added arm64 platform check to skip /proc/dma command check
  tests/show_techsupport/test_techsupport.py
Labels: automerge

#15029 [action] [PR:15001] Adjust fixture order in arp test unknown mac
  tests/arp/test_unknown_mac.py
Labels: automerge

#15028 [action] [PR:15001] Adjust fixture order in arp test unknown mac
  tests/arp/test_unknown_mac.py
Labels: automerge

#15033 [action] [PR:15007] Relocate log_custom_msg to assure test results to be logged
  tests/common/helpers/constants.py
  tests/common/helpers/custom_msg_utils.py
  tests/common/plugins/sanity_check/__init__.py
  tests/conftest.py
Labels: automerge

#15032 [action] [PR:14951] [Refine] Use multi-thread to recover chassis
  tests/common/helpers/parallel_utils.py
  tests/common/plugins/sanity_check/recover.py
  tests/conftest.py
Labels: automerge

#14694 Skip test_telemetry_queue_buffer_cnt test if switch type is voq
  tests/common/plugins/conditional_mark/__init__.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch

#15036 [action] [PR:14694] Skip test_telemetry_queue_buffer_cnt test if switch type is voq
  tests/common/plugins/conditional_mark/__init__.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#15021 Wait BGP sessions estabilished in ACL reboot test
  tests/acl/test_acl.py
Labels: Request for 202405 branch

#15039 [action] [PR:14848] Remove cause of TypeError in get_tsa_tsb_service_uptime
  tests/bgp/test_startup_tsa_tsb_service.py
Labels: automerge

#14892 Fixing the failures in qos-sai on 202405.
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202405 branch

#15040 [action] [PR:15021] Wait BGP sessions estabilished in ACL reboot test
  tests/acl/test_acl.py
Labels: automerge

#15038 [action] [PR:14750] Add skip for test_vs_chassis_setup.py on non-vs testbeds
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14991 [202405][PR:14597] RX_DROP counter if destination MAC is not the router MAC on L3 interface
  tests/ip/test_ip_packet.py
Labels: Request for 202405 branch

#14907 [action] [PR:14334] Support for Cisco-8122 test_qos_sai.py
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#15046 Disable loganalzyer for test_lldp_entry_table_after_reboot
  tests/lldp/test_lldp_syncd.py
Labels: Request for 202405 branch

#14229 [Mellanox] update dynamic buffer test
  tests/qos/test_buffer.py
Labels: Request for 202405 branch

#15068 [action] [PR:15046] Disable loganalzyer for test_lldp_entry_table_after_reboot
  tests/lldp/test_lldp_syncd.py
Labels: automerge

#15075 [action] [PR:14884] [dualtor][sanity] Restart mux simulator if sanity fails to get mux status
  tests/common/dualtor/mux_simulator_control.py
  tests/common/plugins/sanity_check/checks.py
Labels: automerge

#15085 [action] [PR:14942] Cisco-8122 fixes for T1 topology
  tests/qos/files/cisco/qos_param_generator.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#14732 [dhcpv6_relay_test] test if dhcpv6_relay will set correct link address in packet on multiple vlans host
  ansible/roles/test/files/ptftests/py3/dhcpv6_relay_test.py
  tests/common/fixtures/split_vlan.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/dhcp_relay/test_dhcpv6_relay.py
Labels: Request for 202311 branch, Request for 202405 branch

#15086 [action] [PR:14654] [Nokia-7215] Improve test_reboot stability at teardown stage
  tests/platform_tests/test_reboot.py
Labels: automerge

#14855 [BGP TSA/TSB] Update tests execute TSA/TSB on sup cards, refactor test py files slightly, cover test gaps, bug fixes
  tests/bgp/route_checker.py
  tests/bgp/test_startup_tsa_tsb_service.py
  tests/bgp/test_traffic_shift_sup.py
Labels: Request for 202405 branch

#14888 Added test case to verify AZNG Migration for T2 topology
  tests/bgp/test_bgp_azng_migration.py
Labels: Request for 202205 branch, Request for 202405 branch

#15093 [action] [PR:14855] [BGP TSA/TSB] Update tests execute TSA/TSB on sup cards, refactor test py files slightly, cover test gaps, bug fixes
  tests/bgp/route_checker.py
  tests/bgp/test_startup_tsa_tsb_service.py
  tests/bgp/test_traffic_shift_sup.py
Labels: automerge

#14965 snappi: Adding a skip for global pause test in cisco-8000.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch

#15097 [action] [PR:14965] snappi: Adding a skip for global pause test in cisco-8000.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#15100 [action] [PR:15095] Update test_fancontrol.py to support Chassis which needs to run on Supervisor and not just random module
  tests/platform_tests/daemon/test_fancontrol.py
Labels: automerge

#15101 Resolve ip duplication between syslog server and bgp neighbor
  ansible/group_vars/lab/lab.yml
  tests/generic_config_updater/test_ntp.py
  tests/generic_config_updater/test_syslog.py
  tests/vs_voq_cfgs/vlab-t2-01_config_db.json
  tests/vs_voq_cfgs/vlab-t2-01_qos_new_dbfmt_config_db.json
  tests/vs_voq_cfgs/vlab-t2-02_config_db.json
  tests/vs_voq_cfgs/vlab-t2-02_qos_new_dbfmt_config_db.json
  tests/vs_voq_cfgs/vlab-t2-sup_config_db.json
  tests/vs_voq_cfgs/vlab-t2-sup_qos_new_dbfmt_config_db.json
Labels: Request for 202405 branch

#14282 restapi_vxlan_ecmp_test on mlnx 4600 and 8000 T1
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/restapi/test_restapi_vxlan_ecmp.py
Labels: Request for 202311 branch, Request for 202405 branch

#15102 Update qos parameters for hwsku Mellanox-4700-V64 and topology dualtor-aa-64-breakout
  tests/qos/files/qos_params.spc3.yaml
Labels: Request for 202405 branch

#14182 Update platform sfp tests to skip dom check for sfp with flat memory
  tests/common/platform/transceiver_utils.py
  tests/platform_tests/api/test_sfp.py
  tests/platform_tests/conftest.py
  tests/platform_tests/mellanox/test_check_sfp_eeprom.py
  tests/platform_tests/mellanox/util.py
  tests/platform_tests/test_xcvr_info_in_db.py
Labels: Request for 202405 branch

#14941 Skip CRC algorithm test on INNER_IP_PROTOCOL field
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch

#14914 Config vxlan port after config reload
  tests/hash/test_generic_hash.py
Labels: Request for 202311 branch, Request for 202405 branch

#14497 Add a loop check of loopback route after config reload for script test_traffic_shift.py
  tests/bgp/test_traffic_shift.py
Labels: Request for 202405 branch

#14478 Increase the check option of config reload in fixture simulate_small_var_log_partition
  tests/syslog/test_logrotate.py
Labels: Request for 202405 branch

#14427 Update software control module disable steps in fanout deployment
  ansible/roles/fanout/tasks/sonic/fanout_sonic_202311.yml
Labels: Request for 202311 branch, Request for 202405 branch

#14400 Update portchannel ip configuration command in generic hash script
  tests/hash/generic_hash_helper.py
Labels: Request for 202311 branch, Request for 202405 branch

#14399 Update hwsku Mellanox-SN4700-O32 into mellanox_spc3_hwskus
  ansible/group_vars/sonic/variables
Labels: Request for 202311 branch, Request for 202405 branch

#14300 Add dualtor-64-breakout topology to support case test_cacl_application_dualtor
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch

#14111 Update t1-32-lag support to pfcwd script
  tests/pfcwd/conftest.py
Labels: Request for 202405 branch

#15114 [action] [PR:15102] Update qos parameters for hwsku Mellanox-4700-V64 and topology dualtor-aa-64-breakout
  tests/qos/files/qos_params.spc3.yaml
Labels: automerge

#15112 [action] [PR:14282] restapi_vxlan_ecmp_test on mlnx 4600 and 8000 T1
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/restapi/test_restapi_vxlan_ecmp.py
Labels: automerge

#13766 Assign a specific balance deviation threshold for ingress port hash test
  tests/hash/generic_hash_helper.py
  tests/hash/test_generic_hash.py
Labels: Request for 202311 branch, Request for 202405 branch

#13480 Update skip condition of po2vlan test for sonic fanout
  tests/acl/test_acl_outer_vlan.py
  tests/common/helpers/portchannel_to_vlan.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#14008 [bookworm] Update loganalyzer ignore in test_vxlan_ecmp_switchover.py
  tests/vxlan/test_vxlan_ecmp_switchover.py
Labels: Request for 202405 branch

#14412 Fix test issue of the qos for the SPC4
  tests/qos/files/mellanox/qos_param_generator.py
Labels: Request for 202311 branch, Request for 202405 branch

#15121 [action] [PR:14399] Update hwsku Mellanox-SN4700-O32 into mellanox_spc3_hwskus
  ansible/group_vars/sonic/variables
Labels: automerge

#15119 [action] [PR:14427] Update software control module disable steps in fanout deployment
  ansible/roles/fanout/tasks/sonic/fanout_sonic_202311.yml
Labels: automerge

#15118 [action] [PR:14478] Increase the check option of config reload in fixture simulate_small_var_log_partition
  tests/syslog/test_logrotate.py
Labels: automerge

#15117 [action] [PR:14497] Add a loop check of loopback route after config reload for script test_traffic_shift.py
  tests/bgp/test_traffic_shift.py
Labels: automerge

#15116 [action] [PR:14914] Config vxlan port after config reload
  tests/hash/test_generic_hash.py
Labels: automerge

#15131 [action] [PR:14835] sonic-mgmt: Initial support for Arista-7060X6-64PE-C256S2
  ansible/group_vars/sonic/variables
  ansible/module_utils/port_utils.py
Labels: automerge

#15127 [action] [PR:14412] Fix test issue of the qos for the SPC4
  tests/qos/files/mellanox/qos_param_generator.py
Labels: automerge
