Repository sonic-net/sonic-mgmt, pull requests merged in 2024-06, with the labels that each got.

#13004 [dualtor][active-standby] disable timed oscillation
  tests/common/dualtor/dual_tor_utils.py
  tests/conftest.py
Labels: Request for 202311 branch

#13046 Skip test_clock if ntp_server is not provided
  tests/clock/conftest.py
Labels: Request for 202311 branch

#13095 [action] [PR:13046] Skip test_clock if ntp_server is not provided
  tests/clock/conftest.py
Labels: automerge

#13106 [action] [PR:13004] [dualtor][active-standby] disable timed oscillation
  tests/common/dualtor/dual_tor_utils.py
  tests/conftest.py
Labels: automerge

#12895 [Mellanox] Skip asic mock in test_device_checker for mellanox device
  tests/common/fixtures/duthost_utils.py
  tests/system_health/test_system_health.py
Labels: Request for 202311 branch

#12931 Skip iface loopback test if Leaf-fanout switch is running SONiC and Mellanox ASIC
  tests/iface_loopback_action/conftest.py
Labels: Request for 202311 branch

#13128 [action] [PR:12931] Skip iface loopback test if Leaf-fanout switch is running SONiC and Mellanox ASIC
  tests/iface_loopback_action/conftest.py
Labels: automerge

#13145 [action] [PR:12754] Fix switch.py for password based login
  ansible/plugins/connection/switch.py
Labels: automerge

#13150 [action] [PR:13014] Fix GCU Dynamic ACL ARP bug caused by stale ip config in PTFhost
  tests/generic_config_updater/test_dynamic_acl.py
Labels: automerge

#13076 skip bgp/test_bgp_slb::test_bgp_slb_neighbor_persistence_across_advanced_reboot on SN4700
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch, Request for 202311 branch

#12002 [Snappi] Bugfix to ignore ixia chassis for setting up fanouthosts
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#12996 Fix 'drop_packets/test_configurable_drop_counters.py' on dualtor
  tests/drop_packets/test_configurable_drop_counters.py
Labels: Request for 202305 branch, Request for 202311 branch

#13146 [action] [PR:12754] Fix switch.py for password based login
  ansible/plugins/connection/switch.py
Labels: automerge

#13160 [action] [PR:12996] Fix 'drop_packets/test_configurable_drop_counters.py' on dualtor
  tests/drop_packets/test_configurable_drop_counters.py
Labels: automerge

#13062 [Mellanox] Add SONiC as fanout switch
  ansible/roles/fanout/tasks/fanout_sonic.yml
  ansible/roles/fanout/tasks/sonic/fanout_sonic_202311.yml
  ansible/roles/fanout/templates/sonic_deploy_202311.j2
Labels: Request for 202311 branch

#13170 [action] [PR:13062] [Mellanox] Add SONiC as fanout switch
  ansible/roles/fanout/tasks/fanout_sonic.yml
  ansible/roles/fanout/tasks/sonic/fanout_sonic_202311.yml
  ansible/roles/fanout/templates/sonic_deploy_202311.j2
Labels: automerge

#13169 [action] [PR:13062] [Mellanox] Add SONiC as fanout switch
  ansible/roles/fanout/tasks/fanout_sonic.yml
  ansible/roles/fanout/tasks/sonic/fanout_sonic_202311.yml
  ansible/roles/fanout/templates/sonic_deploy_202311.j2
Labels: automerge

#13171 Fix ASIC check on Non-SONiC leaf fanout
  tests/iface_loopback_action/conftest.py
Labels: Request for 202311 branch, Request for 202405 branch

#13174 Stabilize setup_tacacs_client
  tests/tacacs/utils.py
Labels: Request for 202311 branch, Request for 202405 branch

#13178 [action] [PR:13174] Stabilize setup_tacacs_client
  tests/tacacs/utils.py
Labels: automerge

#13176 [action] [PR:13171] Fix ASIC check on Non-SONiC leaf fanout
  tests/iface_loopback_action/conftest.py
Labels: automerge

#13177 [action] [PR:13171] Fix ASIC check on Non-SONiC leaf fanout
  tests/iface_loopback_action/conftest.py
Labels: automerge

#13180 [action] [PR:11998] Add k SKUs for QOS tests
  ansible/group_vars/sonic/variables
Labels: automerge

#13183 [action] [PR:13063] refactor: refactor bfd static route tests
  tests/bfd/bfd_base.py
  tests/bfd/bfd_helpers.py
  tests/bfd/conftest.py
  tests/bfd/test_bfd_static_route.py
  tests/common/plugins/sanity_check/checks.py
Labels: automerge

#12848 [Mellanox]Add support for new hwsku of SN5600
  ansible/group_vars/sonic/variables
  ansible/module_utils/port_utils.py
  tests/common/mellanox_data.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202311 branch, Request for 202405 branch

#13207 [action] [PR:12735] Add buffer queue counters test case to telemetry test
  tests/telemetry/test_telemetry.py
Labels: automerge

#13208 Skip SNMP link local test in 202311 branch
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202311 branch, Request for 202405 branch

#13212 [action] [PR:13208] Skip SNMP link local test in 202311 branch
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#13184 Fix gnmi client compatible issue
  tests/gnmi/conftest.py
  tests/gnmi/helper.py
  tests/gnmi/test_gnmi_appldb.py
  tests/gnmi/test_gnmi_configdb.py
Labels: Request for 202405 branch

#12975 Add t1-28-lag to the supported T1 topo of pfcwd test
  tests/pfcwd/conftest.py
Labels: Request for 202405 branch

#13219 [action] [PR:13184] Fix gnmi client compatible issue
  tests/gnmi/conftest.py
  tests/gnmi/helper.py
  tests/gnmi/test_gnmi_appldb.py
  tests/gnmi/test_gnmi_configdb.py
Labels: automerge

#13225 [action] [PR:11928] Add script `arp/test_stress_arp.py` into nightly test
  tests/arp/test_stress_arp.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#13224 [action] [PR:11928] Add script `arp/test_stress_arp.py` into nightly test
  tests/arp/test_stress_arp.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#13222 [action] [PR:11922] Remove unnecessary steps in script `test_stress_arp.py` to save running time.
  tests/arp/test_stress_arp.py
Labels: automerge

#13213 ipv6_fixture needs to wait for all services to be up
  tests/common/fixtures/duthost_utils.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#13232 [action] [PR:13208] Skip SNMP link local test in 202311 branch
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#13237 [action] [PR:13213] ipv6_fixture needs to wait for all services to be up
  tests/common/fixtures/duthost_utils.py
Labels: automerge

#13239 [action] [PR:12996] Fix 'drop_packets/test_configurable_drop_counters.py' on dualtor
  tests/drop_packets/test_configurable_drop_counters.py
Labels: automerge

#13238 [action] [PR:13118] Fix route/test_forced_mgmt_route.py
  tests/route/test_forced_mgmt_route.py
Labels: automerge

#13236 [action] [PR:11998] Add k SKUs for QOS tests
  ansible/group_vars/sonic/variables
Labels: automerge

#12202 Fixing global_pause attribute and speed typecasting
  tests/common/snappi_tests/snappi_fixtures.py
  tests/snappi_tests/multidut/pfc/files/multidut_helper.py
Labels: Request for 202205 branch

#8026 [Snappi] Adding Many To One Fluctuating Lossless Testcase
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/test_m2o_fluctuating_lossless.py
Labels: chassis

#13252 [action] [PR:12848] [Mellanox] Add support for new hwsku of SN5600
  ansible/group_vars/sonic/variables
  ansible/module_utils/port_utils.py
  tests/common/mellanox_data.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#13251 [action] [PR:12975] Add t1-28-lag to the supported T1 topo of pfcwd test
  tests/pfcwd/conftest.py
Labels: automerge

#13250 [action] [PR:12996] Fix 'drop_packets/test_configurable_drop_counters.py' on dualtor
  tests/drop_packets/test_configurable_drop_counters.py
Labels: automerge

#13248 [action] [PR:13115] Remove lldp as default service for Chassis
  tests/common/devices/multi_asic.py
Labels: automerge

#13246 [action] [PR:13234] feat: add completeness level to BFD static route tests
  tests/bfd/conftest.py
  tests/bfd/test_bfd_static_route.py
Labels: automerge

#13249 [action] [PR:13111] [Arista] Add Quicksilver HW SKUs
  ansible/group_vars/sonic/variables
Labels: automerge

#13054 [action] [PR:13001] Fix definitions of active-active dualtor fixtures
  tests/common/dualtor/dual_tor_utils.py
Labels: automerge

#13230 Add TH5 ASIC type for QoS Tests
  tests/qos/qos_sai_base.py
Labels: Request for 202311 branch

#13223 [action] [PR:11922] Remove unnecessary steps in script `test_stress_arp.py` to save running time.
  tests/arp/test_stress_arp.py
Labels: automerge

#13254 Fix test_check_show_lpmode testcase failure
  tests/platform_tests/sfp/test_show_intf_xcvr.py
  tests/platform_tests/sfp/util.py
Labels: Request for 202405 branch

#13181 Fix the issue where test_copp.py::TestCOPP::test_remove_trap is stuck on Cisco platform
  tests/copp/test_copp.py
Labels: Request for 202311 branch, Request for 202405 branch

#13188 Don't call expensive fixtures if skipping sanity
  tests/common/plugins/sanity_check/__init__.py
Labels: Request for 202311 branch, Request for 202405 branch

#13261 [action] [PR:13230] Add TH5 ASIC type for QoS Tests
  tests/qos/qos_sai_base.py
Labels: automerge

#13260 [action] [PR:13119] Fix qos/test_qos_dscp_mapping.py
  tests/common/helpers/ptf_tests_helper.py
  tests/qos/test_qos_dscp_mapping.py
Labels: automerge

#13259 [action] [PR:12608] Fix platform_tests/api/test_fan_drawer_fans.py
  tests/platform_tests/api/test_fan_drawer_fans.py
Labels: automerge

#13258 [action] [PR:12608] Fix platform_tests/api/test_fan_drawer_fans.py
  tests/platform_tests/api/test_fan_drawer_fans.py
Labels: automerge

#13257 [action] [PR:12530] Fix qos/test_pfc_pause.py for dualtor-aa
  tests/qos/test_pfc_pause.py
Labels: automerge

#13263 Fix mux simulator post
  tests/common/dualtor/mux_simulator_control.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#13264 [dualtor] Skip advanced reboot cases on dualtor-aa
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#13268 [action] [PR:13188] Don't call expensive fixtures if skipping sanity
  tests/common/plugins/sanity_check/__init__.py
Labels: automerge

#13265 [action] [PR:13181] Fix the issue where test_copp.py::TestCOPP::test_remove_trap is stuck on Cisco platform
  tests/copp/test_copp.py
Labels: automerge

#13267 [action] [PR:13188] Don't call expensive fixtures if skipping sanity
  tests/common/plugins/sanity_check/__init__.py
Labels: automerge

#13266 [action] [PR:13181] Fix the issue where test_copp.py::TestCOPP::test_remove_trap is stuck on Cisco platform
  tests/copp/test_copp.py
Labels: automerge

#13275 [action] [PR:13263] Fix mux simulator post
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#13273 [action] [PR:13264] [dualtor] Skip advanced reboot cases on dualtor-aa
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#13271 [action] [PR:13263] Fix mux simulator post
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#12925 Skip inner hashing test on non-required platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch, Request for 202311 branch

#13289 [action] [PR:12202] Fixing global_pause attribute and speed typecasting
  tests/common/snappi_tests/snappi_fixtures.py
  tests/snappi_tests/multidut/pfc/files/multidut_helper.py
Labels: automerge

#13288 [action] [PR:8026] [Snappi] Adding Many To One Fluctuating Lossless Testcase
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/test_m2o_fluctuating_lossless.py
Labels: automerge

#13287 [action] [PR:13155] Adding warm-up traffic for multidut pfcwd case
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_basic_helper.py
Labels: automerge

#13285 [action] [PR:13154] Fixing Oversubscription verification and removing config_reload from ecn
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/multidut/ecn/test_multidut_dequeue_ecn_with_snappi.py
  tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
  tests/snappi_tests/multidut/pfc/test_lossless_response_to_external_pause_storms.py
  tests/snappi_tests/multidut/pfc/test_lossless_response_to_throttling_pause_storms.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless_lossy.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossy.py
Labels: automerge

#13284 [action] [PR:12002] [Snappi] Bugfix to ignore ixia chassis for setting up fanouthosts
  tests/conftest.py
Labels: automerge

#13286 [action] [PR:12135] Fix for passing snappi api credentials
  tests/common/snappi_tests/snappi_fixtures.py
Labels: automerge

#12853 Fixing iteration count and kmin,kmax for ecn scripts
  tests/snappi_tests/ecn/test_red_accuracy_with_snappi.py
  tests/snappi_tests/multidut/ecn/files/multidut_helper.py
  tests/snappi_tests/multidut/ecn/test_multidut_dequeue_ecn_with_snappi.py
  tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
Labels: Request for 202405 branch

#11968 Full Mesh Traffic Sanity verification
  tests/common/plugins/conditional_mark/__init__.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202311 branch, Request for 202405 branch

#13297 [action] [PR:13277] Fix convert_and_restore_config_db_to_ipv6_only reload config failure
  tests/common/fixtures/duthost_utils.py
Labels: automerge

#13296 [action] [PR:13277] Fix convert_and_restore_config_db_to_ipv6_only reload config failure
  tests/common/fixtures/duthost_utils.py
Labels: automerge

#13295 [action] [PR:13277] Fix convert_and_restore_config_db_to_ipv6_only reload config failure
  tests/common/fixtures/duthost_utils.py
Labels: automerge

#13272 [action] [PR:13263] Fix mux simulator post
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#13306 [action] [PR:13280] Fix Test_syslog_source_ip issue
  tests/syslog/test_syslog_source_ip.py
Labels: automerge

#13305 [action] [PR:13280] Fix Test_syslog_source_ip issue
  tests/syslog/test_syslog_source_ip.py
Labels: automerge

#13307 [action] [PR:12853] Fixing iteration count and kmin,kmax for ecn scripts
  tests/snappi_tests/ecn/test_red_accuracy_with_snappi.py
  tests/snappi_tests/multidut/ecn/files/multidut_helper.py
  tests/snappi_tests/multidut/ecn/test_multidut_dequeue_ecn_with_snappi.py
  tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
Labels: automerge

#13299 [action] [PR:12467] [test_fdb_mac_move] Only output error level message into syslog if /var/log size limitation
  tests/fdb/test_fdb_mac_move.py
Labels: automerge

#13300 [action] [PR:12467] [test_fdb_mac_move] Only output error level message into syslog if /var/log size limitation
  tests/fdb/test_fdb_mac_move.py
Labels: automerge

#13292 [action] [PR:12925] Skip inner hashing test on non-required platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#13291 [action] [PR:12925] Skip inner hashing test on non-required platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#13247 [action] [PR:13119] Fix qos/test_qos_dscp_mapping.py
  tests/common/helpers/ptf_tests_helper.py
  tests/qos/test_qos_dscp_mapping.py
Labels: automerge

#12480 [BGP suppress fib] Use safe config reload in test case test_bgp_route_with_suppress
  tests/bgp/test_bgp_suppress_fib.py
Labels: Request for 202311 branch, Request for 202405 branch

#13096 Improve test_bgpmon - use `ip route replace` instead of `ip route add`
  tests/bgp/test_bgpmon.py
Labels: Request for 202311 branch

#13325 [action] [PR:13096] Improve test_bgpmon - use `ip route replace` instead of `ip route add`
  tests/bgp/test_bgpmon.py
Labels: automerge

#13294 Add error tolerance for drop counter test
  tests/common/helpers/drop_counters/drop_counters.py
Labels: Request for 202311 branch, Request for 202405 branch

#13328 [action] [PR:13294] Add error tolerance for drop counter test
  tests/common/helpers/drop_counters/drop_counters.py
Labels: automerge

#13327 [action] [PR:13294] Add error tolerance for drop counter test
  tests/common/helpers/drop_counters/drop_counters.py
Labels: automerge

#13331 [action] [PR:13302] Fix import AnsibleConnectionFailure from ansible.errors issue.
  tests/common/fixtures/duthost_utils.py
Labels: automerge

#13330 [action] [PR:13302] Fix import AnsibleConnectionFailure from ansible.errors issue.
  tests/common/fixtures/duthost_utils.py
Labels: automerge

#13329 [action] [PR:13302] Fix import AnsibleConnectionFailure from ansible.errors issue.
  tests/common/fixtures/duthost_utils.py
Labels: automerge

#13333 [action] [PR:13323] Update getbuild.py to support both PAT and access_token
  tests/scripts/getbuild.py
Labels: automerge

#13334 [action] [PR:13323] Update getbuild.py to support both PAT and access_token
  tests/scripts/getbuild.py
Labels: automerge

#13339 [platform_tests.broadcom.test_ser] update timeout items for test ser case
  tests/platform_tests/broadcom/files/ser_injector.py
Labels: Request for 202311 branch

#13346 [action] [PR:13339] [platform_tests.broadcom.test_ser] update timeout items for test ser case
  tests/platform_tests/broadcom/files/ser_injector.py
Labels: automerge

#13348 [action] [PR:13230] Add TH5 ASIC type for QoS Tests
  tests/qos/qos_sai_base.py
Labels: automerge

#13349 Ignore message SDK_LOG|-E-HLD-0
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#13352 [action] [PR:13349] Ignore message SDK_LOG|-E-HLD-0
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#13351 [action] [PR:13349] Ignore message SDK_LOG|-E-HLD-0
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#13350 [action] [PR:13349] Ignore message SDK_LOG|-E-HLD-0
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#13332 [action] [PR:13323] Update getbuild.py to support both PAT and access_token
  tests/scripts/getbuild.py
Labels: automerge

#13357 [action] [PR:13309] Skip the temperature checks for empty SFP ports
  tests/platform_tests/mellanox/check_sysfs.py
Labels: automerge

#13362 Remove skip conditional - test_decap on 8111 T0 and 8111 T1 topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#13279 Fix dualtor_mgmt/test_toggle_mux.py
  tests/dualtor_mgmt/test_toggle_mux.py
Labels: Request for 202311 branch, Request for 202405 branch

#13358 [action] [PR:13309] Skip the temperature checks for empty SFP ports
  tests/platform_tests/mellanox/check_sysfs.py
Labels: automerge

#13374 [action] [PR:12719] port_alias.py: Handle port_config.ini header change
  ansible/library/port_alias.py
Labels: automerge

#13373 [action] [PR:13279] Fix dualtor_mgmt/test_toggle_mux.py
  tests/dualtor_mgmt/test_toggle_mux.py
Labels: automerge

#13371 [action] [PR:13362] Remove skip conditional - test_decap on 8111 T0 and 8111 T1 topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#13370 [action] [PR:13362] Remove skip conditional - test_decap on 8111 T0 and 8111 T1 topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#13161 [action] [PR:13118] Fix route/test_forced_mgmt_route.py
  tests/route/test_forced_mgmt_route.py
Labels: automerge

#13381 [action] [PR:12480] [BGP suppress fib] Use safe config reload in test case test_bgp_route_with_suppress
  tests/bgp/test_bgp_suppress_fib.py
Labels: automerge

#13360 Add physical mark for bfd tests
  tests/bfd/test_bfd.py
  tests/bfd/test_bfd_static_route.py
Labels: Request for 202405 branch

#12004 [Fix]: Fixing extra args, comments and adding skip warm reboot for Issue #11999
  tests/snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py
  tests/snappi_tests/test_multidut_snappi.py
Labels: Request for 202405 branch

#12882 [Mellanox] Stabilize test_crm_route
  tests/common/helpers/dut_utils.py
  tests/crm/conftest.py
  tests/crm/test_crm.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#13354 [Mellanox]Revert "Skip available route check for mellanox platforms (#12787)"
  tests/crm/test_crm.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#13341 feat: support stress routes test on T2 topo
  tests/stress/conftest.py
  tests/stress/test_stress_routes.py
  tests/stress/utils.py
Labels: Request for 202205 branch, Request for 202405 branch

#13401 [action] [PR:13363] Fix test_qos_sai teardown for dualtor
  tests/qos/qos_sai_base.py
Labels: automerge

#13397 [action] [PR:13320] Fix force_mgmt_route failed on some hardware because snmp agent can't bind to eth1 address issue.
  tests/override_config_table/utilities.py
  tests/route/test_forced_mgmt_route.py
Labels: automerge

#12969 Add pkts_num_hysteresis for new rx cgm profile
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/files/qos_params.gb.yaml
  tests/qos/files/qos_params.pac.yaml
Labels: Request for 202311 branch, Request for 202405 branch

#13398 [action] [PR:13320] Fix force_mgmt_route failed on some hardware because snmp agent can't bind to eth1 address issue.
  tests/override_config_table/utilities.py
  tests/route/test_forced_mgmt_route.py
Labels: automerge

#13430 [action] [PR:12959] Pin requests to version 2.31.0 in main.yml
  ansible/roles/vm_set/tasks/main.yml
Labels: automerge

#13426 [action] [PR:13411] Enhance the test_ro_user test case to check for user permissions errors.
  tests/tacacs/test_ro_user.py
Labels: automerge

#13420 [action] [PR:12969] Add pkts_num_hysteresis for new rx cgm profile
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/files/qos_params.gb.yaml
  tests/qos/files/qos_params.pac.yaml
Labels: automerge

#13399 [action] [PR:13320] Fix force_mgmt_route failed on some hardware because snmp agent can't bind to eth1 address issue.
  tests/override_config_table/utilities.py
  tests/route/test_forced_mgmt_route.py
Labels: automerge

#13396 [action] [PR:13342] [TACACS] Fix error in accounting test case
  tests/tacacs/test_accounting.py
Labels: automerge

#13387 [action] [PR:13354] [Mellanox]Revert "Skip available route check for mellanox platforms (#12787)"
  tests/crm/test_crm.py
Labels: automerge

#13406 Adding support for RDMA cases for pfcQueueGroupSize of 4
  tests/common/snappi_tests/snappi_fixtures.py
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/variables.py
Labels: Request for 202405 branch

#13245 Adding ansible file samples for snappi-sonic
  ansible/files/graph_groups.yml
  ansible/files/sonic_example_ixia_devices.csv
  ansible/files/sonic_example_ixia_link.csv
  ansible/files/sonic_snappi-sonic_devices.csv
  ansible/files/sonic_snappi-sonic_links.csv
  ansible/group_vars/snappi-sonic/secrets.yml
  ansible/group_vars/snappi-sonic/snappi-sonic.yml
  ansible/snappi-sonic
  ansible/testbed.csv
  ansible/testbed.yaml
  tests/snappi_tests/DockerCommands.md
  tests/snappi_tests/README.md
Labels: Request for 202405 branch

#13316 Add loganalyzer_common_ignore regexs for config reload on broadcom
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202311 branch

#13395 fix: correct show bgp summary output typo references
  docs/testbed/README.testbed.VsSetup.md
  tests/route/test_route_flow_counter.py
  tests/stress/utils.py
Labels: Request for 202405 branch

#13429 [action] [PR:12959] Pin requests to version 2.31.0 in main.yml
  ansible/roles/vm_set/tasks/main.yml
Labels: automerge

#13425 [action] [PR:13411] Enhance the test_ro_user test case to check for user permissions errors.
  tests/tacacs/test_ro_user.py
Labels: automerge

#13442 [action] [PR:13316] Add loganalyzer_common_ignore regexs for config reload on broadcom
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#13432 [action] [PR:12959] Pin requests to version 2.31.0 in main.yml
  ansible/roles/vm_set/tasks/main.yml
Labels: automerge

#13431 [action] [PR:12959] Pin requests to version 2.31.0 in main.yml
  ansible/roles/vm_set/tasks/main.yml
Labels: automerge

#13385 [202311]Skip warmreboot on SN4700 t0 devices since it is currently not qualified.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202311 branch

#13427 [action] [PR:13411] Enhance the test_ro_user test case to check for user permissions errors.
  tests/tacacs/test_ro_user.py
Labels: automerge

#13386 [action] [PR:12878] [Arista] Add BTHD and CTD HW SKUs
  ansible/group_vars/sonic/variables
Labels: automerge

#13445 [action] [PR:13395] fix: correct show bgp summary output typo references
  docs/testbed/README.testbed.VsSetup.md
  tests/route/test_route_flow_counter.py
  tests/stress/utils.py
Labels: automerge

#13421 [action] [PR:13341] feat: support stress routes test on T2 topo
  tests/stress/conftest.py
  tests/stress/test_stress_routes.py
  tests/stress/utils.py
Labels: automerge

#12564 Enhance generic hash test cases
  ansible/roles/test/files/ptftests/py3/generic_hash_test.py
  tests/common/devices/sonic.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/hash/conftest.py
  tests/hash/generic_hash_helper.py
  tests/hash/test_generic_hash.py
Labels: Request for 202311 branch, Request for 202405 branch

#13456 [action] [PR:13344] [TACACS] Add debug info for check nss config missing issue.
  tests/tacacs/conftest.py
Labels: automerge

#13457 Fix dualtor sanity mux probe recovery
  tests/common/plugins/sanity_check/checks.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch
