Repository sonic-net/sonic-mgmt, pull requests merged in 2024-04, with the labels that each got.

#12062 assign correct test ports for th platflorm's t1-64-lag topology
  tests/qos/files/qos_params.th.yaml
Labels: Request for 202305 branch, Request for 202311 branch

#12246 [action] [PR:12062] assign correct test ports for th platflorm's t1-64-lag topology
  tests/qos/files/qos_params.th.yaml
Labels: automerge

#12245 [action] [PR:12062] assign correct test ports for th platflorm's t1-64-lag topology
  tests/qos/files/qos_params.th.yaml
Labels: automerge

#12223 [Snappi] Validate pfc frame test enhancement
  tests/common/snappi_tests/read_pcap.py
  tests/snappi_tests/multidut/pfc/files/multidut_helper.py
  tests/snappi_tests/pfc/files/helper.py
Labels: Request for 202305 branch, Request for 202311 branch

#12228 [Snappi] Change polling interval for traffic flows for pfc pause tests
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/multidut/pfc/files/multidut_helper.py
  tests/snappi_tests/pfc/files/helper.py
Labels: Request for 202305 branch, Request for 202311 branch

#12174 Ignore error messages when querying debug counter
  tests/drop_packets/test_configurable_drop_counters.py
Labels: Request for 202305 branch, Request for 202311 branch

#12239 Improve test case test_encap_with_mirror_session to support Active-Active DualToR
  tests/dualtor/test_ipinip.py
Labels: Request for 202305 branch, Request for 202311 branch

#12261 [action] [PR:12239] Improve test case test_encap_with_mirror_session to support Active-Active DualToR
  tests/dualtor/test_ipinip.py
Labels: automerge

#12260 [action] [PR:12239] Improve test case test_encap_with_mirror_session to support Active-Active DualToR
  tests/dualtor/test_ipinip.py
Labels: automerge

#12253 Add a common function to connect DUT using paramiko.
  tests/common/utilities.py
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#12252 [action] [PR:10276] Dtor changes
  tests/common/dualtor/constants.py
  tests/common/dualtor/data_plane_utils.py
  tests/common/fixtures/ptfhost_utils.py
Labels: automerge

#12251 [action] [PR:10276] Dtor changes
  tests/common/dualtor/constants.py
  tests/common/dualtor/data_plane_utils.py
  tests/common/fixtures/ptfhost_utils.py
Labels: automerge

#12250 [action] [PR:10425] Dynamic PORT selection for PFC storm testing
  tests/telemetry/events/swss_events.py
Labels: automerge

#12249 [action] [PR:11892] ACL testcases in A/A setup need additional rules to ALLOW the ICMP keepalives to ensure both TORs don't go in STANDBY mode
  tests/acl/templates/acltb_test_rules.j2
  tests/acl/templates/acltb_test_rules_part_1.j2
  tests/acl/templates/acltb_test_rules_part_2.j2
  tests/acl/test_acl.py
Labels: automerge

#12248 [action] [PR:11892] ACL testcases in A/A setup need additional rules to ALLOW the ICMP keepalives to ensure both TORs don't go in STANDBY mode
  tests/acl/templates/acltb_test_rules.j2
  tests/acl/templates/acltb_test_rules_part_1.j2
  tests/acl/templates/acltb_test_rules_part_2.j2
  tests/acl/test_acl.py
Labels: automerge

#12084 remove low speed port from test port list for breakout test scenario
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: Request for 202305 branch, Request for 202311 branch

#12272 [action] [PR:12084] remove low speed port from test port list for breakout test scenario
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: automerge

#12271 [action] [PR:12084] remove low speed port from test port list for breakout test scenario
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: automerge

#12274 [action] [PR:12074] Fix dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_default for dualtor.
  tests/dhcp_relay/test_dhcp_relay.py
Labels: automerge

#12263 Fix IndexError in test_no_pfc
  tests/qos/test_pfc_pause.py
Labels: Request for 202305 branch, Request for 202311 branch

#12277 [action] [PR:11695] Fix dhcpv6 testcase failures in Dual TOR Setups
  ansible/roles/test/files/ptftests/py3/dhcpv6_counter_test.py
  ansible/roles/test/files/ptftests/py3/dhcpv6_relay_test.py
  tests/dhcp_relay/test_dhcpv6_relay.py
Labels: automerge

#12276 [action] [PR:11695] Fix dhcpv6 testcase failures in Dual TOR Setups
  ansible/roles/test/files/ptftests/py3/dhcpv6_counter_test.py
  ansible/roles/test/files/ptftests/py3/dhcpv6_relay_test.py
  tests/dhcp_relay/test_dhcpv6_relay.py
Labels: automerge

#12237 Add test case to verify snmp over mgmt IPv6 with ipv6 only config
  tests/ip/test_mgmt_ipv6_only.py
Labels: Request for 202305 branch, Request for 202311 branch

#12280 [action] [PR:11777] Generic Config Updater Dynamic ACL Update test
  tests/generic_config_updater/gu_utils.py
  tests/generic_config_updater/templates/create_arp_forward_rule.json
  tests/generic_config_updater/templates/create_custom_table.j2
  tests/generic_config_updater/templates/create_custom_table_type.json
  tests/generic_config_updater/templates/create_dhcp_forward_rule_both.json
  tests/generic_config_updater/templates/create_forward_rules.j2
  tests/generic_config_updater/templates/create_initial_drop_rule.j2
  tests/generic_config_updater/templates/create_ndp_forward_rule.json
  tests/generic_config_updater/templates/create_secondary_drop_rule.j2
  tests/generic_config_updater/templates/create_three_drop_rules.j2
  tests/generic_config_updater/templates/remove_ipv4_forward_rule.json
  tests/generic_config_updater/templates/remove_ipv6_forward_rule.json
  tests/generic_config_updater/templates/remove_nonexistent_table.json
  tests/generic_config_updater/templates/remove_rule.j2
  tests/generic_config_updater/templates/remove_table.json
  tests/generic_config_updater/templates/remove_table_type.json
  tests/generic_config_updater/templates/remove_third_drop_rule.json
  tests/generic_config_updater/templates/replace_nonexistent_rule.json
  tests/generic_config_updater/templates/replace_rules.j2
  tests/generic_config_updater/test_dynamic_acl.py
Labels: automerge

#12259 [Bugfix][Warmboot][PFCWD] PFC storm triggers to debug mode only during warmboot tests
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: Request for 202305 branch, Request for 202311 branch

#12282 [action] [PR:12174] Ignore error messages when querying debug counter
  tests/drop_packets/test_configurable_drop_counters.py
Labels: automerge

#12265 fix 7050cx lossyqueue failure
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202305 branch, Request for 202311 branch

#12273 Skip test_ssh_default_password.py due to password rotation
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#12301 [action] [PR:12273] Skip test_ssh_default_password.py due to password rotation
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#12299 [action] [PR:12273] Skip test_ssh_default_password.py due to password rotation
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#12300 [action] [PR:12273] Skip test_ssh_default_password.py due to password rotation
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#12298 [action] [PR:12273] Skip test_ssh_default_password.py due to password rotation
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#12295 [action] [PR:12263] Fix IndexError in test_no_pfc
  tests/qos/test_pfc_pause.py
Labels: automerge

#12294 [action] [PR:12265] fix 7050cx lossyqueue failure
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#12293 [action] [PR:12265] fix 7050cx lossyqueue failure
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#12264 Fix issues in `test_ssh_ciphers.py` caused by password rotation
  tests/ssh/test_ssh_ciphers.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#12255 Fix the issue in `test_ssh_limit.py` due to password rotation
  tests/common/utilities.py
  tests/ssh/test_ssh_limit.py
  tests/tacacs/test_authorization.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#12291 [Bugfix] Get crm_interface fixture results on backend testbeds
  tests/crm/conftest.py
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#11698 Refactor upgrade path tests
  tests/common/fixtures/advanced_reboot.py
  tests/platform_tests/args/advanced_reboot_args.py
  tests/upgrade_path/test_upgrade_path.py
  tests/upgrade_path/upgrade_helpers.py
Labels: Request for 202305 branch, Request for 202311 branch

#12315 [action] [PR:11705] Disable test_bgp_queue mlnx 2700 T1
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#12303 Fix ptf can't ssh dut issue due to password rotation
  tests/common/utilities.py
  tests/conftest.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#12327 [action] [PR:12216] [multi-password] Add action plugin to get the hash of currently used password
  ansible/plugins/action/current_password.py
  ansible/plugins/connection/multi_passwd_ssh.py
Labels: automerge

#12322 [action] [PR:12320] Revert "ACL testcases in A/A setup need additional rules to ALLOW the ICMP keepalives to ensure both TORs don't go in STANDBY mode"
  tests/acl/templates/acltb_test_rules.j2
  tests/acl/templates/acltb_test_rules_part_1.j2
  tests/acl/templates/acltb_test_rules_part_2.j2
  tests/acl/test_acl.py
Labels: automerge

#12325 [IPv6 only] Fix ipv6_only fixture to remove ipv4 from snmp agent address
  tests/common/fixtures/duthost_utils.py
Labels: Request for 202305 branch, Request for 202311 branch

#12341 [action] [PR:12325] [IPv6 only] Fix ipv6_only fixture to remove ipv4 from snmp agent address
  tests/common/fixtures/duthost_utils.py
Labels: automerge

#12196 Add conditional marker to xfail IP-IP dscp mapping test on broadcom asics
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#12289 [Bugfix] Test_copp bugfix for backend testbeds
  tests/copp/conftest.py
  tests/copp/test_copp.py
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#12332 [202305] Fix issues due to password rotation.
  tests/common/utilities.py
  tests/conftest.py
  tests/ssh/test_ssh_ciphers.py
  tests/ssh/test_ssh_limit.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202311 branch

#12343 [action] [PR:12283] [Testfix ]vxlan ecmp rest api test disable for T0.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#12340 [action] [PR:12325] [IPv6 only] Fix ipv6_only fixture to remove ipv4 from snmp agent address
  tests/common/fixtures/duthost_utils.py
Labels: automerge

#12348 [action] [PR:12289] [Bugfix] Test_copp bugfix for backend testbeds
  tests/copp/conftest.py
  tests/copp/test_copp.py
Labels: automerge

#12347 [action] [PR:12196] Add conditional marker to xfail IP-IP dscp mapping test on broadcom asics
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#12330 [action] [PR:12216] [multi-password] Add action plugin to get the hash of currently used password
  ansible/plugins/action/current_password.py
  ansible/plugins/connection/multi_passwd_ssh.py
Labels: automerge

#12329 [action] [PR:12216] [multi-password] Add action plugin to get the hash of currently used password
  ansible/plugins/action/current_password.py
  ansible/plugins/connection/multi_passwd_ssh.py
Labels: automerge

#12328 [action] [PR:12216] [multi-password] Add action plugin to get the hash of currently used password
  ansible/plugins/action/current_password.py
  ansible/plugins/connection/multi_passwd_ssh.py
Labels: automerge

#12270 [Fix] Fix ssh connect failed due to default password rotation for getting default passwords
  tests/disk/test_disk_exhaustion.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#12357 [action] [PR:11393] Add forced mgmt route test case.
  tests/route/test_forced_mgmt_route.py
Labels: automerge

#12356 [action] [PR:11393] Add forced mgmt route test case.
  tests/route/test_forced_mgmt_route.py
Labels: automerge

#12335 Add log for exited critical process in common function `get_critical_processes_status`
  tests/common/platform/processes_utils.py
Labels: Request for 202305 branch, Request for 202311 branch

#12360 Revert "Fix dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_default for dualtor."
  tests/dhcp_relay/test_dhcp_relay.py
Labels: Request for 202305 branch, Request for 202311 branch

#12367 [action] [PR:12005] Enable SSH keep-alive when connecting via Ansible
  ansible/ansible.cfg
Labels: automerge

#12363 [action] [PR:12270] [Fix] Fix ssh connect failed due to default password rotation for getting default passwords
  tests/disk/test_disk_exhaustion.py
Labels: automerge

#12371 [action] [PR:12318] Enhance the "switch" connection plugin to hand Passwordless Login
  ansible/plugins/connection/switch.py
Labels: automerge

#12370 [action] [PR:12318] Enhance the "switch" connection plugin to hand Passwordless Login
  ansible/plugins/connection/switch.py
Labels: automerge

#12369 [action] [PR:12005] Enable SSH keep-alive when connecting via Ansible
  ansible/ansible.cfg
Labels: automerge

#12368 [action] [PR:12005] Enable SSH keep-alive when connecting via Ansible
  ansible/ansible.cfg
Labels: automerge

#12366 [action] [PR:12005] Enable SSH keep-alive when connecting via Ansible
  ansible/ansible.cfg
Labels: automerge

#12365 [action] [PR:12335] Add log for exited critical process in common function `get_critical_processes_status`
  tests/common/platform/processes_utils.py
Labels: automerge

#12364 [action] [PR:12335] Add log for exited critical process in common function `get_critical_processes_status`
  tests/common/platform/processes_utils.py
Labels: automerge

#12373 [action] [PR:12360] Revert "Fix dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_default for dualtor."
  tests/dhcp_relay/test_dhcp_relay.py
Labels: automerge

#12372 [action] [PR:12360] Revert "Fix dhcp_relay/test_dhcp_relay.py::test_dhcp_relay_default for dualtor."
  tests/dhcp_relay/test_dhcp_relay.py
Labels: automerge

#12380 [action] [PR:12351] Skip test_snmp_loopback on backend device, it not supported topology backend
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#12345 T2-VOQ-VS: Add command to loganalyzer ignore
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202305 branch

#12381 [action] [PR:12351] Skip test_snmp_loopback on backend device, it not supported topology backend
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#12358 [Bugfix][QoS] Add port index fix for t0 backend
  tests/qos/qos_sai_base.py
Labels: Request for 202305 branch, Request for 202311 branch

#12323 fix cisco lossyQueueVoq failure
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: Request for 202305 branch, Approved for 202305 branch, Approved for 202311 branch, Request for 202311 branch

#12384 [action] [PR:12050] Update gnmi test to support DUT which all interfaces are routed
  tests/gnmi/test_gnmi_configdb.py
Labels: automerge

#12383 [action] [PR:12050] Update gnmi test to support DUT which all interfaces are routed
  tests/gnmi/test_gnmi_configdb.py
Labels: automerge

#12382 [action] [PR:12270] [Fix] Fix ssh connect failed due to default password rotation for getting default passwords
  tests/disk/test_disk_exhaustion.py
Labels: automerge

#12386 [action] [PR:12323] fix cisco lossyQueueVoq failure
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: automerge

#12385 [action] [PR:12323] fix cisco lossyQueueVoq failure
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: automerge

#12379 [E1031] Update the command for restart swss/syncd container in testcase
  tests/platform_tests/test_sequential_restart.py
Labels: Request for 202305 branch, Request for 202311 branch

#12394 [test_bgp_update_timer] to support backend tor router
  tests/bgp/test_bgp_update_timer.py
Labels: Request for 202305 branch, Request for 202311 branch

#12402 [action] [PR:12379] [E1031] Update the command for restart swss/syncd container in testcase
  tests/platform_tests/test_sequential_restart.py
Labels: automerge

#12401 [action] [PR:12379] [E1031] Update the command for restart swss/syncd container in testcase
  tests/platform_tests/test_sequential_restart.py
Labels: automerge

#12400 [action] [PR:12394] [test_bgp_update_timer] to support backend tor router
  tests/bgp/test_bgp_update_timer.py
Labels: automerge

#12414 [action] [PR:12063] Add ipv6 only mgmt syslog test case
  tests/bgp/test_bgp_fact.py
  tests/ip/test_mgmt_ipv6_only.py
  tests/syslog/test_syslog.py
  tests/test_features.py
Labels: automerge

#12413 [action] [PR:12063] Add ipv6 only mgmt syslog test case
  tests/bgp/test_bgp_fact.py
  tests/ip/test_mgmt_ipv6_only.py
  tests/syslog/test_syslog.py
  tests/test_features.py
Labels: automerge

#12412 [action] [PR:12291] [Bugfix] Get crm_interface fixture results on backend testbeds
  tests/crm/conftest.py
Labels: automerge

#12411 [action] [PR:12291] [Bugfix] Get crm_interface fixture results on backend testbeds
  tests/crm/conftest.py
Labels: automerge

#12410 [action] [PR:12289] [Bugfix] Test_copp bugfix for backend testbeds
  tests/copp/conftest.py
  tests/copp/test_copp.py
Labels: automerge

#12418 [action] [PR:12203] Add ipv6 only mgmt TACACS test case
  tests/ip/test_mgmt_ipv6_only.py
Labels: automerge

#12417 [action] [PR:12203] Add ipv6 only mgmt TACACS test case
  tests/ip/test_mgmt_ipv6_only.py
Labels: automerge

#12406 Fix snmp_pdu_controller cannot handle secrets vars in snmp_rwcommunity
  tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Labels: Approved for 202012 branch, Approved for 202205 branch, Approved for 202305 branch, Approved for 202311 branch

#12266 skip headroom pool test for Force10-S6100 T1 topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch, Request for 202311 branch

#12424 [action] [PR:12406] Fix snmp_pdu_controller cannot handle secrets vars in snmp_rwcommunity
  tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Labels: automerge

#12423 [action] [PR:12406] Fix snmp_pdu_controller cannot handle secrets vars in snmp_rwcommunity
  tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Labels: automerge

#12422 [action] [PR:12406] Fix snmp_pdu_controller cannot handle secrets vars in snmp_rwcommunity
  tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Labels: automerge

#12421 [action] [PR:12406] Fix snmp_pdu_controller cannot handle secrets vars in snmp_rwcommunity
  tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Labels: automerge

#12432 [dualtor][active-standby] Improve the toggle by checking on both sides
  tests/common/dualtor/mux_simulator_control.py
Labels: Request for 202305 branch, Request for 202311 branch

#12438 [action] [PR:12237] Add test case to verify snmp over mgmt IPv6 with ipv6 only config
  tests/ip/test_mgmt_ipv6_only.py
Labels: automerge

#12437 [action] [PR:12237] Add test case to verify snmp over mgmt IPv6 with ipv6 only config
  tests/ip/test_mgmt_ipv6_only.py
Labels: automerge

#11970 Fix for scp/test_scp_copy.py sonic-mgmt Issue 11969, to use generic sonicuser_admin
  tests/scp/test_scp_copy.py
Labels: Request for 202305 branch, Request for 202311 branch

#12439 [action] [PR:12432] [dualtor][active-standby] Improve the toggle by checking on both sides
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#12441 Fix extra space issue in loganalyzer regex
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202205 branch, Request for 202305 branch

#12445 [action] [PR:12225] Fix testQosSaiHeadroomPoolSize on Mellanox T1 in dualtor deployment
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: automerge

#12388 Make test_vlan_ping stable
  tests/vlan/test_vlan_ping.py
Labels: Request for 202305 branch, Request for 202311 branch

#12447 [action] [PR:12432] [dualtor][active-standby] Improve the toggle by checking on both sides
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#12448 [action] [PR:12388] Make test_vlan_ping stable
  tests/vlan/test_vlan_ping.py
Labels: automerge

#12452 [action] [PR:12428] [test_ser] modify ser_injector.py run as async mode
  tests/platform_tests/broadcom/files/ser_injector.py
  tests/platform_tests/broadcom/test_ser.py
Labels: automerge

#12451 [action] [PR:12428] [test_ser] modify ser_injector.py run as async mode
  tests/platform_tests/broadcom/files/ser_injector.py
  tests/platform_tests/broadcom/test_ser.py
Labels: automerge

#12449 [action] [PR:12388] Make test_vlan_ping stable
  tests/vlan/test_vlan_ping.py
Labels: automerge

#12390 Add topology mark in the module already in PR test
  tests/arp/test_neighbor_mac.py
  tests/generic_config_updater/test_bgp_prefix.py
  tests/platform_tests/test_cpu_memory_usage.py
  tests/test_vs_chassis_setup.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#12429 Unify console access to use account from group vars
  .azure-pipelines/recover_testbed/dut_connection.py
  .azure-pipelines/recover_testbed/recover_testbed.py
  .azure-pipelines/recover_testbed/testbed_status.py
  ansible/devutil/devices/ansible_hosts.py
  ansible/devutil/inv_helpers.py
  ansible/files/sonic_lab_console_links.csv
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#12224 sonic-mgmt: Use yaml.safe_load
  ansible/TestbedProcessing.py
Labels: Request for 202311 branch

#12465 [action] [PR:12390] Add topology mark in the module already in PR test
  tests/arp/test_neighbor_mac.py
  tests/generic_config_updater/test_bgp_prefix.py
  tests/platform_tests/test_cpu_memory_usage.py
  tests/test_vs_chassis_setup.py
Labels: automerge

#12464 [action] [PR:12390] Add topology mark in the module already in PR test
  tests/arp/test_neighbor_mac.py
  tests/generic_config_updater/test_bgp_prefix.py
  tests/platform_tests/test_cpu_memory_usage.py
  tests/test_vs_chassis_setup.py
Labels: automerge

#11333 Add skip for route flap and radv test for some topology
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch, Request for 202311 branch

#11839 Add skip for test_nbr_health test by github issue
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch, Request for 202311 branch

#11843 Add skip for ecmp test on some mellanox platform by github issue
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch, Request for 202311 branch

#12376 Fix test issue in test_bgp_update_timer_session_down
  tests/bgp/test_bgp_update_timer.py
Labels: Request for 202311 branch

#12151 Fix Qos Xon Test
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202311 branch

#12375 [Qos] Add an error to ignore in qos test
  tests/qos/test_qos_sai.py
Labels: Request for 202311 branch

#12392 Change t1-56-lag-spine.j2 to symbolic link
  ansible/roles/eos/templates/t1-56-lag-spine.j2
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#12434 [Mellanox] Update qos_params.spc3.yaml to support 400000_40m for dualtor pcbb xoff test on Nvidia platform
  tests/qos/files/qos_params.spc3.yaml
Labels: Request for 202305 branch, Request for 202311 branch

#12469 [action] [PR:10989] Fix test_bgp_update_time by increasing threshold
  tests/bgp/test_bgp_update_timer.py
Labels: automerge

#12468 [action] [PR:12376] Fix test issue in test_bgp_update_timer_session_down
  tests/bgp/test_bgp_update_timer.py
Labels: automerge

#12470 [dualtor][warmboot] skip `test_reboot.py` warmboot case on dualtor
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch, Request for 202311 branch

#12460 [Enhancement] Test route perf enhancement for backend testbeds
  tests/route/conftest.py
  tests/route/test_route_perf.py
  tests/route/utils.py
Labels: Request for 202305 branch, Request for 202311 branch

#12476 [action] [PR:12470] [dualtor][warmboot] skip `test_reboot.py` warmboot case on dualtor
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#12047 [platform][cli] PSU Status Tests: Permit Daemons Some Time to enter RUNNING State
  tests/platform_tests/cli/test_show_platform.py
Labels: Request for 202311 branch

#11712 Test Plan for new Link-Local Tests
  docs/testplan/Img/link_local_dut_v6_dip.png
  docs/testplan/Img/link_local_v4_v6_sip.png
  docs/testplan/Img/link_local_vlan_dip.png
  docs/testplan/link-local-test-plan.md
Labels: Test Plan

#12324 [macsec]: Add a sleep at the link flap retry for the flaky failure
  tests/macsec/test_fault_handling.py
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#11921 Fixed test issues for dualtor topologies.
  git
  tests/common/dualtor/dual_tor_utils.py
  tests/dhcp_relay/test_dhcp_relay.py
  tests/drop_packets/test_configurable_drop_counters.py
  tests/dualtor/test_ipinip.py
  tests/dualtor/test_tor_ecn.py
  tests/pfcwd/test_pfcwd_function.py
  tests/qos/test_tunnel_qos_remap.py
  tests/route/test_route_flap.py
  tests/snmp/test_snmp_fdb.py
Labels: Request for 202305 branch, Request for 202311 branch

#12489 [action] [PR:11921] Fixed test issues for dualtor topologies.
  git
  tests/common/dualtor/dual_tor_utils.py
  tests/dhcp_relay/test_dhcp_relay.py
  tests/drop_packets/test_configurable_drop_counters.py
  tests/dualtor/test_ipinip.py
  tests/dualtor/test_tor_ecn.py
  tests/pfcwd/test_pfcwd_function.py
  tests/qos/test_tunnel_qos_remap.py
  tests/route/test_route_flap.py
  tests/snmp/test_snmp_fdb.py
Labels: automerge

#12488 [action] [PR:11921] Fixed test issues for dualtor topologies.
  git
  tests/common/dualtor/dual_tor_utils.py
  tests/dhcp_relay/test_dhcp_relay.py
  tests/drop_packets/test_configurable_drop_counters.py
  tests/dualtor/test_ipinip.py
  tests/dualtor/test_tor_ecn.py
  tests/pfcwd/test_pfcwd_function.py
  tests/qos/test_tunnel_qos_remap.py
  tests/route/test_route_flap.py
  tests/snmp/test_snmp_fdb.py
Labels: automerge

#12477 [Bugfix] Support for disk exhaust test for backend switches
  tests/disk/test_disk_exhaustion.py
Labels: Request for 202305 branch, Request for 202311 branch

#12498 [action] [PR:12467] [test_fdb_mac_move] Only output error level message into syslog if /var/log size limitation
  tests/fdb/test_fdb_mac_move.py
Labels: automerge

#12494 Fix IPv6 NTP test case missing an import
  tests/ip/test_mgmt_ipv6_only.py
Labels: Request for 202305 branch, Request for 202311 branch

#12493 Fix bug in scale test for Dynamic ACL via GCU on Arista 7260 devices
  tests/generic_config_updater/test_dynamic_acl.py
Labels: Request for 202311 branch

#12508 [action] [PR:12494] Fix IPv6 NTP test case missing an import
  tests/ip/test_mgmt_ipv6_only.py
Labels: automerge

#12491 [Enhancement] Test route perf enhancement for backend testbeds
  tests/route/conftest.py
  tests/route/test_route_perf.py
  tests/route/utils.py
Labels: Request for 202305 branch, Request for 202311 branch

#12142 Update warm-reboot sad in_boot test
  ansible/roles/test/files/ptftests/sad_path.py
Labels: Request for 202305 branch, Request for 202311 branch

#11886 [upgrade test]Fix issues when the image path is not url
  ansible/library/reduce_and_add_sonic_images.py
Labels: Request for 202305 branch, Request for 202311 branch

#11842 Add skip for some GCU test by github issue
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch, Request for 202311 branch

#7916 [Snappi] Added multi dut pfcwd a2a test case
  tests/snappi_tests/multidut/pfcwd/__init__.py
  tests/snappi_tests/multidut/pfcwd/files/__init__.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_multi_node_helper.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_a2a_with_snappi.py
Labels: chassis, Request for 202205 branch, Request for 202305 branch

#7917 [Snappi] Added multi dut pfcwd basic test case
  tests/snappi_tests/files/helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_basic_helper.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
Labels: chassis, Request for 202205 branch, Request for 202305 branch

#7918 [Snappi] Added multi dut pfcwd burst test case
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_burst_storm_helper.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_burst_storm_with_snappi.py
Labels: chassis

#7920 [Snappi] Added multi dut pfcwd runtime test case
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_runtime_traffic_helper.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py
Labels: chassis

#12505 Fix the module `test_sfpshow.py` and add it in PR test.
  .azure-pipelines/pr_test_scripts.yaml
  tests/platform_tests/sfp/util.py
Labels: Request for 202012 branch, Request for 202205 branch, Request for 202305 branch, Request for 202311 branch
