Repository sonic-net/sonic-mgmt, pull requests merged in 2024-11, with the labels that each got.

#15313 [action] [PR:15258] Multi-asic fixes for `lldp/test_lldp_syncd.py`
  tests/lldp/test_lldp_syncd.py
Labels: automerge

#15298 fix: handle EOFError for cache reading
  tests/common/cache/facts_cache.py
  tests/common/devices/duthosts.py
Labels: Request for 202405 branch

#15099 Move the common code from testcases to the fixtures.
  tests/common/snappi_tests/qos_fixtures.py
  tests/common/snappi_tests/snappi_fixtures.py
  tests/snappi_tests/files/helper.py
  tests/snappi_tests/multidut/pfc/files/multidut_helper.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/test_multidut_snappi.py
Labels: Request for 202405 branch

#14917 Adding fixes for the docker0 ipv6 issue.
  tests/qos/qos_sai_base.py
Labels: Request for 202405 branch

#15320 [action] [PR:15315] [chassis]: Add all running_golden_config files for multi-asics based on num_asic
  tests/common/config_reload.py
Labels: automerge

#15319 [action] [PR:14917] Adding fixes for the docker0 ipv6 issue.
  tests/qos/qos_sai_base.py
Labels: automerge

#15318 [action] [PR:15298] fix: handle EOFError for cache reading
  tests/common/cache/facts_cache.py
  tests/common/devices/duthosts.py
Labels: automerge

#15137 Address test gap in test_mgmt_ipv6
  tests/common/helpers/syslog_helpers.py
Labels: Request for 202405 branch

#15317 [Bugfix] Fix fixture not found issue in script `pfc_asym/test_pfc_asym.py`.
  tests/pfc_asym/test_pfc_asym.py
Labels: Request for 202405 branch

#15326 [action] [PR:15317] [Bugfix] Fix fixture not found issue in script `pfc_asym/test_pfc_asym.py`.
  tests/pfc_asym/test_pfc_asym.py
Labels: automerge

#15168 Add topo t1-isolated-d224u8
  ansible/vars/topo_t1-isolated-d224u8.yaml
  ansible/veos
  docs/testbed/README.testbed.Overview.md
Labels: Request for 202405 branch

#15335 [action] [PR:15268] Add cEOS neighbor support for bgp/test_4-byte_asn_community.py
  tests/bgp/templates/bgp_id.template
  tests/bgp/test_4-byte_asn_community.py
  tests/common/devices/multi_asic.py
  tests/common/devices/sonic_asic.py
Labels: automerge

#15207 [action] [PR:15057] [Snappi] Change multidut reboot cases to use enum with completeness_level
  tests/conftest.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
Labels: automerge

#15266 [dualtor-aa] Fix arp flux of soc IPs
  ansible/roles/vm_set/library/vm_topology.py
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#15336 Ignore test_bgp_allow_list and test_bgp_bbr for Cisco 8122 compute AI deployment
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch

#15250 adding 8122 platforms to watchdog.yml file
  tests/platform_tests/api/watchdog.yml
Labels: Request for 202405 branch

#15346 [action] [PR:15219] skip vxlan_decap testcase on cisco 8122 platform - New
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#15345 [action] [PR:15250] adding 8122 platforms to watchdog.yml file
  tests/platform_tests/api/watchdog.yml
Labels: automerge

#15344 [action] [PR:15336] Ignore test_bgp_allow_list and test_bgp_bbr for Cisco 8122 compute AI deployment
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#15351 [action] [PR:15168] Add topo t1-isolated-d224u8
  ansible/vars/topo_t1-isolated-d224u8.yaml
  ansible/veos
  docs/testbed/README.testbed.Overview.md
Labels: automerge

#15354 [action] [PR:15226] [dualtor][mux_simulator] Fix mux simulator stuck
  ansible/roles/vm_set/files/mux_simulator.py
Labels: automerge

#14825 sonic-mgmt/IXIA test to verify the PFC frame sent by DUT has a valid src_mac address
  tests/common/snappi_tests/read_pcap.py
  tests/snappi_tests/pfc/files/cisco_pfc_packet.py
  tests/snappi_tests/pfc/files/valid_src_mac_pfc_frame_helper.py
  tests/snappi_tests/pfc/test_valid_src_mac_pfc_frame.py
Labels: Request for 202405 branch

#15361 [action] [PR:15328] Cisco-8122 Q watermark test update
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#15327 Fix conflicted skipping condition for test_pfc_asym
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch

#15368 [action] [PR:14065] Update pretest script to provide asic type value for generic hash test script
  tests/common/devices/sonic.py
  tests/test_pretest.py
Labels: automerge

#15282 [action] [PR:14088] Skip the bfd test case by the github issue
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14475 Add static route ASIC DB check for test_nhop_group test
  tests/ipfwd/test_nhop_group.py
Labels: Request for 202405 branch

#15337 Fix mismatch between show lldp table and the content of lldp entry table
  tests/lldp/test_lldp_syncd.py
Labels: Request for 202405 branch

#15373 [action] [PR:14475] Add static route ASIC DB check for test_nhop_group test
  tests/ipfwd/test_nhop_group.py
Labels: automerge

#15371 [action] [PR:15327] Fix conflicted skipping condition for test_pfc_asym
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#15338 [action] [PR:13290] [T2-Chassis] - New tests for Reliable-TSA feature
  tests/bgp/bgp_helpers.py
  tests/bgp/route_checker.py
  tests/bgp/test_reliable_tsa.py
  tests/bgp/test_startup_tsa_tsb_service.py
  tests/bgp/test_traffic_shift.py
  tests/bgp/test_traffic_shift_sup.py
Labels: automerge

#15364 [m0][mx] Skip check pfcwd during config reload for m0/mx
  tests/common/config_reload.py
Labels: Request for 202405 branch

#15363 [m0][mx] Skip queue related tests for m0/mx
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch

#15341 [drop_packets] Skip drop_packets on MGFX
  tests/common/plugins/conditional_mark/tests_mark_conditions_drop_packets.yaml
Labels: Request for 202405 branch

#15390 [action] [PR:15312] Add check to see if bgp sessions are up before proceeding with the tests
  tests/bgp/test_seq_idf_isolation.py
Labels: automerge

#15314 Stabilize pfcwd warm-reboot test on Mellanox platform
  tests/pfcwd/conftest.py
Labels: Request for 202405 branch

#15398 [action] [PR:15314] Stabilize pfcwd warm-reboot test on Mellanox platform
  tests/pfcwd/conftest.py
Labels: automerge

#15303 Update qos pcbb parameter for SN4600C on dualtor aa topology
  tests/qos/files/qos_params.spc3.yaml
Labels: Request for 202405 branch

#15062 Fix test_check_show_lpmode case
  tests/platform_tests/sfp/test_show_intf_xcvr.py
  tests/platform_tests/sfp/util.py
Labels: Request for 202405 branch

#15378 Fix testQosSaiDscpToPgMapping issue
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202405 branch

#15377 Fix the wrong reboot wait/timeout setting on test_link_down
  tests/platform_tests/test_link_down.py
Labels: Request for 202405 branch

#15385 Use lldp0/lldp1 instead of lldp, since container lldp was removed from the host (#13172)
  tests/lldp/test_lldp.py
Labels: Request for 202405 branch

#13648 [Mellanox] update for test_acl_tcp_rst due to design change
  tests/dash/dash_acl.py
Labels: Request for 202405 branch

#15367 Increase startup_tsa_tsb time based on Cisco's observation.
  tests/bgp/test_reliable_tsa.py
  tests/bgp/test_startup_tsa_tsb_service.py
Labels: Request for 202405 branch

#15408 [action] [PR:15377] Fix the wrong reboot wait/timeout setting on test_link_down
  tests/platform_tests/test_link_down.py
Labels: automerge

#15406 [action] [PR:15378] Fix testQosSaiDscpToPgMapping issue
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#15405 [action] [PR:15303] Update qos pcbb parameter for SN4600C on dualtor aa topology
  tests/qos/files/qos_params.spc3.yaml
Labels: automerge

#15412 [action] [PR:13648] [Mellanox] update for test_acl_tcp_rst due to design change
  tests/dash/dash_acl.py
Labels: automerge

#15404 ACL testcase fix for Cisco 8122 Platform
  tests/acl/test_acl.py
Labels: Request for 202405 branch

#15422 test_chassis_reboot.py apply threaded reboot to avoid ansible command timeout
  tests/platform_tests/test_chassis_reboot.py
Labels: Request for 202405 branch

#15441 [action] [PR:15422] test_chassis_reboot.py apply threaded reboot to avoid ansible command timeout
  tests/platform_tests/test_chassis_reboot.py
Labels: automerge

#15437 [action] [PR:15404] ACL testcase fix for Cisco 8122 Platform
  tests/acl/test_acl.py
Labels: automerge

#15382 [action] [PR:15052] Skip check for Rx PFC count if multiple lossy TC bits are set
  tests/common/snappi_tests/traffic_generation.py
Labels: automerge

#15443 [action] [PR:9230] [renumber-topo] Add extra mgmt ip to ptf redeploy step
  ansible/roles/vm_set/tasks/renumber_topo.yml
Labels: automerge

#15442 [action] [PR:15420] Adding log analyzer ignore messages based on Cisco Chassis
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#15198 Added new testcase for checking console connections from supervisor t…
  tests/common/helpers/console_helper.py
  tests/dut_console/test_console_chassis_conn.py
Labels: Test gap, Chassis Test Gap

#14982 Multi-asic Support for Telemetry Test
  .azure-pipelines/pr_test_scripts.yaml
  tests/common/devices/multi_asic.py
  tests/common/devices/sonic.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/telemetry/telemetry_utils.py
  tests/telemetry/test_telemetry.py
Labels: Request for 202405 branch

#15217 [dut_console/test_console_baud_rate]: cast expected baudrate to str
  tests/dut_console/test_console_baud_rate.py
Labels: Request for 202405 branch

#15451 [action] [PR:14788] Retry test_psu.py::TestPsuApi::test_power if power not within tolerance
  tests/platform_tests/api/platform_api_test_base.py
  tests/platform_tests/api/test_psu.py
Labels: automerge

#15413 [action] [PR:15367] Increase startup_tsa_tsb time based on Cisco's observation.
  tests/bgp/test_reliable_tsa.py
  tests/bgp/test_startup_tsa_tsb_service.py
Labels: automerge

#15375 [action] [PR:15337] Fix mismatch between show lldp table and the content of lldp entry table
  tests/lldp/test_lldp_syncd.py
Labels: automerge

#15449 chore: enable parallel run for more tests
  tests/test_parallel_modes.json
Labels: Request for 202405 branch

#15370 refactor: optimize BFD test
  tests/bfd/bfd_base.py
  tests/bfd/bfd_helpers.py
  tests/bfd/test_bfd_static_route.py
  tests/bfd/test_bfd_traffic.py
Labels: Request for 202405 branch

#15450 Cisco-8122 Increase buffer pool watermark test margin
  tests/qos/files/cisco/qos_param_generator.py
Labels: Request for 202405 branch

#15460 [action] [PR:15274] Modify Small Partition Size to 300M from 100M
  tests/syslog/test_logrotate.py
Labels: automerge

#15465 [action] [PR:15450] Cisco-8122 Increase buffer pool watermark test margin
  tests/qos/files/cisco/qos_param_generator.py
Labels: automerge

#15464 [action] [PR:15370] refactor: optimize BFD test
  tests/bfd/bfd_base.py
  tests/bfd/bfd_helpers.py
  tests/bfd/test_bfd_static_route.py
  tests/bfd/test_bfd_traffic.py
Labels: automerge

#15462 [action] [PR:15217] [dut_console/test_console_baud_rate]: cast expected baudrate to str
  tests/dut_console/test_console_baud_rate.py
Labels: automerge

#15461 [action] [PR:15449] chore: enable parallel run for more tests
  tests/test_parallel_modes.json
Labels: automerge

#15418 feat: fix pfcwd storm flaky test
  tests/common/templates/pfc_storm_sonic_t2.j2
  tests/common/templates/pfc_storm_stop_sonic_t2.j2
Labels: Request for 202405 branch

#15445 [T2:multidut]: Change reboot to reboot-fixture in pfcwd_basic.
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
Labels: Request for 202405 branch

#15434 [GCU] Extend timeout to 10min
  tests/common/gu_utils.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#15472 [action] [PR:15445] [T2:multidut]: Change reboot to reboot-fixture in pfcwd_basic.
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
Labels: automerge

#15471 [action] [PR:15418] feat: fix pfcwd storm flaky test
  tests/common/templates/pfc_storm_sonic_t2.j2
  tests/common/templates/pfc_storm_stop_sonic_t2.j2
Labels: automerge

#15414 [action] [PR:15364] [m0][mx] Skip check pfcwd during config reload for m0/mx
  tests/common/config_reload.py
Labels: automerge

#15448 [Cherry-pick #13069,14585,14802] qos_yaml j2C+ changes for new _vsq thresholds
  tests/qos/files/qos_params.j2c.yaml
  tests/qos/files/qos_params.jr2.yaml
Labels: P0

#15473 [action] [PR:14566] [mx] Enable dhcp_server feature for mx in deploy-mg
  ansible/library/generate_golden_config_db.py
Labels: automerge

#15439 [action] [PR:15400] Cisco-8000 Revise TX XOFF counter check
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#15438 [action] [PR:13533] [Snappi] ECN snappi test polling delay and packet capture fix
  tests/common/snappi_tests/read_pcap.py
  tests/snappi_tests/ecn/files/helper.py
  tests/snappi_tests/multidut/ecn/files/multidut_helper.py
Labels: automerge

#15122 [action] [PR:14111] Update t1-32-lag support to pfcwd script
  tests/pfcwd/conftest.py
Labels: automerge

#14975 [action] [PR:14117] Add BBR testcases
  docs/testplan/BGP-BBR.md
  tests/bgp/test_bgp_bbr.py
Labels: automerge

#14695 [action] [PR:14274] ensure flex_db counters match expected number on setup of pfcwd_status tests
  tests/generic_config_updater/test_pfcwd_status.py
Labels: automerge

#15485 [action] [PR:15469] feat: add support for clearing counter for ingress
  tests/common/snappi_tests/multi_dut_params.py
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
Labels: automerge

#15452 [multi-asic fix] fix new change in test_route_perf.py to support multi-asic
  .azure-pipelines/pr_test_scripts.yaml
  tests/route/test_route_perf.py
Labels: Request for 202405 branch

#15480 [action] [PR:15209] Fix for test_voq_ip_fwd
  tests/voq/test_voq_ipfwd.py
Labels: automerge

#15191 Address test gap to verify portchannel member packet forwarding w.r.t SAI_LAG_MEMBER_ATTR_EGRESS/INGRESS enable/disable state
  tests/common/devices/sonic.py
  tests/common/devices/sonic_asic.py
  tests/pc/test_lag_member_forwarding.py
Labels: Request for 202405 branch

#15286 Adding minor misc fixes for pfcwd scripts.
  tests/common/snappi_tests/common_helpers.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_burst_storm_helper.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
Labels: Request for 202405 branch

#15479 Skipping test_dip_sip for Cisco 8122 platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch

#15496 [action] [PR:15479] Skipping test_dip_sip for Cisco 8122 platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#15487 [action] [PR:14825] sonic-mgmt/IXIA test to verify the PFC frame sent by DUT has a valid src_mac address
  tests/common/snappi_tests/read_pcap.py
  tests/snappi_tests/pfc/files/cisco_pfc_packet.py
  tests/snappi_tests/pfc/files/valid_src_mac_pfc_frame_helper.py
  tests/snappi_tests/pfc/test_valid_src_mac_pfc_frame.py
Labels: automerge

#15384 add hwsku definition Cisco-8122-O128
  ansible/module_utils/port_utils.py
Labels: Request for 202405 branch

#15017 skipping test_route_flow_counter.py on Cisco 8122 platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch

#15305 Use COUNTER_MARGIN in PFCXonTest check.
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202405 branch

#15493 [action] [PR:15286] Adding minor misc fixes for pfcwd scripts.
  tests/common/snappi_tests/common_helpers.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_burst_storm_helper.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py
Labels: automerge

#15505 [action] [PR:15017] skipping test_route_flow_counter.py on Cisco 8122 platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#15504 [action] [PR:15384] add hwsku definition Cisco-8122-O128
  ansible/module_utils/port_utils.py
Labels: automerge

#15508 [action] [PR:13391] [GCU] Update AAA test with recent setup
  tests/generic_config_updater/test_aaa.py
Labels: automerge

#15491 [TACACS] Add --no-pager to tacacs utils
  tests/tacacs/utils.py
Labels: Request for 202405 branch

#15482 Fix the parameters for AllPortQueueWaterMark Testcase.
  tests/qos/files/qos_params.gb.yaml
  tests/qos/test_qos_sai.py
Labels: Request for 202405 branch

#15503 [M0-2VLAN] Update test_vlan_ping for m0-2vlan topo
  tests/vlan/test_vlan_ping.py
Labels: Request for 202405 branch

#15523 [action] [PR:15249] sonic-mgmt: fix info in testbed_vm_info.py err msg
  ansible/library/testbed_vm_info.py
Labels: automerge

#15521 [action] [PR:15311] fix sample_golden_config_db.j2 portchannel undefined
  tests/golden_config_infra/templates/sample_golden_config_db.j2
Labels: automerge

#15517 Increase the sleep time after change the interface status
  tests/fdb/test_fdb_mac_learning.py
Labels: Request for 202405 branch

#15331 [202405] Fix intermittent issue on reboot in test_lldp_syncd
  tests/lldp/test_lldp_syncd.py
Labels: Request for 202405 branch

#15535 [action] [PR:15331] [202405] Fix intermittent issue on reboot in test_lldp_syncd
  tests/lldp/test_lldp_syncd.py
Labels: automerge

#15536 fix 7260 headroom pool watermark test failure
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202405 branch

#15248 Skip RX_DRP check on Mellanox platform in test_drop_l3_ip_packet_non_dut_mac
  tests/ip/test_ip_packet.py
Labels: Request for 202405 branch

#15071 Ensure correct testing telemetry config after config reload
  tests/common/helpers/telemetry_helper.py
  tests/telemetry/test_telemetry.py
Labels: Request for 202405 branch

#15540 [action] [PR:15248] Skip RX_DRP check on Mellanox platform in test_drop_l3_ip_packet_non_dut_mac
  tests/ip/test_ip_packet.py
Labels: automerge

#15360 [action] [PR:15002] Fixed the failure of test_valid_pfc_frame_with_snappi.py in Cisco DUT
  tests/snappi_tests/pfc/files/helper.py
Labels: automerge

#15537 [snappi] skip multidut bgp instead of assert if testbed doesn't support.
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_downlink_port_flap.py
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_downlink_process_crash.py
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_tsa.py
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_multi_po_flap.py
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_flap.py
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_member_flap.py
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_process_crash.py
Labels: Request for 202405 branch

#15546 [action] [PR:15482] Fix the parameters for AllPortQueueWaterMark Testcase.
  tests/qos/files/qos_params.gb.yaml
  tests/qos/test_qos_sai.py
Labels: automerge

#15545 [action] [PR:15537] [snappi] skip multidut bgp instead of assert if testbed doesn't support.
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_downlink_port_flap.py
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_downlink_process_crash.py
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_tsa.py
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_multi_po_flap.py
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_flap.py
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_member_flap.py
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_process_crash.py
Labels: automerge

#15527 Update pfc_gen_t2.py
  tests/common/helpers/pfc_gen_t2.py
Labels: Request for 202405 branch

#15544 fix: fix flaky pfc_storm
  tests/pfcwd/test_pfcwd_function.py
Labels: Request for 202405 branch

#14389 Update fanout deploy yaml file to support using 2024 image
  ansible/roles/fanout/tasks/fanout_sonic.yml
  ansible/roles/fanout/tasks/sonic/fanout_sonic_202405.yml
Labels: Request for 202311 branch, Request for 202405 branch

#15557 [action] [PR:15452] [multi-asic fix] fix new change in test_route_perf.py to support multi-asic
  .azure-pipelines/pr_test_scripts.yaml
  tests/route/test_route_perf.py
Labels: automerge

#15556 [action] [PR:15409] nhop_group: Fix expected mac address dictionary for Cisco 8122
  tests/ipfwd/test_nhop_group.py
Labels: automerge

#15525 [action] [PR:15503] [M0-2VLAN] Update test_vlan_ping for m0-2vlan topo
  tests/vlan/test_vlan_ping.py
Labels: automerge

#15526 fix flaky tests/autorestart/test_container_autorestart.py
  tests/autorestart/test_container_autorestart.py
Labels: Request for 202405 branch

#15272 Skipping test_static_route on Cisco 8122
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch

#15569 [action] [PR:13586] Reg:IPFWD TC test_nhop_group_interface_flap Dut Selection & Interface up time
  tests/ipfwd/test_nhop_group.py
Labels: automerge

#15568 [action] [PR:13690] [QoS]Test_buffer_model test skip for Nokia platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#15567 [action] [PR:14022] [Qos]Updating lldp error regex for loganalyzer ignore
  tests/qos/test_qos_sai.py
Labels: automerge

#15566 [action] [PR:14021] Fix dut selection for bgp-passive-peering tests
  tests/bgp/test_passive_peering.py
Labels: automerge

#15554 [dualtor-io] Support using fix source IP for upstream packets
  tests/common/dualtor/data_plane_utils.py
  tests/common/dualtor/dual_tor_io.py
  tests/dualtor_io/test_tor_bgp_failure.py
Labels: Request for 202405 branch

#15532 [action] [PR:15400] Cisco-8000 Revise TX XOFF counter check
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#15550 refactor: optimize BFD traffic test
  tests/bfd/bfd_base.py
  tests/bfd/conftest.py
  tests/bfd/test_bfd_traffic.py
Labels: Request for 202405 branch

#15575 [action] [PR:15529] [dualtor] Fix snmp/* tests failure on fixture teardown
  tests/snmp/conftest.py
Labels: automerge

#15577 Fix REBOOT_TYPE_SUPERVISOR "check" value
  tests/common/reboot.py
Labels: Bug :bug:, Request for 202405 branch

#15411 `bgp/test_bgp_session_flap.py` Fix condition intended to skip iBGP neighbors to work on single-asic
  tests/bgp/test_bgp_session_flap.py
Labels: Request for 202405 branch

#15580 [action] [PR:15550] refactor: optimize BFD traffic test
  tests/bfd/bfd_base.py
  tests/bfd/conftest.py
  tests/bfd/test_bfd_traffic.py
Labels: automerge

#13513 Skip sonic-mgmt HdrmPoolSizeTest for Nokia-IXR7250E hwsku
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch

#15574 [action] [PR:15526] fix flaky tests/autorestart/test_container_autorestart.py
  tests/autorestart/test_container_autorestart.py
Labels: automerge

#15549 [action] [PR:15074] Fix qos node selection for single-asic in qos_sai_base test
  tests/qos/qos_sai_base.py
Labels: automerge

#15530 [action] [PR:15517] Increase the sleep time after change the interface status
  tests/fdb/test_fdb_mac_learning.py
Labels: automerge

#15522 [action] [PR:15297] Fix asic identification
  tests/common/devices/sonic.py
Labels: automerge

#15562 fix TestPfcwdFunc::test_pfcwd_multi_port t2
  tests/pfcwd/test_pfcwd_function.py
Labels: Request for 202405 branch

#15576 [action] [PR:15272] Skipping test_static_route on Cisco 8122
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#15570 Wait BGP sessions after changing mgmt IP
  tests/common/fixtures/duthost_utils.py
Labels: Request for 202405 branch

#15588 [action] [PR:15570] Wait BGP sessions after changing mgmt IP
  tests/common/fixtures/duthost_utils.py
Labels: automerge

#15593 [action] [PR:15411] `bgp/test_bgp_session_flap.py` Fix condition intended to skip iBGP neighbors to work on single-asic
  tests/bgp/test_bgp_session_flap.py
Labels: automerge

#15590 [action] [PR:15577] Fix REBOOT_TYPE_SUPERVISOR "check" value
  tests/common/reboot.py
Labels: automerge

#15591 [action] [PR:13513] Skip sonic-mgmt HdrmPoolSizeTest for Nokia-IXR7250E hwsku
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#15597 [action] [PR:15562] fix TestPfcwdFunc::test_pfcwd_multi_port t2
  tests/pfcwd/test_pfcwd_function.py
Labels: automerge

#15542 sonic-mgmt: fix t0-isolated-d128u128s2 topo
  ansible/roles/eos/templates/t0-isolated-d128u128s2-leaf.j2
  ansible/roles/test/files/helpers/change_mac.sh
  ansible/testbed-new.yaml
  ansible/vars/topo_t0-isolated-d128u128s1.yml
  ansible/vars/topo_t0-isolated-d128u128s2.yml
  ansible/veos
Labels: Request for 202405 branch

#15598 [Snappi] add back T0/T1 merge
  tests/snappi_tests/files/helper.py
Labels: Request for 202405 branch

#15612 [action] [PR:14713] [T2] [Chassis] Skip override_config_table_masic test for upstream line card
  tests/override_config_table/test_override_config_table_masic.py
Labels: automerge

#15611 [action] [PR:14804] [T2] [Chassis] Route flap fix on upstream LC for AZNG route changes
  tests/conftest.py
  tests/route/test_route_flap.py
Labels: automerge

#15609 [action] [PR:13269] [platform_tests.broadcom.test_ser] add failure info in assert log if script return failure
  tests/platform_tests/broadcom/test_ser.py
Labels: automerge
