Repository sonic-net/sonic-mgmt, pull requests merged in 2024-09, with the labels that each got.

#14343 Enhance test_ro_disk to ensure device finally be recovered by PDU reboot
  tests/tacacs/test_ro_disk.py
Labels: Request for 202311 branch, Request for 202405 branch

#14352 [action] [PR:14343] Enhance test_ro_disk to ensure device finally be recovered by PDU reboot
  tests/tacacs/test_ro_disk.py
Labels: automerge

#14321 Skip test_bgp_bbr.py with Cisco 8111 compute-ai platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#14357 [action] [PR:14321] Skip test_bgp_bbr.py with Cisco 8111 compute-ai platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14356 [action] [PR:14321] Skip test_bgp_bbr.py with Cisco 8111 compute-ai platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14355 [action] [PR:14321] Skip test_bgp_bbr.py with Cisco 8111 compute-ai platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14354 [action] [PR:14200] Refactor neighbor VM image downloading
  ansible/group_vars/vm_host/ceos.yml
  ansible/group_vars/vm_host/main.yml
  ansible/group_vars/vm_host/vcisco.yml
  ansible/group_vars/vm_host/veos.yml
  ansible/group_vars/vm_host/vsonic.yml
  ansible/roles/eos/tasks/ceos.yml
  ansible/roles/vm_set/tasks/add_ceos_list.yml
  ansible/roles/vm_set/tasks/kickstart_vm.yml
  ansible/roles/vm_set/tasks/main.yml
  ansible/roles/vm_set/tasks/probe_ceos_image_url.yml
  ansible/roles/vm_set/tasks/probe_image_url.yml
  ansible/roles/vm_set/tasks/start.yml
  ansible/roles/vm_set/tasks/start_vm.yml
  ansible/testbed_start_VMs.yml
  ansible/testbed_start_k8s_VMs.yml
Labels: automerge

#14353 [action] [PR:14200] Refactor neighbor VM image downloading
  ansible/group_vars/vm_host/ceos.yml
  ansible/group_vars/vm_host/main.yml
  ansible/group_vars/vm_host/vcisco.yml
  ansible/group_vars/vm_host/veos.yml
  ansible/group_vars/vm_host/vsonic.yml
  ansible/roles/eos/tasks/ceos.yml
  ansible/roles/vm_set/tasks/add_ceos_list.yml
  ansible/roles/vm_set/tasks/kickstart_vm.yml
  ansible/roles/vm_set/tasks/main.yml
  ansible/roles/vm_set/tasks/probe_ceos_image_url.yml
  ansible/roles/vm_set/tasks/probe_image_url.yml
  ansible/roles/vm_set/tasks/start.yml
  ansible/roles/vm_set/tasks/start_vm.yml
  ansible/testbed_start_VMs.yml
  ansible/testbed_start_k8s_VMs.yml
Labels: automerge

#14351 [action] [PR:14343] Enhance test_ro_disk to ensure device finally be recovered by PDU reboot
  tests/tacacs/test_ro_disk.py
Labels: automerge

#14323 [action] [PR:13203] Ignore received packets that weren't sent during examine_flow
  ansible/roles/test/files/ptftests/py3/advanced-reboot.py
Labels: automerge

#14316 [action] [PR:14199] [dualtor] Ignore syncd's SAI_API_TUNNEL:_brcm_sai_mptnl* logs
  tests/dualtor_io/test_tor_bgp_failure.py
  tests/log_fidelity/test_bgp_shutdown.py
  tests/route/test_default_route.py
Labels: automerge

#14326 [action] [PR:14119] Imporve TACACS accounting test case, add debug information
  tests/tacacs/test_accounting.py
Labels: automerge

#14324 [action] [PR:13203] Ignore received packets that weren't sent during examine_flow
  ansible/roles/test/files/ptftests/py3/advanced-reboot.py
Labels: automerge

#14315 [action] [PR:14124] BGP [T2] - Update neighbor admin down only for specific asic under test
  tests/common/helpers/bgp.py
Labels: automerge

#14294 [action] [PR:13211] [pc]: Skip if there's not enough members in the VLAN
  tests/pc/test_lag_member.py
Labels: automerge

#14293 [action] [PR:13211] [pc]: Skip if there's not enough members in the VLAN
  tests/pc/test_lag_member.py
Labels: automerge

#14280 [action] [PR:14025] added log ignore to ignore BFD session creation failure logs. On mlnx…
  tests/vxlan/test_vxlan_ecmp.py
Labels: automerge

#14364 [action] [PR:14142] Enable readiness check in the config_reload of the core_dump and config check
  tests/acl/test_acl.py
  tests/conftest.py
Labels: automerge

#14378 [action] [PR:14163] [test_bgp_stress_link_flap] case hung sometimes due to memory exhaust
  tests/bgp/test_bgp_stress_link_flap.py
Labels: automerge

#13821 Fix syslog test failure about fixture tbinfo
  tests/syslog/test_logrotate.py
Labels: Request for 202405 branch

#14360 Skip test_bgp_allow_list.py for Cisco 8111 T1 compute ai deployment
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#14366 Update some references of `ceos.yml` to the new path.
  ansible/roles/vm_set/tasks/add_ceos_list.yml
  docs/testbed/README.testbed.WANSetup.md
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#14384 [action] [PR:14360] Skip test_bgp_allow_list.py for Cisco 8111 T1 compute ai deployment
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14383 [action] [PR:14360] Skip test_bgp_allow_list.py for Cisco 8111 T1 compute ai deployment
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14391 [action] [PR:14367] Skip BGPAllowListMgr syslog in test_bgp_prefix_tc1_suite for Cisco 8111 CompuateAI deployment
  tests/generic_config_updater/test_bgp_prefix.py
Labels: automerge

#14392 [action] [PR:14367] Skip BGPAllowListMgr syslog in test_bgp_prefix_tc1_suite for Cisco 8111 CompuateAI deployment
  tests/generic_config_updater/test_bgp_prefix.py
Labels: automerge

#14390 [action] [PR:14367] Skip BGPAllowListMgr syslog in test_bgp_prefix_tc1_suite for Cisco 8111 CompuateAI deployment
  tests/generic_config_updater/test_bgp_prefix.py
Labels: automerge

#14171 Update report uploader upgrade and reboot JSON logs regex
  test_reporting/report_uploader.py
Labels: Request for 202311 branch, Request for 202405 branch

#14021 Fix dut selection for bgp-passive-peering tests
  tests/bgp/test_passive_peering.py
Labels: Request for 202405 branch

#13586 Reg:IPFWD TC test_nhop_group_interface_flap Dut Selection & Interface up time
  tests/ipfwd/test_nhop_group.py
Labels: Request for 202405 branch

#14410 [action] [PR:14304] [Test gap][BBR] Test for default state after restart
  tests/bgp/test_bgp_bbr_default_state.py
Labels: automerge

#14408 [action] [PR:14368] [Chassis] Recover chassis by config reload all RP/LCs
  tests/common/config_reload.py
  tests/common/helpers/parallel_utils.py
  tests/common/plugins/sanity_check/__init__.py
  tests/common/plugins/sanity_check/checks.py
  tests/common/plugins/sanity_check/recover.py
  tests/common/reboot.py
  tests/conftest.py
Labels: automerge

#14407 [action] [PR:14299] [wol_test] implement tests for wol
  tests/common/utilities.py
  tests/wol/conftest.py
  tests/wol/test_wol.py
Labels: automerge

#14406 [action] [PR:13070] Modify snmp link local test to use config cli
  tests/snmp/test_snmp_link_local.py
Labels: automerge

#14405 [action] [PR:14335] Stabilize test_pfcwd_timer_accuracy
  tests/common/templates/pfc_storm_mlnx_sonic.j2
  tests/common/templates/pfc_storm_stop_mlnx_sonic.j2
  tests/pfcwd/files/pfcwd_helper.py
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#14404 [action] [PR:14335] Stabilize test_pfcwd_timer_accuracy
  tests/common/templates/pfc_storm_mlnx_sonic.j2
  tests/common/templates/pfc_storm_stop_mlnx_sonic.j2
  tests/pfcwd/files/pfcwd_helper.py
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#14140 Fix test_events flakiness
  tests/telemetry/events/event_utils.py
  tests/telemetry/events/host_events.py
  tests/telemetry/events/run_events_test.py
  tests/telemetry/telemetry_utils.py
  tests/telemetry/test_events.py
Labels: Request for 202311 branch, Request for 202405 branch

#14385 [action] [PR:14360] Skip test_bgp_allow_list.py for Cisco 8111 T1 compute ai deployment
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#13844 [Snappi]: Support for selecting buffer-sizes associated with ingress lossless profile with Nokia7250 platform.
  tests/common/snappi_tests/common_helpers.py
Labels: Request for 202405 branch, IXIA_CHASSIS

#14239 Fix arp/test_stress_arp.py bad checks and make cleanup failure a warning
  tests/arp/test_stress_arp.py
Labels: Request for 202311 branch, Request for 202405 branch

#14413 [action] [PR:13844] [Snappi]: Support for selecting buffer-sizes associated with ingress lossless profile with Nokia7250 platform.
  tests/common/snappi_tests/common_helpers.py
Labels: automerge

#13813 Add t0-28 topo
  ansible/roles/eos/templates/t0-28-leaf.j2
  ansible/roles/test/vars/testcases.yml
  ansible/vars/topo_t0-28.yml
  ansible/veos_vtb
  tests/qos/qos_sai_base.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202405 branch

#14397 add conditional mark to skip LLDP and SNMP testcases for standalone topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202311 branch, Request for 202405 branch

#13848 [Snappi] Support for DUT statistics - Interface counters, PFC counters, and Queue counters.
  tests/common/snappi_tests/common_helpers.py
Labels: Request for 202405 branch, IXIA_CHASSIS

#14387 [wol_test] Test expected failure like invalid parameters, down interface etc.
  tests/wol/test_wol.py
Labels: Request for 202311 branch, Request for 202405 branch

#14285 [Snappi] fix TypeError in multidut snappi test cases and topo maker
  tests/common/snappi_tests/common_helpers.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py
Labels: Request for 202405 branch

#14430 [action] [PR:14299] [wol_test] implement tests for wol
  tests/common/utilities.py
  tests/wol/conftest.py
  tests/wol/test_wol.py
Labels: automerge

#14429 [action] [PR:13848] [Snappi] Support for DUT statistics - Interface counters, PFC counters, and Queue counters.
  tests/common/snappi_tests/common_helpers.py
Labels: automerge

#14435 [action] [PR:14414] [Feature] Use cache to speed up test module preparation
  tests/common/cache/facts_cache.py
  tests/common/devices/sonic.py
  tests/common/devices/sonic_asic.py
  tests/common/helpers/cache_utils.py
Labels: automerge

#14432 [action] [PR:14285] [Snappi] fix TypeError in multidut snappi test cases and topo maker
  tests/common/snappi_tests/common_helpers.py
  tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py
Labels: automerge

#14421 [golden_config_infra] Backup and Restore config before test
  tests/golden_config_infra/test_config_reload_with_rendered_golden_config.py
Labels: Request for 202405 branch

#14438 [action] [PR:14421] [golden_config_infra] Backup and Restore config before test
  tests/golden_config_infra/test_config_reload_with_rendered_golden_config.py
Labels: automerge

#14454 [action] [PR:13070] Modify snmp link local test to use config cli
  tests/snmp/test_snmp_link_local.py
Labels: automerge

#14446 [action] [PR:14138] Fix reload_config failed on M0 device because PFCWD feature does not exist
  tests/common/config_reload.py
Labels: automerge

#14461 [action] [PR:14436] add hwsku cisco-8122-O64
  ansible/group_vars/sonic/variables
Labels: automerge

#14457 [action] [PR:14231] disabled test_restapi::test_create_vrf for non-t1 platforms.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14456 [action] [PR:14387] [wol_test] Test expected failure like invalid parameters, down interface etc.
  tests/wol/test_wol.py
Labels: automerge

#14453 [action] [PR:14164] [dhcp_relay] Add dhcpv6 relay bind test when dhcpv6_server is not configured
  tests/dhcp_relay/test_dhcpv6_relay.py
Labels: automerge

#14452 [action] [PR:14164] [dhcp_relay] Add dhcpv6 relay bind test when dhcpv6_server is not configured
  tests/dhcp_relay/test_dhcpv6_relay.py
Labels: automerge

#14464 [action] [PR:14012] [dhcp_relay] Refactor dhcp_relay for dualtor
  ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/dhcp_relay/test_dhcp_relay.py
Labels: automerge

#13927 sonic-mgmt: reduce fdb test time for large topos
  tests/fdb/test_fdb.py
Labels: arista, Request for 202311 branch, Request for 202405 branch

#14466 [action] [PR:13889] Subject: Skip some route tests for standalone topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14465 [action] [PR:13927] sonic-mgmt: reduce fdb test time for large topos
  tests/fdb/test_fdb.py
Labels: automerge

#14455 [action] [PR:14387] [wol_test] Test expected failure like invalid parameters, down interface etc.
  tests/wol/test_wol.py
Labels: automerge

#14029 [snappi]:Change ipv4 to random-src-port udp traffic.
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_basic_helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_burst_storm_helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_multi_node_helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_runtime_traffic_helper.py
  tests/snappi_tests/test_multidut_snappi.py
Labels: Request for 202405 branch

#14470 [action] [PR:14029] [snappi]:Change ipv4 to random-src-port udp traffic.
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_basic_helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_burst_storm_helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_multi_node_helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_runtime_traffic_helper.py
  tests/snappi_tests/test_multidut_snappi.py
Labels: automerge

#14431 Remove dependence in script `bfd_helpers.py`.
  tests/bfd/bfd_helpers.py
Labels: Request for 202405 branch

#14063 [Mellanox] Update dynamic buffer parameter for x86_64-nvidia_sn4280-r0
  tests/qos/files/dynamic_buffer_param.json
Labels: Request for 202405 branch

#14445 Skip test_neighbor_mac_noptf on standalone topologies
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202311 branch, Request for 202405 branch

#14487 [action] [PR:14089] Make oscillation fix persistent across reboots and config reload
  tests/common/dualtor/dual_tor_utils.py
Labels: automerge

#14486 [action] [PR:14089] Make oscillation fix persistent across reboots and config reload
  tests/common/dualtor/dual_tor_utils.py
Labels: automerge

#14484 [action] [PR:13564] Add pcbb_xoff parameters for dualtor-aa-56 topo and 50000_40m profile
  tests/qos/files/qos_params.th2.yaml
Labels: automerge

#14481 [action] [PR:14445] Skip test_neighbor_mac_noptf on standalone topologies
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14003 Fix lag flap check for sonic peer
  ansible/roles/test/files/ptftests/sonic.py
Labels: Request for 202311 branch, Request for 202405 branch

#14489 [action] [PR:14154] Enhancement of test_sensors.py to address several issues
  tests/platform_tests/sensors_utils/psu_data.yaml
  tests/platform_tests/sensors_utils/psu_sensor_utils.py
  tests/platform_tests/sensors_utils/psu_sensors.json
  tests/platform_tests/test_sensors.py
Labels: automerge

#14480 [action] [PR:14063] [Mellanox] Update dynamic buffer parameter for x86_64-nvidia_sn4280-r0
  tests/qos/files/dynamic_buffer_param.json
Labels: automerge

#14460 Enable test_pktgen.py for Cisco-8000 ASIC Type
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/test_pktgen.py
Labels: Request for 202405 branch

#14509 [action] [PR:12986] Fix BGP status sanity check failure when topology doesn't have any VMs.
  tests/common/plugins/sanity_check/checks.py
Labels: automerge

#14508 [action] [PR:14477] [dhcp_server_test] fix index error because of no ip left in list
  tests/dhcp_server/test_dhcp_server_multi_vlans.py
Labels: automerge

#14507 [action] [PR:14477] [dhcp_server_test] fix index error because of no ip left in list
  tests/dhcp_server/test_dhcp_server_multi_vlans.py
Labels: automerge

#14505 [action] [PR:14304] [Test gap][BBR] Test for default state after restart
  tests/bgp/test_bgp_bbr_default_state.py
Labels: automerge

#14504 [action] [PR:14304] [Test gap][BBR] Test for default state after restart
  tests/bgp/test_bgp_bbr_default_state.py
Labels: automerge

#14501 [action] [PR:14003] Fix lag flap check for sonic peer
  ansible/roles/test/files/ptftests/sonic.py
Labels: automerge

#14500 [action] [PR:14003] Fix lag flap check for sonic peer
  ansible/roles/test/files/ptftests/sonic.py
Labels: automerge

#14488 [action] [PR:14154] Enhancement of test_sensors.py to address several issues
  tests/platform_tests/sensors_utils/psu_data.yaml
  tests/platform_tests/sensors_utils/psu_sensor_utils.py
  tests/platform_tests/sensors_utils/psu_sensors.json
  tests/platform_tests/test_sensors.py
Labels: automerge

#14511 tests-common: Handle SSHConsoleConn being closed prematurely
  tests/common/connections/ssh_console_conn.py
Labels: Included in 202311 branch, Included in 202405 branch

#14536 [action] [PR:14394] Improve TestbedProcessing.py
  ansible/TestbedProcessing.py
Labels: automerge

#14534 [action] [PR:14394] Improve TestbedProcessing.py
  ansible/TestbedProcessing.py
Labels: automerge

#14532 [action] [PR:12558] [logrotate]: Relax APPL_DB check tolerance
  tests/syslog/test_logrotate.py
Labels: automerge

#14232 Update test_qos_sai for ComputeAI config
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/files/qos_params.gr.yaml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202311 branch, Request for 202405 branch

#14546 [tests/configlet] Update configlet test to align with swss update
  tests/configlet/util/common.py
Labels: Request for 202311 branch, Request for 202405 branch

#14552 Prolong wait/timeout for chassis in reboot
  tests/common/reboot.py
Labels: Request for 202405 branch

#14553 [mx][deploy-mg] Add dependent tables in golden_config_db for mx in deploy-mg
  ansible/library/generate_golden_config_db.py
Labels: Request for 202311 branch, Request for 202405 branch

#14558 [action] [PR:14553] [mx][deploy-mg] Add dependent tables in golden_config_db for mx in deploy-mg
  ansible/library/generate_golden_config_db.py
Labels: automerge

#14556 [action] [PR:14546] [tests/configlet] Update configlet test to align with swss update
  tests/configlet/util/common.py
Labels: automerge

#14555 [action] [PR:14552] Prolong wait/timeout for chassis in reboot
  tests/common/reboot.py
Labels: automerge

#14554 [action] [PR:14546] [tests/configlet] Update configlet test to align with swss update
  tests/configlet/util/common.py
Labels: automerge

#14547 [action] [PR:13821] Fix syslog test failure about fixture tbinfo
  tests/syslog/test_logrotate.py
Labels: automerge

#14544 [action] [PR:14511] tests-common: Handle SSHConsoleConn being closed prematurely
  tests/common/connections/ssh_console_conn.py
Labels: automerge

#14538 [action] [PR:14397] add conditional mark to skip LLDP and SNMP testcases for standalone topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14537 [action] [PR:14397] add conditional mark to skip LLDP and SNMP testcases for standalone topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14535 [action] [PR:14394] Improve TestbedProcessing.py
  ansible/TestbedProcessing.py
Labels: automerge

#14545 Refactor test_acl.py with multi-thread for multi-dut scenario
  tests/acl/test_acl.py
  tests/common/config_reload.py
  tests/common/helpers/multi_thread_utils.py
  tests/common/port_toggle.py
  tests/common/reboot.py
Labels: Request for 202405 branch

#14496 Optimise some scripts under folder `tests/generic_config_updater`
  tests/arp/arp_utils.py
  tests/arp/conftest.py
  tests/arp/test_arp_extended.py
  tests/arp/test_stress_arp.py
  tests/common/utilities.py
  tests/generic_config_updater/test_dynamic_acl.py
  tests/generic_config_updater/test_mgmt_interface.py
  tests/route/test_forced_mgmt_route.py
Labels: Request for 202405 branch

#14517 [bugfix] fix pfc_counter does not select the correct dut_host_name
  tests/qos/test_pfc_counters.py
Labels: Request for 202405 branch

#14092 [action] [PR:13976] Degrade PFC storm detection in PFCWD all ports storm test
  tests/pfcwd/files/pfc_detect_mellanox.lua
  tests/pfcwd/test_pfcwd_all_port_storm.py
Labels: automerge

#14560 [action] [PR:13907] Q200 longlink qos params update, xoff threshold change from 90MB to 25MB
  tests/qos/files/qos_params.gb.yaml
Labels: automerge

#14548 Fix conditional mark error for `vxlan/test_vxlan_crm.py`
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#14549 [action] [PR:14232] Update test_qos_sai for ComputeAI config
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/files/qos_params.gr.yaml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#14564 [action] [PR:14517] [bugfix] fix pfc_counter does not select the correct dut_host_name
  tests/qos/test_pfc_counters.py
Labels: automerge

#14562 Loose PFCWD timer accuracy test on Mellanox testbed with Non-Onyx or Non-Mellanox leaf fanout
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: Approved for 202311 branch, Approved for 202405 branch

#14361 [Snappi] Infra changes to make snappi multidut work for T0/T1 testbed
  tests/common/fixtures/conn_graph_facts.py
  tests/common/snappi_tests/common_helpers.py
  tests/common/snappi_tests/snappi_fixtures.py
  tests/snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
Labels: Request for 202405 branch, IXIA_CHASSIS

#14490 [Snappi] fix Error in get_pg_dropped_packets for T2 testbed
  tests/common/snappi_tests/common_helpers.py
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/multidut/pfc/files/multidut_helper.py
Labels: Request for 202405 branch, IXIA_CHASSIS

#14442 [Fix] Fixing ecnconfig command
  tests/common/snappi_tests/common_helpers.py
Labels: Request for 202405 branch, IXIA_CHASSIS

#14566 [mx] Enable dhcp_server feature for mx in deploy-mg
  ansible/library/generate_golden_config_db.py
Labels: Request for 202405 branch

#14570 [action] [PR:14562] Loose PFCWD timer accuracy test on Mellanox testbed with Non-Onyx or Non-Mellanox leaf fanout
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#14571 [action] [PR:14562] Loose PFCWD timer accuracy test on Mellanox testbed with Non-Onyx or Non-Mellanox leaf fanout
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#13497 Set inner packet next header as TCP
  ansible/roles/test/files/ptftests/py3/generic_hash_test.py
Labels: Request for 202311 branch, Request for 202405 branch

#14576 [action] [PR:14442] [Fix] Fixing ecnconfig command
  tests/common/snappi_tests/common_helpers.py
Labels: automerge

#14575 [action] [PR:14490] [Snappi] fix Error in get_pg_dropped_packets for T2 testbed
  tests/common/snappi_tests/common_helpers.py
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/multidut/pfc/files/multidut_helper.py
Labels: automerge

#14574 [action] [PR:14361] [Snappi] Infra changes to make snappi multidut work for T0/T1 testbed
  tests/common/fixtures/conn_graph_facts.py
  tests/common/snappi_tests/common_helpers.py
  tests/common/snappi_tests/snappi_fixtures.py
  tests/snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
Labels: automerge

#14543 [action] [PR:14511] tests-common: Handle SSHConsoleConn being closed prematurely
  tests/common/connections/ssh_console_conn.py
Labels: automerge

#14557 [action] [PR:14553] [mx][deploy-mg] Add dependent tables in golden_config_db for mx in deploy-mg
  ansible/library/generate_golden_config_db.py
Labels: automerge

#14485 [action] [PR:13564] Add pcbb_xoff parameters for dualtor-aa-56 topo and 50000_40m profile
  tests/qos/files/qos_params.th2.yaml
Labels: automerge

#14587 [action] [PR:12152] Fix fixture invocation order in qos/qos_sai_base.py
  tests/qos/qos_sai_base.py
Labels: automerge

#14593 [action] [PR:14589] [pfcwd] Add half of polling time as compensation for test_pfcwd_timer_accuracy
  tests/common/helpers/pfc_gen.py
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#14592 [action] [PR:14589] [pfcwd] Add half of polling time as compensation for test_pfcwd_timer_accuracy
  tests/common/helpers/pfc_gen.py
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#14591 [action] [PR:14080] Test Plan: Verification of LLDP_ENTRY_TABLE in SONiC APPL_DB
  docs/testplan/LLDP-syncd-test-plan.md
Labels: automerge

#14594 [test_orchagent_slb] Fix test_orchagent_slb
  tests/common/dualtor/tunnel_traffic_utils.py
Labels: Request for 202311 branch, Request for 202405 branch

#14579 Solve 202405 branch conflicts in the PR #14041
  tests/pfcwd/files/pfcwd_helper.py
  tests/pfcwd/test_pfcwd_function.py
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: Request for 202405 branch

#14598 [action] [PR:14520] Skip test_config_fec_oper_mode test for unsupported speeds
  tests/platform_tests/test_intf_fec.py
Labels: automerge

#14606 [action] [PR:14594] [test_orchagent_slb] Fix test_orchagent_slb
  tests/common/dualtor/tunnel_traffic_utils.py
Labels: automerge

#14605 [action] [PR:14594] [test_orchagent_slb] Fix test_orchagent_slb
  tests/common/dualtor/tunnel_traffic_utils.py
Labels: automerge

#14604 [action] [PR:11968] Full Mesh Traffic Sanity verification
  tests/common/plugins/conditional_mark/__init__.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#14611 [action] [PR:14445] Skip test_neighbor_mac_noptf on standalone topologies
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#14596 Remove any null characters before parsing string in test_snmp_phy_entity
  tests/snmp/test_snmp_phy_entity.py
Labels: Request for 202311 branch, Request for 202405 branch

#14599 Add an additional check to verify FEC stat counters
  tests/platform_tests/test_intf_fec.py
Labels: Request for 202405 branch

#14203 Cisco-8111: adjust reduced_pause_thr to hardware value
  tests/qos/files/cisco/qos_param_generator.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch

#13809 [Smartswitch] Fix lldp test for smart switch
  tests/common/platform/interface_utils.py
  tests/lldp/test_lldp.py
Labels: Request for 202405 branch

#14585 Updating J2C+ qos yaml for 400G and 100G profile _egress_pkt count for lossy profile
  tests/qos/files/qos_params.j2c.yaml
  tests/qos/files/qos_params.jr2.yaml
Labels: Request for 202205 branch, Request for 202405 branch

#14402 Added consistency checker
  tests/common/fixtures/consistency_checker/consistency_checker.py
  tests/common/fixtures/consistency_checker/constants.py
  tests/common/fixtures/consistency_checker/query-asic/parser.py
  tests/common/fixtures/consistency_checker/query-asic/query-asic.py
  tests/common/helpers/upgrade_helpers.py
  tests/platform_tests/args/advanced_reboot_args.py
  tests/upgrade_path/test_upgrade_path.py
Labels: Request for 202311 branch, Request for 202405 branch

#14097 [Snappi]: Support to clear and check fabric counters
  tests/common/snappi_tests/snappi_fixtures.py
Labels: Request for 202405 branch

#14627 [COPP][720DT] Fix copp test failure for 720dt
  ansible/roles/test/files/ptftests/py3/copp_tests.py
  tests/copp/test_copp.py
Labels: Request for 202311 branch, Request for 202405 branch

#14498 [snappi] Fix helper config_wred to config RED for Broadcom ASIC
  tests/common/snappi_tests/common_helpers.py
Labels: Request for 202405 branch, IXIA_CHASSIS

#13317 Enhance log processing for sonic neighbors
  ansible/roles/test/files/ptftests/sonic.py
Labels: Request for 202311 branch, Request for 202405 branch

#14638 [action] [PR:14204] Enable ComputeAI deployment for hwsku Cisco-8111-O32
  ansible/config_sonic_basedon_testbed.yml
Labels: automerge

#14637 [action] [PR:14204] Enable ComputeAI deployment for hwsku Cisco-8111-O32
  ansible/config_sonic_basedon_testbed.yml
Labels: automerge

#14633 [action] [PR:13809] [Smartswitch] Fix lldp test for smart switch
  tests/common/platform/interface_utils.py
  tests/lldp/test_lldp.py
Labels: automerge

#14630 [action] [PR:12071] [dhcp_relay] Add time wait for route check
  tests/dhcp_relay/test_dhcp_relay.py
Labels: automerge

#14626 [action] [PR:14203] Cisco-8111: adjust reduced_pause_thr to hardware value
  tests/qos/files/cisco/qos_param_generator.py
Labels: automerge
