Repository sonic-net/sonic-mgmt, pull requests merged in 2024-02, with the labels that each got.

#11444 [CoPP] Enhancing ptftests/py3/copp_tests.py testcase to handle no trap condition
  ansible/roles/test/files/ptftests/py3/copp_tests.py
Labels: Request for 202305 branch, Request for 202311 branch

#11457 Fix DataLoader cannot be imported with py3only sonic-mgmt-docker
  ansible/library/testbed_vm_info.py
Labels: Request for 202305 branch, Request for 202311 branch

#11479 [action] [PR:11431] [dualtor-aa] Fix OpenFlow select method change on Ubuntu 20.04
  ansible/dualtor/nic_simulator/nic_simulator.py
  tests/common/dualtor/dual_tor_io.py
Labels: automerge

#11477 [action] [PR:11319] Extend timeout after reboot in copp
  tests/copp/test_copp.py
Labels: automerge

#11475 [action] [PR:11298] [Mellanox] Fix sensor data for platform MSN2700-A1
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: automerge

#11476 [action] [PR:11298] [Mellanox] Fix sensor data for platform MSN2700-A1
  ansible/group_vars/sonic/sku-sensors-data.yml
Labels: automerge

#11474 [action] [PR:11263] test_voq_chassis_app_db_consistency.py: Increase timeout of config reload and reboot
  tests/voq/test_voq_chassis_app_db_consistency.py
Labels: automerge

#11463 [action] [PR:10748] Update test_memory_checker to support gnmi and telemetry containers
  .azure-pipelines/pr_test_scripts.yaml
  tests/memory_checker/test_memory_checker.py
Labels: automerge

#11541 [action] [PR:6425] Correct the error handling in EOS if wrong eos login occurred
  tests/common/devices/eos.py
Labels: automerge

#11532 [action] [PR:11258] Fix T2 advertise_withdraw test failure
  ansible/library/announce_routes.py
  tests/route/test_route_consistency.py
Labels: automerge

#11528 [action] [PR:11206] [route flap] Update logic to get dev_port
  tests/route/test_route_flap.py
Labels: automerge

#11525 [action] [PR:11148] [SNMP E2E Testing] Select the right PDU controller in Dual-TOR testbed
  tests/snmp/test_snmp_phy_entity.py
Labels: automerge

#11524 [action] [PR:11131] Support using SONiC 202305 image as leaf fanout switch
  ansible/module_utils/port_utils.py
  ansible/roles/fanout/tasks/fanout_sonic.yml
  ansible/roles/fanout/tasks/sonic/copp_cfg_mlnx.j2
  ansible/roles/fanout/tasks/sonic/fanout_sonic_202305.yml
  ansible/roles/fanout/templates/sonic_deploy_202305.j2
Labels: automerge

#11523 [action] [PR:11092] Add Serial Number check test case.
  tests/platform_tests/cli/test_show_platform.py
Labels: automerge

#11522 [action] [PR:11092] Add Serial Number check test case.
  tests/platform_tests/cli/test_show_platform.py
Labels: automerge

#11518 [action] [PR:10651] Add docker0's IPv6 address since it was removed when disabling IPv6
  tests/qos/qos_sai_base.py
Labels: automerge

#11546 [action] [PR:11282] Mutli_asic check for T2_arppopulate qos_test
  tests/qos/qos_sai_base.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#11545 [action] [PR:11282] Mutli_asic check for T2_arppopulate qos_test
  tests/qos/qos_sai_base.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#11544 [action] [PR:11282] Mutli_asic check for T2_arppopulate qos_test
  tests/qos/qos_sai_base.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#11543 [action] [PR:11216] Skip test_memory_exhaustion on 6100 platform
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: automerge

#11542 [action] [PR:10821] [Arista] skip testing sfp interfaces on Arista-7050QX-32S-S4Q31
  tests/platform_tests/conftest.py
Labels: automerge

#11540 [action] [PR:11444] [CoPP] Enhancing ptftests/py3/copp_tests.py testcase to handle no trap condition
  ansible/roles/test/files/ptftests/py3/copp_tests.py
Labels: automerge

#11539 [action] [PR:11444] [CoPP] Enhancing ptftests/py3/copp_tests.py testcase to handle no trap condition
  ansible/roles/test/files/ptftests/py3/copp_tests.py
Labels: automerge

#11538 [action] [PR:11331] Update hash_test.py to fix issue #10961
  ansible/roles/test/files/ptftests/py3/hash_test.py
Labels: automerge

#11537 [action] [PR:11331] Update hash_test.py to fix issue #10961
  ansible/roles/test/files/ptftests/py3/hash_test.py
Labels: automerge

#11535 [action] [PR:11330] Fix issue due to TypeError: 'dict_keys' object is not subscriptable
  tests/common/fixtures/fib_utils.py
Labels: automerge

#11534 [action] [PR:11330] Fix issue due to TypeError: 'dict_keys' object is not subscriptable
  tests/common/fixtures/fib_utils.py
Labels: automerge

#11533 [action] [PR:11258] Fix T2 advertise_withdraw test failure
  ansible/library/announce_routes.py
  tests/route/test_route_consistency.py
Labels: automerge

#11531 [action] [PR:11258] Fix T2 advertise_withdraw test failure
  ansible/library/announce_routes.py
  tests/route/test_route_consistency.py
Labels: automerge

#11529 [action] [PR:11225] Skip po2vlan test for sonic fanout
  tests/common/helpers/portchannel_to_vlan.py
Labels: automerge

#11530 [action] [PR:11225] Skip po2vlan test for sonic fanout
  tests/common/helpers/portchannel_to_vlan.py
Labels: automerge

#11527 [action] [PR:11206] [route flap] Update logic to get dev_port
  tests/route/test_route_flap.py
Labels: automerge

#11526 [action] [PR:11148] [SNMP E2E Testing] Select the right PDU controller in Dual-TOR testbed
  tests/snmp/test_snmp_phy_entity.py
Labels: automerge

#11521 [action] [PR:11004] check in topo_t1-56-lag.yml for O8C48
  ansible/vars/topo_t1-56-lag.yml
Labels: automerge

#11519 [action] [PR:10834] Make bgp/test_bgp_queue.py aware of multi-asic
  tests/bgp/test_bgp_queue.py
Labels: automerge

#11516 [action] [PR:10966] Add github issue skip to link_flap test
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#11515 [action] [PR:10914] Update sfp test for sonic-utilities PR#2953
  tests/platform_tests/sfp/test_sfputil.py
Labels: automerge

#11513 [action] [PR:10886] platform_tests: Fix skip_modules check in test_power_budget_info.py
  tests/platform_tests/test_power_budget_info.py
Labels: automerge

#11512 [action] [PR:10870] Increase timeout for copp test_trap_config_save_after_reboot
  tests/copp/test_copp.py
Labels: automerge

#11511 [action] [PR:10870] Increase timeout for copp test_trap_config_save_after_reboot
  tests/copp/test_copp.py
Labels: automerge

#11510 [action] [PR:10870] Increase timeout for copp test_trap_config_save_after_reboot
  tests/copp/test_copp.py
Labels: automerge

#11509 [action] [PR:10853] Add skip for test_custom_acl_table.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#11508 [action] [PR:10851] Move fixture skip_when_buffer_is_dynamic_model to conftest file
  tests/generic_config_updater/conftest.py
  tests/generic_config_updater/test_incremental_qos.py
  tests/generic_config_updater/test_mmu_dynamic_threshold_config_update.py
Labels: automerge

#11505 [action] [PR:10727] Fix test_fabric_reach.py to run on t2 min topology.
  tests/voq/test_fabric_reach.py
Labels: automerge

#11504 [action] [PR:10727] Fix test_fabric_reach.py to run on t2 min topology.
  tests/voq/test_fabric_reach.py
Labels: automerge

#11503 [action] [PR:10720] [chassis][voq] Add jr2/j2c+ Arista hwsku on variable file
  ansible/group_vars/sonic/variables
Labels: automerge

#11501 [action] [PR:10720] [chassis][voq] Add jr2/j2c+ Arista hwsku on variable file
  ansible/group_vars/sonic/variables
Labels: automerge

#11502 [action] [PR:10720] [chassis][voq] Add jr2/j2c+ Arista hwsku on variable file
  ansible/group_vars/sonic/variables
Labels: automerge

#11500 [action] [PR:10714] [Mellanox] Enable TestQosSaiDscpToPgMapping and skip testIPIPQosSaiDscpToPgMapping
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/qos/test_qos_sai.py
Labels: automerge

#11499 [action] [PR:10705] [Mellanox] Add topology marker for test_vxlan_crm script
  tests/vxlan/test_vxlan_crm.py
Labels: automerge

#11496 [action] [PR:11457] Fix DataLoader cannot be imported with py3only sonic-mgmt-docker
  ansible/library/testbed_vm_info.py
Labels: automerge

#11495 [action] [PR:11457] Fix DataLoader cannot be imported with py3only sonic-mgmt-docker
  ansible/library/testbed_vm_info.py
Labels: automerge

#11494 [action] [PR:10468] Ignore kdump-tools log message from loganalyzer
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#11493 [action] [PR:10430] [Nvidia] Fix dscp remapping cases
  tests/saitests/py3/sai_base_test.py
Labels: automerge

#11492 [action] [PR:10430] [Nvidia] Fix dscp remapping cases
  tests/saitests/py3/sai_base_test.py
Labels: automerge

#11491 [action] [PR:10239] [chassis] To Verify In TSA Loopback0 IP's of all LC's should be advertised to peer neighbors
  tests/bgp/test_traffic_shift.py
Labels: automerge

#11490 [action] [PR:10239] [chassis] To Verify In TSA Loopback0 IP's of all LC's should be advertised to peer neighbors
  tests/bgp/test_traffic_shift.py
Labels: automerge

#11489 [action] [PR:10685] Fix an error in parsing the neighbor analysis for SONiC neighbors
  ansible/roles/test/files/ptftests/advanced-reboot.py
Labels: automerge

#11488 [action] [PR:10074] Use pytest option for swapping syncd in dscp remapping test
  tests/qos/tunnel_qos_remap_base.py
Labels: automerge

#11487 [action] [PR:10074] Use pytest option for swapping syncd in dscp remapping test
  tests/qos/tunnel_qos_remap_base.py
Labels: automerge

#11486 [action] [PR:10047] Add platform test for kdump
  tests/common/reboot.py
  tests/platform_tests/test_kdump.py
Labels: automerge

#11485 [action] [PR:10047] Add platform test for kdump
  tests/common/reboot.py
  tests/platform_tests/test_kdump.py
Labels: automerge

#11484 [action] [PR:9619] [Nvidia] [Dual-Tor] [Active-Standby] Add new active-standby dual-tor egress drop cases for Nvidia platforms
  tests/common/devices/sonic.py
  tests/common/dualtor/dual_tor_utils.py
  tests/dualtor_mgmt/test_egress_drop_nvidia.py
Labels: automerge

#11483 [action] [PR:9198] [Dual-Tor] Improve the stability of dualtor memory leak test
  tests/dualtor/test_tunnel_memory_leak.py
Labels: automerge

#11480 [action] [PR:11431] [dualtor-aa] Fix OpenFlow select method change on Ubuntu 20.04
  ansible/dualtor/nic_simulator/nic_simulator.py
  tests/common/dualtor/dual_tor_io.py
Labels: automerge

#11478 [action] [PR:11382] Disable iface_loopback_action tests on Broadcom switches
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#11473 [action] [PR:11263] test_voq_chassis_app_db_consistency.py: Increase timeout of config reload and reboot
  tests/voq/test_voq_chassis_app_db_consistency.py
Labels: automerge

#11472 [action] [PR:11263] test_voq_chassis_app_db_consistency.py: Increase timeout of config reload and reboot
  tests/voq/test_voq_chassis_app_db_consistency.py
Labels: automerge

#11471 [action] [PR:11197] Add setup_streaming_telemetry fixture to cache tests
  tests/telemetry/test_events.py
Labels: automerge

#11469 [action] [PR:11135] Ignore the migration error in upgrade path test when downgrading to the from_image
  ansible/library/reduce_and_add_sonic_images.py
  tests/upgrade_path/test_upgrade_path.py
Labels: automerge

#11468 [action] [PR:11033] Define new topology t0-56-o8v48
  ansible/vars/topo_t0-56-o8v48.yml
Labels: automerge

#11466 [action] [PR:10907] Fix loopback action reload test
  tests/iface_loopback_action/iface_loopback_action_helper.py
  tests/iface_loopback_action/test_iface_loopback_action.py
Labels: automerge

#11465 [action] [PR:8942] Add swss events to test_events
  tests/telemetry/events/swss_events.py
  tests/telemetry/test_events.py
Labels: automerge

#10926 [Fix]:PFC multidut helper fix for latest traffic_generator.py
  tests/snappi_tests/multidut/pfc/files/multidut_helper.py
  tests/snappi_tests/multidut/pfc/test_multidut_global_pause_with_snappi.py
Labels: chassis

#11347 [techsupport] Add err msg ignore for techsupport test
  tests/show_techsupport/conftest.py
Labels: Request for 202305 branch, Request for 202311 branch

#7912 [Snappi] Added multi dut PFC Lossless test case
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
Labels: chassis, Request for 202205 branch, Request for 202305 branch

#10398 [T2] update wred qos params for pacific (cisco Q100)
  tests/qos/files/qos_params.pac.yaml
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: included in internal-2022205

#11561 Adjust the memory check threshold for Mellanox-SN3800
  tests/platform_tests/test_cpu_memory_usage.py
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#11562 Fix syntax issue in TunnelDscpToPgMapping
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202305 branch, Request for 202311 branch

#11579 [action] [PR:10481] [T2]:Change the hbm-check condition to check the cable length.
  tests/pfcwd/test_pfcwd_function.py
Labels: automerge

#11577 [action] [PR:10398] [T2] update wred qos params for pacific (cisco Q100)
  tests/qos/files/qos_params.pac.yaml
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#11583 [action] [PR:11347] [techsupport] Add err msg ignore for techsupport test
  tests/show_techsupport/conftest.py
Labels: automerge

#11584 [action] [PR:11445] [chassis] Fixed expected_num_asics for Supervisor in test_show_platform
  tests/platform_tests/cli/test_show_platform.py
Labels: automerge

#11384 Change the losslessvoq ports to use the ones coming from qos-sai-base.
  tests/qos/test_qos_sai.py
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#10896 Cisco: Qos-sai: Change the tests to use only downlink ports.
  tests/qos/test_qos_sai.py
Labels: Request for 202311 branch

#11616 [action] [PR:11409] Skip test_replace_fec for known issue
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#11615 [action] [PR:11409] Skip test_replace_fec for known issue
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#11605 [action] [PR:11384] Change the losslessvoq ports to use the ones coming from qos-sai-base.
  tests/qos/test_qos_sai.py
Labels: automerge

#11634 [action] [PR:11618] Revert "[CoPP] Enhancing ptftests/py3/copp_tests.py testcase to handle no trap condition"
  ansible/roles/test/files/ptftests/py3/copp_tests.py
Labels: automerge

#11633 [action] [PR:11618] Revert "[CoPP] Enhancing ptftests/py3/copp_tests.py testcase to handle no trap condition"
  ansible/roles/test/files/ptftests/py3/copp_tests.py
Labels: automerge

#11607 [action] [PR:10896] Cisco: Qos-sai: Change the tests to use only downlink ports.
  tests/qos/test_qos_sai.py
Labels: automerge

#11606 [action] [PR:11384] Change the losslessvoq ports to use the ones coming from qos-sai-base.
  tests/qos/test_qos_sai.py
Labels: automerge

#11589 [action] [PR:11562] Fix syntax issue in TunnelDscpToPgMapping
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#11588 [action] [PR:11561] Adjust the memory check threshold for Mellanox-SN3800
  tests/platform_tests/test_cpu_memory_usage.py
Labels: automerge

#11585 [action] [PR:11445] [chassis] Fixed expected_num_asics for Supervisor in test_show_platform
  tests/platform_tests/cli/test_show_platform.py
Labels: automerge

#11581 [action] [PR:11347] [techsupport] Add err msg ignore for techsupport test
  tests/show_techsupport/conftest.py
Labels: automerge

#11578 [action] [PR:10481] [T2]:Change the hbm-check condition to check the cable length.
  tests/pfcwd/test_pfcwd_function.py
Labels: automerge

#11576 [action] [PR:10398] [T2] update wred qos params for pacific (cisco Q100)
  tests/qos/files/qos_params.pac.yaml
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#11571 [action] [PR:11328] Update regex for detecting a MAC jump for Broadcom platforms
  tests/platform_tests/reboot_timing_constants.py
  tests/platform_tests/templates/expect_boot_messages
Labels: automerge

#11645 [action] [PR:11312] Fix to use non RegionalHub peers to test route entry presence
  tests/voq/test_voq_ipfwd.py
Labels: automerge

#11643 [action] [PR:11312] Fix to use non RegionalHub peers to test route entry presence
  tests/voq/test_voq_ipfwd.py
Labels: automerge

#11644 [action] [PR:11312] Fix to use non RegionalHub peers to test route entry presence
  tests/voq/test_voq_ipfwd.py
Labels: automerge

#11642 [action] [PR:10892] Fix iface_namingmode alias check
  tests/iface_namingmode/test_iface_namingmode.py
Labels: automerge

#11641 [action] [PR:10892] Fix iface_namingmode alias check
  tests/iface_namingmode/test_iface_namingmode.py
Labels: automerge

#11640 [action] [PR:11227] Ignore firmware failed to load ERR messages
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#11639 [action] [PR:11227] Ignore firmware failed to load ERR messages
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#11646 [action] [PR:11553] update skip condition for cisco T2
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: automerge

#11462 [master]Vxlan ecmp test cleanup and fix.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/vxlan/test_vxlan_ecmp.py
  tests/vxlan/test_vxlan_ecmp_switchover.py
Labels: Request for 202305 branch, Request for 202311 branch

#11657 [pc] Fix test_lag_member_traffic arp issue
  tests/pc/test_lag_member.py
Labels: Request for 202305 branch, Request for 202311 branch

#11661 [action] [PR:11657] [pc] Fix test_lag_member_traffic arp issue
  tests/pc/test_lag_member.py
Labels: automerge

#11660 [action] [PR:11657] [pc] Fix test_lag_member_traffic arp issue
  tests/pc/test_lag_member.py
Labels: automerge

#11659 [Snappi] Bug fix for PFC class enable vector test
  tests/common/snappi_tests/traffic_generation.py
Labels: Request for 202305 branch, Request for 202311 branch

#11679 [action] [PR:11462] [master]Vxlan ecmp test cleanup and fix.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/vxlan/test_vxlan_ecmp.py
  tests/vxlan/test_vxlan_ecmp_switchover.py
Labels: automerge

#11678 [action] [PR:11462] [master]Vxlan ecmp test cleanup and fix.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/vxlan/test_vxlan_ecmp.py
  tests/vxlan/test_vxlan_ecmp_switchover.py
Labels: automerge

#10838 [T2] Add case to test lossy fair-voq
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/qos/files/cisco/qos_param_generator.py
  tests/qos/files/qos_params.gb.yaml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202305 branch, Request for 202311 branch

#11665 Add support of t0-56-o8v48 to continuous_reboot test
  ansible/roles/test/vars/testcases.yml
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#11416 Update sflow test to check sflow config installation status
  tests/sflow/test_sflow.py
Labels: Request for 202305 branch, Request for 202311 branch

#11378 Update qos_sai_base.py to support dualtor-64 topology
  tests/qos/qos_sai_base.py
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#11254 Update test_pg_headroom_update to check buffer mode before running
  tests/generic_config_updater/test_pg_headroom_update.py
Labels: Request for 202305 branch, Request for 202311 branch

#11240 [Mellanox]Add new Mellanox HwSku
  ansible/group_vars/sonic/variables
Labels: Request for 202305 branch, Request for 202311 branch

#11165 [Mellanox] Ignore checking ASIC/module temperature if thermal updater is there
  tests/platform_tests/mellanox/mellanox_thermal_control_test_helper.py
Labels: Request for 202311 branch

#11664 Update skip condition for test_tunnel_memory_leak
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#11464 Set random seed for tests
  tests/common/helpers/constants.py
  tests/common/plugins/allure_server/__init__.py
  tests/common/plugins/random_seed/__init__.py
  tests/conftest.py
Labels: Request for 202311 branch

#11391 Compress pcap files before copying it from pft to sonic-mgmt
  tests/ptf_runner.py
Labels: Request for 202305 branch, Request for 202311 branch

#11253 Update script test_syslog_source_ip for stablization
  tests/syslog/syslog_utils.py
  tests/syslog/test_syslog_source_ip.py
Labels: Request for 202305 branch, Request for 202311 branch

#11560 Update J2 100_120k qos profile to match J2c
  tests/qos/files/qos_params.jr2.yaml
Labels: Request for 202205 branch

#11690 [action] [PR:11253] Update script test_syslog_source_ip for stablization
  tests/syslog/syslog_utils.py
  tests/syslog/test_syslog_source_ip.py
Labels: automerge

#11689 [action] [PR:11391] Compress pcap files before copying it from pft to sonic-mgmt
  tests/ptf_runner.py
Labels: automerge

#11688 [action] [PR:11391] Compress pcap files before copying it from pft to sonic-mgmt
  tests/ptf_runner.py
Labels: automerge

#11687 [action] [PR:11459] [dualtor-aa][nic_simulator] Improve the upstream flow
  ansible/dualtor/nic_simulator/nic_simulator.py
Labels: automerge

#11686 [action] [PR:11459] [dualtor-aa][nic_simulator] Improve the upstream flow
  ansible/dualtor/nic_simulator/nic_simulator.py
Labels: automerge

#11707 Skip service warm restart test on Mellanox platform
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202305 branch, Request for 202311 branch

#11705 Disable test_bgp_queue mlnx 2700 T1
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202305 branch, Request for 202311 branch

#11652 Update the static dns test case
  tests/dns/static_dns/test_static_dns.py
Labels: Request for 202311 branch

#11718 [action] [PR:11680] [add-topo] Increase server IPv6 route cache size from default 4096 to 16384
  ansible/roles/vm_set/tasks/main.yml
Labels: automerge

#11717 [action] [PR:11680] [add-topo] Increase server IPv6 route cache size from default 4096 to 16384
  ansible/roles/vm_set/tasks/main.yml
Labels: automerge

#11716 [action] [PR:11680] [add-topo] Increase server IPv6 route cache size from default 4096 to 16384
  ansible/roles/vm_set/tasks/main.yml
Labels: automerge

#11715 [action] [PR:11680] [add-topo] Increase server IPv6 route cache size from default 4096 to 16384
  ansible/roles/vm_set/tasks/main.yml
Labels: automerge

#11708 Modify test_get_transceiver_info to handle get_transceiver_info_firmware_versions API
  tests/common/helpers/platform_api/sfp.py
  tests/platform_tests/api/test_sfp.py
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#11722 fix keyerror of PR #10382
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#11720 Change "Compute-AI" to "ComputeAI"
  ansible/config_sonic_basedon_testbed.yml
  ansible/templates/minigraph_meta.j2
Labels: Request for 202305 branch, Request for 202311 branch

#11725 [action] [PR:11722] fix keyerror of PR #10382
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: automerge

#11724 [action] [PR:11722] fix keyerror of PR #10382
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: automerge

#11726 [action] [PR:11720] Change "Compute-AI" to "ComputeAI"
  ansible/config_sonic_basedon_testbed.yml
  ansible/templates/minigraph_meta.j2
Labels: automerge

#11719 Revert "tuning timeout for test_turn_on_off_psu_and_check_psustatus (…
  tests/platform_tests/test_platform_info.py
Labels: Request for 202305 branch

#11150 skip collecting pcap file when ptf cmd executes successfully
  tests/ptf_runner.py
Labels: Request for 202205 branch, Approved for 202205 branch, Request for 202305 branch, Approved for 202305 branch

#11663 Add community skip condition due to github issue 11404
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202205 branch, Request for 202305 branch, Request for 202311 branch

#11730 [action] [PR:11719] Revert "tuning timeout for test_turn_on_off_psu_and_check_psustatus (…
  tests/platform_tests/test_platform_info.py
Labels: automerge

#11399 Relax the check on the number of PORT_READY messages
  tests/platform_tests/conftest.py
Labels: Request for 202305 branch, Request for 202311 branch

#11736 [action] [PR:11399] Relax the check on the number of PORT_READY messages
  tests/platform_tests/conftest.py
Labels: automerge
