Repository sonic-net/sonic-mgmt, pull requests merged in 2025-10, with the labels that each got.

#20890 Add a regex option to support multiple DPU reboot reasons
  tests/smartswitch/common/device_utils_dpu.py
  tests/smartswitch/platform_tests/test_reload_dpu.py
Labels: Request for msft-202506 Branch

#20868 [action] [PR:20793] [dualtor] Stablize `test_static_route`
  tests/route/test_static_route.py
Labels: automerge

#20911 [action] [PR:20883] Fix k8s node joining failure for Arista-7060X6-16PE-384C-B-O128S2 SKU
  tests/kubesonic/test_k8s_join_disjoin.py
Labels: automerge

#20929 [action] [PR:20895] Add dry run to DWRR weight change test
  tests/qos/files/qos_params.th5.yaml
  tests/qos/test_qos_sai.py
Labels: automerge

#19700 [dash] Add tests to cover PLNSG, FNIC, trusted VNI, return path ECMP
  tests/common/devices/multi_asic.py
  tests/common/helpers/smartswitch_util.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/dash/configs/privatelink_config.py
  tests/dash/conftest.py
  tests/dash/constants.py
  tests/dash/dash_utils.py
  tests/dash/gnmi_utils.py
  tests/dash/packets.py
  tests/dash/proto_utils.py
  tests/dash/test_dash_eni_counter.py
  tests/dash/test_dash_privatelink.py
  tests/dash/test_fnic.py
  tests/dash/test_plnsg.py
Labels: Request for msft-202506 Branch, Cherry Pick Conflict_msft-202506
