Repository sonic-net/sonic-mgmt, pull requests merged in 2025-01, with the labels that each got.

#16263 [action] [PR:16112] [dhcp_relay][telemetry] Fix incorrect client mac in dhcp_relay related telemetry test
  tests/telemetry/events/dhcp-relay_events.py
  tests/telemetry/events/event_utils.py
Labels: automerge

#16079 T2:snappi_tests: Increase the number of background flows for cisco-8000 to 10.
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
Labels: Request for 202405 branch, IXIA_CHASSIS, Request for 202411 branch

#16176 T2/snappi: Use natsort instead of sort for sorting the asic list in disable_pfcwd and enable_pfcwd functions.
  tests/common/snappi_tests/qos_fixtures.py
Labels: Request for 202405 branch, Request for 202411 branch

#15253 feat: add more sanity checks for T2
  tests/common/plugins/sanity_check/__init__.py
  tests/common/plugins/sanity_check/checks.py
Labels: Request for 202405 branch, Request for 202411 branch

#16211 [action] [PR:16197] feat: add one_dut fixture to only use one dut
  tests/conftest.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
Labels: automerge

#16277 [action] [PR:15253] feat: add more sanity checks for T2
  tests/common/plugins/sanity_check/__init__.py
  tests/common/plugins/sanity_check/checks.py
Labels: automerge

#16276 [action] [PR:16176] T2/snappi: Use natsort instead of sort for sorting the asic list in disable_pfcwd and enable_pfcwd functions.
  tests/common/snappi_tests/qos_fixtures.py
Labels: automerge

#16283 [action] [PR:15979] test_console_baud_rate.py skip if no console port info on dut
  tests/dut_console/test_console_baud_rate.py
Labels: automerge

#16286 [action] [PR:15949] fix: fix port does not exist error test_bgp_queue
  tests/bgp/test_bgp_queue.py
  tests/common/devices/sonic_asic.py
Labels: automerge

#16284 [action] [PR:15951] Adjust t2 timing in tests/platform_tests/test_reload_config.py
  tests/platform_tests/test_reload_config.py
Labels: automerge

#16281 [action] [PR:15849] ECN IXIA test for verifying equal marking due to traffic causing congestion
  tests/snappi_tests/multidut/ecn/files/multidut_helper.py
  tests/snappi_tests/multidut/ecn/test_multidut_ecn_marking_with_snappi.py
Labels: automerge

#16285 [action] [PR:15987] test_multidut_pfc_pause_lossy_with_snappi.py fix typo
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
Labels: automerge

#16282 [action] [PR:15919] snappi_tests/multidut: Fixturize a few cases in pfc folder.
  tests/snappi_tests/multidut/pfc/test_lossless_response_to_external_pause_storms.py
  tests/snappi_tests/multidut/pfc/test_lossless_response_to_throttling_pause_storms.py
  tests/snappi_tests/multidut/pfc/test_m2o_fluctuating_lossless.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossless_lossy.py
  tests/snappi_tests/multidut/pfc/test_m2o_oversubscribe_lossy.py
Labels: automerge

#16280 [action] [PR:15501] change swapsyncd to module level.
  tests/qos/qos_sai_base.py
Labels: automerge

#16274 [action] [PR:16019] [snmp]Skipping enable_queue_counterpoll_type fixture for Nokia 7215 armhf platforms
  tests/snmp/conftest.py
Labels: automerge

#16295 [action] [PR:15969] Change the verify_in_flight_buffer_pkts to use ingress duthost's buffer size
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/multidut/pfc/files/multidut_helper.py
  tests/snappi_tests/pfc/files/helper.py
Labels: automerge

#16299 [action] [PR:15126] Use WRED red for DNX
  tests/common/snappi_tests/common_helpers.py
Labels: automerge

#16291 [action] [PR:16176] T2/snappi: Use natsort instead of sort for sorting the asic list in disable_pfcwd and enable_pfcwd functions.
  tests/common/snappi_tests/qos_fixtures.py
Labels: automerge

#16226 refactor: enhance override config masic test
  tests/override_config_table/test_override_config_table_masic.py
Labels: Request for 202405 branch, Request for 202411 branch

#15466 Updating techsupport commands to include optimized bgp neighbor commands
  tests/show_techsupport/tech_support_cmds.py
Labels: Request for 202411 branch

#16031 [platform_tests/test_reload_config]: Respect overridden timeout
  tests/common/reboot.py
  tests/platform_tests/test_reload_config.py
Labels: chassis, Request for 202405 branch, Request for 202411 branch

#16206 fix: bump memory limit for Cisco 8000 supervisor
  tests/platform_tests/test_cpu_memory_usage.py
Labels: Request for 202405 branch, Request for 202411 branch

#16278 chore: support parallel for more tests
  tests/test_parallel_modes/cisco_t2_8800.json
Labels: Request for 202405 branch, Request for 202411 branch

#16308 [action] [PR:15944] [T2 IXIA] Update show queue counters api to use -n
  tests/common/snappi_tests/common_helpers.py
Labels: automerge

#16298 [action] [PR:16162] fix flaky issue in test_set_fans_speed
  tests/platform_tests/api/test_chassis_fans.py
Labels: automerge

#16296 [action] [PR:14856] [Snappi]: New base config function to accomodate mixed-speed ingress and egress tests.
  tests/common/snappi_tests/snappi_fixtures.py
Labels: automerge

#16294 [action] [PR:15906] Minor changes for snappi_tests for T2-ixia, change udp port calculations.
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_basic_helper.py
Labels: automerge

#15982 Skipping test_voq_queue_counter[multi_dut_shortlink_to_longlink]. Issue #21098
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: chassis, Request for 202405 branch

#16316 [action] [PR:16278] chore: support parallel for more tests
  tests/test_parallel_modes/cisco_t2_8800.json
Labels: automerge

#15778 Fix a couple issues in `change_lag_lacp_timer`
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: chassis, Request for 202405 branch, Request for 202411 branch

#15962 [default-route-bgp-flap]: Fix for 9052 - test failure
  tests/route/test_default_route.py
Labels: Request for 202405 branch, Request for 202411 branch

#16319 [action] [PR:15972] Update tests to handle PSUs with multiple PDUs
  tests/common/helpers/psu_helpers.py
  tests/platform_tests/test_platform_info.py
  tests/snmp/test_snmp_phy_entity.py
Labels: automerge

#16311 [action] [PR:16226] refactor: enhance override config masic test
  tests/override_config_table/test_override_config_table_masic.py
Labels: automerge

#16297 [action] [PR:15352] update skip conditions for watermark cases
  tests/qos/test_qos_sai.py
Labels: automerge

#16301 [loganalyzer] Ignore pmon#stormond iSmart binary format ERR log
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202405 branch, Request for 202411 branch

#16292 [action] [PR:16079] T2:snappi_tests: Increase the number of background flows for cisco-8000 to 10.
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
Labels: automerge

#16310 [action] [PR:16226] refactor: enhance override config masic test
  tests/override_config_table/test_override_config_table_masic.py
Labels: automerge

#16060 [action] [PR:16057] chore: skip PSU check for chassis LC
  tests/platform_tests/test_platform_info.py
Labels: automerge

#16333 [action] [PR:15934] Cisco specific: Check debug shell status before ecn marking test
  tests/snappi_tests/files/helper.py
  tests/snappi_tests/multidut/ecn/test_multidut_ecn_marking_with_snappi.py
Labels: automerge

#16329 [action] [PR:15964] T2/Snappi: Move global definitions of test and background flow rates to be local to the function they are used.
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_multi_node_helper.py
Labels: automerge

#16326 [action] [PR:16197] feat: add one_dut fixture to only use one dut
  tests/conftest.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
Labels: automerge

#16332 [action] [PR:16057] chore: skip PSU check for chassis LC
  tests/platform_tests/test_platform_info.py
Labels: automerge

#16129 [action] [PR:16119] Lower log level for message `DUT type file doesn't exist`
  tests/ptf_runner.py
Labels: automerge

#16309 Fix fabric_cli_and_db so it only tests on connected links.
  tests/voq/test_fabric_cli_and_db.py
Labels: Request for 202405 branch, Request for 202411 branch

#16271 Make test_idf_isolated_withdraw_all more robust
  tests/bgp/test_seq_idf_isolation.py
Labels: Request for 202405 branch, Request for 202411 branch

#16327 [action] [PR:16079] T2:snappi_tests: Increase the number of background flows for cisco-8000 to 10.
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
Labels: automerge

#16339 [action] [PR:15909] ECN probabilistic marking with PFC induced congestion
  tests/common/snappi_tests/common_helpers.py
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/multidut/ecn/files/multidut_helper.py
  tests/snappi_tests/multidut/ecn/test_multidut_ecn_marking_with_pfc_quanta_variance_with_snappi.py
Labels: automerge

#16342 [action] [PR:16301] [loganalyzer] Ignore pmon#stormond iSmart binary format ERR log
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#16076 support Ixia topology in sanity check
  tests/common/plugins/sanity_check/checks.py
  tests/conftest.py
Labels: Request for 202405 branch, Request for 202411 branch

#16322 Support 2 vlan config in topology for test_acl
  tests/acl/test_acl.py
Labels: Request for 202311 branch, Request for 202405 branch, Request for 202411 branch

#16347 Ignore NTP leap second file expired syslog
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202405 branch, Request for 202411 branch

#16350 [action] [PR:16076] support Ixia topology in sanity check
  tests/common/plugins/sanity_check/checks.py
  tests/conftest.py
Labels: automerge

#16349 [action] [PR:16076] support Ixia topology in sanity check
  tests/common/plugins/sanity_check/checks.py
  tests/conftest.py
Labels: automerge

#16343 [action] [PR:16301] [loganalyzer] Ignore pmon#stormond iSmart binary format ERR log
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#16337 T2: Snappi Based Route Convergence Test Changes
  tests/snappi_tests/multidut/bgp/files/bgp_outbound_helper.py
  tests/snappi_tests/multidut/bgp/test_bgp_outbound_uplink_po_member_flap.py
  tests/snappi_tests/variables.py
Labels: Request for 202405 branch, Request for 202411 branch

#16369 [action] [PR:16164] [dualtor] Improve `mux_simulator`
  ansible/roles/vm_set/files/mux_simulator.py
  ansible/roles/vm_set/tasks/control_mux_simulator.yml
  ansible/roles/vm_set/templates/mux-simulator.service.j2
Labels: automerge

#15773 [T2] Updated JR2 tuning values for T2 systems
  tests/qos/files/qos_params.jr2.yaml
Labels: Request for 202405 branch, Request for 202411 branch

#16368 Check AN enabled port is in connection graph
  ansible/templates/minigraph_link_meta.j2
Labels: Request for 202405 branch, Request for 202411 branch

#16381 [action] [PR:16368] Check AN enabled port is in connection graph
  ansible/templates/minigraph_link_meta.j2
Labels: automerge

#16366 refactor: optimize reliable tsa test
  tests/bgp/test_reliable_tsa.py
Labels: Request for 202405 branch, Request for 202411 branch

#16357 [sanity_check][bgp] Enhance sanity check recover for bgp default route missing
  tests/common/plugins/sanity_check/__init__.py
  tests/common/plugins/sanity_check/recover.py
Labels: Request for 202311 branch, Request for 202405 branch, Request for 202411 branch

#16371 Temporarily skipping a test in test_arp_dualtor.py that is failing consistently
  tests/arp/test_arp_dualtor.py
Labels: Request for 202411 branch, Approved for 202411 branch

#16169 Correcting client arguments to `dynamically_compensate_leakout` in `PGSharedWatermarkTest`
  tests/saitests/py3/sai_qos_tests.py
Labels: chassis, Request for 202405 branch, Request for 202411 branch

#16166 Fix test ipfwd/test_nhop_group.py for Arista 7050CX3 SKU
  tests/ipfwd/test_nhop_group.py
Labels: Request for 202405 branch, Request for 202411 branch, Approved for 202411 branch

#16396 Temporarily skipping a failing test in test_arp_dualtor.py
  tests/arp/test_arp_dualtor.py
Labels: Request for 202411 branch

#16397 [action] [PR:16396] Temporarily skipping a failing test in test_arp_dualtor.py
  tests/arp/test_arp_dualtor.py
Labels: automerge

#15199 [T0/T1/T2]: New ECMP Hashing test upon member flap trigger
  ansible/roles/test/files/ptftests/fib_test.py
  tests/common/fixtures/fib_utils.py
  tests/fib/test_fib.py
Labels: chassis, Chassis Test Gap, Request for 202305 branch, Request for 202311 branch, Request for 202405 branch, Request for 202411 branch

#16385 Deprecate sonic-common agent pool.
  .azure-pipelines/pytest-collect-only.yml
  azure-pipelines.yml
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch, Request for 202411 branch

#16392 update pkts_num_trig_pfc of wm_pg_shared_lossless in yaml file
  tests/qos/files/qos_params.gb.yaml
Labels: Request for 202405 branch, Request for 202411 branch

#16402 Update the err msg ignore list
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202405 branch, Request for 202411 branch

#16426 Temporarily skipping a failing test in test_arp_extended.py
  tests/arp/test_arp_extended.py
Labels: Request for 202411 branch, Approved for 202411 branch

#16427 [action] [PR:16426] Temporarily skipping a failing test in test_arp_extended.py
  tests/arp/test_arp_extended.py
Labels: automerge

#16422 [action] [PR:16392] update pkts_num_trig_pfc of wm_pg_shared_lossless in yaml file
  tests/qos/files/qos_params.gb.yaml
Labels: automerge

#16360 test_config_fec_oper_mode: Set the fec_mode to align with the current configuration of the interface.
  tests/platform_tests/test_intf_fec.py
Labels: Request for 202405 branch, Request for 202411 branch

#16394 snappi: T2: Convert all udp port numbers to serial sequence.
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/multidut/ecn/files/multidut_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_runtime_traffic_helper.py
Labels: Request for 202405 branch, IXIA_CHASSIS, Request for 202411 branch

#16434 [action] [PR:16394] snappi: T2: Convert all udp port numbers to serial sequence.
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/multidut/ecn/files/multidut_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_runtime_traffic_helper.py
Labels: automerge

#16430 [action] [PR:16366] refactor: optimize reliable tsa test
  tests/bgp/test_reliable_tsa.py
Labels: automerge

#16423 [action] [PR:16392] update pkts_num_trig_pfc of wm_pg_shared_lossless in yaml file
  tests/qos/files/qos_params.gb.yaml
Labels: automerge

#16443 [loganalyzer] Ignore pmon iSmart binary format ERR log
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202405 branch, Request for 202411 branch

#16425 [action] [PR:16402] Update the err msg ignore list
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#16455 [action] [PR:16443] [loganalyzer] Ignore pmon iSmart binary format ERR log
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#16458 [action] [PR:16216] [dhcp_relay][telemetry] Update events test for dhcp6relay bind issue
  tests/telemetry/events/dhcp-relay_events.py
Labels: automerge

#16459 [action] [PR:16216] [dhcp_relay][telemetry] Update events test for dhcp6relay bind issue
  tests/telemetry/events/dhcp-relay_events.py
Labels: automerge

#16159 Add pfc-timer-set to 500mS for pfcwd tests.
  tests/pfcwd/cisco/default_pfc_time.py
  tests/pfcwd/cisco/set_pfc_time.py
  tests/pfcwd/conftest.py
  tests/pfcwd/test_pfcwd_all_port_storm.py
  tests/pfcwd/test_pfcwd_function.py
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: chassis, Request for 202405 branch, Request for 202411 branch

#16428 refactor: optimize qos sai test
  tests/qos/qos_sai_base.py
Labels: Request for 202405 branch, Request for 202411 branch

#16469 [action] [PR:16159] Add pfc-timer-set to 500mS for pfcwd tests.
  tests/pfcwd/cisco/default_pfc_time.py
  tests/pfcwd/cisco/set_pfc_time.py
  tests/pfcwd/conftest.py
  tests/pfcwd/test_pfcwd_all_port_storm.py
  tests/pfcwd/test_pfcwd_function.py
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#16460 [gcu][dhcp_relay] Fix dhcp_relay container is not running in gcu test
  tests/common/dhcp_relay_utils.py
  tests/generic_config_updater/test_dhcp_relay.py
Labels: Request for 202405 branch, Request for 202411 branch

#16461 SNMP link-local test: wait until snmp agent fully start
  tests/snmp/test_snmp_link_local.py
Labels: Request for 202405 branch, Request for 202411 branch

#16315 qos-sai:dwrr:cisco-8000:Handle non-multiasic part as well for the dshell-script change.
  tests/qos/qos_sai_base.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202411 branch

#16199 Porting 15718 to 202405: Adding a fixture to set scheduler to slower speeds and revert it back.
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: chassis

#16473 [action] [PR:15108] Update the way of shutdown bgp service in qos sai test
  tests/qos/qos_sai_base.py
Labels: automerge

#16412 add fanout support for 202405 and 202411
  ansible/roles/fanout/tasks/fanout_sonic.yml
  ansible/roles/fanout/tasks/sonic/fanout_sonic_202405.yml
  ansible/roles/fanout/templates/sonic_deploy_202405.j2
Labels: Request for 202411 branch

#16482 [action] [PR:16461] SNMP link-local test: wait until snmp agent fully start
  tests/snmp/test_snmp_link_local.py
Labels: automerge

#16479 [action] [PR:15718] Adding a fixture to set scheduler to slower speeds and revert it back.
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#16486 [action] [PR:16412] add fanout support for 202405 and 202411
  ansible/roles/fanout/tasks/fanout_sonic.yml
  ansible/roles/fanout/tasks/sonic/fanout_sonic_202405.yml
  ansible/roles/fanout/templates/sonic_deploy_202405.j2
Labels: automerge

#16386 [action] [PR:16357] [sanity_check][bgp] Enhance sanity check recover for bgp default route missing
  tests/common/plugins/sanity_check/__init__.py
  tests/common/plugins/sanity_check/recover.py
Labels: automerge

#16488 [action] [PR:16428] refactor: optimize qos sai test
  tests/qos/qos_sai_base.py
Labels: automerge

#16497 [action] [PR:16135] [test_genric_hash.py]: cisco platform checks fix
  tests/hash/generic_hash_helper.py
Labels: automerge

#16424 Do the skip instead of failing test for FEC-BER unsupported interfaces
  tests/platform_tests/test_intf_fec.py
Labels: Request for 202411 branch

#13814 Enhance the fwutil test
  ansible/ansible.cfg
  tests/platform_tests/fwutil/conftest.py
  tests/platform_tests/fwutil/fwutil_common.py
  tests/platform_tests/fwutil/test_fwutil.py
Labels: Request for 202405 branch, Request for 202411 branch

#16499 [action] [PR:16424] Do the skip instead of failing test for FEC-BER unsupported interfaces
  tests/platform_tests/test_intf_fec.py
Labels: automerge

#16409 Stabilize `test_snmp_fdb_send_tagged`
  tests/snmp/test_snmp_fdb.py
Labels: Request for 202405 branch, Request for 202411 branch

#13864 [Snappi] Infra changes for new PFC-ECN testcases.
  tests/common/snappi_tests/snappi_test_params.py
  tests/common/snappi_tests/traffic_generation.py
Labels: IXIA_CHASSIS, Request for 202411 branch, Request for msft-202405 Branch

#16026 [#16015 Fix]: Cleaning up unused code from snappi_fixtures
  tests/common/snappi_tests/snappi_fixtures.py
Labels: chassis, IXIA_CHASSIS, Request for 202411 branch, Request for msft-202405 Branch

#16433 [action] [PR:16360] test_config_fec_oper_mode: Set the fec_mode to align with the current configuration of the interface.
  tests/platform_tests/test_intf_fec.py
Labels: automerge

#16399 [action] [PR:16322] Support 2 vlan config in topology for test_acl
  tests/acl/test_acl.py
Labels: automerge

#16506 [action] [PR:16026] [#16015 Fix]: Cleaning up unused code from snappi_fixtures
  tests/common/snappi_tests/snappi_fixtures.py
Labels: automerge

#16435 [action] [PR:16394] snappi: T2: Convert all udp port numbers to serial sequence.
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/multidut/ecn/files/multidut_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfcwd/files/pfcwd_multidut_runtime_traffic_helper.py
Labels: automerge

#16470 [TH5] add minimized t0-isolated-d16u16 and t1-isolated-d28u1 topology
  ansible/generate_topo.py
  ansible/roles/eos/templates/t0-isolated-d16u16s1-leaf.j2
  ansible/roles/eos/templates/t0-isolated-d16u16s2-leaf.j2
  ansible/roles/eos/templates/t1-isolated-d28u1-spine.j2
  ansible/roles/eos/templates/t1-isolated-d28u1-tor.j2
  ansible/vars/topo_t0-isolated-d128u128s2.yml
  ansible/vars/topo_t0-isolated-d16u16s1.yml
  ansible/vars/topo_t0-isolated-d16u16s2.yml
  ansible/vars/topo_t1-isolated-d224u8.yml
  ansible/vars/topo_t1-isolated-d28u1.yml
  ansible/veos
Labels: Request for 202411 branch, Request for msft-202412 branch

#16510 chore: disable parallel run for ro disk test
  tests/test_parallel_modes/cisco_t2_8800.json
Labels: Request for 202405 branch, Request for 202411 branch

#16514 [action] [PR:16510] chore: disable parallel run for ro disk test
  tests/test_parallel_modes/cisco_t2_8800.json
Labels: automerge

#16290 [test_snmp_cpu]Use timeout configuration in all SNMP request, increase SNMP request timeout to 20
  ansible/library/snmp_facts.py
Labels: Request for 202405 branch, Request for 202411 branch

#16077 [Chassis] Reduce wait/timeout time for chassis
  tests/common/config_reload.py
  tests/common/plugins/sanity_check/checks.py
  tests/common/reboot.py
  tests/tacacs/test_ro_disk.py
Labels: Request for 202405 branch, Request for 202411 branch

#16519 [action] [PR:16290] [test_snmp_cpu]Use timeout configuration in all SNMP request, increase SNMP request timeout to 20
  ansible/library/snmp_facts.py
Labels: automerge

#16515 [action] [PR:16510] chore: disable parallel run for ro disk test
  tests/test_parallel_modes/cisco_t2_8800.json
Labels: automerge

#16496 [action] [PR:16135] [test_genric_hash.py]: cisco platform checks fix
  tests/hash/generic_hash_helper.py
Labels: automerge

#14122 [Snappi]: PFC - Mixed Speed testcases
  tests/common/snappi_tests/common_helpers.py
  tests/snappi_tests/pfc/files/mixed_speed_multidut_helper.py
  tests/snappi_tests/pfc/test_pfc_mixed_speed.py
  tests/snappi_tests/pfcwd/test_pfcwd_mixed_speed.py
  tests/snappi_tests/variables.py
Labels: IXIA_CHASSIS, Request for 202411 branch, Request for msft-202405 Branch

#13865 [Snappi] New testcases for PFC-ECN.
  tests/snappi_tests/pfc/files/pfc_congestion_helper.py
  tests/snappi_tests/pfc/test_pfc_no_congestion_throughput.py
  tests/snappi_tests/pfc/test_pfc_port_congestion.py
  tests/snappi_tests/pfcwd/files/pfcwd_actions_helper.py
  tests/snappi_tests/pfcwd/test_pfcwd_actions.py
Labels: IXIA_CHASSIS, Request for 202411 branch, Request for msft-202405 Branch

#16520 [action] [PR:16077] [Chassis] Reduce wait/timeout time for chassis
  tests/common/config_reload.py
  tests/common/plugins/sanity_check/checks.py
  tests/common/reboot.py
  tests/tacacs/test_ro_disk.py
Labels: automerge

#16505 [action] [PR:13864] [Snappi] Infra changes for new PFC-ECN testcases.
  tests/common/snappi_tests/snappi_test_params.py
  tests/common/snappi_tests/traffic_generation.py
Labels: automerge

#16500 [action] [PR:16460] [gcu][dhcp_relay] Fix dhcp_relay container is not running in gcu test
  tests/common/dhcp_relay_utils.py
  tests/generic_config_updater/test_dhcp_relay.py
Labels: automerge

#16498 [action] [PR:16360] test_config_fec_oper_mode: Set the fec_mode to align with the current configuration of the interface.
  tests/platform_tests/test_intf_fec.py
Labels: automerge

#16468 [action] [PR:16159] Add pfc-timer-set to 500mS for pfcwd tests.
  tests/pfcwd/cisco/default_pfc_time.py
  tests/pfcwd/cisco/set_pfc_time.py
  tests/pfcwd/conftest.py
  tests/pfcwd/test_pfcwd_all_port_storm.py
  tests/pfcwd/test_pfcwd_function.py
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#16518 [action] [PR:16290] [test_snmp_cpu]Use timeout configuration in all SNMP request, increase SNMP request timeout to 20
  ansible/library/snmp_facts.py
Labels: automerge

#16521 [action] [PR:16077] [Chassis] Reduce wait/timeout time for chassis
  tests/common/config_reload.py
  tests/common/plugins/sanity_check/checks.py
  tests/common/reboot.py
  tests/tacacs/test_ro_disk.py
Labels: automerge

#16535 Fix ASIC check in test_pfcwd_function
  tests/pfcwd/test_pfcwd_function.py
Labels: Request for 202405 branch, Request for 202411 branch

#16539 [action] [PR:16535] Fix ASIC check in test_pfcwd_function
  tests/pfcwd/test_pfcwd_function.py
Labels: automerge

#15913 Initial version of defining the interfaces to accept metrics
  test_reporting/telemetry/examples.py
  test_reporting/telemetry/metrics.py
  test_reporting/telemetry/reporter_factory.py
Labels: Request for msft-202412 branch

#16272 [Snappi] Replacing dut.shell with dut.command for clearing counters in snappi clear_counter function
  tests/common/snappi_tests/common_helpers.py
Labels: IXIA_CHASSIS, Request for 202411 branch

#16508 [infra][mux simulaotr] Improve mux simulator toggle performance
  ansible/roles/vm_set/files/mux_simulator.py
Labels: Request for 202411 branch

#16525 [action] [PR:13865] [Snappi] New testcases for PFC-ECN.
  tests/snappi_tests/pfc/files/pfc_congestion_helper.py
  tests/snappi_tests/pfc/test_pfc_no_congestion_throughput.py
  tests/snappi_tests/pfc/test_pfc_port_congestion.py
  tests/snappi_tests/pfcwd/files/pfcwd_actions_helper.py
  tests/snappi_tests/pfcwd/test_pfcwd_actions.py
Labels: automerge

#16502 [action] [PR:16409] Stabilize `test_snmp_fdb_send_tagged`
  tests/snmp/test_snmp_fdb.py
Labels: automerge

#16543 [action] [PR:16272] [Snappi] Replacing dut.shell with dut.command for clearing counters in snappi clear_counter function
  tests/common/snappi_tests/common_helpers.py
Labels: automerge

#16540 [action] [PR:16535] Fix ASIC check in test_pfcwd_function
  tests/pfcwd/test_pfcwd_function.py
Labels: automerge

#16538 [action] [PR:14122] [Snappi]: PFC - Mixed Speed testcases
  tests/common/snappi_tests/common_helpers.py
  tests/snappi_tests/pfc/files/mixed_speed_multidut_helper.py
  tests/snappi_tests/pfc/test_pfc_mixed_speed.py
  tests/snappi_tests/pfcwd/test_pfcwd_mixed_speed.py
  tests/snappi_tests/variables.py
Labels: automerge

#16549 [dualtor] Fix `testFdbMacLearning`
  tests/fdb/test_fdb_mac_learning.py
Labels: Request for 202405 branch, Request for 202411 branch

#16555 [action] [PR:16549] [dualtor] Fix `testFdbMacLearning`
  tests/fdb/test_fdb_mac_learning.py
Labels: automerge

#16536 Support smartswitch in get_testbed_type and announce_routes
  ansible/library/announce_routes.py
  tests/common/testbed.py
Labels: Request for 202405 branch, Request for 202411 branch

#16558 [action] [PR:16409] Stabilize `test_snmp_fdb_send_tagged`
  tests/snmp/test_snmp_fdb.py
Labels: automerge

#16557 [action] [PR:16508] [infra][mux simulaotr] Improve mux simulator toggle performance
  ansible/roles/vm_set/files/mux_simulator.py
Labels: automerge

#16561 [action] [PR:16536] Support smartswitch in get_testbed_type and announce_routes
  ansible/library/announce_routes.py
  tests/common/testbed.py
Labels: automerge

#16547 Temporarily skip lpmode test for some transceivers with known issue
  tests/platform_tests/api/test_sfp.py
Labels: Request for 202411 branch, Approved for 202411 branch, Request for msft-202405 Branch

#16375 flap interface after sfp reset
  tests/common/devices/multi_asic.py
  tests/common/platform/interface_utils.py
  tests/common/platform/transceiver_utils.py
  tests/common/port_toggle.py
  tests/platform_tests/api/test_sfp.py
  tests/platform_tests/sfp/test_sfputil.py
Labels: chassis, Request for 202405 branch, Request for 202411 branch

#16556 [action] [PR:16494] [dhcp_relay] Add test case to verify dhcp6relay LLA waiting logic
  tests/dhcp_relay/test_dhcpv6_relay.py
Labels: automerge

#16570 [action] [PR:16375] flap interface after sfp reset
  tests/common/devices/multi_asic.py
  tests/common/platform/interface_utils.py
  tests/common/platform/transceiver_utils.py
  tests/common/port_toggle.py
  tests/platform_tests/api/test_sfp.py
  tests/platform_tests/sfp/test_sfputil.py
Labels: automerge

#16507 [override] Remove table test which has no YANG model
  tests/override_config_table/test_override_config_table.py
  tests/override_config_table/test_override_config_table_masic.py
Labels: Request for 202411 branch

#15748 [testbed] announce routes with routes generation switch, aggregate routes and variable ipv6 address pattern
  ansible/library/announce_routes.py
  ansible/roles/vm_set/tasks/announce_routes.yml
Labels: Request for msft-202412 branch

#16569 [action] [PR:16547] Temporarily skip lpmode test for some transceivers with known issue
  tests/platform_tests/api/test_sfp.py
Labels: automerge

#16581 Fix double reboot bug introduced in #16348
  tests/common/reboot.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#15643 [testbed-cli] Code change on add-topo and deploy-minigraph for deploying testbed with peers on multiple servers
  ansible/config_sonic_basedon_testbed.yml
  ansible/fanout_connect.yml
  ansible/library/announce_routes.py
  ansible/library/test_facts.py
  ansible/library/testbed_vm_info.py
  ansible/module_utils/multi_servers_utils.py
  ansible/plugins/filter/filters.py
  ansible/roles/eos/tasks/main.yml
  ansible/roles/fanout/templates/arista_7260_connect.j2
  ansible/roles/vm_set/library/vm_topology.py
  ansible/roles/vm_set/tasks/add_topo.yml
  ansible/roles/vm_set/tasks/announce_routes.yml
  ansible/roles/vm_set/tasks/create_dut_port.yml
  ansible/roles/vm_set/tasks/get_dut_port.yml
  ansible/roles/vm_set/tasks/main.yml
  ansible/roles/vm_set/tasks/remove_topo.yml
  ansible/testbed-cli.sh
  ansible/testbed.yaml
  ansible/testbed_add_vm_topology.yml
Labels: Request for msft-202412 branch
