Repository sonic-net/sonic-mgmt, pull requests merged in 2025-02, with the labels that each got.

#16756 [action] [PR:16742] [chassis] Reduce timeout for packet chassis
  tests/cacl/test_cacl_function.py
  tests/common/helpers/snmp_helpers.py
Labels: automerge

#16757 fix: pfc timer accuracy timestamp regex
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: Request for 202411 branch, Approved for 202411 branch, Request for msft-202405 Branch, Approved for msft-202405 Branch

#16763 [action] [PR:16757] fix: pfc timer accuracy timestamp regex
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#15812 [action] [PR:15811] Update test_dhcp_relay_stress Testcase: Add XFail Conditions for dualtor
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#16747 [action] [PR:16737] [Chassis] Add extra wait after port toggle so that the routes got programmed into hardware
  tests/acl/test_acl.py
Labels: automerge

#16642 Replacing hardcoded values for GCU suites with dynamic calculated
  tests/generic_config_updater/test_eth_interface.py
  tests/generic_config_updater/test_portchannel_interface.py
Labels: Request for 202405 branch

#16513 [Qos]Loganalyser ignore_regex update for all nodes in test_qos
  tests/qos/test_qos_sai.py
Labels: Request for 202405 branch

#16781 refactor: optimize traffic shift sup test
  tests/bgp/test_traffic_shift_sup.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#16782 [action] [PR:16081] Enable BMP feature switch in Nightly test
  ansible/library/generate_golden_config_db.py
Labels: automerge

#16755 Skip the LC reboot-cause check since it's broken on Arista
  tests/bgp/test_startup_tsa_tsb_service.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#16795 Add support for configurable container registry for cEOS net base image
  ansible/roles/vm_set/tasks/add_ceos_list.yml
Labels: Request for 202411 branch

#16790 chore: bump timeout limit in reliable tsa test
  tests/bgp/test_reliable_tsa.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#16442 [ip/test_mgmt_ipv6_only]: Refactor to properly cleanup on failure
  tests/common/fixtures/duthost_utils.py
  tests/common/helpers/ntp_helper.py
  tests/common/helpers/tacacs/tacacs_helper.py
  tests/common/helpers/telemetry_helper.py
  tests/conftest.py
  tests/ip/test_mgmt_ipv6_only.py
  tests/ntp/test_ntp.py
  tests/tacacs/conftest.py
  tests/telemetry/conftest.py
Labels: Test gap, Request for 202411 branch, Approved for 202411 branch, Request for msft-202405 Branch

#16626 chore: fix console password
  tests/common/helpers/dut_utils.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Cherry Pick Conflict_msft-202405

#16788 add topo_t0-d18u8s4
  ansible/roles/eos/templates/t0-d18u8s4-leaf.j2
  ansible/vars/topo_t0-d18u8s4.yml
  ansible/veos
Labels: Request for 202411 branch

#16804 [action] [PR:16795] Add support for configurable container registry for cEOS net base image
  ansible/roles/vm_set/tasks/add_ceos_list.yml
Labels: automerge

#16754 T2-Snappi-Route-Conv: Update process crash Testcase
  tests/snappi_tests/multidut/bgp/files/bgp_outbound_helper.py
  tests/snappi_tests/variables.py
Labels: Request for 202405 branch, Request for 202411 branch

#16816 [GCU] Update the testcase to avoid duplicate ip range
  tests/generic_config_updater/test_bgp_speaker.py
Labels: Request for 202405 branch, Request for 202411 branch

#16621 Fix test_crm.py::test_crm_neighbor neighbor resource issues to update dynamically
  tests/crm/test_crm.py
Labels: Request for 202405 branch, Request for 202411 branch

#16550 T2: Change XOFF threshold for backplane links on long link line card
  tests/qos/files/qos_params.gb.yaml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#16792 [action] [PR:16781] refactor: optimize traffic shift sup test
  tests/bgp/test_traffic_shift_sup.py
Labels: automerge

#16838 [action] [PR:16795] Add support for configurable container registry for cEOS net base image
  ansible/roles/vm_set/tasks/add_ceos_list.yml
Labels: automerge

#16837 [action] [PR:16795] Add support for configurable container registry for cEOS net base image
  ansible/roles/vm_set/tasks/add_ceos_list.yml
Labels: automerge

#16798 [action] [PR:16684] Skip kubesonic test case for public branch
  tests/kubesonic/test_k8s_join_disjoin.py
Labels: automerge

#16187 Increase Orch CPU utilization timeout before link flap
  tests/platform_tests/link_flap/test_cont_link_flap.py
Labels: chassis, Request for 202411 branch, Request for msft-202405 Branch

#16832 [Snappi] increase tolerance for rounding in m2o tests
  tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#16839 [action] [PR:16795] Add support for configurable container registry for cEOS net base image
  ansible/roles/vm_set/tasks/add_ceos_list.yml
Labels: automerge

#16843 [action] [PR:16621] Fix test_crm.py::test_crm_neighbor neighbor resource issues to update dynamically
  tests/crm/test_crm.py
Labels: automerge

#16810 [action] [PR:16790] chore: bump timeout limit in reliable tsa test
  tests/bgp/test_reliable_tsa.py
Labels: automerge

#16844 [action] [PR:16550] T2: Change XOFF threshold for backplane links on long link line card
  tests/qos/files/qos_params.gb.yaml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: automerge

#16694 [t0 t1 merge] Migrate multidut pfc to t2
  tests/snappi_tests/multidut/pfc/files/multidut_helper.py
  tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#16850 [action] [PR:15749] Add E2E bmp feature test cases
  tests/bmp/__init__.py
  tests/bmp/conftest.py
  tests/bmp/helper.py
  tests/bmp/test_bmp_configdb.py
  tests/bmp/test_bmp_redis_instance.py
  tests/bmp/test_bmp_statedb.py
  tests/bmp/test_docker_restart.py
  tests/common/helpers/bmp_utils.py
Labels: automerge

#16856 [action] [PR:16643] [ecmp] Skip warm-reboot tests on dualtor
  tests/ecmp/test_ecmp_sai_value.py
Labels: automerge

#16048 Macsec profile deploy on peer VM's and DUT for macsec topo pipeline.
  ansible/config_sonic_basedon_testbed.yml
  ansible/library/generate_golden_config_db.py
  ansible/library/get_macsec_profile.py
  ansible/roles/eos/tasks/ceos_config.yml
  ansible/roles/eos/templates/t2-core.j2
  ansible/templates/golden_config_db_t2.j2
Labels: chassis, Request for 202405 branch, Request for 202411 branch

#16682 Added safe reload=True option for config reload performed in syslog_rate_limit to eliminate intermittent failures
  tests/syslog/test_syslog_rate_limit.py
Labels: Request for 202405 branch, Request for 202411 branch

#16841 [action] [PR:16816] [GCU] Update the testcase to avoid duplicate ip range
  tests/generic_config_updater/test_bgp_speaker.py
Labels: automerge

#16812 [action] [PR:16442] [ip/test_mgmt_ipv6_only]: Refactor to properly cleanup on failure
  tests/common/fixtures/duthost_utils.py
  tests/common/helpers/ntp_helper.py
  tests/common/helpers/tacacs/tacacs_helper.py
  tests/common/helpers/telemetry_helper.py
  tests/conftest.py
  tests/ip/test_mgmt_ipv6_only.py
  tests/ntp/test_ntp.py
  tests/tacacs/conftest.py
  tests/telemetry/conftest.py
Labels: automerge

#16800 [action] [PR:16684] Skip kubesonic test case for public branch
  tests/kubesonic/test_k8s_join_disjoin.py
Labels: automerge

#16732 [action] [PR:16722] test_verify_fec_stats_counters: Enhance the condition for robustness and optimize its efficiency.
  tests/platform_tests/test_intf_fec.py
Labels: automerge

#16859 [action] [PR:16854] Add memory consumption check for bgpd/openbmpd during test_default_route_with_bgp_flap stress test
  tests/route/test_default_route.py
Labels: automerge

#16818 [action] [PR:16788] add topo_t0-d18u8s4
  ansible/roles/eos/templates/t0-d18u8s4-leaf.j2
  ansible/vars/topo_t0-d18u8s4.yml
  ansible/veos
Labels: automerge

#16799 [action] [PR:16684] Skip kubesonic test case for public branch
  tests/kubesonic/test_k8s_join_disjoin.py
Labels: automerge

#16860 [Bugfix] Fix import error in `device_utils.py`.
  tests/conftest.py
  tests/platform_tests/api/conftest.py
Labels: Request for 202411 branch

#16862 [action] [PR:16682] Added safe reload=True option for config reload performed in syslog_rate_limit to eliminate intermittent failures
  tests/syslog/test_syslog_rate_limit.py
Labels: automerge

#16861 [action] [PR:16682] Added safe reload=True option for config reload performed in syslog_rate_limit to eliminate intermittent failures
  tests/syslog/test_syslog_rate_limit.py
Labels: automerge

#15878 Clean up the fdb on the sonic fanout in fdb test
  tests/fdb/test_fdb.py
  tests/fdb/test_fdb_flush.py
  tests/fdb/test_fdb_mac_move.py
  tests/fdb/utils.py
Labels: Request for 202405 branch, Request for 202411 branch

#16880 [action] [PR:15878] Clean up the fdb on the sonic fanout in fdb test
  tests/fdb/test_fdb.py
  tests/fdb/test_fdb_flush.py
  tests/fdb/test_fdb_mac_move.py
  tests/fdb/utils.py
Labels: automerge

#16305 [snappi]: Remove references of 'sudo ip netns exec asic' for ECN configuration in common_helpers file
  tests/common/snappi_tests/common_helpers.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#16456 Change the test case name to not include 'teamd_' in it
  tests/pc/test_retry_count.py
Labels: Request for 202405 branch, Request for 202411 branch

#16852 Align acl test case for new t0 topo
  tests/acl/custom_acl_table/test_custom_acl_table.py
  tests/acl/null_route/test_null_route_helper.py
  tests/acl/test_acl.py
Labels: Request for msft-202412 Branch

#16809 [action] [PR:15639] Fix test_syslog_source_ip issue
  tests/syslog/test_syslog_source_ip.py
Labels: automerge

#16890 [action] [PR:16757] fix: pfc timer accuracy timestamp regex
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#16878 [dualtor] Restart linkmgrd before toggle
  tests/common/dualtor/mux_simulator_control.py
Labels: Request for 202405 branch, Request for 202411 branch

#16900 [action] [PR:16795] Add support for configurable container registry for cEOS net base image
  ansible/roles/vm_set/tasks/add_ceos_list.yml
Labels: automerge

#16881 RDMA Tests Enhancements
  tests/common/snappi_tests/qos_fixtures.py
Labels: Request for 202405 branch, Request for 202411 branch

#16887 Skip test_ip_packet.py for t2-min topology
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch, Request for 202411 branch

#16888 Skip NVGRE hash tests for Broadcom SKUs
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202411 branch, Approved for 202411 branch

#16908 [action] [PR:16754] T2-Snappi-Route-Conv: Update process crash Testcase
  tests/snappi_tests/multidut/bgp/files/bgp_outbound_helper.py
  tests/snappi_tests/variables.py
Labels: automerge

#16749 [snappi]: Fix for rx_l1_rate_gbps index error issue in traffic_generation file.
  tests/common/snappi_tests/traffic_generation.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#16656 skipping dynamic_acl TC on Cisco Q200 platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch, Request for 202411 branch

#16932 [action] [PR:16897] [test_pfcwd_timer_accuracy]: fix pfc timer accuracy timestamp regex
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#16910 Retry gnmi_get calls for potential server startup timing issue
  tests/telemetry/telemetry_utils.py
  tests/telemetry/test_telemetry_cert_rotation.py
Labels: Request for 202405 branch, Request for 202411 branch

#16911 [action] [PR:16888] Skip NVGRE hash tests for Broadcom SKUs
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#16807 Adjust TSA-TSB related sonic-mgmt testcases
  tests/bgp/test_reliable_tsa.py
  tests/bgp/test_startup_tsa_tsb_service.py
  tests/common/config_reload.py
Labels: Request for 202405 branch, Request for 202411 branch

#16902 [action] [PR:16669] fix(tests): add backplane port only in srv6 tests
  ansible/roles/test/files/ptftests/remote.py
  tests/common/plugins/ptfadapter/__init__.py
  tests/iface_loopback_action/conftest.py
  tests/srv6/test_srv6_basic_sanity.py
Labels: automerge

#16923 fix test_psud collect_data bug
  tests/platform_tests/daemon/test_psud.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#16924 [action] [PR:16876] feat: add fixture for disabling route check
  tests/conftest.py
  tests/platform_tests/link_flap/test_cont_link_flap.py
Labels: automerge

#15905 [T2][macsec] Fixes to tests for running them with macsec enabled topology
  ansible/roles/test/files/ptftests/fib_test.py
  ansible/roles/test/files/ptftests/macsec.py
  ansible/roles/test/files/ptftests/py3/IP_decap_test.py
  ansible/roles/test/files/ptftests/py3/hash_test.py
  tests/common/macsec/__init__.py
  tests/common/macsec/macsec_config_helper.py
  tests/common/macsec/macsec_helper.py
  tests/common/plugins/conditional_mark/__init__.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/common/plugins/ptfadapter/__init__.py
  tests/everflow/everflow_test_utilities.py
  tests/macsec/test_deployment.py
Labels: Request for 202405 branch, Request for 202411 branch

#16940 [action] [PR:16931] chore: disable parallel run for po cleanup test
  tests/test_parallel_modes/cisco_t2_8800.json
Labels: automerge

#16939 [action] [PR:16923] fix test_psud collect_data bug
  tests/platform_tests/daemon/test_psud.py
Labels: automerge

#16785 [action] [PR:16769] Add filtering to skip two new check items for voq chassis in sanity check
  tests/common/plugins/sanity_check/__init__.py
Labels: automerge

#16637 Fix GCU test_dynamic_acl failure on 2vlan config testbed
  tests/generic_config_updater/test_dynamic_acl.py
Labels: Request for 202405 branch, Request for 202411 branch

#16951 [action] [PR:16637] Fix GCU test_dynamic_acl failure on 2vlan config testbed
  tests/generic_config_updater/test_dynamic_acl.py
Labels: automerge

#16950 [action] [PR:16637] Fix GCU test_dynamic_acl failure on 2vlan config testbed
  tests/generic_config_updater/test_dynamic_acl.py
Labels: automerge

#16907 [action] [PR:16887] Skip test_ip_packet.py for t2-min topology
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#16957 Add new topo files for T2 Snappi route-conv automation tests
  ansible/templates/minigraph_png.j2
  ansible/vars/topo_tgen_t2_2lc_masic_route_conv.yml
  ansible/vars/topo_tgen_t2_2lc_route_conv.yml
Labels: Request for 202405 branch, Request for 202411 branch

#16960 chore: disable route checker for crm nexthop group
  tests/crm/test_crm.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#16416 Skip test_syslog_config_work_after_reboot
  tests/syslog/test_syslog_source_ip.py
Labels: Request for 202405 branch, Request for 202411 branch

#16961 [action] [PR:16807] Adjust TSA-TSB related sonic-mgmt testcases
  tests/bgp/test_reliable_tsa.py
  tests/bgp/test_startup_tsa_tsb_service.py
  tests/common/config_reload.py
Labels: automerge

#16963 [action] [PR:16960] chore: disable route checker for crm nexthop group
  tests/crm/test_crm.py
Labels: automerge

#16967 [action] [PR:16416] Skip test_syslog_config_work_after_reboot
  tests/syslog/test_syslog_source_ip.py
Labels: automerge

#16438 Increase timeout for wait_bgp_sessions for T2 duts
  tests/common/fixtures/duthost_utils.py
Labels: chassis, Request for 202411 branch, Request for msft-202405 Branch, Cherry Pick Conflict_msft-202405

#16975 [action] [PR:16438] Increase timeout for wait_bgp_sessions for T2 duts
  tests/common/fixtures/duthost_utils.py
Labels: automerge

#16974 [action] [PR:16959] [Chassis] Fix flakiness of nhop_group, routes not programmed into har…
  tests/ipfwd/test_nhop_group.py
Labels: automerge

#16906 add assertion error messages
  tests/srv6/test_srv6_static_config.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#16966 [action] [PR:16416] Skip test_syslog_config_work_after_reboot
  tests/syslog/test_syslog_source_ip.py
Labels: automerge

#16981 [action] [PR:16976] [test_pfcwd_timer_accuracy]: fix pfc timer accuracy date cmd input string issue
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#16973 [720DT] Ignore error logs for 720DT
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202411 branch

#16969 Add safe_reload for config_reload in test_syslog_srouce_ip
  tests/syslog/test_syslog_source_ip.py
Labels: Request for 202411 branch

#16687 Fixed logic to delete the interface from BUFFER_QUEUE
  tests/snmp/test_snmp_queue_counters.py
Labels: Request for 202405 branch, Request for 202411 branch

#16990 [action] [PR:16021] [lag_member] add necessary missed imports to test
  tests/pc/test_lag_member.py
Labels: automerge

#16996 [action] [PR:16687] Fixed logic to delete the interface from BUFFER_QUEUE
  tests/snmp/test_snmp_queue_counters.py
Labels: automerge

#16991 [action] [PR:16973] [720DT] Ignore error logs for 720DT
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#16993 [action] [PR:16969] Add safe_reload for config_reload in test_syslog_srouce_ip
  tests/syslog/test_syslog_source_ip.py
Labels: automerge

#16980 Lower Dynamic ACL test rules to fix bug in dualtor devices
  tests/generic_config_updater/templates/create_arp_forward_rule.json
  tests/generic_config_updater/templates/create_dhcp_forward_rule_both.json
  tests/generic_config_updater/templates/create_forward_rules.j2
  tests/generic_config_updater/templates/create_initial_drop_rule.j2
  tests/generic_config_updater/templates/create_ndp_forward_rule.json
  tests/generic_config_updater/templates/create_secondary_drop_rule.j2
  tests/generic_config_updater/templates/create_secondary_forward_rules.j2
  tests/generic_config_updater/templates/create_three_drop_rules.j2
  tests/generic_config_updater/templates/replace_nonexistent_rule.json
  tests/generic_config_updater/templates/replace_rules.j2
  tests/generic_config_updater/test_dynamic_acl.py
Labels: Request for 202311 branch, Request for 202405 branch, Request for 202411 branch

#16999 [action] [PR:16998] Skip test_syslog_source_ip due to testbed unreachable issue
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#16977 Generalize Cisco 8122 test markings for QOS SAI
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202405 branch, Request for 202411 branch

#16725 [QOS - Test PFC Pause] Multi VLAN Support
  tests/qos/qos_helpers.py
  tests/qos/test_pfc_pause.py
Labels: Request for 202405 branch, Request for 202411 branch

#16994 [action] [PR:16969] Add safe_reload for config_reload in test_syslog_srouce_ip
  tests/syslog/test_syslog_source_ip.py
Labels: automerge

#17007 [action] [PR:16651] [dualtor][mux simulator] Fine-tune the mux simulator control post timeout
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#16954 [action] [PR:16881] RDMA Tests Enhancements
  tests/common/snappi_tests/qos_fixtures.py
Labels: automerge

#16955 Running test_gnmi.py on each hwsku instead of selecting one rand hwsku
  tests/gnmi/test_gnmi.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Cherry Pick Conflict_msft-202405

#17016 Skip test_syslog_source_ip to avoid testbed unreachable issue
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202411 branch

#17017 [action] [PR:17016] Skip test_syslog_source_ip to avoid testbed unreachable issue
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#16213 [isolated-topo] make ipv4 and ipv4 BGP sessions optional, make ipv6 only topology deployable
  ansible/library/announce_routes.py
  ansible/library/test_facts.py
  ansible/library/vlan_config.py
  ansible/plugins/filter/filters.py
  ansible/roles/eos/templates/t1-isolated-d254u2s1-spine.j2
  ansible/roles/eos/templates/t1-isolated-d254u2s1-tor.j2
  ansible/roles/eos/templates/t1-isolated-d254u2s2-spine.j2
  ansible/roles/eos/templates/t1-isolated-d254u2s2-tor.j2
  ansible/roles/vm_set/tasks/announce_routes.yml
  ansible/templates/minigraph_dpg.j2
  ansible/vars/topo_t1-isolated-d254u2s1.yml
  ansible/vars/topo_t1-isolated-d254u2s2.yml
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#17002 [M0/Mx] Skip Vxlan hash and Nvgre hash test on M0/Mx testbeds
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202411 branch

#17025 [action] [PR:17002] [M0/Mx] Skip Vxlan hash and Nvgre hash test on M0/Mx testbeds
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#17008 [action] [PR:16651] [dualtor][mux simulator] Fine-tune the mux simulator control post timeout
  tests/common/dualtor/mux_simulator_control.py
Labels: automerge

#17019 [test_l2_configure] Ensure minigraph restore when the test fails
  tests/l2/test_l2_configure.py
Labels: Request for 202411 branch, 202411 issue

#17038 [action] [PR:16402] Update the err msg ignore list
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#16718 Fix bgp/test_bgp_route_neigh_learning.py BGP AS assumption
  tests/bgp/test_bgp_route_neigh_learning.py
Labels: Request for 202411 branch

#17022 [action] [PR:16725] [QOS - Test PFC Pause] Multi VLAN Support
  tests/qos/qos_helpers.py
  tests/qos/test_pfc_pause.py
Labels: automerge

#17049 [action] [PR:16640] LLDP: Add multi-asic support for test_lldp_entry_table_after_syncd_orchagent and some other fixes.
  tests/lldp/test_lldp_syncd.py
Labels: automerge

#17036 Fix test_everflow_dscp_with_policer in py3 env
  ansible/roles/test/files/acstests/everflow_policer_test.py
Labels: Request for 202411 branch

#17063 [action] [PR:17036] Fix test_everflow_dscp_with_policer in py3 env
  ansible/roles/test/files/acstests/everflow_policer_test.py
Labels: automerge

#16796 refactor: optimize drop counters test
  tests/common/helpers/drop_counters/drop_counters.py
  tests/drop_packets/test_drop_counters.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#17061 [action] [PR:16925] Exclude tests that are not intended for the virtual switch
  tests/platform_tests/cli/test_show_platform.py
  tests/platform_tests/test_platform_info.py
Labels: automerge

#17050 Add support for Azure/sonic-buildimage-msft in PR Testing.
  .azure-pipelines/run-test-elastictest-template.yml
Labels: Request for msft-202412 Branch

#17055 Fix failures of test_dynamic_acl on dualtor
  tests/generic_config_updater/test_dynamic_acl.py
Labels: Request for 202405 branch, Request for 202411 branch

#17046 Restore configuration after test_vxlan_bfd_tsa.py
  tests/vxlan/test_vxlan_bfd_tsa.py
Labels: Request for 202405 branch, Request for 202411 branch

#17075 [action] [PR:16509] [Collect Only PR check] Force remove "sonic-mgmt-collect" container before "docker run"
  .azure-pipelines/pytest-collect-only.yml
Labels: automerge

#17076 [action] [PR:16509] [Collect Only PR check] Force remove "sonic-mgmt-collect" container before "docker run"
  .azure-pipelines/pytest-collect-only.yml
Labels: automerge

#17067 [action] [PR:16796] refactor: optimize drop counters test
  tests/common/helpers/drop_counters/drop_counters.py
  tests/drop_packets/test_drop_counters.py
Labels: automerge

#17021 [action] [PR:16725] [QOS - Test PFC Pause] Multi VLAN Support
  tests/qos/qos_helpers.py
  tests/qos/test_pfc_pause.py
Labels: automerge

#16847 cisco-8000: pfcwd: Open up the new pfcwd fixture for t0/t1.
  tests/pfcwd/cisco/set_pfc_time.py
  tests/pfcwd/conftest.py
Labels: Request for 202411 branch, Approved for 202411 branch

#17072 [action] [PR:16639] Extend KVM dualtor memory to 8G to fix memory utilization issue
  ansible/roles/vm_set/templates/sonic.xml.j2
Labels: automerge

#17088 [action] [PR:16847] cisco-8000: pfcwd: Open up the new pfcwd fixture for t0/t1.
  tests/pfcwd/cisco/set_pfc_time.py
  tests/pfcwd/conftest.py
Labels: automerge

#17083 [action] [PR:17046] Restore configuration after test_vxlan_bfd_tsa.py
  tests/vxlan/test_vxlan_bfd_tsa.py
Labels: automerge

#17066 Skip test_everflow_frwd_with_bkg_trf on dualtor platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202411 branch

#17029 Fix the logic of getting pid of process inside container for BGP convergence testing
  tests/snappi_tests/multidut/bgp/files/bgp_outbound_helper.py
Labels: Request for msft-202405 Branch

#16791 [action] [PR:16706] Intuitive custom msg
  tests/common/plugins/sanity_check/__init__.py
  tests/conftest.py
Labels: automerge

#17074 [action] [PR:16509] [Collect Only PR check] Force remove "sonic-mgmt-collect" container before "docker run"
  .azure-pipelines/pytest-collect-only.yml
Labels: automerge

#17097 [action] [PR:17066] Skip test_everflow_frwd_with_bkg_trf on dualtor platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#17073 [action] [PR:16509] [Collect Only PR check] Force remove "sonic-mgmt-collect" container before "docker run"
  .azure-pipelines/pytest-collect-only.yml
Labels: automerge

#17047 [action] [PR:16718] Fix bgp/test_bgp_route_neigh_learning.py BGP AS assumption
  tests/bgp/test_bgp_route_neigh_learning.py
Labels: automerge

#16927 [action] [PR:16239] Ignore nss_tacplus error message reported by NTPD
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#17084 [action] [PR:17046] Restore configuration after test_vxlan_bfd_tsa.py
  tests/vxlan/test_vxlan_bfd_tsa.py
Labels: automerge

#16864 Enable secondary subnet for topo_t0-118 and fix the issue of applying secondary subnet config
  ansible/library/vlan_config.py
  ansible/templates/minigraph_dpg.j2
  ansible/vars/topo_t0-118.yml
  tests/acl/null_route/test_null_route_helper.py
  tests/arp/test_neighbor_mac_noptf.py
  tests/generic_config_updater/test_dynamic_acl.py
Labels: Request for 202405 branch, Request for 202411 branch

#17077 [action] [PR:17051] Update bgp suppress fib script for vrf case
  tests/bgp/test_bgp_suppress_fib.py
Labels: automerge

#17010 Gnmi Test Case Fix
  tests/gnmi/helper.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#16336 [action] [PR:15948] test_cpu_memory_usage.py update memory threshold for 4600 and 2700
  tests/platform_tests/test_cpu_memory_usage.py
Labels: automerge

#15395 [testbed_doc] Design doc for deploying a single testbed with multiple servers
  docs/testbed/README.testbed.DeployWithMultipleServers.md.md
  docs/testbed/img/multi-servers-testbed.png
  docs/testbed/img/ptf-connection-on-multi-servers-testbed.png
  docs/testbed/img/single-server-testbed.png
Labels: Request for msft-202412 Branch

#17098 Mark test_uDT46_config as only applicable to VS platform
  tests/srv6/test_srv6_static_config.py
Labels: Request for msft-202412 Branch

#16866 [t0 t1 test merge] migrate ECN multidiut
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/snappi_tests/ecn/files/helper.py
  tests/snappi_tests/ecn/test_dequeue_ecn_with_snappi.py
  tests/snappi_tests/ecn/test_ecn_marking_with_pfc_quanta_variance_with_snappi.py
  tests/snappi_tests/ecn/test_ecn_marking_with_snappi.py
  tests/snappi_tests/ecn/test_red_accuracy_with_snappi.py
  tests/snappi_tests/multidut/ecn/__init__.py
  tests/snappi_tests/multidut/ecn/files/__init__.py
  tests/snappi_tests/multidut/ecn/files/multidut_helper.py
  tests/snappi_tests/multidut/ecn/test_multidut_dequeue_ecn_with_snappi.py
  tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py
Labels: Request for msft-202405 Branch, Cherry Pick Conflict_msft-202405

#17137 [action] [PR:16368] Check AN enabled port is in connection graph
  ansible/templates/minigraph_link_meta.j2
Labels: automerge

#17112 Skip warm reboot related tests in 202412 testing
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for msft-202412 Branch

#17142 [WoL] Enable WoL test on M0 topo
  tests/wol/test_wol.py
Labels: Request for 202411 branch

#17105 [vxlan]: Enhance vxlan decap test to support non-portchannel testcases
  ansible/roles/test/files/ptftests/py3/vxlan-decap.py
  tests/vxlan/test_vxlan_decap.py
Labels: Request for msft-202412 Branch

#17144 [action] [PR:17142] [WoL] Enable WoL test on M0 topo
  tests/wol/test_wol.py
Labels: automerge

#17080 Stabilize bgp suppress fib test on switch with low power CPU and a lot of BGP neighbors
  tests/bgp/test_bgp_suppress_fib.py
Labels: Request for 202411 branch
