Repository sonic-net/sonic-mgmt, pull requests merged in 2025-08, with the labels that each got.

#19955 [conditional mark] xfail test_generic_hash
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#19979 [action] [PR:19955] [conditional mark] xfail test_generic_hash
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19996 [action] [PR:18254] Validate BGP sessions are up | generic hash nexthop flap test
  tests/hash/test_generic_hash.py
Labels: automerge

#19994 [action] [PR:19762] wait for the change to be applied after async patch requests in test_restapi_vxlan_ecmp
  tests/restapi/test_restapi_vxlan_ecmp.py
Labels: automerge

#19988 [action] [PR:19970] Add support for ft2 bgp neighbor bgp.test_bgp_update_timer
  tests/bgp/test_bgp_update_timer.py
Labels: automerge

#19986 [action] [PR:19839] [Smartswitch] Fix the post_test_switch_check for dpu platform tests
  tests/smartswitch/common/device_utils_dpu.py
Labels: automerge

#19984 [action] [PR:18854] Stabilize the crm test
  tests/crm/conftest.py
Labels: automerge

#19983 [action] [PR:19284] Remove kill exabgp on PTF in remove topo step
  ansible/roles/vm_set/tasks/remove_topo.yml
Labels: automerge

#19977 [action] [PR:19748] cherry pick for the PR#17101
  tests/platform_tests/api/watchdog.yml
Labels: automerge

#19991 [action] [PR:19952] Skip smartswitch tests on non-smartswitch T1s
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19981 Ensure get_db_dump is not called on rebooting DUT
  tests/voq/test_voq_chassis_app_db_consistency.py
Labels: Request for msft-202503 Branch, Request for 202505 branch

#17307 [add_rack]: Add ignore of apsel, host lane and media lane count attributes preset in TRANSCEIVER_INFO for add rack test case
  tests/common/configlet/utils.py
Labels: Request for 202411 branch, Request for 202505 branch

#20034 [action] [PR:17307] [add_rack]: Add ignore of apsel, host lane and media lane count attributes preset in TRANSCEIVER_INFO for add rack test case
  tests/common/configlet/utils.py
Labels: automerge

#19963 Add an expected log error to PSU test
  tests/platform_tests/test_platform_info.py
Labels: Request for msft-202412 Branch

#19821 MIGSMSFT-1146 Use queue occupancy to determine whether oq/voq watchdog is triggered
  tests/qos/test_oq_watchdog.py
  tests/qos/test_voq_watchdog.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for msft-202405 Branch, Request for 202505 branch

#19845 [T2] Add testplan for T2 anchor routes
  docs/testplan/BGP-T2-Anchor-prefix-test-plan.md
Labels: Test Plan

#20042 [action] [PR:20037] Fix bug: In master/202505, multi-asic device's configuration can't be refreshed after deploy-mg
  ansible/library/generate_golden_config_db.py
Labels: automerge

#20041 [action] [PR:19821] MIGSMSFT-1146 Use queue occupancy to determine whether oq/voq watchdog is triggered
  tests/qos/test_oq_watchdog.py
  tests/qos/test_voq_watchdog.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#19985 [action] [PR:19724] Use "get_vms_by_dut_interfaces" function to get VMs for multi-server
  tests/conftest.py
Labels: automerge

#20047 [action] [PR:19816] Add Redis service check after reboot
  tests/common/reboot.py
Labels: automerge

#20049 [Arista] Ignore SRV6 ERR log on Arista platforms
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202505 branch

#20026 [test_nhop_group.py::test_nhop_group_interface_flap] Use conditional sleep based on route scale
  tests/ipfwd/test_nhop_group.py
Labels: Request for msft-202503 Branch, Approved for msft-202503 Branch, Request for 202505 branch

#19938 [action] [PR:18160] added wait_until logic ACL rule creation and verification of log to appear
  tests/show_techsupport/test_techsupport.py
Labels: automerge

#20057 [action] [PR:19963] Add an expected log error to PSU test
  tests/platform_tests/test_platform_info.py
Labels: automerge

#20056 [action] [PR:20026] [test_nhop_group.py::test_nhop_group_interface_flap] Use conditional sleep based on route scale
  tests/ipfwd/test_nhop_group.py
Labels: automerge

#20030 update autoneg setting to support 'off' when deploy-mg
  ansible/templates/minigraph_link_meta.j2
Labels: Request for msft-202412 Branch, Request for 202505 branch

#19903 [action] [PR:19586] Add support of DeviceProperty SonicQosProfile in minigraph.xml
  ansible/group_vars/sonic/variables
  ansible/templates/minigraph_meta.j2
  tests/db_migrator/test_migrate_dns.py
Labels: automerge

#19911 Add xfail for test_vxlan_bfd_tsa.py due to github issue 22615
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#19704 [Dualtor][Qos SAI] Fix qos sai test for dualtor
  tests/qos/qos_sai_base.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202411 branch, Request for 202505 branch

#19830 [Mellanox] Adjust margin to 2% of share buffer size for testQosSaiLossyQueue for spc4 above platform
  tests/qos/files/mellanox/qos_param_generator.py
Labels: Request for msft-202412 Branch, Request for 202505 branch

#19848 Fix the console log fetching, to prevent a race condition
  tests/common/reboot.py
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18005 Added xfail for test restapi based at issue 17797
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202412 Branch, Request for 202505 branch

#20085 [action] [PR:19785] [Mellanox] Fix test_dpu_console issue
  tests/smartswitch/platform_tests/test_platform_dpu.py
Labels: automerge

#20084 [action] [PR:19910] skip test_transceiver_info due to sonic-buildimage issue 22213
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#20082 [action] [PR:19704] [Dualtor][Qos SAI] Fix qos sai test for dualtor
  tests/qos/qos_sai_base.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#20081 [action] [PR:19830] [Mellanox] Adjust margin to 2% of share buffer size for testQosSaiLossyQueue for spc4 above platform
  tests/qos/files/mellanox/qos_param_generator.py
Labels: automerge

#20079 [action] [PR:18005] Added xfail for test restapi based at issue 17797
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#20080 [action] [PR:20003] Remove 7060CX sku from the kubesonic test not support list
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19973 Ensure 'portA' and 'portB' are different in pick_ports
  tests/voq/test_voq_ipfwd.py
Labels: Request for msft-202503 Branch, Approved for msft-202503 Branch, Request for 202505 branch

#20093 [action] [PR:19704] [Dualtor][Qos SAI] Fix qos sai test for dualtor
  tests/qos/qos_sai_base.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#19140 Clean up mgmtvrf test for ntp by reusing existing code
  tests/mvrf/test_mgmtvrf.py
Labels: Request for 202505 branch

#19811 [sonic-mgmt][master]Skip IPv6 everflow cases under test_everflow_testbed.py for Arista-7060CX
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#20108 [action] [PR:19871] [dualtor] Skip toggle failure introduced by `setup_dualtor_mux_ports`
  tests/conftest.py
  tests/ip/test_mgmt_ipv6_only.py
Labels: automerge

#20059 [DHCP relay counter] Add all DHCP packet type for DHCP relay counter tests
  ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py
  tests/dhcp_relay/test_dhcp_relay.py
Labels: Request for 202505 branch

#20114 [action] [PR:19888] Fix test_config_reload by checking for redis-db running status
  tests/platform_tests/test_reload_config.py
Labels: automerge

#20112 [action] [PR:19811] [sonic-mgmt][master]Skip IPv6 everflow cases under test_everflow_testbed.py for Arista-7060CX
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19358 [action] [PR:17633] Fix DWRR scheduler LAG member search
  tests/qos/qos_sai_base.py
Labels: automerge

#20054 Fix advanced-rebootpy datetime EDecimal type issue.
  ansible/roles/test/files/ptftests/py3/advanced-reboot.py
Labels: Request for master, Request for 202311 branch, Request for 202405 branch, Request for 202411 branch, Request for 202505 branch

#20136 [action] [PR:19973] Ensure 'portA' and 'portB' are different in pick_ports
  tests/voq/test_voq_ipfwd.py
Labels: automerge

#20134 [action] [PR:20090] [Snappi] change logs output to logs/ folder
  tests/snappi_tests/pfc/test_pfc_mixed_speed.py
  tests/snappi_tests/pfc/test_pfc_no_congestion_throughput.py
  tests/snappi_tests/pfc/test_pfc_port_congestion.py
  tests/snappi_tests/pfcwd/test_pfcwd_actions.py
  tests/snappi_tests/pfcwd/test_pfcwd_mixed_speed.py
Labels: automerge

#20133 [action] [PR:20054] Fix advanced-rebootpy datetime EDecimal type issue.
  ansible/roles/test/files/ptftests/py3/advanced-reboot.py
Labels: automerge

#20130 [action] [PR:19633] Fix loganalyzer crash with `Exception: pop from empty list`
  tests/common/plugins/loganalyzer/utils.py
Labels: automerge

#20128 [action] [PR:18420] Fix `fib/test_fib.py::test_ecmp_group_member_flap` to not filter ports on `t2_single_node`
  tests/fib/test_fib.py
Labels: automerge

#20138 [action] [PR:19003] [crm] Fix test failures on SN4700 by batching neighbor creation
  tests/crm/test_crm.py
Labels: automerge

#16936 [platform] Fix the test_status_led error in case if the chassis led is not controllable
  tests/platform_tests/api/test_chassis.py
Labels: Request for 202405 branch, Request for 202411 branch

#20113 Ignore router advertisements in PTF
  ansible/roles/vm_set/tasks/add_topo.yml
Labels: Request for 202411 branch, Request for 202505 branch

#19797 bmp: Fix docker restart test for multi-asic
  tests/bmp/test_docker_restart.py
Labels: Request for 202505 branch

#20164 [action] [PR:19797] bmp: Fix docker restart test for multi-asic
  tests/bmp/test_docker_restart.py
Labels: automerge

#20005 fix missing eos templates for isolated topos
  .azure-pipelines/meta_validator.yml
  ansible/roles/eos/templates/t1-isolated-d448u15-lag-spine.j2
  ansible/roles/eos/templates/t1-isolated-d448u15-lag-tor.j2
  ansible/roles/eos/templates/t1-isolated-v6-d28u1-tor.j2
  ansible/roles/eos/templates/t1-isolated-v6-d448u15-lag-spine.j2
  ansible/roles/eos/templates/t1-isolated-v6-d448u15-lag-tor.j2
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 branch

#20120 Fix shutdown/startup flow in test_reset to support multi-asic
  tests/platform_tests/api/test_sfp.py
Labels: Request for msft-202412 Branch, Request for 202505 branch

#20148 Ignore timing issues introduced by parallelization in `vm_topology.py`
  ansible/roles/vm_set/library/vm_topology.py
Labels: Request for msft-202412 Branch

#19909 Add xfail for generic hash case test_lag_hash due to github issue 22586
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#20126 Stabilize hash_test on FT2 topology
  ansible/roles/test/files/ptftests/py3/hash_test.py
Labels: Request for msft-202503 Branch, Request for 202505 branch

#20106 Enhance test_disk_exhaustion with using /host for Simulating Disk Full.
  tests/disk/test_disk_exhaustion.py
Labels: Request for 202411 branch, Request for 202505 branch

#20177 [action] [PR:19776] Add autoneg config for sonic 202405 fanout
  ansible/roles/fanout/templates/sonic_deploy_202405.j2
Labels: automerge

#20091 Xfail test_lldp_neighbor_post_orchagent_reboot due to github issue 19658
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#20208 [action] [PR:20062] Add function to set counter poll interval
  tests/common/devices/sonic.py
Labels: automerge

#20213 Add 8101C01 to the hwsku list
  ansible/group_vars/sonic/variables
Labels: Request for 202411 branch, Request for 202505 branch

#20156 skip srv6 for Moby topology t0-isolated-d96u32s2
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202412 Branch, Request for 202505 branch

#20169 skip warm reboot for pfcwd on isolated topology.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202412 Branch, Approved for msft-202412 Branch, Included in msft-202412 Branch, Request for 202505 branch

#20187 skip test_gcu_acl_dhcp_rule_creation for isolated topology
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202412 Branch, Request for 202505 branch

#20212 Enhance the qos_remap test case with flushing the buffer
  tests/qos/test_tunnel_qos_remap.py
Labels: Request for 202411 branch, Request for 202505 branch

#20220 [action] [PR:20212] Enhance the qos_remap test case with flushing the buffer
  tests/qos/test_tunnel_qos_remap.py
Labels: automerge

#19967 Update restapi test to invoke apply_cert_config in smartswitch and isolated topology
  tests/restapi/conftest.py
  tests/restapi/test_restapi.py
Labels: Request for 202505 branch

#20160 Adjust FEC based on speed for test_config_interface_speed_40G_100G
  tests/common/devices/sonic.py
  tests/iface_namingmode/test_iface_namingmode.py
Labels: Request for 202505 branch

#18997 Fix macsec test_interop_protocol for t2 single node topo
  ansible/library/minigraph_facts.py
  ansible/templates/minigraph_link_meta.j2
  tests/macsec/test_interop_protocol.py
Labels: Request for msft-202503 Branch, Approved for msft-202503 Branch, Request for 202505 branch

#19606 Skip IPv4 BGP network command test in IPv6 topology
  tests/bgp/test_bgp_command.py
Labels: Request for 202411 branch, Request for msft-202412 Branch, Request for 202505 branch

#20268 [test route perf] Ignore ERR log during config reload
  tests/route/test_route_perf.py
Labels: Request for 202505 branch

#20196 Fix retry count test case to properly teardown in case of failure
  tests/pc/test_retry_count.py
Labels: Request for 202411 branch, Request for 202505 branch

#19092 Align the QoS sai test to the features of Per-Queue, Per-Priority, and Per-Direction
  tests/qos/qos_sai_base.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 branch

#19424 [Dualtor] Double the DROP_MARGIN in drop counters test for dualtor
  tests/common/helpers/drop_counters/drop_counters.py
Labels: Request for 202411 branch, Request for 202505 branch

#20278 [action] [PR:20115] Add instances to shorten PR test time
  .azure-pipelines/impacted_area_testing/calculate-instance-numbers.yml
  .azure-pipelines/impacted_area_testing/calculate_instance_number.py
Labels: automerge

#20245 [action] [PR:20160] Adjust FEC based on speed for test_config_interface_speed_40G_100G
  tests/common/devices/sonic.py
  tests/iface_namingmode/test_iface_namingmode.py
Labels: automerge

#20235 [action] [PR:20189] ignore queryAttributeEnumValuesCapability HASH_ALGORITHM error message
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#20243 [action] [PR:20219] [DT2] Enable test_buffer for DT2 platforms
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#20234 [action] [PR:20183] [dualtor] Skip toggle failure in `test_container_checker`
  tests/container_checker/test_container_checker.py
Labels: automerge

#20284 [action] [PR:20190] Fix typo in PR19199 in the test name
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: automerge

#20282 [action] [PR:20196] Fix retry count test case to properly teardown in case of failure
  tests/pc/test_retry_count.py
Labels: automerge

#20279 [action] [PR:19606] Skip IPv4 BGP network command test in IPv6 topology
  tests/bgp/test_bgp_command.py
Labels: automerge

#20241 [action] [PR:20169] skip warm reboot for pfcwd on isolated topology.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#20236 [action] [PR:19743] Remove the duplicated sad type from the multihop upgrade test
  tests/upgrade_path/test_multi_hop_upgrade_path.py
Labels: automerge

#20118 [action] [PR:20059] [DHCP relay counter] Add all DHCP packet type for DHCP relay counter tests
  ansible/roles/test/files/ptftests/py3/dhcp_relay_test.py
  tests/dhcp_relay/test_dhcp_relay.py
Labels: automerge

#20285 [action] [PR:19424] [Dualtor] Double the DROP_MARGIN in drop counters test for dualtor
  tests/common/helpers/drop_counters/drop_counters.py
Labels: automerge

#19966 Add transceiver status flag clear time to keys to skip comparison in …
  tests/common/configlet/utils.py
Labels: Request for 202505 branch

#20264 Add log errors to common ignore list by the ticket 22795 and 23199
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202505 branch

#20311 [action] [PR:20269] [snmp] use snmpv3 in pdu controller
  tests/common/plugins/pdu_controller/snmp_pdu_controllers.py
Labels: automerge

#20308 [action] [PR:18335] Xfail test due to github issue #20414
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#20329 [action] [PR:20232] Update expect_regex in test_duplicate_route to support bulk update mode
  tests/route/test_duplicate_route.py
Labels: automerge

#20330 [action] [PR:20264] Add log errors to common ignore list by the ticket 22795 and 23199
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#20328 [action] [PR:19966] Add transceiver status flag clear time to keys to skip comparison in …
  tests/common/configlet/utils.py
Labels: automerge

#20305 [action] [PR:20152] Enhance bgp suppress fib test to validate the tcpdump generated pcap file exist
  tests/common/helpers/tcpdump_sniff_helper.py
Labels: automerge

#20125 Handle Multi-port portchannel member case in ECMP member flap TC
  tests/fib/test_fib.py
Labels: Request for 202505 branch

#20277 refactor: optimize traffic shift test for T2
  tests/bgp/test_traffic_shift.py
  tests/bgp/test_traffic_shift_lc.py
Labels: Request for 202505 branch

#20347 [action] [PR:20277] refactor: optimize traffic shift test for T2
  tests/bgp/test_traffic_shift.py
  tests/bgp/test_traffic_shift_lc.py
Labels: automerge

#20346 update FRR bgp memory for high bgp sessions count hwskus
  tests/common/plugins/memory_utilization/memory_utilization_dependence.json
Labels: Request for 202505 branch

#20362 [action] [PR:20125] Handle Multi-port portchannel member case in ECMP member flap TC
  tests/fib/test_fib.py
Labels: automerge

#20340 Fix saithrift VERSION_CODENAME on multi-asic issue
  tests/test_pretest.py
Labels: Request for 202505 branch, Approved for 202505 branch

#20332 [vxlan.test_vnet_bgp_route_precedence]: Remove xfail as test has been fixed
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#20238 Add fixture to provide designed routes information of topology file
  ansible/library/announce_routes.py
  tests/bgp/test_ipv6_bgp_scale.py
  tests/conftest.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#20366 Skip test_bgp_operation_in_ro due to feature reverted
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#20371 [action] [PR:20367] Fix ports_list to address test error
  tests/common/fixtures/duthost_utils.py
Labels: automerge

#20374 [action] [PR:20366] Skip test_bgp_operation_in_ro due to feature reverted
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19614 Add multi binding acl test into everflow test scope
  tests/acl/test_acl.py
  tests/common/fixtures/duthost_utils.py
  tests/everflow/everflow_test_utilities.py
  tests/everflow/test_everflow_testbed.py
Labels: Request for 202505 branch

#18326 [CoPP]: Added neighbor_miss trap verification and cli test
  ansible/roles/test/files/ptftests/py3/copp_tests.py
  tests/copp/copp_utils.py
  tests/copp/scripts/update_copp_config.py
  tests/copp/test_copp.py
Labels: Request for 202505 branch

#20388 [action] [PR:20303] MIGSMSFT-1155 separate handling for Q200 and G200 in testQosSaiPfcXonLimit
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#20336 fix xon key error for th2 asic's qos test
  tests/qos/files/qos_params.th2.yaml
Labels: Request for 202505 branch

#20135 Fixed test_cold_reboot_dpus test
  tests/smartswitch/common/reboot.py
  tests/smartswitch/platform_tests/test_reload_dpu.py
Labels: Request for 202505 branch

#19680 [action] [PR:19585] Fix qos/test_qos_sai.py for active-active dualtor
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: automerge

#20338 Ignore error message "Failed to confirm VDM freeze" due to github issue 23426
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#19639 Add is_ipv6_only_topology utilities and IPv6 topology check to skip …
  tests/common/utilities.py
  tests/generic_config_updater/test_ip_bgp.py
Labels: Request for 202411 branch, Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 branch

#20216 Set func_len in test_srv6_static_config as 0
  tests/srv6/test_srv6_static_config.py
Labels: Request for msft-202412 Branch

#20350 Fix flakiness of test_pfcwd_show_stat
  tests/pfcwd/test_pfcwd_cli.py
Labels: Request for 202505 branch

#20404 [action] [PR:20350] Fix flakiness of test_pfcwd_show_stat
  tests/pfcwd/test_pfcwd_cli.py
Labels: automerge

#20398 [action] [PR:20154] Add ping before executing py_gnmicli.py at ptf docker
  tests/gnmi/helper.py
Labels: automerge

#20396 [action] [PR:20336] fix xon key error for th2 asic's qos test
  tests/qos/files/qos_params.th2.yaml
Labels: automerge

#20389 [Test Gap] enable test_forced_mgmt_route for lt2 and ft2
  tests/route/test_forced_mgmt_route.py
Labels: Request for msft-202503 Branch, Request for 202505 branch

#20402 [action] [PR:20338] Ignore error message "Failed to confirm VDM freeze" due to github issue 23426
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#20401 [action] [PR:20310] remove dangerous fixture disable_ipv6 for ptf container
  tests/common/fixtures/ptfhost_utils.py
Labels: automerge

#20399 [action] [PR:20332] [vxlan.test_vnet_bgp_route_precedence]: Remove xfail as test has been fixed
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#20397 [action] [PR:18326] [CoPP]: Added neighbor_miss trap verification and cli test
  ansible/roles/test/files/ptftests/py3/copp_tests.py
  tests/copp/copp_utils.py
  tests/copp/scripts/update_copp_config.py
  tests/copp/test_copp.py
Labels: automerge

#19282 Increase max dpu processes up timeout from 360s to 400s
  tests/smartswitch/common/device_utils_dpu.py
Labels: Request for 202505 branch

#20417 [action] [PR:20389] [Test Gap] enable test_forced_mgmt_route for lt2 and ft2
  tests/route/test_forced_mgmt_route.py
Labels: automerge

#20426 [action] [PR:19282] Increase max dpu processes up timeout from 360s to 400s
  tests/smartswitch/common/device_utils_dpu.py
Labels: automerge

#20412 [action] [PR:19639] Add is_ipv6_only_topology utilities and IPv6 topology check to skip …
  tests/common/utilities.py
  tests/generic_config_updater/test_ip_bgp.py
Labels: automerge

#20391 refactor: optimize test link down for T2
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
  tests/common/plugins/conditional_mark/tests_mark_conditions_sonic_vpp.yaml
  tests/common/plugins/conditional_mark/tests_mark_conditions_vs_t2.yaml
  tests/platform_tests/test_link_down.py
  tests/platform_tests/test_link_down_sup.py
  tests/platform_tests/utils.py
Labels: Request for 202505 branch

#20074 T2:snappi_tests:Change the speed_tol to correct number in pfcwd_actions.
  tests/snappi_tests/pfcwd/test_pfcwd_actions.py
Labels: Request for msft-202405 Branch, Request for 202505 branch
