Repository sonic-net/sonic-mgmt, pull requests merged in 2025-04, with the labels that each got.

#17754 Set mgmt branch to build branch in PR test
  .azure-pipelines/run-test-elastictest-template.yml
  azure-pipelines.yml
Labels: Request for 202411 branch

#17766 [action] [PR:17661] Stabilize suppress fib vrf config reload test
  tests/bgp/test_bgp_suppress_fib.py
Labels: automerge

#16440 Update qos sai due to no lossless pg for some platforms
  tests/qos/files/mellanox/qos_param_generator.py
  tests/qos/files/mellanox/special_qos_config.yml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_base_test.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#17776 Skip test_vnet_decap on Cisco-8000 with 202411
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202411 branch, Approved for 202411 branch

#17786 [action] [PR:17776] Skip test_vnet_decap on Cisco-8000 with 202411
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#17453 Add SRv6 data plane test script
  tests/common/helpers/dut_utils.py
  tests/show_techsupport/test_auto_techsupport.py
  tests/srv6/conftest.py
  tests/srv6/srv6_utils.py
  tests/srv6/test_srv6_dataplane.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#17365 Skip qos incremental test in case of no lossless buffer.
  tests/generic_config_updater/test_incremental_qos.py
Labels: Request for msft-202412 Branch

#17291 Remove a redundant blank space in dut_utils.py
  tests/common/helpers/dut_utils.py
Labels: Request for 202411 branch, Approved for 202411 branch

#17775 [action] [PR:16605] Increase verify_db_timeout as github issue #15644
  tests/common/dualtor/control_plane_utils.py
Labels: automerge

#17799 [action] [PR:17291] Remove a redundant blank space in dut_utils.py
  tests/common/helpers/dut_utils.py
Labels: automerge

#17787 [720DT] Skip test_ser for 720DT
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202405 branch, Request for 202411 branch

#17802 [action] [PR:17426] Unify the ipv6 address to upper case in generic hash case
  tests/hash/generic_hash_helper.py
Labels: automerge

#17765 Dualtor AA enablement for QOS SAI
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/qos/qos_sai_base.py
Labels: Request for 202411 branch

#17804 [action] [PR:17787] [720DT] Skip test_ser for 720DT
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: automerge

#17813 [action] [PR:17752] One vlan by default for topo_t0-118, with secondary subnet enabled
  ansible/vars/topo_t0-118.yml
Labels: automerge

#17812 [action] [PR:17752] One vlan by default for topo_t0-118, with secondary subnet enabled
  ansible/vars/topo_t0-118.yml
Labels: automerge

#17749 To fix the issue that ARM platform was skipped for bmp test unexpectedly
  tests/bmp/conftest.py
Labels: Request for 202411 branch

#17737 [action] [PR:17634] Add logging and a grace period to expect_acl_table_match_multiple_bindings method
  tests/common/gu_utils.py
Labels: automerge

#17825 [action] [PR:17541] [Mellanox] Skip test_check_sfp_eeprom_with_option_dom on spc3 and later
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: automerge

#17714 [action] [PR:15732] Fix for redis memory check failure after link flap and also sometimes cpu usage high failure
  tests/platform_tests/link_flap/link_flap_utils.py
  tests/platform_tests/link_flap/test_cont_link_flap.py
  tests/platform_tests/link_flap/test_link_flap.py
Labels: automerge

#17625 Add python script to collect dump on all duts
  .azure-pipelines/collect_dump.py
  tests/test_posttest.py
Labels: Request for 202311 branch, Request for 202405 branch, Request for 202411 branch

#17828 [action] [PR:15886] Revert "Test case for BFD echo-mode"
  tests/bfd/test_bfd.py
Labels: automerge

#17703 skip platform_tests/test_reboot.py::test_fast_reboot on 202412
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for msft-202412 Branch

#17723 Add hwsku Arista-7060X6-64PE-B-C512S2 and Arista-7060X6-64PE-B-C448O16 in sonic-mgmt
  ansible/group_vars/sonic/variables
  ansible/module_utils/port_utils.py
Labels: Request for msft-202412 Branch

#17770 update isolated 512 and v6 only topo in veos
  ansible/veos
Labels: Request for msft-202412 Branch

#17817 Fixed syslog rate-limit tests
  tests/common/plugins/loganalyzer/loganalyzer.py
  tests/syslog/test_syslog_rate_limit.py
Labels: Request for 202411 branch

#17844 [action] [PR:17709] Fix wr_arp slow arp response time on big topos
  ansible/roles/test/files/ptftests/py3/wr_arp.py
Labels: automerge

#17839 [action] [PR:17678] Loop check snmp facts in test_snmp_fdb.py
  tests/snmp/test_snmp_fdb.py
Labels: automerge

#17579 Added testcase to verify ecn marking on the Fabric and Back plane interfaces in T2 [ Cisco specific]
  tests/common/snappi_tests/common_helpers.py
  tests/snappi_tests/ecn/files/bpfabric_helper.py
  tests/snappi_tests/ecn/files/ecnhelper.py
  tests/snappi_tests/ecn/test_bp_fabric_ecn_marking_with_snappi.py
  tests/snappi_tests/files/helper.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#17864 [action] [PR:17817] Fixed syslog rate-limit tests
  tests/common/plugins/loganalyzer/loganalyzer.py
  tests/syslog/test_syslog_rate_limit.py
Labels: automerge

#17833 Fix pfcwd/test_pfcwd_function.py for dualtor topologies
  tests/common/helpers/pfcwd_helper.py
  tests/pfcwd/conftest.py
Labels: Request for 202411 branch

#17831 Choose correct vlan ip for 2vlan config in advance_reboot
  tests/common/fixtures/advanced_reboot.py
  tests/common/helpers/dut_ports.py
Labels: Request for 202405 branch, Request for 202411 branch

#17848 skip dynamic_acl on platform x86_64-8101_32fh_o_c01-r0
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202411 branch

#17400 [action] [PR:17257] Fix PCBB watermark test flaky issue
  tests/qos/test_tunnel_qos_remap.py
Labels: automerge

#17867 [action] [PR:17833] Fix pfcwd/test_pfcwd_function.py for dualtor topologies
  tests/common/helpers/pfcwd_helper.py
  tests/pfcwd/conftest.py
Labels: automerge

#17871 [action] [PR:17848] skip dynamic_acl on platform x86_64-8101_32fh_o_c01-r0
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#17869 [action] [PR:17831] Choose correct vlan ip for 2vlan config in advance_reboot
  tests/common/fixtures/advanced_reboot.py
  tests/common/helpers/dut_ports.py
Labels: automerge

#17875 [action] [PR:17849] tests/hash/test_generic_hash.py test_reboot warm boot to config save before reboot
  tests/hash/test_generic_hash.py
Labels: automerge

#17870 [action] [PR:17831] Choose correct vlan ip for 2vlan config in advance_reboot
  tests/common/fixtures/advanced_reboot.py
  tests/common/helpers/dut_ports.py
Labels: automerge

#17704 [action] [PR:17543] Fix the issue introduced when handle the 2 PRs #16948 and #16970
  tests/common/fixtures/ptfhost_utils.py
Labels: automerge

#17810 Ignore subnet decap test when no portchannels found
  tests/decap/test_subnet_decap.py
Labels: Request for 202411 branch

#17873 [sonic-mgmt][dualtor-aa] Fix flakiness of fdb/test_fdb_mac_learning.py
  tests/fdb/test_fdb_mac_learning.py
Labels: Request for 202411 branch

#17901 [action] [PR:17873] [sonic-mgmt][dualtor-aa] Fix flakiness of fdb/test_fdb_mac_learning.py
  tests/fdb/test_fdb_mac_learning.py
Labels: automerge

#17904 Increase timeout to 5 in verify_packet_any_port for background traffic
  tests/everflow/test_everflow_ipv6.py
Labels: Request for 202411 branch

#17726 Cisco update to lossy queue voq test expectations
  tests/qos/files/cisco/qos_param_generator.py
Labels: Request for 202411 branch

#17921 [action] [PR:17904] Increase timeout to 5 in verify_packet_any_port for background traffic
  tests/everflow/test_everflow_ipv6.py
Labels: automerge

#17868 Skip test_reload_configuration_checks on Cisco platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202411 branch, Approved for 202411 branch

#17888 update d18u8s4 PT0 ASN to 4 bytes
  ansible/vars/topo_t0-d18u8s4.yml
Labels: Request for msft-202412 Branch

#17909 [dualtor_io] Allow duplications for link down downstream I/O
  tests/common/dualtor/data_plane_utils.py
  tests/common/dualtor/dual_tor_io.py
  tests/dualtor_io/test_link_failure.py
Labels: Request for 202411 branch

#17942 [action] [PR:17941] Revert "Skip test_vnet_decap on Cisco-8000 with 202411"
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#17939 [action] [PR:17926] Only print the matched syslog in loganalzyer teardown check, no traceback info printed
  tests/common/helpers/parallel.py
Labels: automerge

#17897 add hwsku Cisco-8101-V64
  ansible/module_utils/port_utils.py
Labels: Request for 202411 branch

#17860 Specify 1-1 default map for TC_TO_DSCP for Cisco-8000
  tests/qos/tunnel_qos_remap_base.py
Labels: Request for 202411 branch

#17898 add template t0-isolated-d96u32s2-leaf.j2 and Arista-7060X6-16PE-384C-O128S2 into th5 hwsku
  ansible/group_vars/sonic/variables
  ansible/roles/eos/templates/t0-isolated-d96u32s2-leaf.j2
Labels: Request for msft-202412 Branch

#17949 [action] [PR:17916] Add dualtor fixtures to PFC-WD no_traffic test
  tests/pfcwd/test_pfcwd_function.py
Labels: automerge

#17948 [action] [PR:17860] Specify 1-1 default map for TC_TO_DSCP for Cisco-8000
  tests/qos/tunnel_qos_remap_base.py
Labels: automerge

#17767 Restore config after vxlan_crm from vxlan_ecmp.
  tests/vxlan/test_vxlan_ecmp.py
Labels: Request for 202405 branch, Request for 202411 branch

#17861 Add test_srv6_uN_no_vlan_flooding test case
  tests/srv6/test_srv6_vlan_forwarding.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#17788 [Mellanox] Update qos sai test for SN56xx buffer configuration alignment
  tests/qos/qos_sai_base.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#17979 [action] [PR:14727] [dhcp_relay] Use restart_dhcp_service instead of simple restart dhcp_…
  tests/dhcp_relay/test_dhcp_relay.py
Labels: automerge

#17280 Improve arp_responder.py performance
  ansible/roles/test/files/ptftests/py3/advanced-reboot.py
  tests/scripts/arp_responder.py
Labels: Request for 202411 branch

#16778 Pfcwd multi port: Fix for Multi-asic Scenario and test_multi_port Requirement of 3 routed ports
  tests/pfcwd/conftest.py
  tests/pfcwd/test_pfcwd_function.py
Labels: P0, Request for 202411 branch, Request for msft-202405 Branch

#17605 [action] [PR:17470] skip test_bgp_slb advanced reboot for isolated topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#17798 [action] [PR:17570] Update outer UDP sport range to exclude port 53
  ansible/roles/test/files/ptftests/py3/hash_test.py
Labels: automerge

#17846 Fix vlan vs router mac issue with test_qos_dscp_mapping.py
  tests/common/utilities.py
  tests/qos/test_qos_dscp_mapping.py
Labels: Request for 202411 branch

#17950 add hwsku Cisco-8101-V64 to the cisco-8000_gb_hwskus list
  ansible/group_vars/sonic/variables
Labels: Request for 202411 branch, Approved for 202411 branch

#17991 [action] [PR:17889] Disable PFC-WD during PCBB and some wmk test improvements
  tests/qos/test_tunnel_qos_remap.py
  tests/qos/tunnel_qos_remap_base.py
Labels: automerge

#17741 [action] [PR:17722] [dualtor_io] Collect syslog to debug
  tests/dualtor_io/test_link_failure.py
  tests/dualtor_io/test_tor_failure.py
Labels: automerge

#17679 Add retry when checking fec mode restore status in tests/platform_tests/test_intf_fec.py
  tests/platform_tests/test_intf_fec.py
Labels: Request for 202411 branch

#17253 Enhance arp update test to support port toggle at dualtor active active testbed
  tests/arp/test_arp_update.py
Labels: Request for 202411 branch

#16989 limit parallel_run cct tasks number from 24 to 8 for fixture setup_bgp_graceful_restart
  tests/bgp/conftest.py
Labels: Request for 202405 branch, Request for 202411 branch

#16611 Update CPU threshold for telemetry test_events case
  tests/telemetry/events/host_events.py
Labels: Request for 202405 branch, Request for 202411 branch

#14273 Added skip for test_mgmt_ipv6_only TC if ipv6 mgmt not available
  tests/common/fixtures/duthost_utils.py
Labels: Request for 202405 branch, Request for 202411 branch

#16217 Update generic hash test to support dualtor active active topology
  tests/hash/generic_hash_helper.py
  tests/hash/test_generic_hash.py
Labels: Request for 202405 branch, Request for 202411 branch

#17998 Fix route/test_static_route.py
  tests/pfcwd/conftest.py
  tests/route/test_static_route.py
Labels: Request for 202411 branch

#18020 Fix incompatible import of scapy and skip when no lldp neigh in test_srv6_dataplane.py
  tests/srv6/test_srv6_dataplane.py
Labels: Request for msft-202412 Branch

#17919 [Fix for Issue #17413] Modified the Tx Rx port id list selection for …
  tests/snappi_tests/pfcwd/files/pfcwd_multi_node_helper.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#18032 [action] [PR:17919] [Fix for Issue #17413] Modified the Tx Rx port id list selection for …
  tests/snappi_tests/pfcwd/files/pfcwd_multi_node_helper.py
Labels: automerge

#17837 [PR#17130] - lldp - Changes for VOQ single-dut multi-asic
  tests/lldp/test_lldp_syncd.py
Labels: Request for msft-202503 Branch

#18034 [action] [PR:17767] Restore config after vxlan_crm from vxlan_ecmp.
  tests/vxlan/test_vxlan_ecmp.py
Labels: automerge

#16765 LLDP: Fix issue with restart_orchagent as VOQ does not support warm restarting of orchagent
  tests/lldp/test_lldp.py
Labels: Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503

#17838 [PR#17130] - fib - Changes for VOQ single-dut multi-asic
  tests/common/fixtures/fib_utils.py
Labels: Request for msft-202503 Branch

#17852 [PR#17130] - VOQ Lag - Changes for VOQ single-dut multi-asic
  tests/common/helpers/voq_lag.py
Labels: Request for msft-202503 Branch

#17845 [PR#17130] - BGP Queue - Changes for VOQ single-dut multi-asic
  tests/bgp/test_bgp_queue.py
Labels: Request for msft-202503 Branch, Approved for msft-202503 Branch

#18026 Force eos default creds to be string
  ansible/group_vars/all/creds.yml
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch, Request for 202411 branch, Request for msft-202412 Branch, Request for msft-202405 Branch, Request for msft-202503 Branch

#18039 [action] [PR:18026] Force eos default creds to be string
  ansible/group_vars/all/creds.yml
Labels: automerge

#18040 [action] [PR:18026] Force eos default creds to be string
  ansible/group_vars/all/creds.yml
Labels: automerge

#17527 [Mellanox] Skip the fib nvgre hash test on SPC1 with t1-lag topology
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202411 branch, 202411 issue

#16532 [default-route-bgp-flap]: [T2] Fix and handle AZNG route-map for upstream LC
  tests/route/test_default_route.py
Labels: Request for msft-202503 Branch

#17999 Remove unused arguments when calling testbed_config_vchassis playbook.
  ansible/testbed-cli.sh
  ansible/testbed_config_vchassis.yml
Labels: P0

#18048 [action] [PR:17406] Skip test_incremental_qos on Mellanox dualtor
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#18041 [action] [PR:18026] Force eos default creds to be string
  ansible/group_vars/all/creds.yml
Labels: automerge

#18029 Fix t0-isolated-v6 topo errors
  ansible/roles/eos/templates/t0-isolated-v6-d128u128s1-leaf.j2
  ansible/roles/eos/templates/t0-isolated-v6-d128u128s2-leaf.j2
  ansible/roles/eos/templates/t0-isolated-v6-d16u16s1-leaf.j2
  ansible/roles/eos/templates/t0-isolated-v6-d16u16s2-leaf.j2
  ansible/roles/eos/templates/t0-isolated-v6-d256u256s2-leaf.j2
  ansible/roles/eos/templates/t0-isolated-v6-d32u32s2-leaf.j2
  ansible/roles/eos/templates/t0-isolated-v6-d96u32s2-leaf.j2
  ansible/roles/eos/templates/t0-v6-leaf.j2
  ansible/templates/topo_t0-isolated-v6.j2
  ansible/templates/topo_t1-isolated-v6.j2
  ansible/vars/topo_t0-isolated-v6-d16u16s2.yml
  ansible/vars/topo_t0-isolated-v6-d256u256s2.yml
  ansible/vars/topo_t0-isolated-v6-d32u32s2.yml
  ansible/vars/topo_t1-isolated-v6-d28u1.yml
  ansible/vars/topo_t1-isolated-v6-d448u16.yml
  ansible/vars/topo_t1-isolated-v6-d56u2.yml
Labels: Request for msft-202412 Branch

#17970 [action] [PR:17909] [dualtor_io] Allow duplications for link down downstream I/O
  tests/common/dualtor/data_plane_utils.py
  tests/common/dualtor/dual_tor_io.py
  tests/dualtor_io/test_link_failure.py
Labels: automerge

#18019 [action] [PR:16217] Update generic hash test to support dualtor active active topology
  tests/hash/generic_hash_helper.py
  tests/hash/test_generic_hash.py
Labels: automerge

#18065 [action] [PR:17505] Remove admin down ports in BUFFER PG check logic
  tests/qos/test_buffer.py
Labels: automerge

#16885 [Qos]HeadroomPoolSize test with dynamic_threshold based buffer allocation
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/qos/files/qos_params.j2c.yaml
  tests/qos/test_qos_sai.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Chassis Test Gap, Request for 202411 branch, Request for msft-202405 Branch, Cherry Pick Conflict_msft-202405, Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503

#17763 Changes to support RDMA Tests for VOQ Chassis
  tests/snappi_tests/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossy_helper.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#17739 [action] [PR:17728] Improve disabling packet aging to support swap_syncd
  tests/qos/test_tunnel_qos_remap.py
  tests/qos/tunnel_qos_remap_base.py
Labels: automerge

#18086 [action] [PR:18071] Mark xfail for generic hash test in isolated topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#18078 skip acl for isolated-v6 topo temporarily
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202412 Branch

#17964 Extend LACP time multiplier for advanced-reboot tests with cEOS peers
  ansible/roles/test/files/ptftests/py3/advanced-reboot.py
Labels: Request for 202411 branch

#18028 Move some SRv6 functions to srv6_helper.py
  tests/common/helpers/srv6_helper.py
  tests/srv6/conftest.py
  tests/srv6/srv6_utils.py
  tests/srv6/test_srv6_dataplane.py
Labels: Request for msft-202412 Branch

#18116 [action] [PR:15886] Revert "Test case for BFD echo-mode"
  tests/bfd/test_bfd.py
Labels: automerge

#18006 Fix for Everflow ACL Table Configuration Error
  tests/everflow/everflow_test_utilities.py
Labels: Request for 202411 branch

#18127 [action] [PR:18006] Fix for Everflow ACL Table Configuration Error
  tests/everflow/everflow_test_utilities.py
Labels: automerge

#18130 Adjust port selection in testQosSaiXonHysteresis for Cisco-8101-O32
  tests/qos/files/cisco/qos_param_generator.py
Labels: Request for 202411 branch

#18135 [action] [PR:18130] Adjust port selection in testQosSaiXonHysteresis for Cisco-8101-O32
  tests/qos/files/cisco/qos_param_generator.py
Labels: automerge

#18112 skip vlan member config if no vlan is defined in fanout.yml deployment
  ansible/roles/fanout/templates/sonic_deploy_202405.j2
Labels: Request for msft-202412 Branch

#18150 [action] [PR:18114] Fix loganalyzer error handling inconsistency and Improve error handling in parallel processes execution
  tests/common/helpers/parallel.py
Labels: automerge

#18149 [action] [PR:18114] Fix loganalyzer error handling inconsistency and Improve error handling in parallel processes execution
  tests/common/helpers/parallel.py
Labels: automerge

#18151 [action] [PR:18114] Fix loganalyzer error handling inconsistency and Improve error handling in parallel processes execution
  tests/common/helpers/parallel.py
Labels: automerge

#18092 [dualtor] Refine `fdb_mac_learning_test.py`
  ansible/roles/test/files/ptftests/py3/fdb_mac_learning_test.py
  tests/fdb/test_fdb_mac_learning.py
Labels: Request for 202411 branch

#18096 [dualtor_io] Fix the start marker not found issue
  tests/dualtor_io/conftest.py
  tests/dualtor_io/test_tor_failure.py
Labels: Request for 202411 branch

#18113 [action] [PR:17964] Extend LACP time multiplier for advanced-reboot tests with cEOS peers
  ansible/roles/test/files/ptftests/py3/advanced-reboot.py
Labels: automerge

#18162 [action] [PR:18096] [dualtor_io] Fix the start marker not found issue
  tests/dualtor_io/conftest.py
  tests/dualtor_io/test_tor_failure.py
Labels: automerge

#18170 [testARPCompleted] Cleanup ptf ip after test failure
  tests/fdb/test_fdb_mac_learning.py
Labels: Request for 202411 branch

#18172 [action] [PR:18092] [dualtor] Refine `fdb_mac_learning_test.py`
  ansible/roles/test/files/ptftests/py3/fdb_mac_learning_test.py
  tests/fdb/test_fdb_mac_learning.py
Labels: automerge

#18175 [action] [PR:18170] [testARPCompleted] Cleanup ptf ip after test failure
  tests/fdb/test_fdb_mac_learning.py
Labels: automerge

#16983 Update sonic port configure and check method
  tests/common/devices/sonic.py
Labels: Request for msft-202412 Branch

#16965 Align stress acl test for the t1-isolated-d28u1 topo
  tests/acl/test_stress_acl.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#17627 Enhance the fib test to run on dualtor active active setup
  tests/fib/test_fib.py
Labels: Request for 202411 branch
