Repository sonic-net/sonic-mgmt, pull requests merged in 2025-07, with the labels that each got.

#19099 LogAnalyzer: Ignore a non-functional error thrown from Linkmgrd
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: Request for 202505 branch

#19202 Added asn_increment for asn_v6, and updated topo_t1-isolated-v6-d56u1…
  ansible/generate_topo.py
  ansible/vars/topo_t1-isolated-v6-d56u1-lag.yml
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 branch

#19151 [dhcp_relay] Verify per-interface counter under stress test
  tests/common/dhcp_relay_utils.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/dhcp_relay/conftest.py
  tests/dhcp_relay/dhcp_relay_utils.py
  tests/dhcp_relay/test_dhcp_counter_stress.py
  tests/dhcp_relay/test_dhcp_relay.py
  tests/dhcp_relay/test_dhcp_relay_stress.py
Labels: Request for 202505 branch

#19051 Bgp block on loopback1 testgap
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/dualtor/conftest.py
  tests/dualtor/test_bgp_block_loopback1.py
  tests/dualtor/test_orchagent_slb.py
Labels: Request for 202505 branch

#19307 [dhcp_relay] Add sleep for stress dhcpmon test
  tests/dhcp_relay/test_dhcp_counter_stress.py
Labels: Request for 202505 branch

#19323 [action] [PR:19299] fix: add xfail for teamd autorestart
  tests/autorestart/test_container_autorestart.py
Labels: automerge

#19291 [action] [PR:19151] [dhcp_relay] Verify per-interface counter under stress test
  tests/common/dhcp_relay_utils.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/dhcp_relay/conftest.py
  tests/dhcp_relay/dhcp_relay_utils.py
  tests/dhcp_relay/test_dhcp_counter_stress.py
  tests/dhcp_relay/test_dhcp_relay.py
  tests/dhcp_relay/test_dhcp_relay_stress.py
Labels: automerge

#19287 Unskip testQosSaiHeadroomPoolWatermark on t0-d18u8s4
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202411 branch, Request for 202505 branch

#19325 [action] [PR:19149] Ignore syncd error log of process_on_fdb_event
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#19061 [master][sonic-mgmt]Fix decap/test_subnet_decap.py::test_vlan_subnet_…
  tests/decap/test_subnet_decap.py
Labels: Request for 202505 branch

#19255 [action] [PR:19074] skip speed change for Arista 7060x6 platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19298 [action] [PR:19099] LogAnalyzer: Ignore a non-functional error thrown from Linkmgrd
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#19300 [action] [PR:19261] Enhance ACL test on LT2 topology
  tests/acl/test_acl.py
Labels: automerge

#19295 [action] [PR:19242] [test_vnet_bgp_route_precedence] Fix VNET prefix and BGP propagation
  tests/vxlan/test_vnet_bgp_route_precedence.py
Labels: automerge

#19250 [action] [PR:19238] Set VM as reflector for LT2/FT2
  ansible/roles/eos/templates/t0-leaf.j2
Labels: automerge

#19246 Updating `test_ecn_config_update.py` to fix nightly test failures
  tests/generic_config_updater/test_ecn_config_update.py
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18625 Batch neighbor add/del commands in `test_crm_neighbor`
  tests/crm/test_crm.py
Labels: Request for 202505 branch

#19337 [dualtor][cisco] Fix `test_encap_with_mirror_session`
  tests/dualtor/test_ipinip.py
Labels: Request for 202411 branch, Request for 202505 branch

#19296 [sanity] Fix sanity check bgp not ready after restart
  tests/common/plugins/sanity_check/checks.py
Labels: Request for 202505 branch

#19341 [GCU] Enhance test_eth_interface
  tests/generic_config_updater/test_eth_interface.py
Labels: Request for 202505 branch

#19297 [action] [PR:19060] Added detailed reason for assert failure for bgp,gnmi,chassis_module
  tests/common/helpers/bgp.py
  tests/gnmi/test_gnmi.py
  tests/platform_tests/cli/test_show_chassis_module.py
Labels: automerge

#19314 [action] [PR:19211] update full isolated topo for C512S2 and C448O16
  ansible/generate_topo.py
  ansible/vars/topo_t0-isolated-d256u256s2.yml
  ansible/vars/topo_t0-isolated-v6-d256u256s2.yml
  ansible/vars/topo_t1-isolated-d448u15-lag.yml
  ansible/vars/topo_t1-isolated-v6-d448u15-lag.yml
  ansible/veos
  tests/acl/test_stress_acl.py
  tests/qos/qos_sai_base.py
Labels: automerge

#19359 [action] [PR:19341] [GCU] Enhance test_eth_interface
  tests/generic_config_updater/test_eth_interface.py
Labels: automerge

#19379 [action] [PR:19368] [PR test] Temporarily mark multi_asic test job as optional
  azure-pipelines.yml
Labels: automerge

#19375 [action] [PR:19340] [routes] Add sorting vms in announce_routes for t0 and t1
  ansible/library/announce_routes.py
Labels: automerge

#19395 [action] [PR:16300] Update background traffic to make pfcwd timer accuracy test more stable
  tests/pfcwd/test_pfcwd_timer_accuracy.py
Labels: automerge

#19390 [action] [PR:19296] [sanity] Fix sanity check bgp not ready after restart
  tests/common/plugins/sanity_check/checks.py
Labels: automerge

#19386 [action] [PR:18625] Batch neighbor add/del commands in `test_crm_neighbor`
  tests/crm/test_crm.py
Labels: automerge

#19385 [action] [PR:19139] Add config change validation to prevent bad bgp config state
  tests/bgp/test_bgp_suppress_fib.py
Labels: automerge

#19355 [action] [PR:18408] Skip BGP check in teardown if `--skip-sanity` is used
  tests/conftest.py
Labels: automerge

#19275 Enable new tests for Nvidia smartswitch
  tests/common/mellanox_data.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/qos/qos_sai_base.py
Labels: Request for 202505 branch

#18144 [Mellanox] Ignore the expected errors in bfd test
  tests/bfd/test_bfd.py
Labels: Request for 202411 branch, Request for msft-202412 Branch, Request for 202505 branch

#18841 Fix ntp synchronization issue for test_ntp
  tests/common/helpers/ntp_helper.py
Labels: Request for 202505 branch

#18867 Update vlan ping test to override the affection of secondary vlan ip
  tests/vlan/test_vlan_ping.py
Labels: Request for 202505 branch

#19408 [action] [PR:18867] Update vlan ping test to override the affection of secondary vlan ip
  tests/vlan/test_vlan_ping.py
Labels: automerge

#19406 [action] [PR:19181] [Smartswitch] Fix test issues in the dpu platform test
  tests/smartswitch/platform_tests/test_platform_dpu.py
Labels: automerge

#19407 [action] [PR:18798] Update script to make script test_mux_port_iptables_entries pass
  ansible/group_vars/sonic/variables
  ansible/library/dual_tor_facts.py
Labels: automerge

#13500 [action] [PR:12944] Verify the PCIe daemon status before retrieving the PCIE_DEVICES table from the database
  tests/platform_tests/daemon/test_pcied.py
Labels: automerge

#13499 [action] [PR:12944] Verify the PCIe daemon status before retrieving the PCIE_DEVICES table from the database
  tests/platform_tests/daemon/test_pcied.py
Labels: automerge

#19394 [action] [PR:19094] Remove S2 port mappings for 7060X O128 port skus
  ansible/module_utils/port_utils.py
Labels: automerge

#18866 Enhance PTF and BGP route sync validation of msft srv6 test cases
  tests/srv6/srv6_utils.py
  tests/srv6/test_srv6_dataplane.py
Labels: Request for msft-202412 Branch, Request for 202505 branch

#19439 [action] [PR:19306] Add support to autogenerate sonicLabConsoleLinks.csv
  ansible/TestbedProcessing.py
Labels: automerge

#19437 [action] [PR:19308] [master][sonic-mgmt]Skip everflow/test_everflow_ipv6 and ipv6 cases under everflow/test_everflow_testbed on Arista-7260CX3
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19021 [test gap] Test plan for ECMP balance test
  docs/testplan/ECMP-Balance-test-plan.md
Labels: Test gap

#13498 [action] [PR:12944] Verify the PCIe daemon status before retrieving the PCIE_DEVICES table from the database
  tests/platform_tests/daemon/test_pcied.py
Labels: automerge

#18117 Add type check for ptf_ports to adapt physical port interface and portchannel interface
  tests/sub_port_interfaces/conftest.py
Labels: Request for 202505 branch

#19316 Fix flakiness with poll mode tests when client has not connected yet or default route has not populated yet
  tests/telemetry/telemetry_utils.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_telemetry_poll.py
Labels: Request for 202505 branch

#19441 [sanity_check] Fix bgp recovery for multi-asic devices
  tests/common/plugins/sanity_check/checks.py
Labels: Request for 202505 branch

#19454 [action] [PR:19441] [sanity_check] Fix bgp recovery for multi-asic devices
  tests/common/plugins/sanity_check/checks.py
Labels: automerge

#18247 [Test gap] Add coverage for IPv6 traffic to the PFCWD PTF test cases
  ansible/library/get_ip_in_range.py
  ansible/roles/test/files/ptftests/py3/pfc_wd.py
  tests/common/helpers/pfcwd_helper.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/conftest.py
  tests/pfcwd/test_pfcwd_all_port_storm.py
  tests/pfcwd/test_pfcwd_cli.py
  tests/pfcwd/test_pfcwd_function.py
  tests/pfcwd/test_pfcwd_timer_accuracy.py
  tests/pfcwd/test_pfcwd_warm_reboot.py
Labels: Test gap, Chassis Test Gap

#19456 [action] [PR:19316] Fix flakiness with poll mode tests when client has not connected yet or default route has not populated yet
  tests/telemetry/telemetry_utils.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_telemetry_poll.py
Labels: automerge

#19422 [M1] Add 7050CX3 M1 HwSKU in TD3 list
  ansible/group_vars/sonic/variables
Labels: Request for 202505 branch

#19378 correct PT0 ASN number in t0-isolated-v6 and full topo.
  ansible/generate_topo.py
  ansible/vars/topo_t0-isolated-d128u128s2.yml
  ansible/vars/topo_t0-isolated-d256u256s2.yml
  ansible/vars/topo_t0-isolated-v6-d16u16s2.yml
  ansible/vars/topo_t0-isolated-v6-d256u256s2.yml
  ansible/vars/topo_t0-isolated-v6-d32u32s2.yml
Labels: Request for msft-202412 Branch, Request for 202505 branch

#19464 [action] [PR:18117] Add type check for ptf_ports to adapt physical port interface and portchannel interface
  tests/sub_port_interfaces/conftest.py
Labels: automerge

#19455 [action] [PR:19431] Fall back to config_db if running_golden_config not exists in recovery
  tests/common/plugins/sanity_check/recover.py
Labels: automerge

#19443 [dualtor] Skip warm/fast reboot cases on dualtor
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#18601 [Test plan] Update snappi-based switch capacity test plan
  docs/testplan/snappi-tests/capacity_test.md
  docs/testplan/snappi-tests/capacity_test_diagram.png
  docs/testplan/snappi/switch_capacity_test.md
Labels: Test Plan

#19266 [Dualtor] Update generic hash script to fix error log
  tests/hash/test_generic_hash.py
Labels: Request for 202411 branch, Request for 202505 branch

#18051 Add packet trimming test cases
  tests/common/helpers/ptf_tests_helper.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/common/utilities.py
  tests/generic_config_updater/test_packet_trimming_config.py
  tests/packet_trimming/__init__.py
  tests/packet_trimming/conftest.py
  tests/packet_trimming/constants.py
  tests/packet_trimming/packet_trimming_helper.py
  tests/packet_trimming/test_packet_trimming.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 branch

#19231 [T2] [single-node-max] Fix for test_voq_system_port_create speed verification
  tests/voq/test_voq_init.py
Labels: Request for msft-202503 Branch, Approved for msft-202503 Branch

#19344 Add wait_until for ARP population on linkflap testcase in test_voq_nbr.py
  tests/voq/test_voq_nbr.py
Labels: Request for msft-202503 Branch, Approved for msft-202503 Branch, Request for 202505 branch

#19430 [test_pfcwd_status] skipped generic_config_updater.test_pfcwd_status for non-supported hwsku SN5640 and Arista7060X6PE
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 branch

#19480 [action] [PR:19416] [PR] Fix the apt install lock issue: 'Could not get lock /var/lib/dpk…
  .azure-pipelines/pytest-collect-only.yml
Labels: automerge

#16018 Everflow - Test for recycle port queue counter
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/everflow/everflow_test_utilities.py
  tests/everflow/test_everflow_testbed.py
Labels: chassis, Chassis Test Gap, Request for 202505 branch

#19481 [logrotate] Fix the issue that no logs will be consider as non-zero return in grep
  tests/syslog/test_logrotate.py
Labels: Request for msft-202405 Branch, Request for 202505 branch

#19497 [action] [PR:19481] [logrotate] Fix the issue that no logs will be consider as non-zero return in grep
  tests/syslog/test_logrotate.py
Labels: automerge

#18959 Increase delay for route convergence if # of routes are above threshold when port toggle and reboot in ACL test
  tests/acl/test_acl.py
Labels: Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503

#19442 [dualtor] Skip warm/fast reboot cases on dualtor
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#19509 [action] [PR:19231] [T2] [single-node-max] Fix for test_voq_system_port_create speed verification
  tests/voq/test_voq_init.py
Labels: automerge

#19484 Optimize large topology deployment by parallelizing serial tasks
  ansible/roles/vm_set/tasks/add_ceos_list.yml
  ansible/roles/vm_set/tasks/remove_topo.yml
Labels: Request for msft-202412 Branch

#19508 [action] [PR:19266] [Dualtor] Update generic hash script to fix error log
  tests/hash/test_generic_hash.py
Labels: automerge

#19514 [action] [PR:19483] Remove config reload in test_config_interface_speed_40G_100G
  tests/iface_namingmode/test_iface_namingmode.py
Labels: automerge

#19515 [action] [PR:19414] fix: metadata not generate for ixia/tgen topology
  tests/test_pretest.py
Labels: automerge

#19494 [7215] Skip unsupported everflow testcases
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#19506 [action] [PR:19361] add topo dualtor-aa-64-breakout to qos_sai_base.py file
  tests/qos/qos_sai_base.py
Labels: automerge

#19476 [DT2] Enable qos_sai for dt2
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503, Request for 202505 branch

#19532 Fix everflow_per_interface test on LT2/FT2
  tests/everflow/test_everflow_per_interface.py
Labels: Request for msft-202503 Branch, Approved for msft-202503 Branch

#18614 Add skip condition for https://github.com/sonic-net/sonic-mgmt/issues/18594
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#18868 Update skip condition for test_decap.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#18952 Fix everflow test for erspan V6
  tests/everflow/test_everflow_per_interface.py
Labels: Request for 202505 branch

#17987 Added pfc tests to skip for 5600/5640 platforms
  tests/common/mellanox_data.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/telemetry/events/swss_events.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 branch, Approved for 202505 branch

#18090 [platform_tests/sfp]: Skip getting sfp info for supervisor
  tests/platform_tests/conftest.py
Labels: Request for 202405 branch, Request for 202411 branch, Request for 202505 branch

#19551 [action] [PR:17987] Added pfc tests to skip for 5600/5640 platforms
  tests/common/mellanox_data.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/telemetry/events/swss_events.py
Labels: automerge

#19538 [devices/eos]: Ignore case when searching for interface speeds
  tests/common/devices/eos.py
Labels: Request for 202405 branch, Request for 202411 branch, Request for 202505 branch

#19563 [action] [PR:18090] [platform_tests/sfp]: Skip getting sfp info for supervisor
  tests/platform_tests/conftest.py
Labels: automerge

#19562 [action] [PR:18614] Add skip condition for https://github.com/sonic-net/sonic-mgmt/issues/18594
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19558 [action] [PR:19541] [memory_utilization] update hwsku specific config for sn4600c
  tests/common/plugins/memory_utilization/memory_utilization.py
  tests/common/plugins/memory_utilization/memory_utilization_dependence.json
Labels: automerge

#19561 [action] [PR:18952] Fix everflow test for erspan V6
  tests/everflow/test_everflow_per_interface.py
Labels: automerge

#19173 MIGSMSFT-1029
  tests/snappi_tests/pfc/files/mixed_speed_multidut_helper.py
Labels: Request for msft-202405 Branch, Request for msft-202503 Branch, Request for 202505 branch

#19402 MIGSMSFT-1070:flaky test_m2o_oversubscribe_lossless_lossy.py. Drop packets outside of 5%
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Request for 202505 branch

#19572 [action] [PR:19070] [snappi] Replace hardcoded lossy flows to random priority lossy flows in PFC m2o oversubscribe tests
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossy_helper.py
  tests/snappi_tests/pfc/test_m2o_oversubscribe_lossless.py
  tests/snappi_tests/pfc/test_m2o_oversubscribe_lossless_lossy.py
  tests/snappi_tests/pfc/test_m2o_oversubscribe_lossy.py
Labels: automerge

#19570 [action] [PR:19402] MIGSMSFT-1070:flaky test_m2o_oversubscribe_lossless_lossy.py. Drop packets outside of 5%
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
Labels: automerge

#19569 [action] [PR:19173] MIGSMSFT-1029
  tests/snappi_tests/pfc/files/mixed_speed_multidut_helper.py
Labels: automerge

#19267 Enhance test_vxlan_bfd_tsa test
  tests/vxlan/test_vxlan_bfd_tsa.py
Labels: Request for 202411 branch, Request for 202505 branch

#19577 chore: add supported hwsku for th5
  ansible/group_vars/sonic/variables
Labels: Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503, Request for 202505 branch

#19581 [dualtor] Fix sniffer not capture packets
  tests/scripts/dual_tor_sniffer.py
Labels: Request for 202505 branch

#19470 [Snappi]: Modified PFCWD testcases with tgen-port-info support
  tests/snappi_tests/pfcwd/test_pfcwd_burst_storm_with_snappi.py
  tests/snappi_tests/pfcwd/test_pfcwd_m2o_with_snappi.py
  tests/snappi_tests/pfcwd/test_pfcwd_runtime_traffic_with_snappi.py
  tests/snappi_tests/test_multidut_snappi.py
Labels: Request for 202505 branch

#19526 [TH5] update t0-isolated-d96u32s2 topo
  ansible/generate_topo.py
  ansible/vars/topo_t0-isolated-d96u32s2.yml
  ansible/vars/topo_t0-isolated-v6-d96u32s2.yml
  ansible/veos
Labels: Request for msft-202412 Branch, Request for 202505 branch

#19575 Fix test_bgp_suppress_fib.py failure with exabgp 4.x version
  tests/bgp/test_bgp_suppress_fib.py
Labels: Request for msft-202412 Branch, Request for 202505 branch

#16953 Added sleep between restapi calls, during verifying routes on test_da…
  tests/restapi/test_restapi.py
Labels: Request for 202405 branch, Request for 202411 branch, Request for msft-202412 Branch

#19609 chore: add topo-lt2-p32o64 in qos_params
  tests/qos/files/qos_params.th5.yaml
Labels: Request for msft-202503 Branch, Request for 202505 branch

#19611 [action] [PR:19557] [route] Fix routes announing issue in isolated T1 topo
  ansible/library/announce_routes.py
Labels: automerge

#19486 skip test_cont_link_flap on SN2 and t1-lag due to issue 23121
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202505 branch

#19628 [action] [PR:19403] Fix SRv6 config_setup fixture
  tests/srv6/conftest.py
Labels: automerge

#19623 [action] [PR:19581] [dualtor] Fix sniffer not capture packets
  tests/scripts/dual_tor_sniffer.py
Labels: automerge

#19618 [action] [PR:19555] Enhance test_disk_exhaustion with leaving some free space to avoid kernel errors
  tests/disk/test_disk_exhaustion.py
Labels: automerge

#19626 [action] [PR:19575] Fix test_bgp_suppress_fib.py failure with exabgp 4.x version
  tests/bgp/test_bgp_suppress_fib.py
Labels: automerge

#19619 [action] [PR:19584] Enable pretest with ipv6 testbeds
  ansible/library/show_ipv6_interface.py
  tests/common/devices/sonic_asic.py
  tests/common/plugins/sanity_check/checks.py
  tests/common/utilities.py
Labels: automerge

#19466 [action] [PR:19310] Fix buffer queue cnt test to account for different BUFFER_QUEUE configs
  tests/telemetry/test_telemetry.py
Labels: automerge

#19624 [action] [PR:19582] enhance test_bgp_session case to handle the exception
  tests/bgp/test_bgp_session.py
Labels: automerge

#19001 Adding fix for port_alias mapping in test_route_flap.py
  tests/route/test_route_flap.py
Labels: Request for msft-202503 Branch

#18372 Skip bgp queue tests due to issue 18349
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 branch

#19670 [action] [PR:19578] [CACL]Increase timeout when waiting for original ACLs to be restored
  tests/cacl/test_cacl_function.py
Labels: automerge

#19665 [action] [PR:19567] [devices/eos]: Handle no auto option for link speed
  tests/common/devices/eos.py
Labels: automerge

#19663 [action] [PR:18372] Skip bgp queue tests due to issue 18349
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19669 [action] [PR:19486] skip test_cont_link_flap on SN2 and t1-lag due to issue 23121
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: automerge

#19679 [action] [PR:19646] Enhance deployment robustness with safe ovs-vsctl operations
  ansible/roles/vm_set/library/vm_topology.py
Labels: automerge

#19604 [test_container_checker] disable_memory_utilization
  tests/container_checker/test_container_checker.py
Labels: Request for 202505 branch

#19585 Fix qos/test_qos_sai.py for active-active dualtor
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: Request for 202411 branch, Request for 202505 branch

#19615 fix: test_bgp_router_id_set for lt2
  tests/bgp/test_bgp_router_id.py
Labels: Request for msft-202503 Branch, Request for 202505 branch

#19696 [action] [PR:19604] [test_container_checker] disable_memory_utilization
  tests/container_checker/test_container_checker.py
Labels: automerge

#19695 [action] [PR:19585] Fix qos/test_qos_sai.py for active-active dualtor
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
Labels: automerge

#19694 [action] [PR:19552] Add wait time to get neighbor mac for SRv6 tests
  tests/srv6/test_srv6_dataplane.py
Labels: automerge

#19472 Adding fixes for bfd_responder, it is giving a bunch of failures.
  ansible/roles/test/files/helpers/bfd_responder.py
Labels: Request for 202505 branch

#19699 [action] [PR:19655] [test_lag_member_forwarding] skip one LAG scenario
  tests/pc/test_lag_member_forwarding.py
Labels: automerge

#19698 [action] [PR:19499] Add additional SRv6 test skip conditions for TH5
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#18928 [action] [PR:16971] [TACACS] Increase tacacs server reachability check timeout
  tests/common/helpers/tacacs/tacacs_helper.py
Labels: automerge

#19701 [action] [PR:19472] Adding fixes for bfd_responder, it is giving a bunch of failures.
  ansible/roles/test/files/helpers/bfd_responder.py
Labels: automerge

#19693 [action] [PR:19119] Reduce the number of ifconfig calls made in add_topo
  ansible/roles/vm_set/library/vm_topology.py
Labels: automerge

#19719 [action] [PR:19171] Update the Topology for upper T2
  ansible/vars/topo_t2_single_node_max.yml
Labels: automerge

#19522 Add interface up check in function apply_dscp_cfg_setup
  tests/common/helpers/ptf_tests_helper.py
Labels: Request for 202505 branch

#19521 Update test test_bgp_prefix_tc1_suite
  tests/generic_config_updater/test_bgp_prefix.py
Labels: Request for 202505 branch

#19465 Skip SRv6 test_srv6_static_config.py::test_uDT46_config test on mellanox platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#17862 Add test skip based on the github issue: #6794
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202411 branch, Request for 202505 branch

#19732 [action] [PR:19449] Add debug info for announce_routes
  ansible/library/announce_routes.py
  ansible/roles/vm_set/tasks/announce_routes.yml
Labels: automerge

#19731 [action] [PR:19521] Update test test_bgp_prefix_tc1_suite
  tests/generic_config_updater/test_bgp_prefix.py
Labels: automerge

#19729 [action] [PR:19544] use safe_reboot in test_check_reset_status
  tests/restapi/test_restapi.py
Labels: automerge

#19487 Update trimming case due to qos update
  tests/packet_trimming/conftest.py
  tests/packet_trimming/constants.py
  tests/packet_trimming/test_packet_trimming.py
Labels: Request for msft-202412 Branch, Request for 202505 branch

#19529 Skipped Everflow IPv6 tests on Arista 7060CX due to SAI issue
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#18948 Fix `tests/snappi_tests/qos/files/packet_reorder_helper.py` failures
  tests/snappi_tests/qos/files/packet_reorder_helper.py
Labels: Request for 202505 branch

#19723 Enable ipv6 for deploy-mg
  ansible/config_sonic_basedon_testbed.yml
Labels: Request for msft-202405 Branch, Request for msft-202503 Branch, Request for 202505 branch

#19760 [action] [PR:19598] T2:snappi-tests:Add deviation modification for cisco-8000.
  tests/snappi_tests/pfcwd/files/pfcwd_basic_helper.py
Labels: automerge

#19756 [action] [PR:19715] Config counter poll interval to 100ms for test_link_local_ip.py
  tests/ip/link_local/test_link_local_ip.py
Labels: automerge

#19752 [action] [PR:19613] Add capability to handle when the counter has ',' in the value
  tests/ip/ip_util.py
Labels: automerge

#19706 [sonic-mgmt]Fix for fib/test_fib.py::test_ipinip_hash for active-active topology variants
  tests/fib/test_fib.py
Labels: Request for 202505 branch

#19188 Added detailed reason for assert failure for snmp
  tests/snmp/test_snmp_phy_entity.py
Labels: Request for 202505 branch

#19468 Added detailed reason for assert failure for qos
  tests/platform_tests/link_flap/test_link_flap.py
  tests/qos/test_pfc_counters.py
Labels: Request for 202505 branch

#19737 Skip PSUs listed under skip_modules
  tests/common/platform/device_utils.py
  tests/platform_tests/test_platform_info.py
Labels: Request for msft-202405 Branch, Approved for msft-202405 Branch, Cherry Pick Conflict_msft-202405, Request for 202505 branch, Approved for 202505 branch

#19781 [action] [PR:18948] Fix `tests/snappi_tests/qos/files/packet_reorder_helper.py` failures
  tests/snappi_tests/qos/files/packet_reorder_helper.py
Labels: automerge

#19778 [action] [PR:19748] cherry pick for the PR#17101
  tests/platform_tests/api/watchdog.yml
Labels: automerge
