Repository sonic-net/sonic-mgmt, pull requests merged in 2025-05, with the labels that each got.

#18044 Updating the BGP convergence cases to latest Snappi Api Model instead of Snappi_convergence module
  tests/common/snappi_tests/snappi_fixtures.py
  tests/gnmi/test_gnoi_system_grpc.py
  tests/snappi_tests/bgp/files/bgp_convergence_helper.py
  tests/snappi_tests/bgp/files/bgp_test_gap_helper.py
  tests/snappi_tests/bgp/test_bgp_convergence_performance.py
  tests/snappi_tests/bgp/test_bgp_local_link_failover.py
  tests/snappi_tests/bgp/test_bgp_remote_link_failover.py
  tests/snappi_tests/bgp/test_bgp_rib_in_capacity.py
  tests/snappi_tests/bgp/test_bgp_rib_in_convergence.py
  tests/snappi_tests/bgp/test_bgp_scalability.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Cherry Pick Conflict_msft-202405

#17882 fixing FixtureLookUp Error
  tests/snappi_tests/pfc/test_pfc_mixed_speed.py
  tests/snappi_tests/pfc/test_pfc_no_congestion_throughput.py
  tests/snappi_tests/pfc/test_pfc_port_congestion.py
  tests/snappi_tests/pfcwd/test_pfcwd_actions.py
  tests/snappi_tests/pfcwd/test_pfcwd_mixed_speed.py
  tests/snappi_tests/test_multidut_snappi.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#18168 Fix IndexError seen in voq/test_voq_ipfwd
  tests/voq/test_voq_ipfwd.py
Labels: Request for msft-202503 Branch, Approved for msft-202503 Branch

#18007 Improve ssh_remote_run_retry method stability by increase retry times.
  tests/common/helpers/tacacs/tacacs_helper.py
Labels: Request for 202411 branch

#18163 Fix parsing error and speedup testing in test_srv6_no_sid_blackhole
  tests/srv6/test_srv6_dataplane.py
Labels: Request for msft-202412 Branch

#18234 chore: fix parameterise mixed speed
  tests/snappi_tests/pfc/test_pfc_mixed_speed.py
  tests/snappi_tests/pfcwd/test_pfcwd_mixed_speed.py
Labels: Request for msft-202405 Branch

#15702 [test plan] Test plan for BGP scale test
  docs/testplan/BGP-Scale-Test.md
  docs/testplan/Img/t0-isolated-d2u254s.png
  docs/testplan/Img/t0-isolated-d2u510.png
  docs/testplan/Img/t1-isolated-d254u2s.png
  docs/testplan/Img/t1-isolated-d510u2.png
Labels: Request for msft-202412 Branch

#18256 [bgp-scale-test] reorder test cases to avoid device unisolation test effect other tests
  tests/bgp/test_ipv6_bgp_scale.py
Labels: Request for msft-202412 Branch

#18266 Skip T2 tests not applicable to disaggregated chassis
  tests/bgp/test_seq_idf_isolation.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202503 Branch

#18063 Considering voq inband routes in local route count for testNeighborMacNoPtf
  tests/arp/test_neighbor_mac_noptf.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202503 Branch

#17934 T2:Snappi Tests:Cisco-8000:Remove la_error ignore fixture, and fix the occurance of LA errors.
  tests/common/snappi_tests/snappi_fixtures.py
  tests/snappi_tests/conftest.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Cherry Pick Conflict_msft-202405

#18018 Snappi: Add the correct queue to select for test_snappi
  tests/snappi_tests/test_snappi.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#17966 Fixing the error seen while generating Snappi configuration for L3 interfaces and Vlan interfaces
  tests/common/snappi_tests/snappi_fixtures.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#18105 [snappi]: Changed order of reboot and pfcwd_disable for reboot cases in pfc_pause_lossless test
  tests/snappi_tests/files/helper.py
  tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py
Labels: Request for 202405 branch, Request for 202411 branch, Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503

#18197 [T2][ACL-test] Allow upstream and downstream rifs in the same namespace
  tests/acl/test_acl.py
Labels: Request for msft-202503 Branch, Approved for msft-202503 Branch

#18271 Handle multi-asic systems in `get_frr_daemon_memory_usage`
  tests/stress/test_stress_routes.py
Labels: t2 pr checker gap, Request for msft-202503 Branch, Approved for msft-202503 Branch

#18299 [dualtor][sniffer] Explicitly set listen ports
  tests/scripts/dual_tor_sniffer.py
Labels: Request for 202411 branch

#18251 Initialize two variables to prevent unbound variable error in upstream_links fixture
  tests/common/helpers/ptf_tests_helper.py
Labels: Request for msft-202412 Branch

#18278 Ensure iptables is restored to original state in kubesonic test
  tests/kubesonic/test_k8s_join_disjoin.py
Labels: Request for 202311 branch, Request for 202405 branch, Request for 202411 branch

#18176 skip 6 TCs for test_generic_hash.py for cisco-8000 (IP_PROTOCOL entropy)
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202411 branch

#18171 Skip warm reboot related case on Arista-7050CX3-32S-C28S4
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for 202405 branch

#18301 Fix PortChannel name matching in verify_attr_change to handle leading spaces
  tests/generic_config_updater/test_portchannel_interface.py
Labels: Request for 202405 branch, Request for 202411 branch

#18360 Support generating golden_config for topo ft2-64
  ansible/library/generate_golden_config_db.py
Labels: Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503

#18343 [dualtor][sniffer] Use python3
  tests/templates/dual_tor_sniffer.conf.j2
Labels: Request for 202411 branch

#18244 Use ip link instead of ifconfig to speed up
  ansible/roles/vm_set/library/vm_topology.py
Labels: Request for msft-202503 Branch

#18382 Skip bfd and mac check on LT2/FT2
  tests/common/plugins/sanity_check/__init__.py
Labels: Request for msft-202503 Branch

#18383 [show_techsupport] Remove asic dependency for show queue counters
  tests/show_techsupport/tech_support_cmds.py
Labels: Request for msft-202405 Branch

#17985 [tests_mark_conditions.yaml]: Skip GNMI/ZMQ test for isolated topology
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202412 Branch

#18289 Fix ACL tests for t1-isolated-d28/128
  tests/acl/test_acl.py
Labels: Request for msft-202412 Branch

#16766 Fix: Adjust wait time for check_orch_cpu_utilization and threshold for validate_redis_memory_increase
  tests/platform_tests/link_flap/link_flap_utils.py
  tests/platform_tests/link_flap/test_cont_link_flap.py
  tests/platform_tests/link_flap/test_link_flap.py
Labels: Request for 202411 branch

#18228 [Snappi] Skip warm and fast reboots for Nokia devices.
  tests/common/nokia_data.py
  tests/snappi_tests/files/helper.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#18215 Add PTF test parameter for ceos neighbor lacp multiplier
  ansible/roles/test/files/ptftests/py3/advanced-reboot.py
  tests/common/fixtures/advanced_reboot.py
  tests/conftest.py
Labels: Request for 202411 branch, Approved for 202411 branch

#18287 [dualtor io] Allow link down duplications on MLNX/Cisco
  tests/common/dualtor/data_plane_utils.py
  tests/common/dualtor/dual_tor_io.py
  tests/dualtor_io/test_link_failure.py
Labels: Request for 202411 branch

#17965 Fix the hardcoded interface issue in PTF
  tests/acl/test_acl.py
  tests/acl/test_stress_acl.py
  tests/common/dualtor/dual_tor_utils.py
  tests/common/plugins/ptfadapter/README.md
  tests/decap/test_subnet_decap.py
  tests/dualtor/test_ipinip.py
  tests/dualtor/test_tor_ecn.py
  tests/everflow/test_everflow_ipv6.py
  tests/everflow/test_everflow_per_interface.py
  tests/everflow/test_everflow_testbed.py
  tests/route/test_static_route.py
Labels: Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503

#18341 [route/test_route_perf] Support reading l3_alpm_template from config.bcm for TH5 platforms
  tests/route/test_route_perf.py
Labels: Request for msft-202412 Branch

#18350 disable pfcwd for lossy platforms in deploy-mg
  ansible/config_sonic_basedon_testbed.yml
  ansible/library/generate_golden_config_db.py
Labels: Request for msft-202412 Branch, Approved for msft-202412 Branch, Included in msft-202412 Branch, Cherry Pick Conflict_msft-202412

#18201 [port_utils]: Add SKU Mellanox-SN5640-C512S2
  ansible/group_vars/sonic/variables
  ansible/module_utils/port_utils.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#18419 Fix pretest failure on UpperSpineRouter when macsec is enabled
  tests/common/devices/sonic.py
Labels: Request for msft-202503 Branch

#18365 Add lt2 announce route
  ansible/library/announce_routes.py
Labels: Request for msft-202503 Branch

#18106 Regex correction for bgp commands in show_tech_cmds.py
  tests/show_techsupport/tech_support_cmds.py
Labels: Request for msft-202503 Branch, Approved for msft-202503 Branch

#18441 Update neighbor type for upperspinerouter
  tests/bgp/test_bgp_peer_shutdown.py
  tests/bgp/test_bgp_update_replication.py
  tests/bgp/test_bgp_update_timer.py
Labels: Request for msft-202503 Branch, Approved for msft-202503 Branch, Cherry Pick Conflict_msft-202503

#16972 Update the sflow test to pass on the t0 topo which does not have portchannel
  tests/sflow/test_sflow.py
Labels: Request for msft-202412 Branch

#17624 Add background traffic for test_pfc_pause_extra_lossless test
  tests/conftest.py
  tests/pfcwd/conftest.py
  tests/qos/test_tunnel_qos_remap.py
Labels: Request for 202411 branch

#18362 [action] [PR:18299] [dualtor][sniffer] Explicitly set listen ports
  tests/scripts/dual_tor_sniffer.py
Labels: automerge

#18385 [action] [PR:18343] [dualtor][sniffer] Use python3
  tests/templates/dual_tor_sniffer.conf.j2
Labels: automerge

#18393 Have Nokia-IXR7250E SKUs check for hearbeat lost with sup when Sup kernel panics
  tests/platform_tests/test_kdump.py
Labels: Request for msft-202405 Branch

#18367 [action] [PR:18176] skip 6 TCs for test_generic_hash.py for cisco-8000 (IP_PROTOCOL entropy)
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#18342 Recovery for inconsistent mux state issue
  tests/common/plugins/sanity_check/checks.py
Labels: Request for 202411 branch

#17700 Update the skip for the ipv6 everflow test
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#18403 [action] [PR:18370] Fix BFD multihop IPv6 test case issue
  ansible/roles/vm_set/library/vm_topology.py
Labels: automerge

#18486 [action] [PR:18465] [TESTGAP] Implement new test case to check the crm nexthop_group
  tests/crm/conftest.py
  tests/crm/test_crm_available.py
Labels: automerge

#18492 [action] [PR:18342] Recovery for inconsistent mux state issue
  tests/common/plugins/sanity_check/checks.py
Labels: automerge

#18276 [Mellanox] Remove the skip/xfail for the dualtor_io link failure test
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202411 branch, Request for 202505 branch

#18508 [action] [PR:18377] Avoid config reload in test_lldp_neighbor_post_orchagent_reboot to save ~4m of test execution time
  tests/lldp/test_lldp.py
Labels: automerge

#18515 [action] [PR:18485] Disable route check in snmp queue counter
  tests/snmp/test_snmp_queue_counters.py
Labels: automerge

#18227 New snappi model changes missing in couple fixtures.
  tests/snappi_tests/ecn/files/bpfabric_helper.py
  tests/snappi_tests/ecn/files/ecnhelper.py
  tests/snappi_tests/ecn/files/helper.py
  tests/snappi_tests/pfc/files/helper.py
Labels: Request for 202411 branch, Request for msft-202405 Branch

#18521 [action] [PR:18466] BFD check in sanity check was always reporting as false
  tests/common/plugins/sanity_check/checks.py
Labels: automerge

#17686 snmp: modify tests to also consider fans under fabric module
  tests/snmp/test_snmp_phy_entity.py
Labels: Chassis Test Gap

#18469 [action] [PR:18213] Use is_alive over isAlive for py3 threads
  ansible/roles/test/files/ptftests/py3/advanced-reboot.py
  ansible/roles/test/files/ptftests/py3/wr_arp.py
Labels: automerge

#18298 [action] [PR:17878] [watchdog] Add the x86_64-8101_32fh_o_c01-r0 config to the platform_tests/api/watchdog.yml
  tests/platform_tests/api/watchdog.yml
Labels: automerge

#18425 feat: add lt2 p32o64 hwsku
  ansible/generate_topo.py
  ansible/library/announce_routes.py
  ansible/module_utils/port_utils.py
  ansible/roles/eos/templates/lt2-o128-leaf.j2
  ansible/roles/eos/templates/lt2-o128-spine.j2
  ansible/roles/eos/templates/lt2-p32o64-leaf.j2
  ansible/roles/eos/templates/lt2-p32o64-spine.j2
  ansible/templates/minigraph_meta.j2
  ansible/templates/minigraph_png.j2
  ansible/templates/topo_lt2_p32o64.j2
  ansible/vars/topo_lt2-o128.yml
  ansible/vars/topo_lt2-p32o64.yml
  ansible/veos
Labels: Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503

#18514 [M1] Adapt ACL test for M1 topo
  tests/acl/test_acl.py
Labels: Request for 202505 branch

#18511 [M1] Update announce routes for M1 topo
  ansible/library/announce_routes.py
  ansible/vars/topo_m1-48.yml
Labels: Request for 202505 branch

#18516 [M1] Collect all upstream ports for ACL test
  tests/acl/test_acl.py
  tests/common/helpers/constants.py
  tests/common/utilities.py
Labels: Request for 202505 branch

#18539 Skipped IPv6 Everflow tests on virtual switch to speed up PR test execution
  tests/everflow/everflow_test_utilities.py
  tests/everflow/test_everflow_ipv6.py
  tests/everflow/test_everflow_per_interface.py
  tests/everflow/test_everflow_testbed.py
Labels: Request for 202505 branch

#18224 update ptf subnet to /22
  ansible/group_vars/vm_host/main.yml
  ansible/templates/topo_t0-isolated.j2
  ansible/templates/topo_t1-isolated.j2
  ansible/vars/topo_t0-isolated-d16u16s1.yml
  ansible/vars/topo_t0-isolated-d16u16s2.yml
  ansible/vars/topo_t0-isolated-d32u32s2.yml
  ansible/vars/topo_t1-isolated-d28u1.yml
  ansible/vars/topo_t1-isolated-d56u2.yml
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18545 [generate_golden_config]: Fix wrong buffer mode for lossy platform
  ansible/library/generate_golden_config_db.py
Labels: Request for msft-202412 Branch

#18537 Disable kill_process test for rewrite.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for 202505 branch

#18563 [action] [PR:18537] Disable kill_process test for rewrite.
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#17534 Change max to min in pfc_gen_t2.py
  tests/common/helpers/pfc_gen_t2.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Request for 202505 branch

#18389 For Cisco platform keeping the traffic bandwidth < 100% of linerate
  tests/snappi_tests/files/helper.py
  tests/snappi_tests/pfc/test_pfc_no_congestion_throughput.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Request for 202505 branch

#17937 Disable voq watchdog in qos_sai script
  tests/qos/qos_sai_base.py
Labels: Request for 202505 branch

#18359 Changes to accommodate Mixed mode testing
  tests/common/snappi_tests/snappi_fixtures.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Request for 202505 branch

#18523 fix test_snappi_multidut.py
  tests/snappi_tests/test_multidut_snappi.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Request for 202505 branch

#18531 [Snappi]: Pass/fail criteria for pfc m2o testcase have thinner margins causing intermittent failures.
  tests/snappi_tests/pfc/files/m2o_fluctuating_lossless_helper.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Request for 202505 branch

#17858 T2:pfcwd:Fix the asic_id check - It fails for asic0
  tests/pfcwd/conftest.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Request for 202505 branch

#18575 [action] [PR:17858] T2:pfcwd:Fix the asic_id check - It fails for asic0
  tests/pfcwd/conftest.py
Labels: automerge

#18574 [action] [PR:18531] [Snappi]: Pass/fail criteria for pfc m2o testcase have thinner margins causing intermittent failures.
  tests/snappi_tests/pfc/files/m2o_fluctuating_lossless_helper.py
Labels: automerge

#18573 [action] [PR:18523] fix test_snappi_multidut.py
  tests/snappi_tests/test_multidut_snappi.py
Labels: automerge

#18572 [action] [PR:18359] Changes to accommodate Mixed mode testing
  tests/common/snappi_tests/snappi_fixtures.py
Labels: automerge

#18571 [action] [PR:17937] Disable voq watchdog in qos_sai script
  tests/qos/qos_sai_base.py
Labels: automerge

#18569 [action] [PR:18389] For Cisco platform keeping the traffic bandwidth < 100% of linerate
  tests/snappi_tests/files/helper.py
  tests/snappi_tests/pfc/test_pfc_no_congestion_throughput.py
Labels: automerge

#18568 [action] [PR:17534] Change max to min in pfc_gen_t2.py
  tests/common/helpers/pfc_gen_t2.py
Labels: automerge

#18543 [action] [PR:18516] [M1] Collect all upstream ports for ACL test
  tests/acl/test_acl.py
  tests/common/helpers/constants.py
  tests/common/utilities.py
Labels: automerge

#18542 [action] [PR:18511] [M1] Update announce routes for M1 topo
  ansible/library/announce_routes.py
  ansible/vars/topo_m1-48.yml
Labels: automerge

#18520 [action] [PR:18227] New snappi model changes missing in couple fixtures.
  tests/snappi_tests/ecn/files/bpfabric_helper.py
  tests/snappi_tests/ecn/files/ecnhelper.py
  tests/snappi_tests/ecn/files/helper.py
  tests/snappi_tests/pfc/files/helper.py
Labels: automerge

#18510 [action] [PR:17917] Readme file for running snappi-tests
  tests/snappi_tests/README.md
Labels: automerge

#18580 [action] [PR:18548] Fix gcu test_bgp_prefix conditional mark condition logical operator incorrect issue
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#18500 [PR test] Enable PR test for feature branches
  azure-pipelines.yml
Labels: Request for 202505 branch

#18467 [action] [PR:18465] [TESTGAP] Implement new test case to check the crm nexthop_group
  tests/crm/conftest.py
  tests/crm/test_crm_available.py
Labels: automerge

#18589 Make impacted area logic branch-aware
  .azure-pipelines/impacted_area_testing/get-impacted-area.yml
  azure-pipelines.yml
Labels: Request for 202505 branch

#17836 [PR#17130] - Everflow - Changes for VOQ single-dut multi-asic
  tests/everflow/everflow_test_utilities.py
Labels: Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503, Created PR to msft-202503 Branch

#18561 MIGSMSFT-848 adjust port index to avoid duplicate queues for same dst port
  tests/qos/files/cisco/qos_param_generator.py
Labels: Request for 202411 branch, Request for 202505 branch

#18605 [action] [PR:18517] [CRM_AVAILABLE] To add delay when read the CRM info
  tests/crm/conftest.py
Labels: automerge

#18525 [action] [PR:17749] To fix the issue that ARM platform was skipped for bmp test unexpectedly
  tests/bmp/conftest.py
Labels: automerge

#18607 [action] [PR:18561] MIGSMSFT-848 adjust port index to avoid duplicate queues for same dst port
  tests/qos/files/cisco/qos_param_generator.py
Labels: automerge

#18152 update t1-isolated-d56u2 topo with port-channel
  ansible/generate_topo.py
  ansible/templates/topo_t1-isolated-v6.j2
  ansible/templates/topo_t1-isolated.j2
  ansible/vars/topo_t1-isolated-d56u2.yml
  ansible/vars/topo_t1-isolated-v6-d56u2.yml
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18600 update quicksilver TH5-512 port name
  ansible/module_utils/port_utils.py
Labels: Request for msft-202412 Branch

#18626 [action] [PR:18613] Skip bgp_port_disable test in 202505 branch
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#18476 [test_orchagent_slb] Enable `exabgp` debug mode and collect logs
  ansible/library/exabgp.py
  tests/common/helpers/bgp.py
  tests/dualtor/test_orchagent_slb.py
Labels: Request for 202411 branch, Request for 202505 branch

#18603 Refine sanity check bgp recover
  tests/common/plugins/sanity_check/checks.py
Labels: Request for 202305 branch, Request for 202311 branch, Request for 202405 branch, Request for 202411 branch, Request for 202505 branch

#18494 [vlan][dhcp_relay] Using config_reload to recover multi-vlan for dhcpv6_relay test
  tests/common/fixtures/split_vlan.py
Labels: Request for 202505 branch

#18636 [action] [PR:18541] [bgp] Add m0/mx mark to test_bgp_stress_link_flap
  tests/bgp/test_bgp_stress_link_flap.py
Labels: automerge

#18635 [action] [PR:18494] [vlan][dhcp_relay] Using config_reload to recover multi-vlan for dhcpv6_relay test
  tests/common/fixtures/split_vlan.py
Labels: automerge

#18633 [action] [PR:18603] Refine sanity check bgp recover
  tests/common/plugins/sanity_check/checks.py
Labels: automerge

#18648 [action] [PR:18517] [CRM_AVAILABLE] To add delay when read the CRM info
  tests/crm/conftest.py
Labels: automerge

#18644 [action] [PR:18232] add dualtor test test_mux_forwarding_state_consistency
  tests/dualtor_mgmt/test_grpc_periodical_sync.py
Labels: automerge

#18639 [action] [PR:16972] Update the sflow test to pass on the t0 topo which does not have portchannel
  tests/sflow/test_sflow.py
Labels: automerge

#18649 [action] [PR:18545] [generate_golden_config]: Fix wrong buffer mode for lossy platform
  ansible/library/generate_golden_config_db.py
Labels: automerge

#18642 [action] [PR:17836] [PR#17130] - Everflow - Changes for VOQ single-dut multi-asic
  tests/everflow/everflow_test_utilities.py
Labels: automerge

#18443 Fix decap test on FT2 topo
  ansible/roles/test/files/ptftests/py3/IP_decap_test.py
Labels: Request for msft-202503 Branch

#18647 [action] [PR:18476] [test_orchagent_slb] Enable `exabgp` debug mode and collect logs
  ansible/library/exabgp.py
  tests/common/helpers/bgp.py
  tests/dualtor/test_orchagent_slb.py
Labels: automerge

#18388 Snappi: T0/T1/T2: Convert all traffic to static routed destinations in snappi scripts.
  tests/common/snappi_tests/snappi_fixtures.py
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossy_helper.py
  tests/snappi_tests/pfcwd/files/pfcwd_basic_helper.py
  tests/snappi_tests/pfcwd/files/pfcwd_burst_storm_helper.py
  tests/snappi_tests/pfcwd/files/pfcwd_multi_node_helper.py
  tests/snappi_tests/pfcwd/files/pfcwd_runtime_traffic_helper.py
  tests/snappi_tests/pfcwd/test_pfcwd_actions.py
  tests/snappi_tests/qos/files/packet_reorder_helper.py
  tests/snappi_tests/test_multidut_snappi.py
  tests/snappi_tests/test_snappi.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Cherry Pick Conflict_msft-202405, Request for 202505 branch

#18665 [action] [PR:18388] Snappi: T0/T1/T2: Convert all traffic to static routed destinations in snappi scripts.
  tests/common/snappi_tests/snappi_fixtures.py
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossy_helper.py
  tests/snappi_tests/pfcwd/files/pfcwd_basic_helper.py
  tests/snappi_tests/pfcwd/files/pfcwd_burst_storm_helper.py
  tests/snappi_tests/pfcwd/files/pfcwd_multi_node_helper.py
  tests/snappi_tests/pfcwd/files/pfcwd_runtime_traffic_helper.py
  tests/snappi_tests/pfcwd/test_pfcwd_actions.py
  tests/snappi_tests/qos/files/packet_reorder_helper.py
  tests/snappi_tests/test_multidut_snappi.py
  tests/snappi_tests/test_snappi.py
Labels: automerge

#18462 [action] [PR:16574] Fix test_sysuptime conversion error
  tests/telemetry/test_telemetry.py
Labels: automerge

#18675 [dualtor-io] Validate and recover active-active setup
  tests/common/dualtor/dual_tor_utils.py
  tests/dualtor_io/test_normal_op.py
Labels: Request for 202411 branch, Request for 202505 branch

#18588 [Mellanox] Fix psu_line_pattern for mellanox devices
  tests/common/platform/device_utils.py
Labels: Request for 202505 branch

#18695 [action] [PR:18674] [dualtor] Fix loganalyzer not exist issue
  tests/dualtor_io/conftest.py
Labels: automerge

#18694 [action] [PR:18286] Update PSU testcases to align with new format
  tests/common/platform/device_utils.py
Labels: automerge

#18698 [action] [PR:18676] [wol] refine test logs
  tests/wol/test_wol.py
Labels: automerge

#18696 [action] [PR:18675] [dualtor-io] Validate and recover active-active setup
  tests/common/dualtor/dual_tor_utils.py
  tests/dualtor_io/test_normal_op.py
Labels: automerge

#18697 [action] [PR:18588] [Mellanox] Fix psu_line_pattern for mellanox devices
  tests/common/platform/device_utils.py
Labels: automerge

#17198 [action] [PR:17180] Fix fixture invocation order in qos_sai_base.py to prevent teardown failure.
  tests/qos/qos_sai_base.py
Labels: automerge

#18664 [action] [PR:18085] Static Route and Cisco ECN test changes
  tests/common/snappi_tests/snappi_fixtures.py
Labels: automerge

#18459 [DT2] Enhance fib test to support FT2
  ansible/roles/test/files/ptftests/fib_test.py
  ansible/roles/test/files/ptftests/py3/hash_test.py
  tests/fib/test_fib.py
Labels: Request for msft-202503 Branch

#18622 [DT2] Enhance everflow test on LT2/FT2 topology
  tests/common/helpers/constants.py
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/everflow/everflow_test_utilities.py
  tests/everflow/test_everflow_ipv6.py
  tests/everflow/test_everflow_testbed.py
Labels: Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503

#18576 feat: add support for dynamic ports
  tests/snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py
Labels: Request for 202505 branch

#18699 fix: correct DUT variable name in startup tsa pretest
  tests/test_pretest.py
Labels: Request for msft-202405 Branch, Request for 202505 branch

#18710 [action] [PR:18576] feat: add support for dynamic ports
  tests/snappi_tests/pfcwd/test_pfcwd_a2a_with_snappi.py
Labels: automerge

#18709 [action] [PR:18564] T2:snappi_tests:Add a fixture to disable voq watchdog, use it in pfc scripts.
  tests/common/cisco_data.py
  tests/qos/qos_sai_base.py
  tests/snappi_tests/cisco/helper.py
  tests/snappi_tests/files/helper.py
  tests/snappi_tests/pfc/test_global_pause_with_snappi.py
  tests/snappi_tests/pfc/test_lossless_response_to_external_pause_storms.py
  tests/snappi_tests/pfc/test_lossless_response_to_throttling_pause_storms.py
  tests/snappi_tests/pfc/test_m2o_fluctuating_lossless.py
  tests/snappi_tests/pfc/test_m2o_oversubscribe_lossless.py
  tests/snappi_tests/pfc/test_m2o_oversubscribe_lossless_lossy.py
  tests/snappi_tests/pfc/test_m2o_oversubscribe_lossy.py
  tests/snappi_tests/pfc/test_pfc_mixed_speed.py
  tests/snappi_tests/pfc/test_pfc_no_congestion_throughput.py
  tests/snappi_tests/pfc/test_pfc_pause_lossless_with_snappi.py
  tests/snappi_tests/pfc/test_pfc_pause_lossy_with_snappi.py
  tests/snappi_tests/pfc/test_pfc_pause_response_with_snappi.py
  tests/snappi_tests/pfc/test_pfc_pause_unset_bit_enable_vector.py
  tests/snappi_tests/pfc/test_pfc_pause_zero_mac.py
  tests/snappi_tests/pfc/test_pfc_port_congestion.py
  tests/snappi_tests/pfc/test_tx_drop_counter_with_snappi.py
  tests/snappi_tests/pfc/test_valid_pfc_frame_with_snappi.py
  tests/snappi_tests/pfc/test_valid_src_mac_pfc_frame.py
Labels: automerge

#18686 [topo file] Fix pt0 announce routes in bgp scale topologies
  ansible/library/announce_routes.py
  ansible/vars/topo_t0-isolated-d2u254.yml
  ansible/vars/topo_t0-isolated-d2u254s1.yml
  ansible/vars/topo_t0-isolated-d2u254s2.yml
  ansible/vars/topo_t0-isolated-d2u510.yml
  ansible/vars/topo_t0-isolated-d2u510s2.yml
Labels: Request for msft-202412 Branch

#18680 [test case] Support multiple servers testbed in bgp scale test
  tests/bgp/test_ipv6_bgp_scale.py
Labels: Request for msft-202412 Branch

#18711 [action] [PR:18699] fix: correct DUT variable name in startup tsa pretest
  tests/test_pretest.py
Labels: automerge

#18718 [action] [PR:18674] [dualtor] Fix loganalyzer not exist issue
  tests/dualtor_io/conftest.py
Labels: automerge

#18717 [action] [PR:18472] Enable the test_ipinip_hash for T0 topo
  tests/fib/test_fib.py
Labels: automerge

#18716 [action] [PR:18675] [dualtor-io] Validate and recover active-active setup
  tests/common/dualtor/dual_tor_utils.py
  tests/dualtor_io/test_normal_op.py
Labels: automerge

#18723 [action] [PR:18666] [dualtor] Fix `test_orchagent_slb`
  tests/dualtor/test_orchagent_slb.py
Labels: automerge

#18727 [M1] Adapt test_route_flap to M1 topo
  tests/conftest.py
  tests/route/test_route_flap.py
Labels: Request for 202505 branch

#18728 [action] [PR:18727] [M1] Adapt test_route_flap to M1 topo
  tests/conftest.py
  tests/route/test_route_flap.py
Labels: automerge
