Repository sonic-net/sonic-mgmt, pull requests merged in 2025-06, with the labels that each got.

#18659 Update cEOS configuration to use next-hop-self
  ansible/roles/eos/tasks/ceos.yml
  ansible/roles/eos/templates/dpu-tor.j2
  ansible/roles/eos/templates/m0-mx.j2
  ansible/roles/eos/templates/t0-8-lag-leaf.j2
  ansible/roles/eos/templates/t0-backend-leaf.j2
  ansible/roles/eos/templates/t0-leaf-lag-2.j2
  ansible/roles/eos/templates/t0-leaf.j2
  ansible/roles/eos/templates/t0-mclag-leaf.j2
  ansible/roles/eos/templates/t0-v6-leaf.j2
  ansible/roles/eos/templates/t1-28-lag-spine.j2
  ansible/roles/eos/templates/t1-28-lag-tor.j2
  ansible/roles/eos/templates/t1-56-lag-tor.j2
  ansible/roles/eos/templates/t1-64-lag-tor.j2
  ansible/roles/eos/templates/t1-8-lag-spine.j2
  ansible/roles/eos/templates/t1-8-lag-tor.j2
  ansible/roles/eos/templates/t1-backend-tor.j2
  ansible/roles/eos/templates/t1-lag-spine.j2
  ansible/roles/eos/templates/t1-lag-tor.j2
  ansible/roles/eos/templates/t1-smartswitch-ha-spine.j2
  ansible/roles/eos/templates/t1-smartswitch-ha-tor.j2
  ansible/roles/eos/templates/t2-core.j2
  ansible/roles/eos/templates/t2-leaf.j2
  ansible/roles/eos/templates/t2-vs-core.j2
  ansible/roles/eos/templates/t2-vs-leaf.j2
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#18669 [BGP Tests] Enable Tests for LT2 and FT2 Topologies
  tests/bgp/conftest.py
Labels: Included in msft-202503 Branch, Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503

#18743 Enhance deploy-minigraph ansible playbook
  ansible/config_sonic_basedon_testbed.yml
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18081 Fix for lag port selection in test_bgp_update_timer.py
  tests/bgp/conftest.py
Labels: Request for msft-202503 Branch

#18734 [ceos_ensure_reachable.yml]: Fix wrong host of ceos
  ansible/roles/eos/tasks/ceos_ensure_reachable.yml
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18749 [action] [PR:18743] Enhance deploy-minigraph ansible playbook
  ansible/config_sonic_basedon_testbed.yml
Labels: automerge

#18756 [action] [PR:17248] Align the test_bgp_suppress_fib for the topo which does not have port channel
  tests/bgp/test_bgp_suppress_fib.py
  tests/bgp/vrf_config_db.j2
Labels: automerge

#18755 [action] [PR:18733] [CRM AVAILABLE] To enhance the crm tests for TD3 and Cisco devices
  tests/crm/conftest.py
  tests/crm/test_crm_available.py
Labels: automerge

#18758 [dualtor-io] fix dualtor sniffer start slow issue
  tests/scripts/dual_tor_sniffer.py
Labels: Request for 202411 branch, Request for 202505 branch

#18719 chore: update announce routes script to match T2
  ansible/library/announce_routes.py
Labels: Request for msft-202503 Branch, Request for 202505 branch

#18706 Enable sequential IDF isolation test on LowerSpineRouter
  tests/bgp/test_seq_idf_isolation.py
Labels: Request for msft-202503 Branch

#18776 [action] [PR:18758] [dualtor-io] fix dualtor sniffer start slow issue
  tests/scripts/dual_tor_sniffer.py
Labels: automerge

#18783 [action] [PR:18758] [dualtor-io] fix dualtor sniffer start slow issue
  tests/scripts/dual_tor_sniffer.py
Labels: automerge

#18765 [action] [PR:18708] Fix test_stress_acl uplinks for t1-isolated-d128
  tests/acl/test_stress_acl.py
Labels: automerge

#18762 [action] [PR:18707] xfail test_bgp_route_with_suppress vrf testing for TH5
  tests/bgp/test_bgp_suppress_fib.py
Labels: automerge

#18761 [action] [PR:18733] [CRM AVAILABLE] To enhance the crm tests for TD3 and Cisco devices
  tests/crm/conftest.py
  tests/crm/test_crm_available.py
Labels: automerge

#18763 [action] [PR:18685] [ceos]: Optimize CEOS image by disabling RPM service
  ansible/roles/vm_set/templates/ceos_dockerfile.j2
Labels: automerge

#18331 Update qos sai tests due to splitting buffer queue configuration for lossy queue only device
  tests/qos/qos_sai_base.py
Labels: Request for 202505 branch

#18804 [action] [PR:18331] Update qos sai tests due to splitting buffer queue configuration for lossy queue only device
  tests/qos/qos_sai_base.py
Labels: automerge

#18793 chore: disable default dynamic var snappi fallback
  tests/conftest.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Cherry Pick Conflict_msft-202405, Request for 202505 branch

#18411 Skip fast / warm reboot testcases in snappi test suite
  tests/snappi_tests/files/helper.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Request for 202505 branch

#18265 Changing Loss Percentage in test_m2o_oversubscribe_lossy.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossy_helper.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Request for 202505 branch

#18591 Multiple test streams for Cisco8000
  tests/snappi_tests/files/helper.py
  tests/snappi_tests/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossy_helper.py
  tests/snappi_tests/pfcwd/files/pfcwd_basic_helper.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Cherry Pick Conflict_msft-202405, Request for 202505 branch

#18811 Change t1-isolated-d28 to d32 in ACL tests
  tests/acl/test_acl.py
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18817 [action] [PR:18591] Multiple test streams for Cisco8000
  tests/snappi_tests/files/helper.py
  tests/snappi_tests/pfc/files/lossless_response_to_external_pause_storms_helper.py
  tests/snappi_tests/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
  tests/snappi_tests/pfc/files/m2o_fluctuating_lossless_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossy_helper.py
  tests/snappi_tests/pfcwd/files/pfcwd_basic_helper.py
Labels: automerge

#18819 [action] [PR:18805] Add snmp lldp state check after config_reload
  tests/snmp/test_snmp_link_local.py
Labels: automerge

#18818 [action] [PR:18592] Clear PFC counter after detecting PFC storm
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/pfcwd/files/pfcwd_actions_helper.py
Labels: automerge

#18671 [ACL] Include service port into upstream neighbors
  tests/acl/test_acl.py
  tests/acl/test_stress_acl.py
  tests/common/helpers/constants.py
  tests/common/helpers/ptf_tests_helper.py
Labels: Request for 202411 branch, Request for 202505 branch

#18827 [action] [PR:18821] [pktgen] Skip test_pktgen in m0/mx/m1
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#18825 [action] [PR:18787] Xfail test_dir_bcast.py due to known issue on Broadcom platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#18830 [action] [PR:18714] Restore configuration after vxlan module
  tests/vxlan/conftest.py
  tests/vxlan/test_vxlan_bfd_tsa.py
  tests/vxlan/test_vxlan_ecmp.py
Labels: automerge

#18802 Fix port mapping for new 4280 hwskus
  ansible/module_utils/port_utils.py
Labels: Request for 202405 branch, Request for 202411 branch, Request for 202505 branch

#18829 [dualtor-io] Fix `test_active_link_admin_down_config_reload_link_up_downstream_standby` on Cisco/MLNX
  tests/dualtor_io/test_link_failure.py
Labels: Request for 202411 branch, Request for 202505 branch

#18828 [dualtor-io] Fix duplication merge condition
  tests/common/dualtor/data_plane_utils.py
Labels: Request for 202411 branch, Request for 202505 branch

#18816 [action] [PR:18265] Changing Loss Percentage in test_m2o_oversubscribe_lossy.py
  tests/snappi_tests/pfc/files/m2o_oversubscribe_lossy_helper.py
Labels: automerge

#18813 [action] [PR:18793] chore: disable default dynamic var snappi fallback
  tests/conftest.py
Labels: automerge

#18376 Update test_config_interface_state in iface_namingmode
  tests/iface_namingmode/test_iface_namingmode.py
Labels: Request for 202505 branch

#18123 Add ASIC DB verification for SRv6 SID entries
  tests/srv6/srv6_utils.py
  tests/srv6/test_srv6_dataplane.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 branch

#17701 Fixed power off reboot test to support multiple outlets
  tests/platform_tests/test_power_off_reboot.py
Labels: Request for 202405 branch, Request for 202411 branch, Request for msft-202412 Branch

#18091 [Snappi] - Test Changes to support Infra changes for dynamic port selection from the setup replacing variables.py file
  tests/snappi_tests/pfc/test_lossless_response_to_throttling_pause_storms.py
  tests/snappi_tests/pfc/test_m2o_fluctuating_lossless.py
  tests/snappi_tests/pfc/test_m2o_oversubscribe_lossless.py
  tests/snappi_tests/pfc/test_m2o_oversubscribe_lossless_lossy.py
  tests/snappi_tests/pfc/test_m2o_oversubscribe_lossy.py
Labels: Request for 202505 branch

#18143 Use ceos 4.32.5M as default ceos image version
  ansible/group_vars/vm_host/ceos.yml
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18857 [action] [PR:18414] [Snappi][Documentation] Dynamic vs Static port selection documentation.
  tests/snappi_tests/static_vs_dynamic_port_selection.md
Labels: automerge

#18858 [action] [PR:18091] [Snappi] - Test Changes to support Infra changes for dynamic port selection from the setup replacing variables.py file
  tests/snappi_tests/pfc/test_lossless_response_to_throttling_pause_storms.py
  tests/snappi_tests/pfc/test_m2o_fluctuating_lossless.py
  tests/snappi_tests/pfc/test_m2o_oversubscribe_lossless.py
  tests/snappi_tests/pfc/test_m2o_oversubscribe_lossless_lossy.py
  tests/snappi_tests/pfc/test_m2o_oversubscribe_lossy.py
Labels: automerge

#18862 [action] [PR:18470] [COPP] Check ptf reachability before running the copp tests
  tests/copp/test_copp.py
Labels: automerge

#18861 [action] [PR:18143] Use ceos 4.32.5M as default ceos image version
  ansible/group_vars/vm_host/ceos.yml
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#18870 [dualtor-aa] Add dualtor-aa support to `test_nvgre_hash`
  tests/fib/test_fib.py
Labels: Request for 202411 branch, Request for 202505 branch

#18775 Add 128 SRv6 sids support
  tests/common/helpers/srv6_helper.py
  tests/srv6/conftest.py
  tests/srv6/srv6_utils.py
  tests/srv6/test_srv6_dataplane.py
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 branch

#18889 [action] [PR:18870] [dualtor-aa] Add dualtor-aa support to `test_nvgre_hash`
  tests/fib/test_fib.py
Labels: automerge

#18864 [action] [PR:18672] Update test_iface_namingmode.py
  tests/iface_namingmode/test_iface_namingmode.py
Labels: automerge

#18826 Add t1-isolated-d56u1-lag into support list.
  ansible/roles/eos/templates/t1-isolated-d56u1-lag-spine.j2
  ansible/roles/eos/templates/t1-isolated-d56u1-lag-tor.j2
  ansible/roles/eos/templates/t1-isolated-v6-d56u1-lag-spine.j2
  ansible/roles/eos/templates/t1-isolated-v6-d56u1-lag-tor.j2
  ansible/veos
  tests/acl/test_stress_acl.py
  tests/qos/qos_sai_base.py
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18852 advertise tor default route for t1-isolated-d128 only
  ansible/library/announce_routes.py
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18773 Fix UnboundLocalError in portchannel_to_vlan fixture
  tests/common/helpers/portchannel_to_vlan.py
Labels: Request for 202411 branch

#18336 [test_bgp_stress_link_flap] update completeness_level for bgp link flap case
  tests/bgp/test_bgp_stress_link_flap.py
Labels: Request for 202505 branch

#18766 [DualToR] enforce same loopback ip and drop bgp pkts on loopback1 for dualtor
  ansible/vars/topo_cable-test.yml
  ansible/vars/topo_dualtor-120.yml
  ansible/vars/topo_dualtor-56.yml
  ansible/vars/topo_dualtor-64-breakout.yml
  ansible/vars/topo_dualtor-64.yml
  ansible/vars/topo_dualtor-aa-120.yml
  ansible/vars/topo_dualtor-aa-56.yml
  ansible/vars/topo_dualtor-aa-64-breakout.yml
  ansible/vars/topo_dualtor-aa-64.yml
  ansible/vars/topo_dualtor-aa.yml
  ansible/vars/topo_dualtor-mixed-120.yml
  ansible/vars/topo_dualtor-mixed-56.yml
  ansible/vars/topo_dualtor-mixed.yml
  ansible/vars/topo_dualtor.yml
  tests/cacl/test_cacl_application.py
Labels: Request for 202411 branch, Request for 202505 branch

#18877 [bgp] Fix test_ipv6_bgp_scale fails in multi-server
  ansible/library/announce_routes.py
  tests/bgp/test_ipv6_bgp_scale.py
Labels: Request for msft-202412 Branch

#18693 xfail test_iface_naming_mode.py::test_config_interface_speed
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18940 [action] [PR:18894] Xfail route perf test with issue for high failure rate in PR test
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#18942 [action] [PR:18011] decrease max system date const in sonic clock test
  tests/clock/test_clock.py
Labels: automerge

#17816 Retry SSH connection if fails after reboot, with logging for easier debugging.
  tests/common/reboot.py
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18900 Increase SSH Wait Timeout After DUT Reboot in SN5640 Platform Tests
  tests/platform_tests/test_link_down.py
Labels: Request for msft-202412 Branch, Approved for msft-202412 Branch, Request for 202505 branch

#18929 [202411] Support Ubuntu 24 server in KVM
  ansible/ansible.cfg
  ansible/devutil/conn_graph_helper.py
  ansible/health_checker.py
  ansible/plugins/connection/multi_passwd_ssh.py
  ansible/recover_server.py
  ansible/restart_nightly_ptf.py
  ansible/roles/vm_set/tasks/control_mux_simulator.yml
  ansible/roles/vm_set/tasks/docker.yml
  ansible/roles/vm_set/tasks/main.yml
  tests/arp/test_unknown_mac.py
  tests/common/cache/facts_cache.py
  tests/common/connections/base_console_conn.py
  tests/common/connections/ssh_console_conn.py
  tests/common/connections/telnet_console_conn.py
  tests/common/devices/duthosts.py
  tests/common/helpers/platform_api/scripts/platform_api_server.py
  tests/ssh/conftest.py
Labels: Request for 202012 branch, Request for 202311 branch, Request for 202405 branch

#18897 [sonic-mgmt] Fix snappi_tests/test_snappi.py failure
  tests/snappi_tests/test_snappi.py
Labels: Request for msft-202405 Branch, Request for 202505 branch

#18918 [action] [PR:18795] fix memory_utilization teardown failure
  tests/common/plugins/memory_utilization/__init__.py
  tests/common/plugins/memory_utilization/memory_utilization.py
Labels: automerge

#18979 [action] [PR:18900] Increase SSH Wait Timeout After DUT Reboot in SN5640 Platform Tests
  tests/platform_tests/test_link_down.py
Labels: automerge

#18912 [action] [PR:18766] [DualToR] enforce same loopback ip and drop bgp pkts on loopback1 for dualtor
  ansible/vars/topo_cable-test.yml
  ansible/vars/topo_dualtor-120.yml
  ansible/vars/topo_dualtor-56.yml
  ansible/vars/topo_dualtor-64-breakout.yml
  ansible/vars/topo_dualtor-64.yml
  ansible/vars/topo_dualtor-aa-120.yml
  ansible/vars/topo_dualtor-aa-56.yml
  ansible/vars/topo_dualtor-aa-64-breakout.yml
  ansible/vars/topo_dualtor-aa-64.yml
  ansible/vars/topo_dualtor-aa.yml
  ansible/vars/topo_dualtor-mixed-120.yml
  ansible/vars/topo_dualtor-mixed-56.yml
  ansible/vars/topo_dualtor-mixed.yml
  ansible/vars/topo_dualtor.yml
  tests/cacl/test_cacl_application.py
Labels: automerge

#18993 [action] [PR:18835] voqWD disable/enable for PFCWD scripts
  tests/common/snappi_tests/traffic_generation.py
  tests/snappi_tests/files/helper.py
  tests/snappi_tests/pfcwd/test_pfcwd_actions.py
  tests/snappi_tests/pfcwd/test_pfcwd_mixed_speed.py
Labels: automerge

#18988 [action] [PR:18540] Fix BGP scale test compare routes
  tests/bgp/test_ipv6_bgp_scale.py
Labels: automerge

#18984 [action] [PR:18693] xfail test_iface_naming_mode.py::test_config_interface_speed
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#18982 [action] [PR:18910] Extend bgp command check to allow multipath routes and "best" routes
  tests/bgp/test_bgp_command.py
Labels: automerge

#18968 [action] [PR:17420] Increase GCUTIMEOUT value for nokia-armhf platforms
  tests/common/gu_utils.py
Labels: automerge

#18976 [isolated-topology] Add ceos config template for PT0 in isolated topology
  ansible/roles/eos/templates/t0-isolated-d2u254s1-tor.j2
  ansible/roles/eos/templates/t0-isolated-d2u254s2-tor.j2
  ansible/roles/eos/templates/t0-isolated-d2u510s2-tor.j2
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18981 [action] [PR:18557] [Fix]: Increasing delay_before_validation to fix the test_sai_sdk_dump
  tests/show_techsupport/test_auto_techsupport.py
Labels: automerge

#18980 [action] [PR:17816] Retry SSH connection if fails after reboot, with logging for easier debugging.
  tests/common/reboot.py
Labels: automerge

#18945 [action] [PR:18775] Add 128 SRv6 sids support
  tests/common/helpers/srv6_helper.py
  tests/srv6/conftest.py
  tests/srv6/srv6_utils.py
  tests/srv6/test_srv6_dataplane.py
Labels: automerge

#18943 [action] [PR:18773] Fix UnboundLocalError in portchannel_to_vlan fixture
  tests/common/helpers/portchannel_to_vlan.py
Labels: automerge

#18925 [action] [PR:18740] revert back AS change in t0-isolated topo
  ansible/generate_topo.py
  ansible/vars/topo_t0-isolated-d16u16s1.yml
  ansible/vars/topo_t0-isolated-d16u16s2.yml
  ansible/vars/topo_t0-isolated-d32u32s2.yml
Labels: automerge

#18911 [action] [PR:18488] Add Power loss match for Kernel Panic - Cisco 8000 chassis
  tests/common/reboot.py
Labels: automerge

#18986 [action] [PR:18558] Skip test_bgp_multipath_relax.py on t1-isolated
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#18983 [action] [PR:17981] Add t1-isolated-d32 topology
  ansible/roles/eos/templates/t1-isolated-d32-tor.j2
  ansible/vars/topo_t1-isolated-d32.yml
Labels: automerge

#18927 [action] [PR:18852] advertise tor default route for t1-isolated-d128 only
  ansible/library/announce_routes.py
Labels: automerge

#18919 [action] [PR:17699] Update generic hash script to support hash field IPV6_FLOW_LABEL
  ansible/roles/test/files/ptftests/py3/generic_hash_test.py
  tests/hash/generic_hash_helper.py
  tests/hash/test_generic_hash.py
Labels: automerge

#18926 [action] [PR:18874] [XFAIL: test_crm_available.py] set xfail of test_crm_available on dualtor platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#18267 Shutdown BGP for PCBB tests instead of stopping processes
  tests/qos/tunnel_qos_remap_base.py
Labels: Request for 202411 branch, Request for 202505 branch

#18735 New test cases to verify voq watchdog
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/qos/test_voq_watchdog.py
  tests/saitests/py3/sai_qos_tests.py
Labels: Request for 202411 branch, Request for msft-202405 Branch, Request for 202505 branch

#19014 [action] [PR:18680] [test case] Support multiple servers testbed in bgp scale test
  tests/bgp/test_ipv6_bgp_scale.py
Labels: automerge

#18917 [action] [PR:18874] [XFAIL: test_crm_available.py] set xfail of test_crm_available on dualtor platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19013 [action] [PR:18976] [isolated-topology] Add ceos config template for PT0 in isolated topology
  ansible/roles/eos/templates/t0-isolated-d2u254s1-tor.j2
  ansible/roles/eos/templates/t0-isolated-d2u254s2-tor.j2
  ansible/roles/eos/templates/t0-isolated-d2u510s2-tor.j2
Labels: automerge

#18368 XFail fib hash/nvgre_hash tests based at issue 18304
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18290 Smartswitch: Added test case for data,control and midplanes sync
  tests/smartswitch/platform_tests/test_platform_dpu.py
Labels: Request for 202505 branch

#19019 Update timeout for gnmi subscribe API
  tests/gnmi/helper.py
Labels: Request for 202411 branch, Request for 202505 branch

#19037 [action] [PR:18290] Smartswitch: Added test case for data,control and midplanes sync
  tests/smartswitch/platform_tests/test_platform_dpu.py
Labels: automerge

#19036 [action] [PR:18901] [test_dynamic_acl] Include all upstream neighbors for t0-d18u8s4
  tests/generic_config_updater/test_dynamic_acl.py
Labels: automerge

#19032 [action] [PR:19028] [T2 IXIA] free variable 'duthost' referenced before assignment in enclosing scope
  tests/snappi_tests/files/helper.py
Labels: automerge

#19047 [action] [PR:18584] Fix failure with unbounded local variable access on Python 3.11+
  tests/gnmi/test_gnmi_appldb.py
Labels: automerge

#19043 skip interface speed change on 7060x6 as it causes crash
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18915 chore: adjust ASN value for LT2 and FT2
  ansible/generate_topo.py
  ansible/vars/topo_ft2-64.yml
  ansible/vars/topo_lt2-p32o64.yml
Labels: Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503, Request for 202505 branch

#19074 skip speed change for Arista 7060x6 platform
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 branch

#19058 [bgp_scale] Update test_ipv6_bgp_scale to support different routes sets
  tests/bgp/conftest.py
  tests/bgp/test_ipv6_bgp_scale.py
Labels: Request for msft-202412 Branch, Request for 202505 branch

#19054 [add-topo] Set `kernel.pty.max` to 8192
  ansible/roles/vm_set/tasks/main.yml
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 branch

#18810 deploy-mg script fails while generating config for MX testbeds
  ansible/library/generate_golden_config_db.py
Labels: Request for 202411 branch, Request for 202505 branch

#19033 [action] [PR:18832] [pr-tests] Remove test_qos_dscp_mapping from pr_test_scripts
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19012 [action] [PR:18995] fix PT0 template in t0-isolated topology.
  ansible/generate_topo.py
  ansible/templates/minigraph_png.j2
  ansible/vars/topo_t0-isolated-d32u32s2.yml
Labels: automerge

#19086 [action] [PR:18659] Update cEOS configuration to use next-hop-self
  ansible/roles/eos/tasks/ceos.yml
  ansible/roles/eos/templates/dpu-tor.j2
  ansible/roles/eos/templates/m0-mx.j2
  ansible/roles/eos/templates/t0-8-lag-leaf.j2
  ansible/roles/eos/templates/t0-backend-leaf.j2
  ansible/roles/eos/templates/t0-leaf-lag-2.j2
  ansible/roles/eos/templates/t0-leaf.j2
  ansible/roles/eos/templates/t0-mclag-leaf.j2
  ansible/roles/eos/templates/t0-v6-leaf.j2
  ansible/roles/eos/templates/t1-28-lag-spine.j2
  ansible/roles/eos/templates/t1-28-lag-tor.j2
  ansible/roles/eos/templates/t1-56-lag-tor.j2
  ansible/roles/eos/templates/t1-64-lag-tor.j2
  ansible/roles/eos/templates/t1-8-lag-spine.j2
  ansible/roles/eos/templates/t1-8-lag-tor.j2
  ansible/roles/eos/templates/t1-backend-tor.j2
  ansible/roles/eos/templates/t1-lag-spine.j2
  ansible/roles/eos/templates/t1-lag-tor.j2
  ansible/roles/eos/templates/t1-smartswitch-ha-spine.j2
  ansible/roles/eos/templates/t1-smartswitch-ha-tor.j2
  ansible/roles/eos/templates/t2-core.j2
  ansible/roles/eos/templates/t2-leaf.j2
  ansible/roles/eos/templates/t2-vs-core.j2
  ansible/roles/eos/templates/t2-vs-leaf.j2
Labels: automerge

#19039 [action] [PR:18136] [reboot] Refresh critical service before checking critical process af…
  tests/common/devices/multi_asic.py
  tests/common/reboot.py
Labels: automerge

#18941 [action] [PR:18558] Skip test_bgp_multipath_relax.py on t1-isolated
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19040 Remove special characters (special quotes) from Python scripts
  ansible/library/generate_golden_config_db.py
  ansible/verify_config.py
  tests/tacacs/utils.py
Labels: Request for msft-202503 Branch, Request for 202505 branch

#19102 Fix test_duplicate_route.py as per new orchagent crash handling changes
  tests/route/test_duplicate_route.py
Labels: Request for 202505 branch

#19100 [action] [PR:18610] [configlet] Skip last_update_time for comparison per design
  tests/common/configlet/utils.py
Labels: automerge

#19090 [action] [PR:18877] [bgp] Fix test_ipv6_bgp_scale fails in multi-server
  ansible/library/announce_routes.py
  tests/bgp/test_ipv6_bgp_scale.py
Labels: automerge

#19015 [action] [PR:18735] New test cases to verify voq watchdog
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
  tests/qos/qos_sai_base.py
  tests/qos/test_qos_sai.py
  tests/qos/test_voq_watchdog.py
  tests/saitests/py3/sai_qos_tests.py
Labels: automerge

#19114 Fix test_poweroff_reboot
  tests/platform_tests/test_power_off_reboot.py
Labels: Request for msft-202405 Branch

#19112 [action] [PR:19040] Remove special characters (special quotes) from Python scripts
  ansible/library/generate_golden_config_db.py
  ansible/verify_config.py
  tests/tacacs/utils.py
Labels: automerge

#19035 Collect techsupport on neighbors if fixture fails in pc/test_retry_count
  tests/pc/test_retry_count.py
Labels: Request for 202505 branch

#17586 Add a new test case for GCU update SRv6 config
  tests/generic_config_updater/test_srv6.py
Labels: Request for msft-202412 Branch, Request for 202505 branch

#19071 voqWD disabling and method to check dshellClient is running
  tests/snappi_tests/cisco/helper.py
  tests/snappi_tests/pfcwd/test_pfcwd_actions.py
Labels: Request for msft-202405 Branch, Request for 202505 branch

#19121 [action] [PR:19035] Collect techsupport on neighbors if fixture fails in pc/test_retry_count
  tests/pc/test_retry_count.py
Labels: automerge

#19057 [action] [PR:18987] add Cisco-8101-V64 into cisco_hwskus list
  ansible/group_vars/sonic/variables
Labels: automerge

#19125 [action] [PR:18777] Added detailed reason for assert failure for bgp,sonic,sfp
  tests/bgp/test_bgp_azng_migration.py
  tests/bgp/test_bgp_suppress_fib.py
  tests/common/devices/sonic.py
  tests/platform_tests/sfp/test_sfputil.py
  tests/platform_tests/sfp/test_show_intf_xcvr.py
  tests/platform_tests/test_reload_config.py
Labels: automerge

#19038 [action] [PR:18368] XFail fib hash/nvgre_hash tests based at issue 18304
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19132 [action] [PR:18686] [topo file] Fix pt0 announce routes in bgp scale topologies
  ansible/library/announce_routes.py
  ansible/vars/topo_t0-isolated-d2u254.yml
  ansible/vars/topo_t0-isolated-d2u254s1.yml
  ansible/vars/topo_t0-isolated-d2u254s2.yml
  ansible/vars/topo_t0-isolated-d2u510.yml
  ansible/vars/topo_t0-isolated-d2u510s2.yml
Labels: automerge

#19145 [action] [PR:19058] [bgp_scale] Update test_ipv6_bgp_scale to support different routes sets
  tests/bgp/conftest.py
  tests/bgp/test_ipv6_bgp_scale.py
Labels: automerge

#19144 [action] [PR:18792] skip 2 TCs for test_nexthop_flap_skip_TCs
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19080 [ACL] Record service ports individually and add them to the acl_table_ports
  tests/acl/test_acl.py
Labels: Request for 202411 branch, Request for 202505 branch

#19159 [action] [PR:19147] [performance_meter] add -f to config reload
  tests/performance_meter/ops.py
Labels: automerge

#19157 [action] [PR:19150] Fix configuration after gnmi test
  tests/gnmi/conftest.py
Labels: automerge

#19148 [dut_console] Fix failure on test_baud_rate_boot_connect
  tests/dut_console/test_console_baud_rate.py
Labels: Request for 202505 branch

#18849 Skip test_traffic_shift_sup.py on t2_single_node topo
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: Request for msft-202503 Branch, Approved for msft-202503 Branch

#18908 [macsec]: Improve test_dataplane for DT2 topology
  tests/macsec/test_dataplane.py
Labels: Request for msft-202503 Branch

#18547 skip loganalyzer when its not instantiated
  tests/snmp/test_snmp_queue_counters.py
Labels: Request for msft-202503 Branch

#18461 [action] [PR:16528] Fix test_sysuptime failure
  tests/telemetry/test_telemetry.py
Labels: automerge

#19183 [action] [PR:19080] [ACL] Record service ports individually and add them to the acl_table_ports
  tests/acl/test_acl.py
Labels: automerge

#19184 [action] [PR:19078] Skip multi-hop upgrade tests on non-T0 testbeds
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19182 [action] [PR:18796] [dhcp_relay] Verify per-interface counter in test_dhcp_relay.py
  tests/dhcp_relay/conftest.py
  tests/dhcp_relay/test_dhcp_relay.py
Labels: automerge

#19076 Consolidate voq watchdog testcases to single testcase
  tests/qos/qos_sai_base.py
  tests/qos/test_voq_watchdog.py
Labels: Request for 202505 branch

#19186 [action] [PR:19117] [bgp_scale] Fix announce_routes for t1-isolated topo
  ansible/library/announce_routes.py
  ansible/roles/vm_set/tasks/announce_routes.yml
  ansible/testbed-cli.sh
  ansible/vars/topo_t1-isolated-d254u2.yml
  ansible/vars/topo_t1-isolated-d254u2s1.yml
  ansible/vars/topo_t1-isolated-d254u2s2.yml
  ansible/vars/topo_t1-isolated-d510u2.yml
  ansible/vars/topo_t1-isolated-d510u2s2.yml
  tests/bgp/test_ipv6_bgp_scale.py
Labels: automerge

#19160 [T1] Add topo t1-isolated-d510u2 in veos
  ansible/veos
Labels: Request for msft-202412 Branch, Request for 202505 branch

#19192 [golden_config_db] Add origin golden_config_db.json and restore it in each test
  ansible/library/generate_golden_config_db.py
  tests/conftest.py
Labels: Request for 202505 branch

#19208 [action] [PR:19193] [acl] Restore config via golden_config_db.json in test_acl.py
  tests/acl/test_acl.py
Labels: automerge

#19138 [testplan][dhcp] Add test plan for dhcpv4 per-interface counter
  docs/testplan/dhcp_relay/DHCP-relay-stress-test.md
  docs/testplan/dhcp_relay/DHCPv4-relay-per-interface-counter-test-plan.md
Labels: Test Plan

#19207 [action] [PR:19129] [M1] Define M1-44, M1-108 and M1-128 topology
  ansible/roles/eos/templates/m1-108-c0.j2
  ansible/roles/eos/templates/m1-108-m0.j2
  ansible/roles/eos/templates/m1-108-ma.j2
  ansible/roles/eos/templates/m1-108-mb.j2
  ansible/roles/eos/templates/m1-128-c0.j2
  ansible/roles/eos/templates/m1-128-m0.j2
  ansible/roles/eos/templates/m1-128-ma.j2
  ansible/roles/eos/templates/m1-128-mb.j2
  ansible/roles/eos/templates/m1-44-c0.j2
  ansible/roles/eos/templates/m1-44-m0.j2
  ansible/roles/eos/templates/m1-44-ma.j2
  ansible/roles/eos/templates/m1-44-mb.j2
  ansible/vars/topo_m1-108.yml
  ansible/vars/topo_m1-128.yml
  ansible/vars/topo_m1-44.yml
  ansible/veos
  ansible/veos_vtb
  tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
Labels: automerge

#19178 [LT2] Fix everflow tests
  tests/common/helpers/constants.py
Labels: Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503, Request for 202505 branch

#19179 [DT2] Update Arista 7060x6 port utils
  ansible/module_utils/port_utils.py
Labels: Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503, Request for 202505 branch

#17990 Added spc5 to test_nhop_group
  tests/ipfwd/test_nhop_group.py
Labels: Request for msft-202412 Branch, Request for 202505 branch

#18898 [test_static_route] Skip PT0 neighbor when checking route redistribution
  tests/route/test_static_route.py
Labels: Request for 202411 branch, Request for 202505 branch

#19220 [action] [PR:17990] Added spc5 to test_nhop_group
  tests/ipfwd/test_nhop_group.py
Labels: automerge

#19135 [action] [PR:19110] Ignore audit rate limit exceeded syslog and avoid false alert for kernel syslog
  ansible/roles/test/files/tools/loganalyzer/loganalyzer_common_ignore.txt
Labels: automerge

#18855 [Mellanox]Update the ecn_mode on Mellanox to be same as other platforms
  tests/decap/test_decap.py
Labels: Request for 202505 branch

#19169 [Conditional mark] Xfail test_ser.py in 202412
  tests/common/plugins/conditional_mark/tests_mark_conditions_platform_tests.yaml
Labels: Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412

#19248 feat: update port mapping for Arista-7060X6-64PE-P64
  ansible/module_utils/port_utils.py
Labels: Request for msft-202503 Branch, Request for 202505 branch

#19238 Set VM as reflector for LT2/FT2
  ansible/roles/eos/templates/t0-leaf.j2
Labels: Request for msft-202503 Branch, Cherry Pick Conflict_msft-202503, Request for 202505 branch
